-- 007-gardening.sql — Grave Gardening: the seeds, herbs and saplings, and the personal plots.
-- GENERATED by tools/build-gardening-sql.mjs from server/rules/content/gardening.ts. Do not edit by hand.
-- Additive and idempotent: re-running it changes nothing.

CREATE TABLE IF NOT EXISTS garden_plots (
  character_id INT UNSIGNED NOT NULL,
  plot         VARCHAR(8) NOT NULL,
  seed_id      VARCHAR(64) NULL,
  planted_at   BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ready_at     BIGINT UNSIGNED NOT NULL DEFAULT 0,
  composted    TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (character_id, plot),
  CONSTRAINT fk_garden_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_mourning_moss', 'Mourning Moss', 'common', 'material', NULL, 0, '{}', NULL, 4, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_nightshade', 'Nightshade', 'uncommon', 'material', NULL, 0, '{}', NULL, 9, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('seed_nightshade', 'Nightshade Seed', 'uncommon', 'material', NULL, 0, '{}', NULL, 4, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_corpse_lily', 'Corpse-lily', 'uncommon', 'material', NULL, 0, '{}', NULL, 18, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('seed_corpse_lily', 'Corpse-lily Seed', 'uncommon', 'material', NULL, 0, '{}', NULL, 8, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_wolfsbane', 'Wolfsbane', 'rare', 'material', NULL, 0, '{}', NULL, 30, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('seed_wolfsbane', 'Wolfsbane Seed', 'rare', 'material', NULL, 0, '{}', NULL, 14, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_bloodroot', 'Bloodroot', 'rare', 'material', NULL, 0, '{}', NULL, 48, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('seed_bloodroot', 'Bloodroot Seed', 'rare', 'material', NULL, 0, '{}', NULL, 22, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('herb_moonpetal', 'Moonpetal', 'epic', 'material', NULL, 0, '{}', NULL, 80, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('seed_moonpetal', 'Moonpetal Seed', 'rare', 'material', NULL, 0, '{}', NULL, 36, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('sapling_oak', 'Coffin-Oak Sapling', 'common', 'material', NULL, 0, '{}', NULL, 6, 0, NULL, 1, 250);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('sapling_yew', 'Churchyard Yew Sapling', 'uncommon', 'material', NULL, 0, '{}', NULL, 20, 0, NULL, 1, 250);
