-- 009-alchemy.sql — Alchemy: herb potions at the Workbench. Recipes use the new `alchemy` profession id, which the server
-- allows from this release (server.js PROFESSION_NAMES). The existing flasks keep their rows; this adds two new potions and the recipes.
-- GENERATED by tools/build-alchemy-sql.mjs from server/rules/content/alchemy.ts. Do not edit by hand.
-- Additive and idempotent (INSERT IGNORE): re-running it changes nothing.

INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('flask_hp_grand', 'Grand Healing Flask', 'rare', 'consumable', NULL, 0, '{"value":150,"effect":"hp_regen","duration":60}', NULL, 45, 1, NULL, 1, 99);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('elixir_moonlight', 'Moonlight Elixir', 'epic', 'consumable', NULL, 0, '{"value":0.25,"effect":"damage_amp","duration":60}', NULL, 120, 1, NULL, 1, 99);

INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_moss_tonic', 'Brew Moss Tonic', 'alchemy', 1, 'flask_hp_minor', 'craft', 4, 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_moss_tonic', 'herb_mourning_moss', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_nightshade_draught', 'Brew Nightshade Draught', 'alchemy', 12, 'flask_hp_major', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_nightshade_draught', 'herb_nightshade', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_nightshade_draught', 'bone_meal', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_swift_tincture', 'Brew Swift Tincture', 'alchemy', 18, 'flask_speed', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_swift_tincture', 'herb_nightshade', 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_swift_tincture', 'herb_mourning_moss', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_lily_tempering', 'Brew Lily Tempering', 'alchemy', 32, 'flask_damage', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_lily_tempering', 'herb_corpse_lily', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_lily_tempering', 'bone_meal', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_wolfsbane_ward', 'Brew Wolfsbane Ward', 'alchemy', 45, 'flask_void_resist', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_wolfsbane_ward', 'herb_wolfsbane', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_bloodroot_grand', 'Brew Grand Healing Flask', 'alchemy', 58, 'flask_hp_grand', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_bloodroot_grand', 'herb_bloodroot', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_bloodroot_grand', 'herb_corpse_lily', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('brew_moonpetal_elixir', 'Brew Moonlight Elixir', 'alchemy', 72, 'elixir_moonlight', 'craft', 4, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_moonpetal_elixir', 'herb_moonpetal', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('brew_moonpetal_elixir', 'herb_bloodroot', 1);
