-- 010-cosmetics.sql — capes and pets: what you have chosen to wear, the companions you have adopted, and the pet charms.
-- Capes are unlocked by skill levels (computed live from `professions`), so only the choice is stored.
-- GENERATED by tools/build-cosmetics-sql.mjs from server/rules/content/cosmetics.ts. Do not edit by hand.
-- Additive and idempotent: re-running it changes nothing.

CREATE TABLE IF NOT EXISTS character_cosmetics (
  character_id INT UNSIGNED NOT NULL PRIMARY KEY,
  cape         VARCHAR(48) NULL,
  pet          VARCHAR(48) NULL,
  CONSTRAINT fk_cosmetics_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS character_pets (
  character_id INT UNSIGNED NOT NULL,
  pet_id       VARCHAR(48) NOT NULL,
  adopted_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (character_id, pet_id),
  CONSTRAINT fk_pets_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('charm_tithe_bat', 'Tithe Bat Charm', 'rare', 'material', NULL, 0, '{}', NULL, 250, 0, NULL, 0, 1);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('charm_grave_rat', 'Grave Rat Charm', 'rare', 'material', NULL, 0, '{}', NULL, 250, 0, NULL, 0, 1);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('charm_drowned_pup', 'Drowned Pup Charm', 'rare', 'material', NULL, 0, '{}', NULL, 250, 0, NULL, 0, 1);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('charm_wee_thrall', 'Wee Thrall Charm', 'epic', 'material', NULL, 0, '{}', NULL, 250, 0, NULL, 0, 1);
INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES ('charm_shroud_moth', 'Shroud Moth Charm', 'epic', 'material', NULL, 0, '{}', NULL, 250, 0, NULL, 0, 1);
