-- Nine discipline-themed armor sets; additive and safe to rerun.
-- Apply to the Death Muffin database after a backup, before publishing the client.
INSERT IGNORE INTO items
  (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, stackable, max_stack_size)
VALUES
  ('set_gravecaller_head', 'Gravecall Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_gravecaller_head.svg', 14, 0, 0, 1),
  ('set_gravecaller_chest', 'Gravecall Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_int":8,"stat_vit":4}', 'art/items/set_gravecaller_chest.svg', 52, 0, 0, 1),
  ('set_gravecaller_hands', 'Gravecall Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_gravecaller_hands.svg', 14, 0, 0, 1),
  ('set_gravecaller_legs', 'Gravecall Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_gravecaller_legs.svg', 39, 0, 0, 1),
  ('set_gravecaller_feet', 'Gravecall Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_gravecaller_feet.svg', 44, 0, 0, 1),
  ('set_warden_head', 'Lamplight Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_vit":2,"stat_str":1}', 'art/items/set_warden_head.svg', 14, 0, 0, 1),
  ('set_warden_chest', 'Lamplight Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_vit":8,"stat_str":4}', 'art/items/set_warden_chest.svg', 52, 0, 0, 1),
  ('set_warden_hands', 'Lamplight Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_vit":2,"stat_str":1}', 'art/items/set_warden_hands.svg', 14, 0, 0, 1),
  ('set_warden_legs', 'Lamplight Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_vit":6,"stat_str":3}', 'art/items/set_warden_legs.svg', 39, 0, 0, 1),
  ('set_warden_feet', 'Lamplight Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_vit":6,"stat_str":3}', 'art/items/set_warden_feet.svg', 44, 0, 0, 1),
  ('set_monk_head', 'Bellwake Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_str":2,"stat_agi":1}', 'art/items/set_monk_head.svg', 14, 0, 0, 1),
  ('set_monk_chest', 'Bellwake Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_str":8,"stat_agi":4}', 'art/items/set_monk_chest.svg', 52, 0, 0, 1),
  ('set_monk_hands', 'Bellwake Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_str":2,"stat_agi":1}', 'art/items/set_monk_hands.svg', 14, 0, 0, 1),
  ('set_monk_legs', 'Bellwake Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_str":6,"stat_agi":3}', 'art/items/set_monk_legs.svg', 39, 0, 0, 1),
  ('set_monk_feet', 'Bellwake Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_str":6,"stat_agi":3}', 'art/items/set_monk_feet.svg', 44, 0, 0, 1),
  ('set_ossuary_head', 'Ivory Reliquary Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_ossuary_head.svg', 14, 0, 0, 1),
  ('set_ossuary_chest', 'Ivory Reliquary Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_int":8,"stat_vit":4}', 'art/items/set_ossuary_chest.svg', 52, 0, 0, 1),
  ('set_ossuary_hands', 'Ivory Reliquary Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_ossuary_hands.svg', 14, 0, 0, 1),
  ('set_ossuary_legs', 'Ivory Reliquary Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_ossuary_legs.svg', 39, 0, 0, 1),
  ('set_ossuary_feet', 'Ivory Reliquary Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_ossuary_feet.svg', 44, 0, 0, 1),
  ('set_mourner_head', 'Widowveil Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_int":2,"stat_agi":1}', 'art/items/set_mourner_head.svg', 14, 0, 0, 1),
  ('set_mourner_chest', 'Widowveil Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_int":8,"stat_agi":4}', 'art/items/set_mourner_chest.svg', 52, 0, 0, 1),
  ('set_mourner_hands', 'Widowveil Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_int":2,"stat_agi":1}', 'art/items/set_mourner_hands.svg', 14, 0, 0, 1),
  ('set_mourner_legs', 'Widowveil Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_int":6,"stat_agi":3}', 'art/items/set_mourner_legs.svg', 39, 0, 0, 1),
  ('set_mourner_feet', 'Widowveil Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":6,"stat_agi":3}', 'art/items/set_mourner_feet.svg', 44, 0, 0, 1),
  ('set_witch_head', 'Carrionbloom Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_witch_head.svg', 14, 0, 0, 1),
  ('set_witch_chest', 'Carrionbloom Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_int":8,"stat_vit":4}', 'art/items/set_witch_chest.svg', 52, 0, 0, 1),
  ('set_witch_hands', 'Carrionbloom Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_witch_hands.svg', 14, 0, 0, 1),
  ('set_witch_legs', 'Carrionbloom Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_witch_legs.svg', 39, 0, 0, 1),
  ('set_witch_feet', 'Carrionbloom Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_witch_feet.svg', 44, 0, 0, 1),
  ('set_rotweaver_head', 'Blightweave Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_rotweaver_head.svg', 14, 0, 0, 1),
  ('set_rotweaver_chest', 'Blightweave Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_int":8,"stat_vit":4}', 'art/items/set_rotweaver_chest.svg', 52, 0, 0, 1),
  ('set_rotweaver_hands', 'Blightweave Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_int":2,"stat_vit":1}', 'art/items/set_rotweaver_hands.svg', 14, 0, 0, 1),
  ('set_rotweaver_legs', 'Blightweave Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_rotweaver_legs.svg', 39, 0, 0, 1),
  ('set_rotweaver_feet', 'Blightweave Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":6,"stat_vit":3}', 'art/items/set_rotweaver_feet.svg', 44, 0, 0, 1),
  ('set_knight_head', 'Hollow Oath Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_str":2,"stat_vit":1}', 'art/items/set_knight_head.svg', 14, 0, 0, 1),
  ('set_knight_chest', 'Hollow Oath Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_str":8,"stat_vit":4}', 'art/items/set_knight_chest.svg', 52, 0, 0, 1),
  ('set_knight_hands', 'Hollow Oath Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_str":2,"stat_vit":1}', 'art/items/set_knight_hands.svg', 14, 0, 0, 1),
  ('set_knight_legs', 'Hollow Oath Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_str":6,"stat_vit":3}', 'art/items/set_knight_legs.svg', 39, 0, 0, 1),
  ('set_knight_feet', 'Hollow Oath Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_str":6,"stat_vit":3}', 'art/items/set_knight_feet.svg', 44, 0, 0, 1),
  ('set_veil_head', 'Threshold Crown', 'uncommon', 'armor_head', 'head', 0, '{"stat_agi":2,"stat_int":1}', 'art/items/set_veil_head.svg', 14, 0, 0, 1),
  ('set_veil_chest', 'Threshold Vestment', 'rare', 'armor_chest', 'chest', 0, '{"stat_agi":8,"stat_int":4}', 'art/items/set_veil_chest.svg', 52, 0, 0, 1),
  ('set_veil_hands', 'Threshold Grips', 'uncommon', 'armor_hands', 'hands', 0, '{"stat_agi":2,"stat_int":1}', 'art/items/set_veil_hands.svg', 14, 0, 0, 1),
  ('set_veil_legs', 'Threshold Legguards', 'rare', 'armor_legs', 'legs', 0, '{"stat_agi":6,"stat_int":3}', 'art/items/set_veil_legs.svg', 39, 0, 0, 1),
  ('set_veil_feet', 'Threshold Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_agi":6,"stat_int":3}', 'art/items/set_veil_feet.svg', 44, 0, 0, 1);
