-- Nine ascended discipline armor sets; additive and safe to rerun.
-- Apply to the Death Muffin database after a backup, before publishing the client.
INSERT IGNORE INTO items
  (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, stackable, max_stack_size)
VALUES
  ('set_gravecaller_ascended_head', 'Epitaph Sovereign Crown', 'rare', 'armor_head', 'head', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_gravecaller_ascended_head.svg', 46, 0, 0, 1),
  ('set_gravecaller_ascended_chest', 'Epitaph Sovereign Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_int":13,"stat_vit":6}', 'art/items/set_gravecaller_ascended_chest.svg', 108, 0, 0, 1),
  ('set_gravecaller_ascended_hands', 'Epitaph Sovereign Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_gravecaller_ascended_hands.svg', 46, 0, 0, 1),
  ('set_gravecaller_ascended_legs', 'Epitaph Sovereign Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_int":10,"stat_vit":4}', 'art/items/set_gravecaller_ascended_legs.svg', 86, 0, 0, 1),
  ('set_gravecaller_ascended_feet', 'Epitaph Sovereign Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":7,"stat_vit":3}', 'art/items/set_gravecaller_ascended_feet.svg', 64, 0, 0, 1),
  ('set_warden_ascended_head', 'Nightwatch Beacon Crown', 'rare', 'armor_head', 'head', 0, '{"stat_vit":5,"stat_str":2}', 'art/items/set_warden_ascended_head.svg', 46, 0, 0, 1),
  ('set_warden_ascended_chest', 'Nightwatch Beacon Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_vit":13,"stat_str":6}', 'art/items/set_warden_ascended_chest.svg', 108, 0, 0, 1),
  ('set_warden_ascended_hands', 'Nightwatch Beacon Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_vit":5,"stat_str":2}', 'art/items/set_warden_ascended_hands.svg', 46, 0, 0, 1),
  ('set_warden_ascended_legs', 'Nightwatch Beacon Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_vit":10,"stat_str":4}', 'art/items/set_warden_ascended_legs.svg', 86, 0, 0, 1),
  ('set_warden_ascended_feet', 'Nightwatch Beacon Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_vit":7,"stat_str":3}', 'art/items/set_warden_ascended_feet.svg', 64, 0, 0, 1),
  ('set_monk_ascended_head', 'Last Toll Crown', 'rare', 'armor_head', 'head', 0, '{"stat_str":5,"stat_agi":2}', 'art/items/set_monk_ascended_head.svg', 46, 0, 0, 1),
  ('set_monk_ascended_chest', 'Last Toll Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_str":13,"stat_agi":6}', 'art/items/set_monk_ascended_chest.svg', 108, 0, 0, 1),
  ('set_monk_ascended_hands', 'Last Toll Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_str":5,"stat_agi":2}', 'art/items/set_monk_ascended_hands.svg', 46, 0, 0, 1),
  ('set_monk_ascended_legs', 'Last Toll Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_str":10,"stat_agi":4}', 'art/items/set_monk_ascended_legs.svg', 86, 0, 0, 1),
  ('set_monk_ascended_feet', 'Last Toll Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_str":7,"stat_agi":3}', 'art/items/set_monk_ascended_feet.svg', 64, 0, 0, 1),
  ('set_ossuary_ascended_head', 'Marrow Regent Crown', 'rare', 'armor_head', 'head', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_ossuary_ascended_head.svg', 46, 0, 0, 1),
  ('set_ossuary_ascended_chest', 'Marrow Regent Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_int":13,"stat_vit":6}', 'art/items/set_ossuary_ascended_chest.svg', 108, 0, 0, 1),
  ('set_ossuary_ascended_hands', 'Marrow Regent Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_ossuary_ascended_hands.svg', 46, 0, 0, 1),
  ('set_ossuary_ascended_legs', 'Marrow Regent Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_int":10,"stat_vit":4}', 'art/items/set_ossuary_ascended_legs.svg', 86, 0, 0, 1),
  ('set_ossuary_ascended_feet', 'Marrow Regent Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":7,"stat_vit":3}', 'art/items/set_ossuary_ascended_feet.svg', 64, 0, 0, 1),
  ('set_mourner_ascended_head', 'Pale Requiem Crown', 'rare', 'armor_head', 'head', 0, '{"stat_int":5,"stat_agi":2}', 'art/items/set_mourner_ascended_head.svg', 46, 0, 0, 1),
  ('set_mourner_ascended_chest', 'Pale Requiem Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_int":13,"stat_agi":6}', 'art/items/set_mourner_ascended_chest.svg', 108, 0, 0, 1),
  ('set_mourner_ascended_hands', 'Pale Requiem Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_int":5,"stat_agi":2}', 'art/items/set_mourner_ascended_hands.svg', 46, 0, 0, 1),
  ('set_mourner_ascended_legs', 'Pale Requiem Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_int":10,"stat_agi":4}', 'art/items/set_mourner_ascended_legs.svg', 86, 0, 0, 1),
  ('set_mourner_ascended_feet', 'Pale Requiem Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":7,"stat_agi":3}', 'art/items/set_mourner_ascended_feet.svg', 64, 0, 0, 1),
  ('set_witch_ascended_head', 'Thorn Covenant Crown', 'rare', 'armor_head', 'head', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_witch_ascended_head.svg', 46, 0, 0, 1),
  ('set_witch_ascended_chest', 'Thorn Covenant Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_int":13,"stat_vit":6}', 'art/items/set_witch_ascended_chest.svg', 108, 0, 0, 1),
  ('set_witch_ascended_hands', 'Thorn Covenant Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_witch_ascended_hands.svg', 46, 0, 0, 1),
  ('set_witch_ascended_legs', 'Thorn Covenant Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_int":10,"stat_vit":4}', 'art/items/set_witch_ascended_legs.svg', 86, 0, 0, 1),
  ('set_witch_ascended_feet', 'Thorn Covenant Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":7,"stat_vit":3}', 'art/items/set_witch_ascended_feet.svg', 64, 0, 0, 1),
  ('set_rotweaver_ascended_head', 'Virulent Choir Crown', 'rare', 'armor_head', 'head', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_rotweaver_ascended_head.svg', 46, 0, 0, 1),
  ('set_rotweaver_ascended_chest', 'Virulent Choir Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_int":13,"stat_vit":6}', 'art/items/set_rotweaver_ascended_chest.svg', 108, 0, 0, 1),
  ('set_rotweaver_ascended_hands', 'Virulent Choir Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_int":5,"stat_vit":2}', 'art/items/set_rotweaver_ascended_hands.svg', 46, 0, 0, 1),
  ('set_rotweaver_ascended_legs', 'Virulent Choir Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_int":10,"stat_vit":4}', 'art/items/set_rotweaver_ascended_legs.svg', 86, 0, 0, 1),
  ('set_rotweaver_ascended_feet', 'Virulent Choir Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_int":7,"stat_vit":3}', 'art/items/set_rotweaver_ascended_feet.svg', 64, 0, 0, 1),
  ('set_knight_ascended_head', 'Oathbreaker Crown', 'rare', 'armor_head', 'head', 0, '{"stat_str":5,"stat_vit":2}', 'art/items/set_knight_ascended_head.svg', 46, 0, 0, 1),
  ('set_knight_ascended_chest', 'Oathbreaker Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_str":13,"stat_vit":6}', 'art/items/set_knight_ascended_chest.svg', 108, 0, 0, 1),
  ('set_knight_ascended_hands', 'Oathbreaker Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_str":5,"stat_vit":2}', 'art/items/set_knight_ascended_hands.svg', 46, 0, 0, 1),
  ('set_knight_ascended_legs', 'Oathbreaker Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_str":10,"stat_vit":4}', 'art/items/set_knight_ascended_legs.svg', 86, 0, 0, 1),
  ('set_knight_ascended_feet', 'Oathbreaker Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_str":7,"stat_vit":3}', 'art/items/set_knight_ascended_feet.svg', 64, 0, 0, 1),
  ('set_veil_ascended_head', 'Umbral Crossing Crown', 'rare', 'armor_head', 'head', 0, '{"stat_agi":5,"stat_int":2}', 'art/items/set_veil_ascended_head.svg', 46, 0, 0, 1),
  ('set_veil_ascended_chest', 'Umbral Crossing Vestment', 'epic', 'armor_chest', 'chest', 0, '{"stat_agi":13,"stat_int":6}', 'art/items/set_veil_ascended_chest.svg', 108, 0, 0, 1),
  ('set_veil_ascended_hands', 'Umbral Crossing Grips', 'rare', 'armor_hands', 'hands', 0, '{"stat_agi":5,"stat_int":2}', 'art/items/set_veil_ascended_hands.svg', 46, 0, 0, 1),
  ('set_veil_ascended_legs', 'Umbral Crossing Legguards', 'epic', 'armor_legs', 'legs', 0, '{"stat_agi":10,"stat_int":4}', 'art/items/set_veil_ascended_legs.svg', 86, 0, 0, 1),
  ('set_veil_ascended_feet', 'Umbral Crossing Treads', 'epic', 'armor_feet', 'feet', 0, '{"stat_agi":7,"stat_int":3}', 'art/items/set_veil_ascended_feet.svg', 64, 0, 0, 1);
