-- 013-necro-weapons.sql: the necromancer weapon line (4 main-hand kinds + 3 off-hands x 5 tiers) and its Workbench recipes.
-- GENERATED by tools/generate-necro-weapons.mjs from server/rules/content/necroWeapons.ts. Do not edit by hand.
-- Additive and idempotent (INSERT IGNORE): safe to rerun. Apply to the Death Muffin database after a backup, before publishing the client.
INSERT IGNORE INTO items
  (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, stackable, max_stack_size)
VALUES
  ('staff_bone', 'Vertebral Staff', 'common', 'weapon', 'main_hand', 1, '{"stat_int":5}', 'art/items/staff_bone.svg', 16, 0, 0, 1),
  ('staff_iron', 'Crypt-Iron Crozier', 'uncommon', 'weapon', 'main_hand', 1, '{"stat_int":9,"stat_vit":1}', 'art/items/staff_iron.svg', 38, 0, 0, 1),
  ('staff_gold', 'Reliquary Staff', 'rare', 'weapon', 'main_hand', 1, '{"stat_int":15,"stat_vit":2}', 'art/items/staff_gold.svg', 88, 0, 0, 1),
  ('staff_hell', 'Hellcoal Crozier', 'epic', 'weapon', 'main_hand', 1, '{"stat_int":22,"stat_vit":4}', 'art/items/staff_hell.svg', 176, 0, 0, 1),
  ('staff_moon', 'Staff of the Pale Moon', 'epic', 'weapon', 'main_hand', 1, '{"stat_int":30,"stat_vit":6}', 'art/items/staff_moon.svg', 352, 0, 0, 1),
  ('scythe_bone', 'Gleaner''s Scythe', 'common', 'weapon', 'main_hand', 1, '{"stat_int":4,"stat_vit":2}', 'art/items/scythe_bone.svg', 18, 0, 0, 1),
  ('scythe_iron', 'Sexton''s Scythe', 'uncommon', 'weapon', 'main_hand', 1, '{"stat_int":8,"stat_vit":3}', 'art/items/scythe_iron.svg', 43, 0, 0, 1),
  ('scythe_gold', 'Tithe-Reaper', 'rare', 'weapon', 'main_hand', 1, '{"stat_int":13,"stat_vit":5}', 'art/items/scythe_gold.svg', 99, 0, 0, 1),
  ('scythe_hell', 'Pyre Reaper', 'epic', 'weapon', 'main_hand', 1, '{"stat_int":19,"stat_vit":8}', 'art/items/scythe_hell.svg', 198, 0, 0, 1),
  ('scythe_moon', 'Moonreaper', 'epic', 'weapon', 'main_hand', 1, '{"stat_int":26,"stat_vit":11}', 'art/items/scythe_moon.svg', 396, 0, 0, 1),
  ('wand_bone', 'Knucklebone Wand', 'common', 'weapon', 'main_hand', 0, '{"stat_int":3}', 'art/items/wand_bone.svg', 12, 0, 0, 1),
  ('wand_iron', 'Iron Mourning Wand', 'uncommon', 'weapon', 'main_hand', 0, '{"stat_int":6,"stat_agi":1}', 'art/items/wand_iron.svg', 29, 0, 0, 1),
  ('wand_gold', 'Gilded Censer Wand', 'rare', 'weapon', 'main_hand', 0, '{"stat_int":10,"stat_agi":2}', 'art/items/wand_gold.svg', 66, 0, 0, 1),
  ('wand_hell', 'Emberthorn Wand', 'epic', 'weapon', 'main_hand', 0, '{"stat_int":15,"stat_agi":3}', 'art/items/wand_hell.svg', 132, 0, 0, 1),
  ('wand_moon', 'Wand of Quiet Stars', 'epic', 'weapon', 'main_hand', 0, '{"stat_int":21,"stat_agi":5}', 'art/items/wand_moon.svg', 264, 0, 0, 1),
  ('sickle_bone', 'Barrow Sickle', 'common', 'weapon', 'main_hand', 0, '{"stat_int":3,"stat_vit":1}', 'art/items/sickle_bone.svg', 13, 0, 0, 1),
  ('sickle_iron', 'Plague Sickle', 'uncommon', 'weapon', 'main_hand', 0, '{"stat_int":6,"stat_vit":2}', 'art/items/sickle_iron.svg', 31, 0, 0, 1),
  ('sickle_gold', 'Sexton''s Gilded Sickle', 'rare', 'weapon', 'main_hand', 0, '{"stat_int":10,"stat_vit":3}', 'art/items/sickle_gold.svg', 72, 0, 0, 1),
  ('sickle_hell', 'Blightfire Sickle', 'epic', 'weapon', 'main_hand', 0, '{"stat_int":14,"stat_vit":5}', 'art/items/sickle_hell.svg', 143, 0, 0, 1),
  ('sickle_moon', 'Moonrot Sickle', 'epic', 'weapon', 'main_hand', 0, '{"stat_int":20,"stat_vit":7}', 'art/items/sickle_moon.svg', 286, 0, 0, 1),
  ('skull_focus_bone', 'Pauper''s Skull Focus', 'common', 'offhand', 'off_hand', 0, '{"stat_int":1,"stat_vit":2}', 'art/items/skull_focus_bone.svg', 10, 0, 0, 1),
  ('skull_focus_iron', 'Iron-Jawed Skull Focus', 'uncommon', 'offhand', 'off_hand', 0, '{"stat_int":3,"stat_vit":3}', 'art/items/skull_focus_iron.svg', 24, 0, 0, 1),
  ('skull_focus_gold', 'Gilded Skull Focus', 'rare', 'offhand', 'off_hand', 0, '{"stat_int":5,"stat_vit":5}', 'art/items/skull_focus_gold.svg', 55, 0, 0, 1),
  ('skull_focus_hell', 'Cinder Skull Focus', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":8,"stat_vit":8}', 'art/items/skull_focus_hell.svg', 110, 0, 0, 1),
  ('skull_focus_moon', 'Moon Skull Focus', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":11,"stat_vit":11}', 'art/items/skull_focus_moon.svg', 220, 0, 0, 1),
  ('grimoire_bone', 'Gravedigger''s Grimoire', 'common', 'offhand', 'off_hand', 0, '{"stat_int":2}', 'art/items/grimoire_bone.svg', 11, 0, 0, 1),
  ('grimoire_iron', 'Iron-Clasped Grimoire', 'uncommon', 'offhand', 'off_hand', 0, '{"stat_int":4}', 'art/items/grimoire_iron.svg', 26, 0, 0, 1),
  ('grimoire_gold', 'Gilt Reliquary Grimoire', 'rare', 'offhand', 'off_hand', 0, '{"stat_int":7}', 'art/items/grimoire_gold.svg', 61, 0, 0, 1),
  ('grimoire_hell', 'Hellbound Grimoire', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":10}', 'art/items/grimoire_hell.svg', 121, 0, 0, 1),
  ('grimoire_moon', 'Moonlit Grimoire', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":14}', 'art/items/grimoire_moon.svg', 242, 0, 0, 1),
  ('mourning_bell_bone', 'Pauper''s Mourning Bell', 'common', 'offhand', 'off_hand', 0, '{"stat_int":1,"stat_agi":1}', 'art/items/mourning_bell_bone.svg', 10, 0, 0, 1),
  ('mourning_bell_iron', 'Iron Mourning Bell', 'uncommon', 'offhand', 'off_hand', 0, '{"stat_int":3,"stat_agi":2}', 'art/items/mourning_bell_iron.svg', 24, 0, 0, 1),
  ('mourning_bell_gold', 'Gilded Mourning Bell', 'rare', 'offhand', 'off_hand', 0, '{"stat_int":5,"stat_agi":3}', 'art/items/mourning_bell_gold.svg', 55, 0, 0, 1),
  ('mourning_bell_hell', 'Cinder Mourning Bell', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":8,"stat_agi":5}', 'art/items/mourning_bell_hell.svg', 110, 0, 0, 1),
  ('mourning_bell_moon', 'Moon Mourning Bell', 'epic', 'offhand', 'off_hand', 0, '{"stat_int":11,"stat_agi":7}', 'art/items/mourning_bell_moon.svg', 220, 0, 0, 1);

INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_staff_bone', 'Vertebral Staff', 'woodcutting', 3, 'staff_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_bone', 'plank_oak', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_bone', 'bones_old', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_staff_iron', 'Crypt-Iron Crozier', 'woodcutting', 8, 'staff_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_iron', 'plank_elm', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_iron', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_staff_gold', 'Reliquary Staff', 'woodcutting', 18, 'staff_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_gold', 'plank_willow', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_gold', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_staff_hell', 'Hellcoal Crozier', 'woodcutting', 42, 'staff_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_hell', 'plank_yew', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_hell', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_staff_moon', 'Staff of the Pale Moon', 'woodcutting', 57, 'staff_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_moon', 'plank_blackthorn', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_staff_moon', 'ingot_moon', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_scythe_bone', 'Gleaner''s Scythe', 'mining', 2, 'scythe_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_bone', 'ingot_copper', 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_bone', 'bones_old', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_scythe_iron', 'Sexton''s Scythe', 'mining', 10, 'scythe_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_iron', 'ingot_iron', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_scythe_gold', 'Tithe-Reaper', 'mining', 20, 'scythe_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_gold', 'ingot_gold', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_gold', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_scythe_hell', 'Pyre Reaper', 'mining', 40, 'scythe_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_hell', 'ingot_hell', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_hell', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_scythe_moon', 'Moonreaper', 'mining', 55, 'scythe_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_moon', 'ingot_moon', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_scythe_moon', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_wand_bone', 'Knucklebone Wand', 'woodcutting', 3, 'wand_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_bone', 'plank_oak', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_bone', 'bones_old', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_wand_iron', 'Iron Mourning Wand', 'woodcutting', 8, 'wand_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_iron', 'plank_elm', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_iron', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_wand_gold', 'Gilded Censer Wand', 'woodcutting', 18, 'wand_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_gold', 'plank_willow', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_gold', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_wand_hell', 'Emberthorn Wand', 'woodcutting', 42, 'wand_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_hell', 'plank_yew', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_hell', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_wand_moon', 'Wand of Quiet Stars', 'woodcutting', 57, 'wand_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_moon', 'plank_blackthorn', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_wand_moon', 'ingot_moon', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_sickle_bone', 'Barrow Sickle', 'mining', 2, 'sickle_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_bone', 'ingot_copper', 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_bone', 'bones_old', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_sickle_iron', 'Plague Sickle', 'mining', 10, 'sickle_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_iron', 'ingot_iron', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_sickle_gold', 'Sexton''s Gilded Sickle', 'mining', 20, 'sickle_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_gold', 'ingot_gold', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_gold', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_sickle_hell', 'Blightfire Sickle', 'mining', 40, 'sickle_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_hell', 'ingot_hell', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_hell', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_sickle_moon', 'Moonrot Sickle', 'mining', 55, 'sickle_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_moon', 'ingot_moon', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_sickle_moon', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_skull_focus_bone', 'Pauper''s Skull Focus', 'mining', 2, 'skull_focus_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_bone', 'ingot_copper', 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_bone', 'bones_old', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_skull_focus_iron', 'Iron-Jawed Skull Focus', 'mining', 10, 'skull_focus_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_iron', 'ingot_iron', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_skull_focus_gold', 'Gilded Skull Focus', 'mining', 20, 'skull_focus_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_gold', 'ingot_gold', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_gold', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_skull_focus_hell', 'Cinder Skull Focus', 'mining', 40, 'skull_focus_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_hell', 'ingot_hell', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_hell', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_skull_focus_moon', 'Moon Skull Focus', 'mining', 55, 'skull_focus_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_moon', 'ingot_moon', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_skull_focus_moon', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_grimoire_bone', 'Gravedigger''s Grimoire', 'woodcutting', 3, 'grimoire_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_bone', 'plank_oak', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_bone', 'bones_old', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_grimoire_iron', 'Iron-Clasped Grimoire', 'woodcutting', 8, 'grimoire_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_iron', 'plank_elm', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_iron', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_grimoire_gold', 'Gilt Reliquary Grimoire', 'woodcutting', 18, 'grimoire_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_gold', 'plank_willow', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_gold', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_grimoire_hell', 'Hellbound Grimoire', 'woodcutting', 42, 'grimoire_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_hell', 'plank_yew', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_hell', 'ingot_hell', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_grimoire_moon', 'Moonlit Grimoire', 'woodcutting', 57, 'grimoire_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_moon', 'plank_blackthorn', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_grimoire_moon', 'ingot_moon', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_mourning_bell_bone', 'Pauper''s Mourning Bell', 'mining', 2, 'mourning_bell_bone', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_bone', 'ingot_copper', 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_bone', 'bones_old', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_mourning_bell_iron', 'Iron Mourning Bell', 'mining', 10, 'mourning_bell_iron', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_iron', 'ingot_iron', 3);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_mourning_bell_gold', 'Gilded Mourning Bell', 'mining', 20, 'mourning_bell_gold', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_gold', 'ingot_gold', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_gold', 'ingot_iron', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_mourning_bell_hell', 'Cinder Mourning Bell', 'mining', 40, 'mourning_bell_hell', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_hell', 'ingot_hell', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_hell', 'ingot_gold', 1);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_mourning_bell_moon', 'Moon Mourning Bell', 'mining', 55, 'mourning_bell_moon', 'craft', 6, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_moon', 'ingot_moon', 3);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_mourning_bell_moon', 'ingot_hell', 1);
