-- 028-trade-goods-recipes.sql — Workbench recipes for the old sell-only trade goods: Bronze Warden Kit, Tin Augment, Garnet Ring, Opal Flask.
-- Recipe and ingredient rows only: every result and ingredient item already exists, no schema change, nothing deleted. Apply after 027.
-- GENERATED by tools/build-trade-goods-sql.mjs from src/content/tradeGoods.ts. Do not edit by hand.
-- Additive and idempotent (INSERT IGNORE): re-running it changes nothing.

INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_bronze_warden_kit', 'Bronze Warden Kit', 'mining', 12, 'kit_iron_warden', 'craft', 4, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_bronze_warden_kit', 'ingot_bronze', 6);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_bronze_warden_kit', 'plank_oak', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_tin_augment', 'Tin Augment', 'mining', 5, 'augment_copper', 'craft', 4, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_tin_augment', 'ingot_tin', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_garnet_ring', 'Garnet Ring', 'mining', 8, 'ring_copper', 'craft', 4, 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_garnet_ring', 'gem_grave_garnet', 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_garnet_ring', 'material_copper_bar', 2);
INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES ('craft_opal_flask', 'Opal Flask', 'fishing', 20, 'flask_damage', 'craft', 4, 2);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_opal_flask', 'gem_bone_opal', 1);
INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES ('craft_opal_flask', 'fish_fillet', 3);
