// GENERATED by tools/build-server-rules.mjs from server/rules/gameplay/affixRules.ts — do not edit by hand.
// Item level and affix rules (pool, rolls, validation, names, value) shared by the web client, the offline mock and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// server/rules/gameplay/affixRules.ts
var affixRules_exports = {};
__export(affixRules_exports, {
  AFFIXES: () => AFFIXES,
  AFFIX_GEAR_TYPES: () => AFFIX_GEAR_TYPES,
  DROP_SOURCES: () => DROP_SOURCES,
  ILVL_MAX: () => ILVL_MAX,
  ILVL_REACH: () => ILVL_REACH,
  MAX_AFFIXES: () => MAX_AFFIXES,
  addInstanceTotals: () => addInstanceTotals,
  affixAcceptRange: () => affixAcceptRange,
  affixDef: () => affixDef,
  affixEffect: () => affixEffect,
  affixIsNecro: () => affixIsNecro,
  affixKind: () => affixKind,
  affixQuality: () => affixQuality,
  affixRange: () => affixRange,
  affixText: () => affixText,
  affixWord: () => affixWord,
  affixedName: () => affixedName,
  clampDropLevel: () => clampDropLevel,
  cleanInstance: () => cleanInstance,
  effectiveRarity: () => effectiveRarity,
  emptyAffixTotals: () => emptyAffixTotals,
  instancePower: () => instancePower,
  instanceProblem: () => instanceProblem,
  instanceSellValue: () => instanceSellValue,
  isAffixGear: () => isAffixGear,
  itemLevelFor: () => itemLevelFor,
  rollAffixCount: () => rollAffixCount,
  rollInstance: () => rollInstance
});
module.exports = __toCommonJS(affixRules_exports);
var MAX_AFFIXES = 3;
var ILVL_MAX = 99;
var DROP_SOURCES = ["kill", "elite", "boss", "first_kill", "surge"];
var AFFIX_GEAR_TYPES = ["weapon", "offhand", "armor_head", "armor_chest", "armor_legs", "armor_feet", "armor_hands", "ring", "trinket"];
var isAffixGear = (itemType) => AFFIX_GEAR_TYPES.includes(itemType);
var clampInt = (x, lo, hi) => Math.max(lo, Math.min(hi, Math.round(x)));
var around = (centre, cap, floor = 1, spread = 0.3) => {
  const lo = clampInt(centre * (1 - spread), floor, cap);
  return [lo, clampInt(Math.max(centre * (1 + spread), lo), lo, cap)];
};
var WIDE = 0.35;
var tenths = (v) => `${+(v / 10).toFixed(1)}%`;
var STAT_NAME = { stat_str: "STR", stat_agi: "AGI", stat_int: "INT", stat_vit: "VIT" };
var statDef = (stat, kind, word) => ({
  id: `${kind === "prefix" ? "p" : "s"}_${stat.slice(5)}`,
  kind,
  word,
  group: stat,
  necro: false,
  weight: 9,
  unit: "stat",
  range: (L) => around(1.2 + 0.1 * Math.min(L, 25) + 0.052 * Math.max(0, L - 25), 20, 1, WIDE),
  legacy: [(L) => around(0.8 + 0.07 * L, 14), (L) => around(0.8 + 0.07 * Math.min(L, 25) + 0.045 * Math.max(0, L - 25), 14)],
  effect: (v) => ({ stats: { [stat]: v } }),
  text: (v) => `+${v} ${STAT_NAME[stat]}`
});
var AFFIXES = [
  statDef("stat_str", "prefix", "Brutal"),
  statDef("stat_agi", "prefix", "Fleet"),
  statDef("stat_int", "prefix", "Occult"),
  statDef("stat_vit", "prefix", "Stout"),
  statDef("stat_str", "suffix", "of the Reaver"),
  statDef("stat_agi", "suffix", "of the Hound"),
  statDef("stat_int", "suffix", "of the Seer"),
  statDef("stat_vit", "suffix", "of the Tomb"),
  {
    id: "p_thrall_dmg",
    kind: "prefix",
    word: "Gravebound",
    group: "thrall_dmg",
    necro: true,
    weight: 13,
    unit: "pct",
    range: (L) => around(10 * (9.2 + 0.1 * L), 340, 1, WIDE),
    legacy: [(L) => around(10 * (5.5 + 0.2 * L), 300), (L) => around(10 * (6.5 + 0.1 * L), 300)],
    effect: (v) => ({ mult: { thrallDamageMult: 1 + v / 1e3 } }),
    text: (v) => `Thralls hit +${tenths(v)} harder`
  },
  {
    id: "s_thrall_hp",
    kind: "suffix",
    word: "of the Legion",
    group: "thrall_hp",
    necro: true,
    weight: 13,
    unit: "pct",
    range: (L) => around(10 * (12.5 + 0.3 * L), 540, 1, WIDE),
    legacy: [(L) => around(10 * (10.6 + 0.38 * L), 500), (L) => around(10 * (9.5 + 0.34 * L), 500)],
    effect: (v) => ({ mult: { thrallHpMult: 1 + v / 1e3 } }),
    text: (v) => `Thralls have +${tenths(v)} health`
  },
  {
    id: "p_essence_regen",
    kind: "prefix",
    word: "Whispering",
    group: "essence_regen",
    necro: true,
    weight: 11,
    unit: "pct",
    range: (L) => around(10 * (13 + 0.55 * L), 760, 1, WIDE),
    legacy: [(L) => around(10 * (10 + 0.42 * L), 600), (L) => around(10 * (10 + 0.5 * L), 600)],
    effect: (v) => ({ mult: { essenceRegenMult: 1 + v / 1e3 } }),
    text: (v) => `+${tenths(v)} essence regeneration`
  },
  {
    id: "s_miasma",
    kind: "suffix",
    word: "of the Rotting Mist",
    group: "miasma",
    necro: true,
    weight: 9,
    unit: "pct",
    range: (L) => around(10 * (7.6 + 0.17 * L), 550, 1, WIDE),
    legacy: [(L) => around(10 * (5.2 + 0.22 * L), 400), (L) => around(10 * (5.2 + 0.12 * L), 400)],
    effect: (v) => ({ mult: { miasmaRadiusMult: 1 + v / 1e3 } }),
    text: (v) => `Miasma is +${tenths(v)} wider`
  },
  {
    id: "p_withered",
    kind: "prefix",
    word: "Blighted",
    group: "withered",
    necro: true,
    weight: 8,
    unit: "count",
    range: (L) => [1, clampInt(3 + Math.floor(L / 12), 3, 4)],
    legacy: [(L) => [1, clampInt(2 + Math.floor(L / 7), 2, 6)], (L) => [1, clampInt(2 + Math.floor(L / 9), 2, 4)]],
    effect: (v) => ({ add: { witheredMaxStacks: v } }),
    text: (v) => `+${v} max Withered stack${v === 1 ? "" : "s"}`
  },
  {
    id: "s_ward",
    kind: "suffix",
    word: "of the Ossuary Wall",
    group: "ward",
    necro: true,
    weight: 9,
    unit: "wardPct",
    range: (L) => around(23 + 0.3 * L, 46, 1, WIDE),
    legacy: [(L) => around(9 + 0.7 * L, 60), (L) => around(12 + 0.55 * L, 55)],
    effect: (v) => ({ add: { wardPerThrall: v / 1e3 } }),
    text: (v) => `${tenths(v)} less damage taken per thrall`
  }
];
var BY_ID = new Map(AFFIXES.map((a) => [a.id, a]));
var affixDef = (id) => BY_ID.get(id);
function affixRange(id, ilvl) {
  const d = BY_ID.get(id);
  return d ? d.range(clampInt(ilvl, 1, ILVL_MAX)) : null;
}
function affixAcceptRange(id, ilvl) {
  const d = BY_ID.get(id);
  if (!d) return null;
  const L = clampInt(ilvl, 1, ILVL_MAX);
  let [lo, hi] = d.range(L);
  for (const g of d.legacy ?? []) {
    const [a, b] = g(L);
    lo = Math.min(lo, a);
    hi = Math.max(hi, b);
  }
  return [lo, hi];
}
var affixEffect = (a) => BY_ID.get(a.id)?.effect(a.v) ?? {};
var affixText = (a) => BY_ID.get(a.id)?.text(a.v) ?? a.id;
var affixIsNecro = (a) => !!BY_ID.get(a.id)?.necro;
var affixKind = (a) => BY_ID.get(a.id)?.kind ?? null;
var affixWord = (a) => BY_ID.get(a.id)?.word ?? "";
function affixQuality(a, ilvl) {
  const r = affixRange(a.id, ilvl);
  return !r || r[1] <= r[0] ? 1 : Math.max(0, Math.min(1, (a.v - r[0]) / (r[1] - r[0])));
}
var SOURCE_ILVL = { kill: 0, elite: 2, boss: 4, first_kill: 5, surge: 2 };
var itemLevelFor = (level, source) => clampInt((Number(level) || 1) + (SOURCE_ILVL[source] ?? 0), 1, ILVL_MAX);
var ILVL_REACH = 10;
var clampDropLevel = (level, characterLevel) => clampInt(Number(level) || 1, 1, Math.min(ILVL_MAX, Math.max(1, characterLevel) + ILVL_REACH));
var COUNT_WEIGHTS = {
  common: [60, 30, 9, 1],
  uncommon: [40, 38, 18, 4],
  rare: [22, 38, 30, 10],
  epic: [10, 30, 40, 20],
  legendary: [0, 15, 45, 40],
  relic: [0, 15, 45, 40]
};
var SOURCE_COUNT = {
  kill: { mult: [1, 1, 1, 1], min: 0 },
  elite: { mult: [0.6, 1, 1.4, 1.8], min: 0 },
  surge: { mult: [0.5, 1, 1.5, 2], min: 0 },
  boss: { mult: [0.15, 0.8, 1.6, 2.4], min: 1 },
  first_kill: { mult: [0, 0.3, 1.6, 2.6], min: 2 }
};
function rollAffixCount(rarity, source, rand) {
  const base = COUNT_WEIGHTS[rarity] ?? COUNT_WEIGHTS.common;
  const s = SOURCE_COUNT[source] ?? SOURCE_COUNT.kill;
  const w = base.map((x, i) => i < s.min ? 0 : x * s.mult[i]);
  const total = w.reduce((a, b) => a + b, 0) || 1;
  let r = rand() * total;
  for (let i = 0; i < 4; i++) {
    r -= w[i];
    if (r < 0) return i;
  }
  return Math.max(s.min, 0);
}
function rollInstance(item, level, source, rand) {
  const ilvl = itemLevelFor(level, source);
  const count = rollAffixCount(item.rarity, source, rand);
  const affixes = [];
  const used = /* @__PURE__ */ new Set();
  for (let n = 0; n < count; n++) {
    const pool = AFFIXES.filter((a) => !used.has(a.group));
    const total = pool.reduce((s, a) => s + a.weight, 0);
    let r = rand() * total;
    let pick = pool[pool.length - 1];
    for (const a of pool) {
      r -= a.weight;
      if (r < 0) {
        pick = a;
        break;
      }
    }
    used.add(pick.group);
    const [lo, hi] = pick.range(ilvl);
    affixes.push({ id: pick.id, v: lo + Math.min(hi - lo, Math.floor(rand() * (hi - lo + 1))) });
  }
  return { ilvl, affixes };
}
function instanceProblem(inst, itemType) {
  if (!isAffixGear(itemType)) return "Only gear can carry affixes.";
  const i = inst;
  if (!i || typeof i !== "object" || !Number.isInteger(i.ilvl) || i.ilvl < 1 || i.ilvl > ILVL_MAX) return "Invalid item level.";
  if (!Array.isArray(i.affixes) || i.affixes.length > MAX_AFFIXES) return "Invalid affixes.";
  const groups = /* @__PURE__ */ new Set();
  for (const a of i.affixes) {
    const d = a && typeof a.id === "string" ? BY_ID.get(a.id) : void 0;
    if (!d || !Number.isInteger(a.v)) return "Unknown affix.";
    if (groups.has(d.group)) return "Duplicate affix.";
    groups.add(d.group);
    const [lo, hi] = affixAcceptRange(d.id, i.ilvl);
    if (a.v < lo || a.v > hi) return "An affix roll is out of range for its item level.";
  }
  return null;
}
var cleanInstance = (inst) => ({ ilvl: inst.ilvl, affixes: inst.affixes.map((a) => ({ id: a.id, v: a.v })) });
function affixedName(baseName, affixes) {
  const pre = affixes.find((a) => affixKind(a) === "prefix");
  const suf = affixes.find((a) => affixKind(a) === "suffix");
  return [pre && affixWord(pre), baseName, suf && affixWord(suf)].filter(Boolean).join(" ");
}
var RARITY_RANK = ["common", "uncommon", "rare", "epic", "legendary", "relic"];
function effectiveRarity(baseRarity, affixCount) {
  const floor = RARITY_RANK[Math.max(0, Math.min(3, affixCount))];
  return RARITY_RANK.indexOf(floor) > RARITY_RANK.indexOf(baseRarity) ? floor : baseRarity;
}
function instanceSellValue(base, inst) {
  if (!inst) return base;
  return Math.max(base, Math.round(base * (1 + 0.02 * inst.ilvl) * (1 + 0.35 * inst.affixes.length)));
}
var instancePower = (inst) => inst ? inst.affixes.length * 1e3 + inst.ilvl : 0;
var emptyAffixTotals = () => ({ mult: {}, add: {}, stats: {} });
function addInstanceTotals(t, affixes) {
  for (const a of affixes) {
    const e = affixEffect(a);
    for (const [k, v] of Object.entries(e.mult ?? {})) t.mult[k] = (t.mult[k] ?? 1) * v;
    for (const [k, v] of Object.entries(e.add ?? {})) t.add[k] = (t.add[k] ?? 0) + v;
    for (const [k, v] of Object.entries(e.stats ?? {})) t.stats[k] = (t.stats[k] ?? 0) + v;
  }
  return t;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  AFFIXES,
  AFFIX_GEAR_TYPES,
  DROP_SOURCES,
  ILVL_MAX,
  ILVL_REACH,
  MAX_AFFIXES,
  addInstanceTotals,
  affixAcceptRange,
  affixDef,
  affixEffect,
  affixIsNecro,
  affixKind,
  affixQuality,
  affixRange,
  affixText,
  affixWord,
  affixedName,
  clampDropLevel,
  cleanInstance,
  effectiveRarity,
  emptyAffixTotals,
  instancePower,
  instanceProblem,
  instanceSellValue,
  isAffixGear,
  itemLevelFor,
  rollAffixCount,
  rollInstance
});
