// GENERATED by tools/build-server-rules.mjs from src/gameplay/authorityRules.ts — do not edit by hand.
// Server authority plausibility numbers (XP/gold ceilings, ground-drop rates) shared by the Death Muffin backend and the tests.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/authorityRules.ts
var authorityRules_exports = {};
__export(authorityRules_exports, {
  AREA_PEAK: () => AREA_PEAK,
  AUTHORITY: () => AUTHORITY,
  DEPTHS_AUTHORITY: () => DEPTHS_AUTHORITY,
  GROUND_RATES: () => GROUND_RATES,
  LEVEL_CAP: () => LEVEL_CAP,
  ceilingsFor: () => ceilingsFor,
  depthBound: () => depthBound,
  isGroundItem: () => isGroundItem,
  itemCap: () => itemCap,
  itemRatePerMin: () => itemRatePerMin,
  splitXp: () => splitXp,
  totalXp: () => totalXp
});
module.exports = __toCommonJS(authorityRules_exports);

// src/content/legendarySets.ts
var LEGENDARY_SETS = {
  legion_unburied: {
    disciplineId: "gravecaller",
    name: "Legion of the Unburied",
    wearer: "Gravecaller",
    color: 3809067,
    accent: 16742973,
    stats: ["stat_int", "stat_vit"],
    lore: "Forged for the one who never lets the dead lie. The legion marches in its wearer\u2019s footsteps, and does not stop.",
    pieces: { head: "Warcrown of the Unburied", chest: "Cuirass of the Unburied", hands: "Gauntlets of the Unburied", legs: "Greaves of the Unburied", feet: "Marching Boots of the Unburied" }
  },
  colossus_mantle: {
    disciplineId: "ossuary",
    name: "Colossus Mantle",
    wearer: "Ossuary",
    color: 8221269,
    accent: 15915402,
    stats: ["stat_int", "stat_vit"],
    lore: "A giant\u2019s ribs, hung with every vow the Covenant ever broke. What strikes the wearer is struck back.",
    pieces: { head: "Colossus Cowl", chest: "Colossus Mantle", hands: "Colossus Fists", legs: "Colossus Cuisses", feet: "Colossus Footings" }
  },
  requiem_wraiths: {
    disciplineId: "mourner",
    name: "Requiem of Wraiths",
    wearer: "Mourner",
    color: 2902622,
    accent: 8381439,
    stats: ["stat_int", "stat_agi"],
    lore: "Woven from the last breath of the mourned. The wraiths still sing in it, and some of them stay to help.",
    pieces: { head: "Wraithveil Hood", chest: "Requiem Shroud", hands: "Wraithgrasp Gloves", legs: "Wraithwoven Leggings", feet: "Requiem Slippers" }
  },
  plague_choir: {
    disciplineId: "rotweaver",
    name: "Plague Choir",
    wearer: "Rotweaver",
    color: 4016668,
    accent: 11992909,
    stats: ["stat_int", "stat_vit"],
    lore: "Sung into being by a congregation that died of its own hymn. Every note it carries is catching.",
    pieces: { head: "Choirmaster\u2019s Mask", chest: "Plague Choir Surplice", hands: "Blightmonger\u2019s Gloves", legs: "Choir Rotleggings", feet: "Plague Choir Treads" }
  }
};
var LEGENDARY_SET_IDS = Object.keys(LEGENDARY_SETS);
var legendaryItemId = (setId, part) => `leg_${setId}_${part}`;
var LEGENDARY_DROP = {
  /**
   * Per boss kill, the SHALLOWEST rolling boss (the Bone Abbess); deeper bosses climb from here (`LEGENDARY_BOSS_CHANCE`). Owner, 3 Oct 2026:
   * "drop rates are like 3%... let's make it more achievable": it was a flat 15% (and 3% for the Gravedigger King), which the Atlas
   * showed as about 2% per piece.
   */
  bossChance: 0.2,
  /** Per Gravedigger King kill (the starter boss, Hollow Graves): lower, so the first legendary can be seen early (owner, 3 Oct 2026). */
  starterBossChance: 0.06,
  /** Per elite kill in the SHALLOWEST level-scaled area (Plague Cloister); the Pyre and the Fen climb from here (`LEGENDARY_ELITE_CHANCE`). */
  eliteChance: 5e-3,
  /** Smart loot: the share of legendary drops that is the player's own discipline's set (the rest splits evenly over the others). */
  ownShare: 0.7
};
var LEGENDARY_BOSS_AREAS = ["ossuary", "nave", "sanctum", "cloister", "pyre", "fen"];
var LEGENDARY_STARTER_AREA = "graves";
var LEGENDARY_BOSS_CHANCE = { ossuary: 0.2, nave: 0.22, sanctum: 0.25, cloister: 0.28, pyre: 0.3, fen: 0.33 };
var LEGENDARY_ELITE_CHANCE = { cloister: 5e-3, pyre: 7e-3, fen: 9e-3 };
var legendaryBossChance = (area) => LEGENDARY_BOSS_AREAS.includes(area) ? LEGENDARY_BOSS_CHANCE[area] ?? LEGENDARY_DROP.bossChance : area === LEGENDARY_STARTER_AREA ? LEGENDARY_DROP.starterBossChance : 0;
var legendaryEliteChance = (area) => LEGENDARY_ELITE_CHANCE[area] ?? 0;

// src/content/armorSets.ts
var ARMOR_PARTS = ["head", "chest", "hands", "legs", "feet"];
var ARMOR_SETS = {
  gravecaller: { name: "Gravecall", wearer: "Gravecaller", color: 8485789, accent: 13090268, stats: ["stat_int", "stat_vit"], lore: "Stitched for those who command the newly buried." },
  warden: { name: "Lamplight", wearer: "Grave Warden", color: 9531463, accent: 16039271, stats: ["stat_vit", "stat_str"], lore: "Brass and soot from the grave watch." },
  monk: { name: "Bellwake", wearer: "Bell Monk", color: 9533794, accent: 14991750, stats: ["stat_str", "stat_agi"], lore: "Worn thin by a thousand measured tolls." },
  ossuary: { name: "Ivory Reliquary", wearer: "Ossuary", color: 13813672, accent: 10194658, stats: ["stat_int", "stat_vit"], lore: "Bone plates engraved with the Covenant dead." },
  mourner: { name: "Widowveil", wearer: "Mourner", color: 6711948, accent: 10795488, stats: ["stat_int", "stat_agi"], lore: "Funeral cloth that remembers every name." },
  witch: { name: "Carrionbloom", wearer: "Carrion Witch", color: 6452546, accent: 12966528, stats: ["stat_int", "stat_vit"], lore: "Living thorns bind the seams shut." },
  rotweaver: { name: "Blightweave", wearer: "Rotweaver", color: 7636039, accent: 13231213, stats: ["stat_int", "stat_vit"], lore: "A sickly mantle spun where the plague took root." },
  knight: { name: "Hollow Oath", wearer: "Hollow Knight", color: 6712188, accent: 13193039, stats: ["stat_str", "stat_vit"], lore: "Blackened plate still bearing its broken vow." },
  veil: { name: "Threshold", wearer: "Veilwalker", color: 6709646, accent: 11445744, stats: ["stat_agi", "stat_int"], lore: "A border of silver marks the edge between worlds." }
};
var ASCENDED_ARMOR_SETS = {
  gravecaller: { name: "Epitaph Sovereign", wearer: "Gravecaller", color: 4208735, accent: 14141951, stats: ["stat_int", "stat_vit"], lore: "A sovereign name is written on every bone clasp." },
  warden: { name: "Nightwatch Beacon", wearer: "Grave Warden", color: 5195318, accent: 16766070, stats: ["stat_vit", "stat_str"], lore: "Its caged flame answers the last watch bell." },
  monk: { name: "Last Toll", wearer: "Bell Monk", color: 6508865, accent: 16768412, stats: ["stat_str", "stat_agi"], lore: "Bronze thread hums with the final note." },
  ossuary: { name: "Marrow Regent", wearer: "Ossuary", color: 11970690, accent: 15985870, stats: ["stat_int", "stat_vit"], lore: "The reliquary opens only for its bearer." },
  mourner: { name: "Pale Requiem", wearer: "Mourner", color: 4540776, accent: 13163775, stats: ["stat_int", "stat_agi"], lore: "A hush follows wherever the silver hem falls." },
  witch: { name: "Thorn Covenant", wearer: "Carrion Witch", color: 3888702, accent: 12120461, stats: ["stat_int", "stat_vit"], lore: "The roots draw strength from what lies beneath." },
  rotweaver: { name: "Virulent Choir", wearer: "Rotweaver", color: 4676390, accent: 14679921, stats: ["stat_int", "stat_vit"], lore: "A bright plague song runs through its seams." },
  knight: { name: "Oathbreaker", wearer: "Hollow Knight", color: 3488070, accent: 16742255, stats: ["stat_str", "stat_vit"], lore: "The oath is broken; the shield remains." },
  veil: { name: "Umbral Crossing", wearer: "Veilwalker", color: 3748950, accent: 13154559, stats: ["stat_agi", "stat_int"], lore: "The wearer leaves no shadow on either side." }
};
var PART_NAMES = { head: "Crown", chest: "Vestment", hands: "Grips", legs: "Legguards", feet: "Treads" };
var PART_POWER = { head: 2, chest: 4, hands: 2, legs: 3, feet: 2 };
var RARITY_SCALE = { common: 1, uncommon: 1, rare: 2, epic: 3, legendary: 4 };
var PART_AREA = { head: "graves", hands: "graves", chest: "ossuary", legs: "nave", feet: "sanctum" };
var PART_RARITY = { head: "uncommon", hands: "uncommon", chest: "rare", legs: "rare", feet: "epic" };
var ASCENDED_AREA = { head: "sanctum", hands: "sanctum", chest: "cloister", legs: "cloister", feet: "pyre" };
var ASCENDED_RARITY = { head: "rare", hands: "rare", chest: "epic", legs: "epic", feet: "epic" };
function piecesFor(sets, collection) {
  return Object.entries(sets).flatMap(([disciplineId, set]) => ARMOR_PARTS.map((part) => ({
    id: collection === 1 ? `set_${disciplineId}_${part}` : `set_${disciplineId}_ascended_${part}`,
    setId: collection === 1 ? disciplineId : `${disciplineId}_ascended`,
    disciplineId,
    collection,
    setName: set.name,
    part,
    name: `${set.name} ${PART_NAMES[part]}`,
    type: `armor_${part}`,
    rarity: collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part],
    area: collection === 1 ? PART_AREA[part] : ASCENDED_AREA[part],
    stats: { [set.stats[0]]: PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] + (collection === 2 ? 1 : 0), [set.stats[1]]: Math.max(1, Math.floor(PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] / 2)) },
    color: set.color,
    accent: set.accent,
    wearer: set.wearer,
    lore: set.lore,
    sell: PART_POWER[part] * ((collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "epic" ? 22 : (collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "rare" ? 13 : 7) + (collection === 2 ? 20 : 0)
  })));
}
function legendaryPieces() {
  return Object.entries(LEGENDARY_SETS).flatMap(([setId, set]) => ARMOR_PARTS.map((part) => ({
    id: legendaryItemId(setId, part),
    setId,
    disciplineId: set.disciplineId,
    collection: 3,
    setName: set.name,
    part,
    name: set.pieces[part],
    type: `armor_${part}`,
    rarity: "legendary",
    // Not an area drop: bosses (and rare elites in scaled areas) roll legendaries. The area is the deepest one, for the tables that need one.
    area: "pyre",
    stats: { [set.stats[0]]: PART_POWER[part] * 3 + 3, [set.stats[1]]: Math.floor(PART_POWER[part] * 1.5) + 1 },
    color: set.color,
    accent: set.accent,
    wearer: set.wearer,
    lore: set.lore,
    sell: PART_POWER[part] * 30 + 60
  })));
}
var ARMOR_PIECES = [...piecesFor(ARMOR_SETS, 1), ...piecesFor(ASCENDED_ARMOR_SETS, 2), ...legendaryPieces()];
var ARMOR_BY_ID = Object.fromEntries(ARMOR_PIECES.map((piece) => [piece.id, piece]));
function armorLoot(area) {
  if (area === "fen") return ARMOR_PIECES.filter((piece) => piece.collection === 2).map((piece) => ({ item: piece.id, weight: 1 }));
  return ARMOR_PIECES.filter((piece) => piece.collection !== 3).filter((piece) => piece.area === area || piece.collection === 1 && (area === "cloister" || area === "pyre") && piece.area !== "graves" || piece.collection === 2 && area === "pyre" && piece.area === "cloister").map((piece) => ({ item: piece.id, weight: 1 }));
}

// src/content/necroWeapons.ts
var NECRO_TIERS = ["bone", "iron", "gold", "hell", "moon"];
var NECRO_WEAPON_TUNING = {
  staff: {
    /** Needle reach: +25%. */
    needleRangeMult: 1.25,
    /** Extra enemies the needle passes through behind its target, and what they take relative to the first. */
    pierce: 1,
    pierceDamageMult: 0.8,
    /** The pierced enemy must be within this distance of the needle's line, and this far behind the target. */
    pierceLane: 1.1,
    pierceReach: 4.5,
    /** Passive: +10% spell damage (folded into derived Spell power, so the stats line shows it). */
    spellDamageMult: 1.1
  },
  scythe: {
    /** LMB becomes a close reaping arc: full cone angle (degrees), reach (metres), targets hit. */
    arcDeg: 100,
    reach: 3,
    /** Reach against a boss (owner, 3 Oct 2026): the long blade lets a reaper fight from the edge of a boss's cones and rings instead of inside them. */
    bossReach: 4,
    maxHits: 3,
    /** Per-target damage relative to a Needle hit, cooldown and lock (a heavier, slower swing), essence per target struck. */
    damageMult: 1.15,
    cooldownMs: 520,
    lockMs: 110,
    gestureSeconds: 0.3,
    essencePerHit: 4,
    /** Bonus souls for a kill the arc delivered, on top of the normal soul every kill gives. */
    soulsPerKill: 1,
    /** How long (ms) a struck enemy still counts as reaped when it dies. */
    reapWindowMs: 1200
  },
  wand: {
    /** Needle cooldown and cast lock are divided by this (+30% cadence). */
    cadenceMult: 1.3,
    /** Needle damage: -15%. */
    damageMult: 0.85
  },
  sickle: {
    /** Each needle adds this many Withered stacks (up to the discipline's cap). */
    witheredStacks: 1,
    /** Passive: Exhume gives back this share of its essence cost. */
    exhumeRefund: 0.2
  },
  skull_focus: {
    /** Thrall cap bonus at or above this tier. */
    thrallCap: 1,
    minTier: "gold"
  },
  grimoire: {
    /** Every rite (not the LMB primary) recovers 10% sooner. */
    riteCooldownMult: 0.9
  },
  mourning_bell: {
    /** A Mourner's wraith hit heals every ally in this range by this share of their max health. */
    allyHealFrac: 0.02,
    allyHealRange: 14
  }
};
var NECRO_TIER_INFO = {
  bone: { label: "Bone", level: 1, rarity: "common", sellMult: 1, area: ["graves", "warren"] },
  iron: { label: "Iron", level: 15, rarity: "uncommon", sellMult: 2.4, area: ["ossuary", "coliseum"] },
  gold: { label: "Gold", level: 30, rarity: "rare", sellMult: 5.5, area: ["nave", "sanctum"] },
  hell: { label: "Hell", level: 45, rarity: "epic", sellMult: 11, area: ["cloister", "pyre"] },
  moon: { label: "Moon", level: 60, rarity: "epic", sellMult: 22, area: ["pyre"] }
};
var PALETTE = {
  bone: { color: 14208957, accent: 15985881 },
  iron: { color: 8027526, accent: 12830674 },
  gold: { color: 14263361, accent: 16769946 },
  hell: { color: 9054746, accent: 16742973 },
  moon: { color: 11188456, accent: 15002623 }
};
var T = NECRO_WEAPON_TUNING;
var pct = (n) => `${Math.round(n * 100)}%`;
var KINDS = {
  staff: {
    label: "Staff",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Vertebral Staff", iron: "Crypt-Iron Crozier", gold: "Reliquary Staff", hell: "Hellcoal Crozier", moon: "Staff of the Pale Moon" },
    int: [5, 9, 15, 22, 30],
    second: { key: "stat_vit", values: [0, 1, 2, 4, 6] },
    sell: 16,
    lore: {
      bone: "Fused vertebrae, still warm from the hand that carried it. Bone Needles fly farther and pierce a second body.",
      iron: "A grave-watch crozier with a bell-metal cap. Bone Needles fly farther and pierce a second body.",
      gold: "Tithe-gold wound round a reliquary shaft. Bone Needles fly farther and pierce a second body.",
      hell: "Quenched in pyre-coal; the skull at its head never stops smoking. Bone Needles fly farther and pierce a second body.",
      moon: "Cut from a bone that never touched the ground. Bone Needles fly farther and pierce a second body."
    },
    effect: `Bone Needle: +${pct(T.staff.needleRangeMult - 1)} range, pierces ${T.staff.pierce} extra target. Passive: +${pct(T.staff.spellDamageMult - 1)} spell damage. Two-handed.`
  },
  scythe: {
    label: "Scythe",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Gleaner's Scythe", iron: "Sexton's Scythe", gold: "Tithe-Reaper", hell: "Pyre Reaper", moon: "Moonreaper" },
    int: [4, 8, 13, 19, 26],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 18,
    lore: {
      bone: "A gleaner cuts what the living left standing. Your left click becomes a reaping arc; kills in it yield a soul.",
      iron: "The sexton swings it at dusk, in rows. Your left click becomes a reaping arc; kills in it yield a soul.",
      gold: "Every swing tolls a coin against the dead. Your left click becomes a reaping arc; kills in it yield a soul.",
      hell: "Its edge glows where it has drunk ash. Your left click becomes a reaping arc; kills in it yield a soul.",
      moon: "The last harvest is always by moonlight. Your left click becomes a reaping arc; kills in it yield a soul."
    },
    effect: `Left click becomes a ${T.scythe.arcDeg}\xB0 reaping arc (${T.scythe.reach} m, ${T.scythe.bossReach} m against a boss, hits up to ${T.scythe.maxHits}); kills in the arc give +${T.scythe.soulsPerKill} soul. Two-handed.`
  },
  wand: {
    label: "Wand",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Knucklebone Wand", iron: "Iron Mourning Wand", gold: "Gilded Censer Wand", hell: "Emberthorn Wand", moon: "Wand of Quiet Stars" },
    int: [3, 6, 10, 15, 21],
    second: { key: "stat_agi", values: [0, 1, 2, 3, 5] },
    sell: 12,
    lore: {
      bone: "Finger bones, bound in a hurry. Bone Needles come faster and strike softer.",
      iron: "A mourner flicks it like a hand-bell. Bone Needles come faster and strike softer.",
      gold: "A censer chain wound round the grip. Bone Needles come faster and strike softer.",
      hell: "Thorned, and warm to the touch. Bone Needles come faster and strike softer.",
      moon: "It weighs nothing, and is never quite still. Bone Needles come faster and strike softer."
    },
    effect: `Bone Needle: +${pct(T.wand.cadenceMult - 1)} cadence, -${pct(1 - T.wand.damageMult)} damage. One-handed: pair it with an off-hand.`
  },
  sickle: {
    label: "Ritual Sickle",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Barrow Sickle", iron: "Plague Sickle", gold: "Sexton's Gilded Sickle", hell: "Blightfire Sickle", moon: "Moonrot Sickle" },
    int: [3, 6, 10, 14, 20],
    second: { key: "stat_vit", values: [1, 2, 3, 5, 7] },
    sell: 13,
    lore: {
      bone: "A curved rib, sharpened on a headstone. Bone Needles leave the target Withered; Exhume returns essence.",
      iron: "The plague priests cut herbs and throats with it. Bone Needles leave the target Withered; Exhume returns essence.",
      gold: "Gilded for rites nobody admits to. Bone Needles leave the target Withered; Exhume returns essence.",
      hell: "The rot burns instead of festering. Bone Needles leave the target Withered; Exhume returns essence.",
      moon: "Its blade is etched with a blight the moon forgave. Bone Needles leave the target Withered; Exhume returns essence."
    },
    effect: `Bone Needle applies ${T.sickle.witheredStacks} Withered stack. Passive: Exhume refunds ${pct(T.sickle.exhumeRefund)} of its essence. One-handed.`
  },
  skull_focus: {
    label: "Skull Focus",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Skull Focus", iron: "Iron-Jawed Skull Focus", gold: "Gilded Skull Focus", hell: "Cinder Skull Focus", moon: "Moon Skull Focus" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 10,
    lore: {
      bone: "A nameless skull that still listens. (Gold and better skulls hold one more thrall.)",
      iron: "Its jaw is wired shut so it cannot argue. (Gold and better skulls hold one more thrall.)",
      gold: "It remembers a legion. Hold it and command one more thrall.",
      hell: "The eyes glow like coals in a cold hearth. Hold it and command one more thrall.",
      moon: "It was a king, once; it still expects to be obeyed. Hold it and command one more thrall."
    },
    effect: `Off-hand. Gold tier and above: +${T.skull_focus.thrallCap} thrall cap.`
  },
  grimoire: {
    label: "Grimoire",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Gravedigger's Grimoire", iron: "Iron-Clasped Grimoire", gold: "Gilt Reliquary Grimoire", hell: "Hellbound Grimoire", moon: "Moonlit Grimoire" },
    int: [2, 4, 7, 10, 14],
    sell: 11,
    lore: {
      bone: "A gravedigger's ledger of names and their uses. Rites recover sooner.",
      iron: "Chained shut, and opened only from the inside. Rites recover sooner.",
      gold: "Every page is gilt, every margin a warning. Rites recover sooner.",
      hell: "Its binding is singed along the spine. Rites recover sooner.",
      moon: "The pages turn themselves to the rite you need. Rites recover sooner."
    },
    effect: `Off-hand. Rites (your other spells, not the left click) recover ${pct(1 - T.grimoire.riteCooldownMult)} faster.`
  },
  mourning_bell: {
    label: "Mourning Bell",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Mourning Bell", iron: "Iron Mourning Bell", gold: "Gilded Mourning Bell", hell: "Cinder Mourning Bell", moon: "Moon Mourning Bell" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_agi", values: [1, 2, 3, 5, 7] },
    sell: 10,
    lore: {
      bone: "Rung once for each name you could not save. A Mourner's wraith hits mend allies.",
      iron: "Its note is flat on purpose. A Mourner's wraith hits mend allies.",
      gold: "The clapper is wrapped in widow's silk. A Mourner's wraith hits mend allies.",
      hell: "It tolls for the ones who should have stayed buried. A Mourner's wraith hits mend allies.",
      moon: "You hear it a moment before it rings. A Mourner's wraith hits mend allies."
    },
    effect: `Off-hand. Mourner: each wraith hit heals allies in ${T.mourning_bell.allyHealRange} m for ${pct(T.mourning_bell.allyHealFrac)} of their max health.`
  }
};
var NECRO_KIND_LABEL = Object.fromEntries(Object.entries(KINDS).map(([k, d]) => [k, d.label]));
function build() {
  const out = [];
  for (const [kind, def] of Object.entries(KINDS)) {
    NECRO_TIERS.forEach((tier, i) => {
      const info = NECRO_TIER_INFO[tier];
      const stats = { stat_int: def.int[i] };
      if (def.second && def.second.values[i] > 0) stats[def.second.key] = def.second.values[i];
      out.push({
        id: `${kind}_${tier}`,
        kind,
        tier,
        name: def.names[tier],
        type: def.type,
        slot: def.slot,
        twoHanded: def.twoHanded,
        rarity: info.rarity,
        level: info.level,
        stats,
        sell: Math.round(def.sell * info.sellMult),
        lore: def.lore[tier],
        effect: def.effect,
        color: PALETTE[tier].color,
        accent: PALETTE[tier].accent
      });
    });
  }
  return out;
}
var NECRO_WEAPONS = build();
var NECRO_WEAPON_BY_ID = Object.fromEntries(NECRO_WEAPONS.map((w) => [w.id, w]));
function necroWeaponLoot(area) {
  const out = [];
  for (const w of NECRO_WEAPONS) {
    if (!NECRO_TIER_INFO[w.tier].area.includes(area)) continue;
    out.push({ item: w.id, weight: w.tier === "moon" ? 0.5 : 1 });
  }
  return out;
}
var WOOD_KINDS = ["staff", "wand", "grimoire"];
var WOOD_RECIPE = {
  bone: { level: 3, ing: [["plank_oak", 3], ["bones_old", 2]] },
  iron: { level: 8, ing: [["plank_elm", 3], ["ingot_iron", 1]] },
  gold: { level: 18, ing: [["plank_willow", 3], ["ingot_gold", 1]] },
  hell: { level: 42, ing: [["plank_yew", 3], ["ingot_hell", 1]] },
  moon: { level: 57, ing: [["plank_blackthorn", 3], ["ingot_moon", 1]] }
};
var SMITH_RECIPE = {
  bone: { level: 2, ing: [["ingot_copper", 2], ["bones_old", 3]] },
  iron: { level: 10, ing: [["ingot_iron", 3]] },
  gold: { level: 20, ing: [["ingot_gold", 3], ["ingot_iron", 1]] },
  hell: { level: 40, ing: [["ingot_hell", 3], ["ingot_gold", 1]] },
  moon: { level: 55, ing: [["ingot_moon", 3], ["ingot_hell", 1]] }
};
var NECRO_RECIPES = NECRO_WEAPONS.map((w) => {
  const wood = WOOD_KINDS.includes(w.kind);
  const r = (wood ? WOOD_RECIPE : SMITH_RECIPE)[w.tier];
  return [`craft_${w.id}`, w.name, wood ? "woodcutting" : "mining", r.level, w.id, 1, r.ing];
});

// src/content/npcSpots.ts
var NPC_IDS = ["prior", "sexton", "apothecary"];
var NPC_SPOTS = {
  prior: { area: "chapterhouse", x: -3.4, z: 15.8, label: "The Prior" },
  sexton: { area: "acre", x: -26, z: 23, label: "The Sexton" },
  // In front of her counter in the Alchemist's Wing (the counter itself stands at areas.ts WING_APOTHECARY_SPOT, x 45.1).
  apothecary: { area: "alchemist_wing", x: 42.6, z: 20, label: "The Apothecary" }
};
var npcInteractableId = (id) => `npc_${id}`;

// src/content/areas.ts
var npcSpots = (area) => NPC_IDS.filter((n) => NPC_SPOTS[n].area === area).map((n) => ({ id: npcInteractableId(n), kind: "npc", label: NPC_SPOTS[n].label, x: NPC_SPOTS[n].x, z: NPC_SPOTS[n].z }));
var DEPTHS_RECT = { x0: 150, z0: -60, x1: 190, z1: -24 };
var DEPTHS_STAIR = { x: -67.2, z: -30 };
var AREAS = {
  chapterhouse: {
    id: "chapterhouse",
    name: "The Chapterhouse",
    subtitle: "Sanctuary of the Ossuary Covenant",
    theme: "chapter",
    rect: { x0: -13, z0: 8, x1: 13, z1: 32 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "reliquary", kind: "inventory", label: "Reliquary", x: -8.5, z: 14 },
      { id: "workbench", kind: "forge", label: "Ossuary Workbench", x: 8.5, z: 14 },
      { id: "niches", kind: "professions", label: "Rite Niches", x: -10.8, z: 26.5 },
      { id: "altar", kind: "upgrades", label: "Altar of Ascension", x: 0, z: 21 },
      { id: "waystone_chapterhouse", kind: "waystone", label: "Waystone", x: 9, z: 26.5 },
      // The Ossuary Vault: the sarcophagus between the Altar and the south braziers (shared stash, key V).
      { id: "ossuary_vault", kind: "vault", label: "Ossuary Vault", x: 0, z: 27 },
      ...npcSpots("chapterhouse")
    ],
    ambient: { fog: 722960, hemiSky: 3877458, hemiGround: 657168, moon: 9412305 }
  },
  // The non-combat gathering zone: every tier of every gathering node, no waves (roadmap §6).
  acre: {
    id: "acre",
    name: "The Sexton's Acre",
    subtitle: "Where the Covenant's dead are tended",
    theme: "acre",
    rect: { x0: -62, z0: 6, x1: -20, z1: 38 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "waystone_acre", kind: "waystone", label: "Waystone", x: -23, z: 25.5 },
      { id: "sawpit", kind: "sawpit", label: "Sawpit", x: -23.5, z: 12.5 },
      { id: "bone_kiln", kind: "kiln", label: "Bone Kiln", x: -23.5, z: 31.6 },
      // Salvaging: grinds spare gear into materials and reagents.
      { id: "bone_grinder", kind: "grinder", label: "Bone Grinder", x: -27, z: 33.2 },
      { id: "cooking_fire", kind: "fire", label: "Cooking Fire", x: -26.5, z: 28.5 },
      { id: "lectern", kind: "lectern", label: "Covenant Lectern", x: -24.2, z: 17.8 },
      ...npcSpots("acre")
    ],
    ambient: { fog: 790288, hemiSky: 6978706, hemiGround: 3820088, moon: 12307416 }
  },
  graves: {
    id: "graves",
    name: "The Hollow Graves",
    subtitle: "Where the Covenant buries what it cannot keep",
    theme: "graveyard",
    rect: { x0: -26, z0: -36, x1: 26, z1: 4 },
    safe: false,
    level: 1,
    enemies: [
      { id: "robber", weight: 52 },
      { id: "hound", weight: 24 },
      { id: "penitent", weight: 11 },
      { id: "sac", weight: 7 },
      { id: "moth", weight: 6 },
      { id: "bat", weight: 5 },
      { id: "ghoul", weight: 6 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6500,
    eliteChance: 0.035,
    loot: [
      ...armorLoot("graves"),
      ...necroWeaponLoot("graves"),
      { item: "material_copper_shard", weight: 30 },
      { item: "ore_copper", weight: 24 },
      { item: "ore_tin", weight: 14 },
      { item: "flask_hp_minor", weight: 12 },
      { item: "log_oak", weight: 8 },
      { item: "ring_copper", weight: 4 },
      { item: "helm_copper", weight: 4 },
      { item: "staff_oak", weight: 3 }
    ],
    itemChance: 0.08,
    breaches: [
      [-18, -29],
      [0, -31],
      [18, -29],
      [-21, -13],
      [21, -11],
      [9, -19],
      [-9, -21],
      [20, -24],
      [-14, -3],
      [14, -4]
    ],
    interactables: [
      { id: "waystone_graves", kind: "waystone", label: "Waystone", x: -5.5, z: 1 },
      // Area bosses (content/bosses.ts summonSpot: each arena's north edge).
      { id: "kings_grave", kind: "boss", label: "The King's Grave", x: -14, z: -30.5 }
    ],
    ambient: { fog: 854548, hemiSky: 4601962, hemiGround: 722960, moon: 10135252 }
  },
  ossuary: {
    id: "ossuary",
    name: "The Marrow Ossuary",
    subtitle: "Ten thousand skulls, and all of them listening",
    theme: "ossuary",
    rect: { x0: 32, z0: -38, x1: 64, z1: -2 },
    safe: false,
    level: 5,
    enemies: [
      { id: "robber", weight: 30 },
      { id: "hound", weight: 30 },
      { id: "sac", weight: 18 },
      { id: "deacon", weight: 12 },
      { id: "penitent", weight: 10 },
      { id: "rat", weight: 10 },
      { id: "golem", weight: 2 },
      { id: "moth", weight: 5 },
      { id: "bat", weight: 4 },
      { id: "ghoul", weight: 4 }
    ],
    cap: 32,
    waveSize: 10,
    waveIntervalMs: 6200,
    eliteChance: 0.045,
    unlock: { area: "graves", kills: 300 },
    loot: [
      ...armorLoot("ossuary"),
      ...necroWeaponLoot("ossuary"),
      { item: "ore_iron", weight: 24 },
      { item: "ore_copper", weight: 14 },
      { item: "material_copper_bar", weight: 14 },
      { item: "ore_bronze", weight: 10 },
      { item: "flask_hp_minor", weight: 10 },
      { item: "augment_copper", weight: 5 },
      { item: "sword_copper", weight: 4 },
      { item: "plate_copper", weight: 4 },
      { item: "helm_iron", weight: 3 }
    ],
    itemChance: 0.09,
    breaches: [[38, -33], [50, -35], [60, -27], [60, -9], [46, -6], [39, -18], [54, -19], [44, -27]],
    interactables: [
      { id: "waystone_ossuary", kind: "waystone", label: "Waystone", x: 35.5, z: -6 },
      { id: "abbess_reliquary", kind: "boss", label: "The Abbess's Reliquary", x: 48, z: -32.5 }
    ],
    ambient: { fog: 920332, hemiSky: 4207434, hemiGround: 854281, moon: 12036494 }
  },
  nave: {
    id: "nave",
    name: "The Drowned Nave",
    subtitle: "The congregation never stopped kneeling",
    theme: "nave",
    rect: { x0: -15, z0: -96, x1: 15, z1: -44 },
    safe: false,
    level: 9,
    enemies: [
      { id: "penitent", weight: 23 },
      { id: "robber", weight: 27 },
      { id: "deacon", weight: 15 },
      { id: "sac", weight: 16 },
      { id: "hound", weight: 19 },
      { id: "wraith", weight: 12 },
      { id: "censer", weight: 6 },
      { id: "gargoyle", weight: 8 },
      { id: "bat", weight: 7 },
      { id: "acolyte", weight: 8 },
      { id: "templar", weight: 3 }
    ],
    cap: 34,
    waveSize: 11,
    waveIntervalMs: 6e3,
    eliteChance: 0.055,
    unlock: { area: "ossuary", kills: 420 },
    loot: [
      ...armorLoot("nave"),
      ...necroWeaponLoot("nave"),
      { item: "ore_silver", weight: 20 },
      { item: "ore_iron", weight: 20 },
      { item: "ore_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "augment_iron", weight: 5 },
      { item: "helm_iron", weight: 6 },
      { item: "chest_iron", weight: 4 }
    ],
    itemChance: 0.1,
    breaches: [[-11, -91], [11, -91], [-11, -72], [11, -72], [-11, -53], [11, -53], [0, -82], [0, -62]],
    interactables: [
      { id: "waystone_nave", kind: "waystone", label: "Waystone", x: 6, z: -47.5 },
      { id: "drowned_font", kind: "boss", label: "The Drowned Font", x: 0, z: -70.35 }
    ],
    ambient: { fog: 723220, hemiSky: 3352666, hemiGround: 525839, moon: 9406168 }
  },
  sanctum: {
    id: "sanctum",
    name: "The Bell Sanctum",
    subtitle: "Seat of the Bell-Sworn Prelate",
    theme: "sanctum",
    rect: { x0: -18, z0: -130, x1: 18, z1: -102 },
    safe: false,
    level: 13,
    enemies: [
      { id: "penitent", weight: 30 },
      { id: "deacon", weight: 20 },
      { id: "robber", weight: 20 },
      { id: "hound", weight: 20 },
      { id: "sac", weight: 10 },
      { id: "censer", weight: 10 },
      { id: "wraith", weight: 10 },
      { id: "golem", weight: 4 },
      { id: "gargoyle", weight: 8 },
      { id: "seraph", weight: 7 },
      { id: "acolyte", weight: 8 },
      { id: "templar", weight: 6 }
    ],
    cap: 26,
    waveSize: 8,
    waveIntervalMs: 6500,
    eliteChance: 0.07,
    unlock: { area: "nave", kills: 520 },
    loot: [
      ...armorLoot("sanctum"),
      ...necroWeaponLoot("sanctum"),
      { item: "ore_gold", weight: 18 },
      { item: "ore_steel", weight: 14 },
      { item: "ingot_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "chest_iron", weight: 7 },
      { item: "helm_gold", weight: 5 },
      { item: "kit_iron_warden", weight: 5 }
    ],
    itemChance: 0.12,
    breaches: [[-14, -126], [14, -126], [-15, -109], [15, -109]],
    interactables: [
      { id: "waystone_sanctum", kind: "waystone", label: "Waystone", x: 6, z: -105 },
      { id: "sundered_bell", kind: "boss", label: "The Sundered Bell", x: 0, z: -123.4 }
    ],
    ambient: { fog: 1050644, hemiSky: 4006738, hemiGround: 787980, moon: 10848984 }
  },
  cloister: {
    id: "cloister",
    name: "The Plague Cloister",
    subtitle: "Where the blight grows with you",
    theme: "cloister",
    rect: { x0: 24, z0: -134, x1: 64, z1: -98 },
    safe: false,
    level: 20,
    scaling: { minLevel: 20 },
    enemies: [
      { id: "plague_doctor", weight: 22 },
      { id: "flagellant", weight: 24 },
      { id: "sac", weight: 14 },
      { id: "rat", weight: 10 },
      { id: "acolyte", weight: 8 },
      { id: "censer", weight: 8 },
      { id: "moth", weight: 6 },
      { id: "templar", weight: 5 },
      { id: "golem", weight: 3 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6e3,
    eliteChance: 0.08,
    unlock: { area: "sanctum", kills: 600 },
    loot: [
      ...armorLoot("cloister"),
      ...necroWeaponLoot("cloister"),
      { item: "ore_steel", weight: 14 },
      { item: "ore_hell", weight: 12 },
      { item: "ore_moon", weight: 6 },
      { item: "ingot_steel", weight: 6 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "gem_bone_opal", weight: 3 },
      { item: "flask_hp_major", weight: 10 },
      { item: "flask_damage", weight: 6 },
      { item: "flask_void_resist", weight: 5 },
      { item: "helm_gold", weight: 5 },
      { item: "chest_iron", weight: 5 }
    ],
    itemChance: 0.14,
    breaches: [[27, -101], [61, -101], [27, -131], [61, -131], [44, -100.5], [62, -116]],
    interactables: [
      { id: "waystone_cloister", kind: "waystone", label: "Waystone", x: 27.5, z: -111 },
      { id: "saints_litter", kind: "boss", label: "The Saint's Litter", x: 44, z: -129.5 }
    ],
    ambient: { fog: 659464, hemiSky: 2898468, hemiGround: 461317, moon: 10273930 }
  },
  // The Cinder Pyre (2026-09-30): the fire realm past the Plague Cloister, level-scaled like it but harder.
  pyre: {
    id: "pyre",
    name: "The Cinder Pyre",
    subtitle: "Where the Covenant burns what it cannot bury",
    theme: "pyre",
    rect: { x0: 70, z0: -134, x1: 110, z1: -98 },
    safe: false,
    level: 30,
    scaling: { minLevel: 30 },
    enemies: [
      { id: "cinder_husk", weight: 30 },
      { id: "pyre_priest", weight: 20 },
      { id: "cinderhound", weight: 22 },
      { id: "slag_brute", weight: 8 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6e3,
    eliteChance: 0.09,
    unlock: { area: "cloister", kills: 700 },
    loot: [
      ...armorLoot("pyre"),
      ...necroWeaponLoot("pyre"),
      { item: "ore_hell", weight: 22 },
      { item: "ingot_hell", weight: 6 },
      { item: "ore_steel", weight: 12 },
      { item: "ingot_steel", weight: 6 },
      { item: "ore_moon", weight: 5 },
      { item: "gem_grave_garnet", weight: 8 },
      { item: "gem_bone_opal", weight: 4 },
      { item: "flask_hp_major", weight: 10 },
      { item: "flask_damage", weight: 7 },
      { item: "flask_void_resist", weight: 5 },
      { item: "helm_gold", weight: 5 },
      { item: "chest_iron", weight: 5 }
    ],
    itemChance: 0.15,
    breaches: [[73, -101], [107, -101], [73, -131], [107, -131], [90, -100.5], [108, -116], [86.5, -131.5]],
    interactables: [
      { id: "waystone_pyre", kind: "waystone", label: "Waystone", x: 73.5, z: -108 },
      // Boss summon at the arena's north edge (content/bosses.ts summonSpot).
      { id: "ember_altar", kind: "boss", label: "The Ember Altar", x: 90, z: -126.35 }
    ],
    ambient: { fog: 1312774, hemiSky: 4858898, hemiGround: 787459, moon: 14191178 }
  },
  // The Alchemist's Wing (2026-10): a safe workshop east of the Chapterhouse, reached by the Chapterhouse's east door.
  // Brewing lives here (cauldron + alembic); the reagent shelf shows what you have found. Props: layout.ts "Alchemist's Wing".
  alchemist_wing: {
    id: "alchemist_wing",
    name: "The Alchemist's Wing",
    subtitle: "Where the dead are distilled",
    theme: "wing",
    rect: { x0: 20, z0: 8, x1: 46, z1: 32 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      ...npcSpots("alchemist_wing"),
      { id: "wing_cauldron", kind: "cauldron", label: "The Great Cauldron", x: 33, z: 19.5 },
      { id: "wing_alembic", kind: "alembic", label: "Alembic", x: 24.5, z: 10.5 },
      { id: "wing_reagent_shelf", kind: "reagents", label: "Reagent Shelf", x: 38.5, z: 10.5 }
    ],
    ambient: { fog: 659469, hemiSky: 11048044, hemiGround: 2761752, moon: 13156512 }
  },
  // The Catacomb Warren (2026-09-30): a chambered side dungeon off the Hollow Graves. Half-walls divide nine chambers;
  // they break Penitent cones and Ossuary-style line of sight, so the rooms are the fun.
  warren: {
    id: "warren",
    name: "The Catacomb Warren",
    subtitle: "Nine chambers, and something is digging in each",
    theme: "warren",
    rect: { x0: -72, z0: -52, x1: -32, z1: -8 },
    safe: false,
    level: 4,
    enemies: [
      { id: "rat", weight: 30 },
      { id: "robber", weight: 22 },
      { id: "ghoul", weight: 14 },
      { id: "bat", weight: 12 },
      { id: "sac", weight: 10 },
      { id: "hound", weight: 8 },
      { id: "penitent", weight: 4 }
    ],
    cap: 26,
    waveSize: 8,
    waveIntervalMs: 6400,
    eliteChance: 0.045,
    unlock: { area: "graves", kills: 150 },
    loot: [
      ...necroWeaponLoot("warren"),
      { item: "bones_old", weight: 20 },
      { item: "bones_barrow", weight: 12 },
      { item: "ore_tin", weight: 18 },
      { item: "ore_iron", weight: 14 },
      { item: "material_copper_bar", weight: 10 },
      { item: "seed_mourning_moss", weight: 8 },
      { item: "flask_hp_minor", weight: 12 },
      { item: "augment_copper", weight: 5 },
      { item: "plate_copper", weight: 4 },
      { item: "helm_iron", weight: 3 }
    ],
    itemChance: 0.1,
    breaches: [[-65, -45], [-52, -45], [-39, -45], [-65, -30], [-55.5, -30], [-65, -15], [-52, -15], [-39, -15]],
    interactables: [
      { id: "waystone_warren", kind: "waystone", label: "Waystone", x: -35.5, z: -27 },
      // The way down to the Catacomb Depths (content/depths.ts): the west chamber, glowing in the dark.
      { id: "depths_stair", kind: "stair", label: "The Stair Down", x: DEPTHS_STAIR.x, z: DEPTHS_STAIR.z }
    ],
    ambient: { fog: 789e3, hemiSky: 3813926, hemiGround: 657414, moon: 11049594 }
  },
  // The Bone Coliseum (2026-09-30): a wave-gauntlet pit east of the Ossuary. Four gates, fast surges, elites everywhere,
  // the best drops before the Sanctum: for players who want a fight, not a walk.
  coliseum: {
    id: "coliseum",
    name: "The Bone Coliseum",
    subtitle: "The dead cheer for whoever is still standing",
    theme: "coliseum",
    rect: { x0: 70, z0: -46, x1: 112, z1: -10 },
    safe: false,
    level: 11,
    enemies: [
      { id: "rat", weight: 18 },
      { id: "hound", weight: 16 },
      { id: "robber", weight: 14 },
      { id: "deacon", weight: 10 },
      { id: "bat", weight: 8 },
      { id: "acolyte", weight: 9 },
      { id: "wraith", weight: 8 },
      { id: "gargoyle", weight: 8 },
      { id: "templar", weight: 6 },
      { id: "censer", weight: 5 },
      { id: "seraph", weight: 5 },
      { id: "golem", weight: 3 }
    ],
    cap: 36,
    waveSize: 14,
    waveIntervalMs: 4200,
    eliteChance: 0.13,
    unlock: { area: "ossuary", kills: 350 },
    loot: [
      ...necroWeaponLoot("coliseum"),
      { item: "ore_silver", weight: 18 },
      { item: "ore_gold", weight: 12 },
      { item: "ingot_silver", weight: 6 },
      { item: "flask_hp_major", weight: 12 },
      { item: "flask_damage", weight: 6 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "gem_bone_opal", weight: 3 },
      { item: "augment_iron", weight: 6 },
      { item: "helm_iron", weight: 6 },
      { item: "chest_iron", weight: 5 },
      { item: "kit_iron_warden", weight: 4 }
    ],
    itemChance: 0.17,
    breaches: [[91, -44], [91, -12], [110, -28], [78, -43], [78, -13], [104, -42], [104, -14], [100, -28]],
    interactables: [{ id: "waystone_coliseum", kind: "waystone", label: "Waystone", x: 73.5, z: -20 }],
    ambient: { fog: 1051658, hemiSky: 4864560, hemiGround: 788486, moon: 13678736 }
  },
  // The Mourning Fen (2026-09-30): a drowned graveyard marsh west of the Drowned Nave, level-scaled like the Pyre. Bog water slows
  // whoever wades it (content/fen.ts); the dry hummocks are where you stand. Its seal is earned in the Pyre (800 kills there) but
  // the door is the Nave's west wall: the player has cleared the Nave long before, the Pyre kills are the gate, not the walk.
  fen: {
    id: "fen",
    name: "The Mourning Fen",
    subtitle: "Where the marsh keeps the names it swallows",
    theme: "fen",
    rect: { x0: -60, z0: -100, x1: -22, z1: -60 },
    safe: false,
    level: 45,
    scaling: { minLevel: 45 },
    enemies: [
      { id: "bog_hag", weight: 18 },
      { id: "mire_leech", weight: 16 },
      { id: "fen_wisp", weight: 20 },
      { id: "drowned_sexton", weight: 8 },
      { id: "wraith", weight: 12 }
    ],
    cap: 24,
    waveSize: 9,
    waveIntervalMs: 6200,
    eliteChance: 0.09,
    unlock: { area: "pyre", kills: 800 },
    loot: [
      ...armorLoot("fen"),
      { item: "gem_void_sapphire", weight: 9 },
      { item: "gem_bone_opal", weight: 8 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "herb_bog_myrtle", weight: 14 },
      { item: "herb_drowned_lotus", weight: 8 },
      { item: "seed_bog_myrtle", weight: 4 },
      { item: "seed_drowned_lotus", weight: 3 },
      { item: "ore_moon", weight: 7 },
      { item: "ingot_hell", weight: 4 },
      { item: "flask_hp_grand", weight: 8 },
      { item: "flask_void_resist", weight: 7 },
      { item: "flask_damage", weight: 6 },
      { item: "elixir_moonlight", weight: 2 },
      { item: "helm_gold", weight: 4 }
    ],
    itemChance: 0.16,
    breaches: [[-58.5, -98.5], [-25.5, -97], [-57, -63], [-28, -63], [-41, -98.5], [-58, -80], [-41, -62]],
    interactables: [
      { id: "waystone_fen", kind: "waystone", label: "Waystone", x: -24.8, z: -85.6 },
      // Boss summon on the arena's north rim (content/bosses.ts summonSpot), on its own hummock.
      { id: "mire_altar", kind: "boss", label: "The Mire Altar", x: -42, z: -90.2 }
    ],
    ambient: { fog: 661016, hemiSky: 2771538, hemiGround: 396302, moon: 8307908, fogMult: 1.7 }
  },
  // The Catacomb Depths (2026-10-02): an endless descent reached by the stair in the Warren's west chamber. An instance, not a hall
  // on the map: this rectangle is where each run's floor is built (gameplay/depthsFloor.ts), nothing else ever stands here. Its
  // enemies, waves, level and loot are the run's (content/depths.ts, WorldSim.startDepths), so the fields below are only the defaults
  // the rest of the game reads: `level` is the display floor; `itemChance` is the chance an ordinary kill drops from the depth's ground.
  depths: {
    id: "depths",
    name: "The Catacomb Depths",
    subtitle: "Down, and further down",
    theme: "depths",
    rect: DEPTHS_RECT,
    safe: false,
    level: 12,
    scaling: { minLevel: 12 },
    instance: true,
    enemies: [
      { id: "rat", weight: 30 },
      { id: "robber", weight: 22 },
      { id: "ghoul", weight: 14 },
      { id: "bat", weight: 12 },
      { id: "sac", weight: 10 },
      { id: "hound", weight: 8 }
    ],
    cap: 24,
    waveSize: 6,
    waveIntervalMs: 3800,
    eliteChance: 0.06,
    // No table of its own: a kill's drop is rolled on the hunting ground whose gear matches the depth (content/depths.ts depthLootArea).
    loot: [],
    itemChance: 0.12,
    breaches: [],
    interactables: [],
    ambient: { fog: 657415, hemiSky: 3156516, hemiGround: 525829, moon: 10128496 }
  }
};
var AREA_ORDER = ["chapterhouse", "acre", "alchemist_wing", "graves", "warren", "ossuary", "nave", "coliseum", "depths", "sanctum", "cloister", "pyre", "fen"];
var HUNT_ORDER = AREA_ORDER.filter((id) => !AREAS[id].safe && !AREAS[id].instance);
var huntRank = (id) => HUNT_ORDER.indexOf(id);
var CHASE_WEIGHT = { base: 1.4, perRung: 0.05 };
var chaseMult = (id) => CHASE_WEIGHT.base + CHASE_WEIGHT.perRung * Math.max(0, huntRank(id));
var GENERIC_CHASE = /^(chest_iron|helm_gold|kit_iron_warden)$/;
var isChaseItem = (item2) => !!ARMOR_BY_ID[item2] || !!NECRO_WEAPON_BY_ID[item2] || GENERIC_CHASE.test(item2);
var RARITY_CHASE = { common: 1, uncommon: 1, rare: 1.25, epic: 1.5, legendary: 1.5 };
for (const id of AREA_ORDER) {
  const area = AREAS[id];
  if (!area.loot.length) continue;
  const m = chaseMult(id);
  area.loot = area.loot.map((e) => {
    if (!isChaseItem(e.item)) return e;
    const rarity = ARMOR_BY_ID[e.item]?.rarity ?? NECRO_WEAPON_BY_ID[e.item]?.rarity ?? "rare";
    return { item: e.item, weight: e.weight * m * (RARITY_CHASE[rarity] ?? 1) };
  });
}
var WING_APOTHECARY_SPOT = { x: 45.1, z: 20, facing: -Math.PI / 2 };

// src/content/runes.ts
var RUNE_IDS = [
  "rune_splinter",
  "rune_marrow_tap",
  "rune_volley",
  "rune_ossuary_ring",
  "rune_impale",
  "rune_mass_grave",
  "rune_bone_colossus",
  "rune_creeping_rot",
  "rune_contagion",
  "rune_hollow_choir",
  "rune_requiem"
];
var RUNE_TUNING = {
  /** Bone Needle. */
  splinter: { reach: 6, damageFrac: 0.3 },
  marrowTap: { essenceBonus: 4, damageMult: 0.7 },
  volley: { every: 4, needles: 3, damageFrac: 0.4, reach: 9 },
  /** Marrow Spear: the ring bursts on the cursor, pulled back to the spear's reach. */
  ring: { radius: 3, maxCastRange: 12, damageMult: 0.8 },
  impale: { rootS: 1.5, damageMult: 1.5 },
  /** Exhume. `slots` is how many legion places the colossus fills. */
  massGrave: { count: 3, statMult: 0.75, pickRadius: 4 },
  colossus: {
    corpses: 5,
    minCorpses: 3,
    slots: 2,
    pickRadius: 6,
    hpPerCorpse: 0.8,
    damagePerCorpse: 0.7,
    cleaveRadius: 2.4,
    cleaveFrac: 0.6,
    range: 2.4,
    interval: 1.2,
    speed: 4.8,
    /** Cooldown multiplier on Exhume's 500 ms (4 s), applied only to a cast that raised a Colossus. */
    cooldownMult: 8
  },
  /** Miasma Circle. */
  creepingRot: { speed: 1.5, radiusMult: 0.85, seekReach: 12 },
  contagion: { neighbours: 2, reach: 4.5, minStacks: 2 },
  /** Black Litany. */
  hollowChoir: { powerMult: 0.6 },
  requiem: { delayMs: 2e3, radiusMult: 1.7 }
};
var pct2 = (x) => `${Math.round(x * 100)}%`;
var T2 = RUNE_TUNING;
var RUNES = {
  rune_splinter: {
    id: "rune_splinter",
    name: "Rune of Splinters",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "The needle shatters on bone and the shards keep looking.",
    short: "Hits splinter to a second foe",
    lines: [`When a needle hits, a splinter flies to the nearest other enemy within ${T2.splinter.reach} m for ${pct2(T2.splinter.damageFrac)} of the damage. Under a scythe, each reaping swing throws one splinter, from the nearest enemy it struck to the nearest one it missed.`],
    cost: null
  },
  rune_marrow_tap: {
    id: "rune_marrow_tap",
    name: "Rune of Marrow-Tap",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "Every wound is a spigot.",
    short: "More essence, softer needle",
    lines: [`Each needle hit returns ${T2.marrowTap.essenceBonus} more Grave Essence. Under a scythe, each swing that lands returns ${T2.marrowTap.essenceBonus} more once, however many enemies it strikes.`],
    cost: `Needles and scythe swings hit for ${pct2(1 - T2.marrowTap.damageMult)} less.`
  },
  rune_volley: {
    id: "rune_volley",
    name: "Rune of the Volley",
    rite: "bone_needle",
    rarity: "rare",
    sell: 60,
    lore: "Four breaths, then a flock.",
    short: "Every 4th needle is a volley",
    lines: [`Every ${T2.volley.every}th needle you throw becomes a volley of ${T2.volley.needles}, aimed at ${T2.volley.needles} different enemies within ${T2.volley.reach} m (or all at one target if it stands alone). The volley returns the essence of one needle between them. Needle only: a scythe's swing is not a volley.`],
    cost: `Each volley needle hits for ${pct2(T2.volley.damageFrac)}.`
  },
  rune_ossuary_ring: {
    id: "rune_ossuary_ring",
    name: "Ossuary Ring Rune",
    rite: "marrow_spear",
    rarity: "rare",
    sell: 60,
    lore: "The dead rise in a circle, like a congregation.",
    short: "Spikes erupt in a ring",
    lines: [`Instead of a line, bone erupts in a ${T2.ring.radius} m ring at the cursor, striking everything inside and applying Fracture and Hemorrhage as usual.`],
    cost: `It no longer reaches down a long line, and strikes for ${pct2(T2.ring.damageMult)}.`
  },
  rune_impale: {
    id: "rune_impale",
    name: "Rune of Impaling",
    rite: "marrow_spear",
    rarity: "uncommon",
    sell: 25,
    lore: "One thorn, driven deep.",
    short: "Skewers and roots the first foe",
    lines: [`The spear stops at the first enemy it meets, hits it for ${pct2(T2.impale.damageMult - 1)} more and roots it for ${T2.impale.rootS} s (a boss shrugs the root off but takes the hit).`],
    cost: "It no longer pierces the line behind."
  },
  rune_mass_grave: {
    id: "rune_mass_grave",
    name: "Mass Grave Rune",
    rite: "exhume",
    rarity: "rare",
    sell: 60,
    lore: "Why dig one grave when the field is full?",
    short: "Raise up to 3 corpses at once",
    lines: [`Exhume raises up to ${T2.massGrave.count} corpses near the cursor at once, each with ${pct2(T2.massGrave.statMult)} of the usual thrall health and damage.`],
    cost: "Each thrall is weaker, and it spends more corpses."
  },
  rune_bone_colossus: {
    id: "rune_bone_colossus",
    name: "Bone Colossus Rune",
    rite: "exhume",
    rarity: "epic",
    sell: 150,
    lore: "Five dead, bound as one, and it remembers being a wall.",
    short: "Five corpses become one giant thrall",
    lines: [
      `When ${T2.colossus.minCorpses} or more corpses lie within ${T2.colossus.pickRadius} m of the one you name, Exhume consumes up to ${T2.colossus.corpses} of them and raises one Bone Colossus instead. With fewer, or while a Colossus stands, it raises an ordinary thrall.`,
      `Its health is ${(T2.colossus.hpPerCorpse * T2.colossus.corpses).toFixed(1)}x and its damage ${(T2.colossus.damagePerCorpse * T2.colossus.corpses).toFixed(1)}x a thrall's with five corpses (less with fewer), and every blow cleaves ${T2.colossus.cleaveRadius} m.`,
      `It fills ${T2.colossus.slots} legion places and you can only keep one: raising another replaces it.`
    ],
    cost: `Exhume takes ${500 * T2.colossus.cooldownMult / 1e3} s to ready again after raising a Colossus.`
  },
  rune_creeping_rot: {
    id: "rune_creeping_rot",
    name: "Creeping Rot Rune",
    rite: "miasma",
    rarity: "uncommon",
    sell: 25,
    lore: "Rot that has learned to walk.",
    short: "The circle crawls toward foes",
    lines: [`The circle drifts ${T2.creepingRot.speed} m/s toward the nearest enemy within ${T2.creepingRot.seekReach} m of it.`],
    cost: `The circle is ${pct2(1 - T2.creepingRot.radiusMult)} narrower.`
  },
  rune_contagion: {
    id: "rune_contagion",
    name: "Contagion Rune",
    rite: "miasma",
    rarity: "rare",
    sell: 60,
    lore: "It does not stop at the grave.",
    short: "Dying Withered foes infect others",
    lines: [`A Withered enemy that dies spreads its Withered stacks (minus one) to the ${T2.contagion.neighbours} nearest enemies within ${T2.contagion.reach} m, and those spread it again when they die (it needs ${T2.contagion.minStacks} stacks to jump).`],
    cost: null
  },
  rune_hollow_choir: {
    id: "rune_hollow_choir",
    name: "Hollow Choir Rune",
    rite: "black_litany",
    rarity: "rare",
    sell: 60,
    lore: "The dead sing, and are not spent.",
    short: "Your thralls sing instead of dying",
    lines: ["Black Litany no longer sacrifices your thralls. They still lend their voices to its power."],
    cost: `The burst hits for ${pct2(1 - T2.hollowChoir.powerMult)} less.`
  },
  rune_requiem: {
    id: "rune_requiem",
    name: "Requiem Rune",
    rite: "black_litany",
    rarity: "epic",
    sell: 150,
    lore: "A hymn is only terrible once it is finished.",
    short: "The burst lands 2 s later, twice as wide",
    lines: [`Black Litany marks the ground, then bursts ${T2.requiem.delayMs / 1e3} s later over ${T2.requiem.radiusMult}x the radius. Corpses and thralls are consumed when it bursts.`],
    cost: "Enemies can walk out of it, and it can take more of your thralls."
  }
};
var RUNE_ORDER = [...RUNE_IDS];
var byRarity = (...rarities) => RUNE_ORDER.filter((id) => rarities.includes(RUNES[id].rarity));
var AREA_RUNE_POOL = {
  graves: byRarity("uncommon"),
  ossuary: byRarity("uncommon", "rare"),
  nave: byRarity("uncommon", "rare"),
  sanctum: byRarity("uncommon", "rare", "epic"),
  cloister: byRarity("uncommon", "rare", "epic"),
  pyre: byRarity("uncommon", "rare", "epic"),
  fen: byRarity("uncommon", "rare", "epic"),
  warren: byRarity("uncommon", "rare"),
  coliseum: byRarity("uncommon", "rare", "epic")
};
var RUNE_WEIGHT = { uncommon: 3, rare: 2, epic: 1 };
var ELITE_RUNE_CHANCE_BY_AREA = {
  graves: 0.05,
  warren: 0.055,
  ossuary: 0.06,
  nave: 0.07,
  coliseum: 0.08,
  sanctum: 0.09,
  cloister: 0.1,
  pyre: 0.11,
  fen: 0.12
};
var ELITE_RUNE_CHANCE = ELITE_RUNE_CHANCE_BY_AREA.graves;
var eliteRuneChance = (area) => ELITE_RUNE_CHANCE_BY_AREA[area] ?? ELITE_RUNE_CHANCE;
var SURGE_RUNE_CHANCE = 0.35;
var BOSS_RUNE_POOL = {
  gravedigger: ["rune_splinter", "rune_marrow_tap", "rune_mass_grave"],
  abbess: ["rune_ossuary_ring", "rune_impale", "rune_bone_colossus", "rune_volley"],
  congregation: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir"],
  prelate: ["rune_requiem", ...RUNE_ORDER],
  saint: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir", "rune_requiem", "rune_bone_colossus"],
  regent: [...RUNE_ORDER],
  mire: [...RUNE_ORDER]
};

// src/content/depths.ts
var DEPTHS = {
  /**
   * The spec said `max(20, player) + d`. A level-20 floor is wrong for the first visitors: the Warren opens at 150 Graves kills (level ~8-12),
   * and enemy health grows 22% of a level-1 body per level (x5 at level 20 against x2.3 at level 12), so depth 1 would be a wall. The floor
   * is the Warren's own entry level instead: `max(12, your level) + depth`. A level-60 hero meets level-61 dead on depth 1 (the Pyre and the
   * Fen are level-scaled the same way) and level-80 dead on depth 20.
   */
  minLevel: 12,
  /** The hero's level is read as the highest among the living players on the floor (solo only for now). */
  levelsPerDepth: 1,
  /** Most dead alive at once on a floor (the plan's "~24"); the global cap (72) is far above it. */
  cap: 24,
  /** Every Nth floor holds a chest and gives elites one more affix. */
  chestEvery: 5,
  extraAffixEvery: 5,
  /** Elites carry at most this many affixes beyond their first (the pool holds four in all). */
  maxExtraAffixes: 3,
  /** Seconds after a floor begins before the first of the dead climbs out. */
  firstWaveDelayS: 1.4,
  /** A floor-clear banner stays this long (ms). */
  bannerMs: 3200
};
var depthEnemyLevel = (depth, heroLevel) => Math.max(DEPTHS.minLevel, Math.floor(heroLevel) || 1) + Math.floor(Math.max(1, depth) * DEPTHS.levelsPerDepth);
var depthEliteBonus = (depth) => Math.min(0.14, 5e-3 * Math.max(0, depth));
var BANDS = [
  { from: 1, add: [{ id: "rat", weight: 30 }, { id: "robber", weight: 22 }, { id: "ghoul", weight: 14 }, { id: "bat", weight: 12 }, { id: "sac", weight: 10 }, { id: "hound", weight: 8 }] },
  { from: 5, add: [{ id: "penitent", weight: 12 }, { id: "deacon", weight: 8 }, { id: "acolyte", weight: 6 }, { id: "wraith", weight: 6 }, { id: "moth", weight: 6 }] },
  { from: 10, add: [{ id: "templar", weight: 8 }, { id: "censer", weight: 6 }, { id: "gargoyle", weight: 8 }, { id: "seraph", weight: 6 }, { id: "plague_doctor", weight: 8 }, { id: "flagellant", weight: 8 }] },
  { from: 15, add: [{ id: "golem", weight: 5 }, { id: "cinder_husk", weight: 8 }, { id: "cinderhound", weight: 8 }, { id: "pyre_priest", weight: 6 }, { id: "slag_brute", weight: 5 }, { id: "bog_hag", weight: 7 }, { id: "drowned_sexton", weight: 4 }] }
];
function depthRoster(depth) {
  const out = /* @__PURE__ */ new Map();
  for (const b of BANDS) {
    if (depth < b.from) continue;
    for (const e of b.add) out.set(e.id, e.weight);
  }
  const bands = BANDS.filter((b) => depth >= b.from).length;
  const fade = Math.pow(0.6, Math.max(0, bands - 1));
  for (const e of BANDS[0].add) out.set(e.id, Math.max(3, Math.round(e.weight * fade)));
  return [...out].map(([id, weight]) => ({ id, weight }));
}
var DEPTH_LOOT_AREAS = ["ossuary", "coliseum", "sanctum", "cloister", "pyre", "fen"];
var FLOOR_DROP_CHANCE = 0.65;
var chestDrops = (depth) => 3 + Math.floor(Math.max(0, depth - 5) / 10);
function chestRunePool(depth) {
  return RUNE_ORDER.filter((id) => RUNES[id].rarity !== "epic" || depth >= 10);
}
var CHEST_PER_MIN_CEILING = 0.5;
var FLOORS_PER_MIN_CEILING = 3;

// src/content/ascension.ts
var ASCENSION = {
  /** Prelate kills this run needed before the Altar will take the run. */
  prelateKillsRequired: 1,
  /** Every enemy (and the Prelate) is this many levels older per rank. */
  levelsPerRank: 3,
  /** Gold and XP bonus per rank, on top of what the older enemies already pay. */
  rewardPerRank: 0.05,
  maxRank: 20
};

// src/content/reagents.ts
var item = (name, rarity, sell, lore, art) => ({ name, rarity, sell, lore, stack: 250, art });
var REAGENT_ITEMS = {
  reagent_grave_dust: item("Grave Dust", "common", 2, "Sifted from what the dead leave behind. Take it to the Great Cauldron in the Alchemist's Wing: four dust brew a Grave-Dust Tonic, no garden needed.", "dust"),
  reagent_wraith_ectoplasm: item("Wraith Ectoplasm", "uncommon", 8, "Cold, weightless and faintly singing. Choir Wraiths and Weeping Seraphs shed it when they unravel. Brews into haste and insight.", "ecto"),
  reagent_plague_bile: item("Plague Bile", "rare", 16, "Bottled from the Cloister dead, still green and still spoiling. The base of the lifesteal and rot-proof brews.", "bile"),
  reagent_cinder_ash: item("Cinder Ash", "rare", 16, "Grey ash with a red heart that never cools. Falls from the Pyre; brews into fire-proofing.", "ash"),
  herb_rot_cap: item("Rot-cap", "rare", 24, "A pale mushroom that grows out of the Cloister flagstones. Forage it there, or plant its seed in the Acre (Gardening 35).", "rotcap"),
  seed_rot_cap: item("Rot-cap Seed", "rare", 10, "Plant it in a Mourning Bed (Grave Gardening 35). Foraged in the Plague Cloister.", "seed_rotcap"),
  herb_ash_bloom: item("Ash-bloom", "rare", 40, "A black flower that only opens in cinders. Forage it in the Pyre, or plant its seed in the Acre (Gardening 50).", "ashbloom"),
  seed_ash_bloom: item("Ash-bloom Seed", "rare", 14, "Plant it in a Mourning Bed (Grave Gardening 50). Foraged in the Cinder Pyre.", "seed_ashbloom"),
  ichor_gravedigger: item("Gravedigger Ichor", "epic", 60, "The Gravedigger King's blood, black as churned earth. Guaranteed from his spoils; top-tier elixirs need it.", "ichor_earth"),
  ichor_abbess: item("Abbess Ichor", "epic", 60, "Marrow-pale and never quite still. Guaranteed from the Bone Abbess; top-tier elixirs need it.", "ichor_bone"),
  ichor_congregation: item("Congregation Ichor", "epic", 60, "Drowned-blue, and it hums a hymn. Guaranteed from the Drowned Congregation; top-tier elixirs need it.", "ichor_water"),
  ichor_prelate: item("Prelate Ichor", "epic", 60, "Bell-bronze and heavy. Guaranteed from the Bell-Sworn Prelate; top-tier elixirs need it.", "ichor_bell"),
  ichor_plague_saint: item("Plague Saint Ichor", "epic", 60, "The Saint's own blight, sweet and green. Guaranteed from the Plague Saint; top-tier elixirs need it.", "ichor_rot"),
  ichor_regent: item("Regent Ichor", "epic", 60, "Liquid ember that does not burn the glass. Guaranteed from the Cinder Regent; top-tier elixirs need it.", "ichor_fire")
};
var BOSS_ICHOR = {
  gravedigger: "ichor_gravedigger",
  abbess: "ichor_abbess",
  congregation: "ichor_congregation",
  prelate: "ichor_prelate",
  saint: "ichor_plague_saint",
  regent: "ichor_regent",
  mire: "ichor_mire"
};
var ELITE_REAGENT_MULT = 4;
var AREA_REAGENT_DROPS = {
  graves: [{ item: "reagent_grave_dust", chance: 0.01, qty: [1, 2] }],
  warren: [{ item: "reagent_grave_dust", chance: 0.012, qty: [1, 2] }],
  cloister: [{ item: "reagent_plague_bile", chance: 0.01, qty: [1, 1] }],
  pyre: [{ item: "reagent_cinder_ash", chance: 0.012, qty: [1, 1] }]
};
var ENEMY_REAGENT_DROPS = {
  wraith: [{ item: "reagent_wraith_ectoplasm", chance: 0.1, qty: [1, 1] }],
  seraph: [{ item: "reagent_wraith_ectoplasm", chance: 0.08, qty: [1, 1] }]
};
var brew = (name, rarity, sell, lore, def, recipe, art) => ({ name, rarity, sell, lore, def, recipe, art });
var REAGENT_BREW_LIST = [
  ["tonic_grave_dust", brew(
    "Grave-Dust Tonic",
    "common",
    6,
    "Tonic. +20% essence regeneration for 60 seconds. Four pinches of grave dust in black water: the first brew anyone can make from what the dead drop.",
    { slot: "tonic", effects: [{ kind: "essence", value: 0.2 }], seconds: 60, label: "Dust-breathed", color: 14208957, glyph: "\u2234" },
    { id: "brew_grave_dust_tonic", name: "Brew Grave-Dust Tonic", level: 1, qty: 2, ings: [["reagent_grave_dust", 4]] },
    "flask_tonic_dust"
  )],
  ["elixir_wraithquick", brew(
    "Wraithquick Elixir",
    "uncommon",
    28,
    "Elixir. +15% cooldown recovery for 45 seconds. Ectoplasm sings in the glass, and your rites come back quicker for it.",
    { slot: "elixir", effects: [{ kind: "haste", value: 0.15 }], seconds: 45, label: "Wraithquick", color: 9417983, glyph: "\u21F6" },
    { id: "brew_wraithquick", name: "Brew Wraithquick Elixir", level: 10, qty: 1, ings: [["reagent_wraith_ectoplasm", 2], ["reagent_grave_dust", 2]] },
    "flask_haste"
  )],
  ["tonic_graveluck", brew(
    "Grave-Luck Tonic",
    "uncommon",
    36,
    "Tonic. +15% item drop chance for 60 seconds. Nightshade and a fistful of grave dust: the dead hold on to their things a little less tightly.",
    { slot: "tonic", effects: [{ kind: "fortune", value: 0.15 }], seconds: 60, label: "Grave-lucky", color: 15254362, glyph: "\u25C6" },
    { id: "brew_graveluck", name: "Brew Grave-Luck Tonic", level: 22, qty: 1, ings: [["reagent_grave_dust", 6], ["herb_nightshade", 2]] },
    "flask_fortune"
  )],
  ["tonic_insight", brew(
    "Sexton's Insight",
    "uncommon",
    40,
    "Tonic. +15% experience from kills for 60 seconds. Ectoplasm and mourning moss steeped together; every death teaches a little more.",
    { slot: "tonic", effects: [{ kind: "wisdom", value: 0.15 }], seconds: 60, label: "Insightful", color: 15128319, glyph: "\u2727" },
    { id: "brew_insight", name: "Brew Sexton's Insight", level: 28, qty: 1, ings: [["reagent_wraith_ectoplasm", 3], ["herb_mourning_moss", 3]] },
    "flask_wisdom"
  )],
  ["elixir_leechblood", brew(
    "Leechblood Elixir",
    "rare",
    52,
    "Elixir. Heal 4% of the damage you deal for 45 seconds (up to three targets per hit, at most 1.5% of your health per hit). Plague bile that remembers being alive.",
    { slot: "elixir", effects: [{ kind: "lifesteal", value: 0.04 }], seconds: 45, label: "Leechblood", color: 12728904, glyph: "\u2756" },
    { id: "brew_leechblood", name: "Brew Leechblood Elixir", level: 38, qty: 1, ings: [["reagent_plague_bile", 2], ["reagent_grave_dust", 3]] },
    "flask_lifesteal"
  )],
  ["elixir_rotproof", brew(
    "Rot-Proof Elixir",
    "rare",
    48,
    "Elixir. 40% less rot and plague damage for 75 seconds (adds to other wards; the total caps at 60%). Bile and rot-cap, taken before the Plague Saint.",
    { slot: "elixir", effects: [{ kind: "resist_rot", value: 0.4 }], seconds: 75, label: "Rot-proof", color: 13099082, glyph: "\u2725" },
    { id: "brew_rotproof", name: "Brew Rot-Proof Elixir", level: 42, qty: 1, ings: [["reagent_plague_bile", 1], ["herb_rot_cap", 3]] },
    "flask_rotproof"
  )],
  ["elixir_cinderskin", brew(
    "Cinderskin Elixir",
    "rare",
    60,
    "Elixir. 40% less fire damage for 75 seconds (adds to other wards; the total caps at 60%). Cinder ash and ash-bloom: walk the Pyre as if it were a hearth.",
    { slot: "elixir", effects: [{ kind: "resist_fire", value: 0.4 }], seconds: 75, label: "Cinderskin", color: 16742954, glyph: "\u25B2" },
    { id: "brew_cinderskin", name: "Brew Cinderskin Elixir", level: 52, qty: 1, ings: [["reagent_cinder_ash", 1], ["herb_ash_bloom", 3]] },
    "flask_cinderskin"
  )],
  ["tonic_ghostwalk", brew(
    "Ghostwalk Tonic",
    "rare",
    90,
    "Tonic. +30% essence regeneration and +10% move speed for 75 seconds. Ectoplasm and wolfsbane: you drift more than you walk.",
    { slot: "tonic", effects: [{ kind: "essence", value: 0.3 }, { kind: "speed", value: 0.1 }], seconds: 75, label: "Ghostwalking", color: 7332808, glyph: "\u2248" },
    { id: "brew_ghostwalk", name: "Brew Ghostwalk Tonic", level: 62, qty: 1, ings: [["reagent_wraith_ectoplasm", 4], ["herb_wolfsbane", 2]] },
    "flask_ghostwalk"
  )],
  ["elixir_bloodmoon", brew(
    "Bloodmoon Elixir",
    "epic",
    200,
    "Elixir. +20% spell damage and heal 6% of the damage you deal for 60 seconds. Two kings' ichor and plague bile, drunk under a red moon.",
    { slot: "elixir", effects: [{ kind: "damage", value: 0.2 }, { kind: "lifesteal", value: 0.06 }], seconds: 60, label: "Bloodmoon", color: 13652072, glyph: "\u25D0" },
    { id: "brew_bloodmoon", name: "Brew Bloodmoon Elixir", level: 70, qty: 1, ings: [["ichor_gravedigger", 1], ["ichor_abbess", 1], ["reagent_plague_bile", 2]] },
    "flask_bloodmoon"
  )],
  ["elixir_hymnal", brew(
    "Hymnal Elixir",
    "epic",
    170,
    "Elixir. 15% less damage taken, 20% less rot and plague damage, and heal 3% of the damage you deal, for 75 seconds. The drowned hymn and the Saint's blight, made to cancel each other out.",
    { slot: "elixir", effects: [{ kind: "ward", value: 0.15 }, { kind: "resist_rot", value: 0.2 }, { kind: "lifesteal", value: 0.03 }], seconds: 75, label: "Hymnal", color: 12175615, glyph: "\u2671" },
    { id: "brew_hymnal", name: "Brew Hymnal Elixir", level: 78, qty: 1, ings: [["ichor_congregation", 1], ["ichor_plague_saint", 1], ["reagent_wraith_ectoplasm", 4]] },
    "flask_hymnal"
  )],
  ["elixir_regent", brew(
    "Regent's Vigil Elixir",
    "epic",
    300,
    "Elixir. +12% spell damage, 15% less damage taken and +10% cooldown recovery for 60 seconds. The Regent's ichor and the Prelate's, bound with cinder ash: the last word in elixirs.",
    { slot: "elixir", effects: [{ kind: "damage", value: 0.12 }, { kind: "ward", value: 0.15 }, { kind: "haste", value: 0.1 }], seconds: 60, label: "Regent's Vigil", color: 16761946, glyph: "\u265B" },
    { id: "brew_regent_vigil", name: "Brew Regent's Vigil Elixir", level: 85, qty: 1, ings: [["ichor_regent", 1], ["ichor_prelate", 1], ["reagent_cinder_ash", 3]] },
    "flask_regent"
  )]
];
var REAGENT_BREWS = Object.fromEntries(REAGENT_BREW_LIST.map(([id, b]) => [id, b.def]));
var SERVER_EFFECT = {
  damage: "damage_amp",
  ward: "resist_void",
  lifesteal: "lifesteal",
  haste: "cooldown_rate",
  resist_fire: "resist_fire",
  resist_rot: "resist_rot",
  speed: "move_speed",
  essence: "essence_regen",
  wisdom: "xp_amp",
  fortune: "drop_amp"
};
function brewStat(def) {
  const [first, ...rest] = def.effects;
  const stat = { value: first.value, effect: SERVER_EFFECT[first.kind], duration: def.seconds };
  if (rest.length) stat.effects = def.effects.map((e) => ({ effect: SERVER_EFFECT[e.kind], value: e.value }));
  return stat;
}
var REAGENT_BREW_ITEMS = Object.fromEntries(
  REAGENT_BREW_LIST.map(([id, b]) => [id, { name: b.name, rarity: b.rarity, sell: b.sell, lore: b.lore, stack: 99, stat: brewStat(b.def), art: b.art }])
);
var REAGENT_RECIPES = REAGENT_BREW_LIST.map(([id, b]) => [b.recipe.id, b.recipe.name, "alchemy", b.recipe.level, id, b.recipe.qty, b.recipe.ings]);
var ALL_REAGENT_IDS = [...Object.keys(REAGENT_ITEMS), ...Object.keys(REAGENT_BREW_ITEMS)];
var ICHORS = Object.values(BOSS_ICHOR);

// src/content/disciplines.ts
var BASE = {
  thrallCap: 3,
  thrallKind: "warrior",
  thrallHpMult: 1,
  thrallDamageMult: 1,
  thrallAttackSpeedMult: 1,
  maxHpMult: 1,
  essenceRegenMult: 1,
  miasmaRadiusMult: 1,
  witheredMaxStacks: 5,
  corpseHeal: 0,
  wardPerThrall: 0,
  litanyBarrier: 0,
  sacrificeLeavesCorpse: false,
  miasmaBurstsCorpses: false,
  thrallDeathBurst: 0,
  championEvery: 0,
  spearRally: 0,
  wardReflect: 0,
  colossusGuard: 0,
  litanyShatter: 0,
  corpseWisp: 0,
  soulHarvestRateMult: 1,
  wraithNova: 0,
  miasmaSpreadsWithered: 0,
  witheredBurstAt: 0
};
var DISCIPLINES = {
  ossuary: {
    classIndex: 1,
    id: "ossuary",
    family: "necromancer",
    name: "Ossuary",
    epithet: "Keeper of the Bone Wall",
    description: "Armours itself in the dead. Raises shield-bearing thralls that hold the line while you work.",
    passive: {
      name: "Bone Ward",
      text: "Thralls rise as Shieldbearers (+100% health, draw aggression). You take 10% less damage per active thrall (30% at the usual three, 60% at most) and have 20% more health. Black Litany grants a bone barrier."
    },
    color: "#d8cfbd",
    portrait: "art/portraits/ossuary.webp",
    modelSlug: "hero_ossuary",
    mods: { ...BASE, thrallKind: "shieldbearer", thrallHpMult: 2, maxHpMult: 1.2, wardPerThrall: 0.1, litanyBarrier: 0.04 }
  },
  gravecaller: {
    classIndex: 2,
    id: "gravecaller",
    family: "necromancer",
    name: "Gravecaller",
    epithet: "Marshal of the Restless",
    description: "Commands the largest legion. Spends thralls freely, because every sacrifice leaves another corpse.",
    passive: {
      name: "Grave Legion",
      text: "Thrall cap 5. Thralls attack 20% faster and hit 15% harder. Thralls sacrificed by Black Litany leave corpses behind."
    },
    color: "#9b5cff",
    portrait: "art/portraits/gravecaller.webp",
    modelSlug: "hero_gravecaller",
    mods: { ...BASE, thrallCap: 5, thrallAttackSpeedMult: 1.2, thrallHpMult: 1, thrallDamageMult: 1.15, sacrificeLeavesCorpse: true }
  },
  mourner: {
    classIndex: 3,
    id: "mourner",
    family: "necromancer",
    name: "Mourner",
    epithet: "Singer of the Funeral Rite",
    description: "Binds spirits instead of bones. Wraiths strike from range and every rite mends the living.",
    passive: {
      name: "Funeral Rites",
      text: "Exhume binds Wraiths that attack from range. Consuming a corpse heals 10% max health. +25% Grave Essence regeneration."
    },
    color: "#8f9ed1",
    portrait: "art/portraits/mourner.webp",
    modelSlug: "hero_mourner",
    mods: { ...BASE, thrallKind: "wraith", thrallHpMult: 1, corpseHeal: 0.1, essenceRegenMult: 1.25 }
  },
  rotweaver: {
    classIndex: 4,
    id: "rotweaver",
    family: "necromancer",
    name: "Rotweaver",
    epithet: "Gardener of Decay",
    description: "Poisons the ground itself. Miasma spreads further, rots deeper, and turns corpses into bombs.",
    passive: {
      name: "Carrion Bloom",
      text: "Miasma Circle is 40% wider and Withered stacks to 8. You have 10% more health. Corpses inside your Miasma burst, damaging and withering nearby enemies."
    },
    color: "#b58cc7",
    portrait: "art/portraits/rotweaver.webp",
    modelSlug: "hero_rotweaver",
    mods: { ...BASE, miasmaRadiusMult: 1.4, witheredMaxStacks: 8, maxHpMult: 1.1, miasmaBurstsCorpses: true }
  },
  /**
   * Release 0.3. Not a necromancer: family 'knight' brings its own kit
   * (content/kits.ts) and resource (Rage, gameplay/resources.ts). The
   * necromancer-only `mods` stay at BASE — the Knight raises no thralls, and its
   * kit never offers the rites that would read them.
   */
  hollow_knight: {
    classIndex: 8,
    id: "hollow_knight",
    family: "knight",
    name: "Hollow Knight",
    epithet: "Oathbound of the Covenant",
    description: "An undead knight still keeping its oath. Builds Rage by taking and dealing punishment, then spends it leaping into the dead.",
    passive: {
      name: "Oathbound",
      text: "Rage instead of Grave Essence: built by damage taken, by every body Hollow Cut catches, and fastest of all by a perfect block. It drains once you leave the fight."
    },
    color: "#b8c0cc",
    portrait: "art/portraits/hollow_knight.webp",
    modelSlug: "hero_hollow_knight",
    mods: { ...BASE }
  },
  grave_warden: {
    classIndex: 5,
    id: "grave_warden",
    family: "warden",
    name: "Grave Warden",
    epithet: "Keeper of the Last Lantern",
    description: "A watchful guardian who burns corpses for Oil, pins enemies with a chain and shelters allies in lantern light.",
    passive: { name: "Lamplighter", text: "Oil refills steadily and rises when a corpse burns. Lantern wards protect everyone standing inside." },
    color: "#f2b84b",
    portrait: "art/portraits/grave_warden.webp",
    modelSlug: "hero_grave_warden",
    mods: { ...BASE }
  },
  bell_monk: {
    classIndex: 6,
    id: "bell_monk",
    family: "monk",
    name: "Bell Monk",
    epithet: "Voice of the Last Toll",
    description: "Strikes on a twelve-beat rhythm, builds Resonance and turns corpses into sounding bells.",
    passive: { name: "The Beat", text: "Hits close to each toll deal more damage and build Resonance faster." },
    color: "#e8d9a0",
    portrait: "art/portraits/bell_monk.webp",
    modelSlug: "hero_bell_monk",
    mods: { ...BASE }
  },
  carrion_witch: {
    classIndex: 7,
    id: "carrion_witch",
    family: "witch",
    name: "Carrion Witch",
    epithet: "Mistress of Hooks and Crows",
    description: "Harvests corpses for Offal, sends crows into a pack and curses foes with a hooked charm.",
    passive: { name: "Corpse Hunger", text: "Offal comes from bodies, never passive regeneration. Save a corpse before spending it." },
    color: "#9a1b2a",
    portrait: "art/portraits/carrion_witch.webp",
    modelSlug: "hero_carrion_witch",
    mods: { ...BASE }
  },
  veilwalker: {
    classIndex: 9,
    id: "veilwalker",
    family: "veil",
    name: "Veilwalker",
    epithet: "One Foot Beyond",
    description: "Walks between life and death, raising brief spectral allies from echoes of the fallen.",
    passive: { name: "Thin Places", text: "Veil refills in Life form and drains in Veil form. Spectral echoes appear where corpses fall." },
    color: "#bff3ff",
    portrait: "art/portraits/veilwalker.webp",
    modelSlug: "hero_veilwalker",
    mods: { ...BASE }
  }
};
var PLAYABLE_DISCIPLINES = [
  DISCIPLINES.ossuary,
  DISCIPLINES.gravecaller,
  DISCIPLINES.mourner,
  DISCIPLINES.rotweaver,
  DISCIPLINES.grave_warden,
  DISCIPLINES.bell_monk,
  DISCIPLINES.carrion_witch,
  DISCIPLINES.hollow_knight,
  DISCIPLINES.veilwalker
];

// src/gameplay/smartLoot.ts
var SMART_LOOT = { ownArmorShare: 0.7, foreignWeaponMult: 1 / 3 };
var smartCache = /* @__PURE__ */ new Map();
function smartTable(area, disciplineId) {
  const key = `${area}|${disciplineId}`;
  let t = smartCache.get(key);
  if (t) return t;
  const table = AREAS[area].loot;
  const armor = table.filter((e) => ARMOR_BY_ID[e.item]);
  const own = armor.filter((e) => ARMOR_BY_ID[e.item].disciplineId === disciplineId);
  const total = armor.reduce((n, e) => n + e.weight, 0);
  const ownTotal = own.reduce((n, e) => n + e.weight, 0);
  const necro = DISCIPLINES[disciplineId]?.family === "necromancer";
  t = table.map((e) => {
    const piece = ARMOR_BY_ID[e.item];
    if (piece && ownTotal > 0 && ownTotal < total) {
      const mine = piece.disciplineId === disciplineId;
      return { item: e.item, weight: mine ? e.weight / ownTotal * total * SMART_LOOT.ownArmorShare : e.weight / (total - ownTotal) * total * (1 - SMART_LOOT.ownArmorShare) };
    }
    if (!necro && NECRO_WEAPON_BY_ID[e.item]) return { item: e.item, weight: e.weight * SMART_LOOT.foreignWeaponMult };
    return e;
  });
  smartCache.set(key, t);
  return t;
}

// src/gameplay/authorityRules.ts
var LEVEL_CAP = 255;
function totalXp(level, xp) {
  const l = Math.max(1, Math.trunc(Number(level) || 1));
  return 50 * l * (l - 1) + Math.max(0, Math.trunc(Number(xp) || 0));
}
function splitXp(total) {
  let t = Math.max(0, Math.trunc(Number(total) || 0));
  let level = 1;
  while (level < LEVEL_CAP && t >= level * 100) {
    t -= level * 100;
    level++;
  }
  return { level, xp: level >= LEVEL_CAP ? Math.min(t, LEVEL_CAP * 100 - 1) : t };
}
var AREA_PEAK = {
  graves: { xp: 2016, gold: 2470, kills: 205 },
  ossuary: { xp: 4902, gold: 4507, kills: 239 },
  nave: { xp: 10202, gold: 8808, kills: 260 },
  sanctum: { xp: 16503, gold: 13135, kills: 203 },
  cloister: { xp: 24015, gold: 17218, kills: 222 },
  pyre: { xp: 43551, gold: 29779, kills: 195 },
  warren: { xp: 1891, gold: 1718, kills: 186 },
  coliseum: { xp: 20609, gold: 16705, kills: 477 },
  fen: { xp: 74831, gold: 25498, kills: 184 },
  // Same settings on held floors of depth 5, 10 and 20 for a level-40 hero, the best column of any discipline, each rate scaled to enemy level 50
  // (depth 10 for that hero; XP x1.25 per level, gold x1.15): `DEPTH_LEVELS=40 DEPTH_DEPTHS=5,10,20 DEPTH_BANDS=max npm run balance:depths`, BALANCE.md.
  depths: { xp: 27600, gold: 16e3, kills: 72 }
};
var DEPTHS_AUTHORITY = { refHero: 40, refDepth: 10, slack: 3, maxDepth: 120 };
var DEPTHS_GATE = "warren";
var depthBound = (deepest) => Math.min(DEPTHS_AUTHORITY.maxDepth, Math.max(0, Math.trunc(Number(deepest) || 0)) + DEPTHS_AUTHORITY.slack);
var AUTHORITY = {
  /** Safety factor over the best measured honest rate: party play, a skilled human out-killing the bot, and tool noise. */
  HEADROOM: 3,
  /** Multipliers the harness does not apply, at their maximum: kill chain (Requiem +25%), the weekly Omen (+20%), a wisdom tonic (+25% XP). */
  CHAIN: 1.25,
  OMEN: 1.2,
  WISDOM: 1.25,
  /** A co-op guest earns at the HOST's Ascension rank. The guest's own record cannot show it, so allow this many ranks above their own. */
  COOP_RANK_ALLOWANCE: 2,
  /** Lump-sum rewards that do not scale with time: boss XP, milestone gold (47 milestones, 8,000 gold at most each), contract payouts. */
  XP_BURST: 5e3,
  GOLD_BURST: 4e4,
  /** Non-combat gold per minute (labor, contracts, selling what a character already holds is credited separately). */
  NONCOMBAT_GOLD_PER_MIN: 1500,
  /** Allowance banks for at most this long: a character that sat idle for a day cannot claim a day of play at once. */
  BANK_MINUTES: 60,
  /** A character the server has never seen before starts with this many minutes in the bank. */
  FIRST_MINUTES: 2,
  /** The most an offline (browser-only) save may claim, in minutes of play, however long its own clock says. */
  OFFLINE_MAX_MINUTES: 7 * 24 * 60,
  /** An offline save claiming no play time at all is still allowed this much (a short session). */
  OFFLINE_MIN_MINUTES: 10,
  /** Item allowances refill at HEADROOM x the item's best honest pickup rate and bank for ITEM_BANK_MINUTES (shorter than XP: rare gear is the point). */
  ITEM_BANK_MINUTES: 10,
  ITEM_BURST_MINUTES: 2,
  ITEM_MIN_BURST: 4,
  /** The cap on gold credited for items sold, per character. */
  SALE_CREDIT_CAP: 3e6
};
var XP_LEVEL_STEP = 0.25;
var GOLD_LEVEL_STEP = 0.15;
function enemyLevel(area, characterLevel, rank) {
  const a = AREAS[area];
  const base = a.scaling ? Math.max(a.scaling.minLevel, characterLevel) : a.level;
  return base + rank * ASCENSION.levelsPerRank;
}
function ceilingsFor(unlocked, ascension, characterLevel, deepest = 0) {
  const rank = Math.min(ASCENSION.maxRank, Math.max(0, Math.trunc(ascension) || 0) + AUTHORITY.COOP_RANK_ALLOWANCE);
  const rankMult = 1 + ASCENSION.rewardPerRank * rank;
  let xp = 0;
  let gold = 0;
  let best = null;
  for (const id of AREA_ORDER) {
    const peak = AREA_PEAK[id];
    if (!peak || !unlocked.includes(id === "depths" ? DEPTHS_GATE : id)) continue;
    const depths = id === "depths";
    const baseLevel = depths ? depthEnemyLevel(DEPTHS_AUTHORITY.refDepth, DEPTHS_AUTHORITY.refHero) : AREAS[id].scaling ? AREAS[id].scaling.minLevel : AREAS[id].level;
    const lvl = depths ? depthEnemyLevel(depthBound(deepest), characterLevel) + rank * ASCENSION.levelsPerRank : enemyLevel(id, characterLevel, rank);
    const x = peak.xp * (1 + XP_LEVEL_STEP * (lvl - 1)) / (1 + XP_LEVEL_STEP * (baseLevel - 1)) * rankMult * AUTHORITY.CHAIN * AUTHORITY.OMEN * AUTHORITY.WISDOM;
    const g = peak.gold * (1 + GOLD_LEVEL_STEP * (lvl - 1)) / (1 + GOLD_LEVEL_STEP * (baseLevel - 1)) * rankMult * AUTHORITY.CHAIN * AUTHORITY.OMEN;
    if (x > xp) {
      xp = x;
      best = id;
    }
    if (g > gold) gold = g;
  }
  return {
    xpPerMin: Math.ceil(xp * AUTHORITY.HEADROOM),
    goldPerMin: Math.ceil(Math.max(gold * AUTHORITY.HEADROOM, AUTHORITY.NONCOMBAT_GOLD_PER_MIN)),
    area: best
  };
}
var BOSS_ICHORS = new Set(Object.values(BOSS_ICHOR));
var ITEM_CHANCE_PEAK = 1 + 0.06 * 8 + 0.2;
var FORTUNE_PEAK = 1.3;
var ELITE_LOOT_MULT = 6;
var ICHOR_PER_MIN = 0.5;
var MATERIAL_QTY = 1.35;
function buildGroundRates() {
  const rates = {};
  const add = (id, perMin) => {
    rates[id] = Math.max(rates[id] ?? 0, perMin);
  };
  const addGround = (lootId, kills, roster, eliteChance, extraPerMin = 0) => {
    const area = AREAS[lootId];
    const elite = Math.min(1, eliteChance + 4e-3 * 8);
    const dropChance = Math.min(1, area.itemChance * ITEM_CHANCE_PEAK * FORTUNE_PEAK * (1 - elite + elite * ELITE_LOOT_MULT));
    for (const table of [area.loot, ...Object.keys(DISCIPLINES).map((d) => smartTable(lootId, d))]) {
      const total = table.reduce((n, l) => n + l.weight, 0) || 1;
      for (const l of table) add(l.item, (kills * dropChance + extraPerMin) * l.weight / total * MATERIAL_QTY);
    }
    const weights = roster.reduce((n, e) => n + e.weight, 0) || 1;
    const reagentPerKill = /* @__PURE__ */ new Map();
    const credit = (item2, chance, qty) => {
      const c = Math.min(1, chance * FORTUNE_PEAK * (1 - elite + elite * ELITE_REAGENT_MULT));
      reagentPerKill.set(item2, (reagentPerKill.get(item2) ?? 0) + c * ((qty[0] + qty[1]) / 2));
    };
    for (const d of AREA_REAGENT_DROPS[lootId] ?? []) credit(d.item, d.chance, d.qty);
    for (const e of roster) for (const d of ENEMY_REAGENT_DROPS[e.id] ?? []) credit(d.item, d.chance * e.weight / weights, d.qty);
    for (const [item2, perKill] of reagentPerKill) add(item2, kills * perKill);
    const pool = AREA_RUNE_POOL[lootId] ?? [];
    const poolWeight = pool.reduce((n, r) => n + RUNE_WEIGHT[RUNES[r].rarity], 0) || 1;
    for (const r of pool) {
      const share = RUNE_WEIGHT[RUNES[r].rarity] / poolWeight;
      add(r, (kills * elite * eliteRuneChance(lootId) * ITEM_CHANCE_PEAK * FORTUNE_PEAK + 0.5 * SURGE_RUNE_CHANCE) * share);
    }
  };
  for (const id of AREA_ORDER) {
    const area = AREAS[id];
    const peak = AREA_PEAK[id];
    if (!peak || area.safe || area.instance) continue;
    addGround(id, peak.kills, area.enemies, area.eliteChance);
  }
  const depthsPeak = AREA_PEAK.depths;
  if (depthsPeak) {
    const deep = depthRoster(DEPTHS_AUTHORITY.maxDepth);
    const elite = AREAS.depths.eliteChance + depthEliteBonus(DEPTHS_AUTHORITY.maxDepth);
    const floorDrops = FLOORS_PER_MIN_CEILING * FLOOR_DROP_CHANCE + CHEST_PER_MIN_CEILING * chestDrops(DEPTHS_AUTHORITY.maxDepth);
    for (const lootId of DEPTH_LOOT_AREAS) addGround(lootId, depthsPeak.kills, deep, elite, floorDrops);
    for (const r of chestRunePool(DEPTHS_AUTHORITY.maxDepth)) add(r, CHEST_PER_MIN_CEILING);
  }
  for (const pool of Object.values(BOSS_RUNE_POOL)) for (const r of pool) add(r, ICHOR_PER_MIN);
  for (const ichor of BOSS_ICHORS) add(ichor, ICHOR_PER_MIN);
  if (LEGENDARY_BOSS_AREAS.length) {
    let elitePerMin = 0;
    for (const id of AREA_ORDER) {
      const peak = AREA_PEAK[id];
      if (peak && AREAS[id].scaling) elitePerMin = Math.max(elitePerMin, peak.kills * Math.min(1, AREAS[id].eliteChance + 4e-3 * 8) * legendaryEliteChance(id));
    }
    const perMin = (ICHOR_PER_MIN * Math.max(...LEGENDARY_BOSS_AREAS.map(legendaryBossChance)) + elitePerMin) * FORTUNE_PEAK;
    for (const set of LEGENDARY_SET_IDS) for (const part of ["head", "chest", "hands", "legs", "feet"]) add(legendaryItemId(set, part), perMin * Math.max(LEGENDARY_DROP.ownShare, 1 / LEGENDARY_SET_IDS.length));
  }
  return rates;
}
var GROUND_RATES = buildGroundRates();
var isGroundItem = (itemId) => Object.prototype.hasOwnProperty.call(GROUND_RATES, itemId);
function itemRatePerMin(itemId) {
  return isGroundItem(itemId) ? GROUND_RATES[itemId] * AUTHORITY.HEADROOM : 0;
}
function itemCap(itemId) {
  const rate = itemRatePerMin(itemId);
  if (rate <= 0) return 0;
  return Math.ceil(Math.max(AUTHORITY.ITEM_MIN_BURST, rate * AUTHORITY.ITEM_BURST_MINUTES) + rate * AUTHORITY.ITEM_BANK_MINUTES);
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  AREA_PEAK,
  AUTHORITY,
  DEPTHS_AUTHORITY,
  GROUND_RATES,
  LEVEL_CAP,
  ceilingsFor,
  depthBound,
  isGroundItem,
  itemCap,
  itemRatePerMin,
  splitXp,
  totalXp
});
