// GENERATED by tools/build-server-rules.mjs from src/gameplay/contractRules.ts — do not edit by hand.
// Sexton's Contracts (the daily delivery board) shared by the web client and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/contractRules.ts
var contractRules_exports = {};
__export(contractRules_exports, {
  CONTRACT_SLOTS: () => CONTRACT_SLOTS,
  bonusFor: () => bonusFor,
  candidatesFor: () => candidatesFor,
  dayKey: () => dayKey,
  generateBoard: () => generateBoard,
  nextResetMs: () => nextResetMs,
  streakOf: () => streakOf
});
module.exports = __toCommonJS(contractRules_exports);

// src/content/cosmetics.ts
var PETS = [
  { id: "pet_tithe_bat", name: "Tithe Bat", charm: "charm_tithe_bat", skill: "woodcutting", model: "tithe_bat", scale: 0.7, fly: { height: 1.5, speed: 17, amp: 0.75, body: 0.22 }, rarity: "rare", lore: "It roosts in the coffin-oaks and follows the sound of the axe." },
  { id: "pet_grave_rat", name: "Grave Rat", charm: "charm_grave_rat", skill: "mining", model: "skull_rat", scale: 1.05, rarity: "rare", lore: "It found a better seam than you did, and it will not tell you where." },
  { id: "pet_drowned_pup", name: "Drowned Pup", charm: "charm_drowned_pup", skill: "fishing", model: "bone_hound", scale: 0.55, tint: 10470612, rarity: "rare", lore: "Pulled from black water, still wet, still hopeful." },
  { id: "pet_wee_thrall", name: "Wee Thrall", charm: "charm_wee_thrall", skill: "gravedigging", model: "skeleton_thrall", scale: 0.32, rarity: "epic", lore: "A very small skeleton with a very large sense of duty." },
  { id: "pet_shroud_moth", name: "Shroud Moth", charm: "charm_shroud_moth", skill: "gardening", model: "shroud_moth", scale: 0.6, fly: { height: 1.7, speed: 8, amp: 0.55, body: 0.16 }, tint: 14215360, rarity: "epic", lore: "It drinks the light from the beds and gives a little back." }
];
var petForSkill = (skill) => PETS.find((p) => p.skill === skill);
var PET_CHANCE = 1 / 3500;
var petChance = (nodeLevel) => PET_CHANCE * (1 + nodeLevel / 100);
var GARDEN_PET_CHANCE = 1 / 35;
var CHARM_ITEMS = Object.fromEntries(
  PETS.map((p) => [p.charm, { name: `${p.name} Charm`, rarity: p.rarity, sell: 250, lore: `Adopt it (Capes & Pets, N) and the ${p.name} is yours for good. ${p.lore}` }])
);

// src/gameplay/gatheringRules.ts
var petLine = (skill, level) => {
  const pet = petForSkill(skill);
  return pet ? [{ item: pet.charm, chance: petChance(level) }] : [];
};
var node = (d) => ({ ...d, extras: [...d.extras ?? [], ...petLine(d.skill, d.level)] });
var CROWS_NEST = [
  { item: "seed_mourning_moss", chance: 1 / 300 },
  { item: "ring_copper", chance: 1 / 600 }
];
var GEMS = (scale) => [
  { item: "gem_grave_garnet", chance: 1 / 250 * 0.6 * scale },
  { item: "gem_bone_opal", chance: 1 / 250 * 0.3 * scale },
  { item: "gem_void_sapphire", chance: 1 / 250 * 0.1 * scale }
];
var NODE_LIST = [
  // Woodcutting
  node({ id: "coffin_oak", skill: "woodcutting", name: "Coffin-Oak", kind: "tree", level: 1, xp: 6, ticks: 4, item: "log_oak", yields: [1, 4], respawnS: 8, extras: [...CROWS_NEST, { item: "sapling_oak", chance: 1 / 40 }], tint: 7033398 }),
  node({ id: "hangman_elm", skill: "woodcutting", name: "Hangman's Elm", kind: "tree", level: 5, xp: 14, ticks: 5, item: "log_elm", yields: [3, 6], respawnS: 12, extras: CROWS_NEST, tint: 6117948 }),
  node({ id: "bleeding_willow", skill: "woodcutting", name: "Bleeding Willow", kind: "tree", level: 15, xp: 24, ticks: 5, item: "log_willow", yields: [4, 8], respawnS: 15, extras: CROWS_NEST, tint: 8010292 }),
  node({ id: "churchyard_yew", skill: "woodcutting", name: "Churchyard Yew", kind: "tree", level: 45, xp: 38, ticks: 6, item: "log_yew", yields: [5, 10], respawnS: 30, extras: [...CROWS_NEST, { item: "sapling_yew", chance: 1 / 50 }], tint: 3099187 }),
  node({ id: "blackthorn", skill: "woodcutting", name: "Blackthorn", kind: "tree", level: 60, xp: 55, ticks: 7, item: "log_blackthorn", yields: [6, 12], respawnS: 45, extras: CROWS_NEST, tint: 2762032 }),
  node({ id: "ghostwood", skill: "woodcutting", name: "Ghostwood", kind: "tree", level: 75, xp: 80, ticks: 8, item: "log_ghostwood", yields: [6, 12], respawnS: 60, extras: CROWS_NEST, tint: 10467504 }),
  node({ id: "bone_elder", skill: "woodcutting", name: "Bone Elder", kind: "tree", level: 90, xp: 115, ticks: 8, item: "log_bone_elder", yields: [8, 14], respawnS: 120, extras: CROWS_NEST, tint: 15129796 }),
  // Mining: one seam model, tinted per ore; geodes for the top tiers.
  node({ id: "seam_copper", skill: "mining", name: "Copper Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_copper", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 4170618 }),
  node({ id: "seam_tin", skill: "mining", name: "Tin Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_tin", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 10134440 }),
  node({ id: "seam_iron", skill: "mining", name: "Iron Seam", kind: "seam", level: 10, xp: 12, ticks: 5, item: "ore_iron", yields: [2, 4], respawnS: 9, extras: GEMS(1), tint: 10115644 }),
  node({ id: "seam_bronze", skill: "mining", name: "Bronze Seam", kind: "seam", level: 20, xp: 18, ticks: 5, item: "ore_bronze", yields: [2, 5], respawnS: 12, extras: GEMS(1), tint: 12618314 }),
  node({ id: "seam_silver", skill: "mining", name: "Silver Seam", kind: "seam", level: 30, xp: 24, ticks: 5, item: "ore_silver", yields: [3, 6], respawnS: 18, extras: GEMS(1.2), tint: 14212582 }),
  node({ id: "seam_gold", skill: "mining", name: "Gold Seam", kind: "seam", level: 40, xp: 32, ticks: 6, item: "ore_gold", yields: [3, 6], respawnS: 25, extras: GEMS(1.4), tint: 15251530 }),
  node({ id: "seam_steel", skill: "mining", name: "Steel Seam", kind: "seam", level: 50, xp: 42, ticks: 6, item: "ore_steel", yields: [4, 7], respawnS: 32, extras: GEMS(1.6), tint: 8228774 }),
  node({ id: "geode_hell", skill: "mining", name: "Hell Geode", kind: "geode", level: 65, xp: 60, ticks: 7, item: "ore_hell", yields: [4, 8], respawnS: 45, extras: GEMS(2), tint: 14701098 }),
  node({ id: "geode_moon", skill: "mining", name: "Moon Geode", kind: "geode", level: 80, xp: 90, ticks: 8, item: "ore_moon", yields: [5, 9], respawnS: 60, extras: GEMS(2.5), tint: 10405119 }),
  // Fishing: spots drift, so a "depleted" pool is a spot that moved on.
  node({ id: "pool_still", skill: "fishing", name: "Still Pool", kind: "pool", level: 1, xp: 6, ticks: 4, item: "fish_river", yields: [8, 16], respawnS: 6, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 2902610 }),
  node({ id: "pool_eels", skill: "fishing", name: "Crypt Eels", kind: "pool", level: 15, xp: 14, ticks: 5, item: "fish_crypt_eel", yields: [8, 16], respawnS: 8, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 3231807 }),
  node({ id: "pool_carp", skill: "fishing", name: "Bell Carp", kind: "pool", level: 30, xp: 24, ticks: 5, item: "fish_bell_carp", yields: [10, 18], respawnS: 10, extras: [{ item: "reliquary_fragment", chance: 1 / 300 }], tint: 5921336 }),
  node({ id: "pool_pike", skill: "fishing", name: "Drowned Pike", kind: "pool", level: 45, xp: 38, ticks: 6, item: "fish_drowned_pike", yields: [10, 18], respawnS: 12, extras: [{ item: "reliquary_fragment", chance: 1 / 250 }], tint: 2375754 }),
  node({ id: "pool_lantern", skill: "fishing", name: "Lanternfish", kind: "pool", level: 62, xp: 58, ticks: 7, item: "fish_lanternfish", yields: [12, 20], respawnS: 14, extras: [{ item: "reliquary_fragment", chance: 1 / 200 }], tint: 3828314 }),
  node({ id: "pool_coelacanth", skill: "fishing", name: "Abyssal Coelacanth", kind: "pool", level: 80, xp: 95, ticks: 8, item: "fish_coelacanth", yields: [12, 20], respawnS: 16, extras: [{ item: "covenant_seal", chance: 1 / 300 }], tint: 1715268 }),
  // Gravedigging: the necromancer's own skill.
  node({
    id: "grave_pauper",
    skill: "gravedigging",
    name: "Pauper's Grave",
    kind: "grave",
    level: 1,
    xp: 7,
    ticks: 4,
    item: "bones_old",
    yields: [2, 4],
    respawnS: 10,
    gold: [0, 2],
    tint: 4865068,
    extras: [{ item: "seed_mourning_moss", chance: 1 / 12 }]
  }),
  node({
    id: "grave_mound",
    skill: "gravedigging",
    name: "Burial Mound",
    kind: "grave",
    level: 20,
    xp: 18,
    ticks: 5,
    item: "bones_barrow",
    yields: [3, 5],
    respawnS: 18,
    gold: [1, 4],
    tint: 5064242,
    extras: [{ item: "ring_copper", chance: 1 / 120 }, { item: "seed_mourning_moss", chance: 1 / 20 }, { item: "seed_nightshade", chance: 1 / 25 }]
  }),
  node({
    id: "grave_crypt",
    skill: "gravedigging",
    name: "Crypt Collapse",
    kind: "grave",
    level: 40,
    xp: 34,
    ticks: 6,
    item: "bones_crypt",
    yields: [3, 6],
    respawnS: 30,
    gold: [2, 6],
    tint: 5920336,
    extras: [{ item: "ore_silver", chance: 1 / 8 }, { item: "reliquary_fragment", chance: 1 / 60 }, { item: "seed_corpse_lily", chance: 1 / 25 }, { item: "seed_wolfsbane", chance: 1 / 40 }]
  }),
  node({
    id: "grave_barrow_king",
    skill: "gravedigging",
    name: "Barrow-King's Tomb",
    kind: "grave",
    level: 70,
    xp: 70,
    ticks: 8,
    item: "bones_ancient",
    yields: [4, 8],
    respawnS: 60,
    gold: [4, 12],
    tint: 6969914,
    extras: [
      { item: "covenant_seal", chance: 1 / 40 },
      { item: "reliquary_fragment", chance: 1 / 25 },
      { item: "seed_bloodroot", chance: 1 / 20 },
      { item: "seed_moonpetal", chance: 1 / 30 },
      { item: "helm_gold", chance: 1 / 900 },
      { item: "chest_iron", chance: 1 / 700 },
      { item: "kit_iron_warden", chance: 1 / 800 }
    ]
  })
];
var NODES = Object.fromEntries(NODE_LIST.map((n) => [n.id, n]));
var NODE_IDS = NODE_LIST.map((n) => n.id);
var TOOL_KIND = { woodcutting: "hatchet", mining: "pickaxe", fishing: "rod", gravedigging: "spade" };
var TOOL_METALS = ["copper", "iron", "silver", "steel", "hell", "moon"];

// src/content/processing.ts
var WOODS = [
  ["elm", "Elm Plank", 5, "common", 8, "Hangman-elm, straight-grained and grim."],
  ["willow", "Willow Plank", 15, "uncommon", 16, "Red-streaked where the sap bled."],
  ["yew", "Yew Plank", 40, "uncommon", 26, "Churchyard yew: springy, and it remembers."],
  ["blackthorn", "Blackthorn Plank", 55, "rare", 42, "Still thorny at the knots."],
  ["ghostwood", "Ghostwood Plank", 70, "rare", 60, "Pale, cold, and lighter than air should allow."],
  ["bone_elder", "Bone Elder Plank", 85, "epic", 90, "It clacks like bone when you stack it."]
];
var FISH = [
  ["crypt_eel", "Smoked Crypt Eel", 12, "common", 10, "Smoked over coffin-wood. Heals over time."],
  ["bell_carp", "Bell Carp Stew", 28, "uncommon", 20, "It still rings faintly in the bowl. Heals over time."],
  ["drowned_pike", "Drowned Pike Fillet", 42, "uncommon", 30, "All teeth removed. Most of them. Heals over time."],
  ["lanternfish", "Lanternfish Supper", 60, "rare", 48, "It glows on the plate. Heals over time."],
  ["coelacanth", "Coelacanth Feast", 78, "epic", 80, "Older than the Covenant, and filling. Heals over time."]
];
var TOOL_NAMES = { hatchet: "Hatchet", pickaxe: "Pickaxe", rod: "Fishing Rod", spade: "Grave Spade" };
var METAL_NAME = ["Copper", "Iron", "Silver", "Steel", "Hell", "Moon"];
var METAL_RARITY = ["common", "common", "uncommon", "rare", "rare", "epic"];
var TOOL_COST = [
  [1, 2, "plank_oak", 1],
  [8, 3, "plank_elm", 2],
  [14, 3, "plank_willow", 2],
  [22, 4, "plank_yew", 2],
  [38, 4, "plank_blackthorn", 3],
  [52, 5, "plank_ghostwood", 3]
];
var PROCESSING_ITEMS = {};
var PROCESSING_RECIPES = [];
for (const [wood, name, level, rarity, sell, lore] of WOODS) {
  PROCESSING_ITEMS[`plank_${wood}`] = { name, rarity, sell, lore, kind: "material", stack: 250 };
  PROCESSING_RECIPES.push([`mill_${wood}_plank`, `Mill ${name}`, "woodcutting", level, `plank_${wood}`, 1, [[`log_${wood}`, 3]]]);
}
for (const [fish, name, level, rarity, sell, lore] of FISH) {
  PROCESSING_ITEMS[`meal_${fish}`] = { name, rarity, sell, lore, kind: "consumable", stack: 99 };
  PROCESSING_RECIPES.push([`cook_${fish}`, `Cook ${name}`, "fishing", level, `meal_${fish}`, 1, [[`fish_${fish}`, 2]]]);
}
PROCESSING_ITEMS.bone_meal = { name: "Bone Meal", rarity: "common", sell: 4, lore: "Ground at the Bone Kiln. Mourning beds love it.", kind: "material", stack: 250 };
PROCESSING_RECIPES.push(
  ["grind_bones_old", "Grind Old Bones", "gravedigging", 1, "bone_meal", 1, [["bones_old", 4]]],
  ["grind_bones_barrow", "Grind Barrow Bones", "gravedigging", 20, "bone_meal", 1, [["bones_barrow", 2]]],
  ["grind_bones_crypt", "Grind Crypt Bones", "gravedigging", 40, "bone_meal", 2, [["bones_crypt", 1]]],
  ["grind_bones_ancient", "Grind Ancient Bones", "gravedigging", 70, "bone_meal", 5, [["bones_ancient", 1]]],
  // Bone meal's first use: a cheaper road to the Major Healing Flask (no iron).
  ["brew_bone_ash_flask", "Brew Bone-Ash Flask", "fishing", 10, "flask_hp_major", 1, [["fish_fillet", 3], ["bone_meal", 2]]]
);
for (const skill of Object.keys(TOOL_KIND)) {
  const kind = TOOL_KIND[skill];
  TOOL_METALS.forEach((metal, i) => {
    const id = `tool_${kind}_${metal}`;
    const [level, ingots, plank, planks] = TOOL_COST[i];
    PROCESSING_ITEMS[id] = {
      name: `${METAL_NAME[i]} ${TOOL_NAMES[kind]}`,
      rarity: METAL_RARITY[i],
      sell: 10 * (i + 1) * (i + 1),
      lore: `Keep it in your bag: +${5 * (i + 1)}% gathering success (the best tool you carry counts).`,
      kind: "material",
      stack: 1
    };
    PROCESSING_RECIPES.push([`smith_${kind}_${metal}`, `Forge ${PROCESSING_ITEMS[id].name}`, "mining", level, id, 1, [[`ingot_${metal}`, ingots], [plank, planks]]]);
  });
}

// src/content/gardening.ts
var herb = (id, level, growMin, plantXp, harvestXp, yields = [3, 6]) => ({
  id: `seed_${id}`,
  kind: "herb",
  level,
  growMin,
  harvest: `herb_${id}`,
  yields,
  plantXp,
  harvestXp,
  seedBack: 0.4
});
var SEEDS = [
  herb("mourning_moss", 1, 20, 6, 40),
  herb("nightshade", 15, 40, 12, 105, [3, 6]),
  herb("corpse_lily", 30, 60, 20, 195),
  herb("wolfsbane", 45, 80, 30, 315, [4, 7]),
  herb("bloodroot", 60, 100, 42, 480, [4, 8]),
  herb("moonpetal", 75, 120, 60, 690, [5, 9]),
  { id: "sapling_oak", kind: "tree", level: 10, growMin: 120, harvest: "log_oak", yields: [14, 24], plantXp: 25, harvestXp: 225, seedBack: 0.15 },
  { id: "sapling_yew", kind: "tree", level: 40, growMin: 360, harvest: "log_yew", yields: [10, 18], plantXp: 60, harvestXp: 630, seedBack: 0.15 }
];
var SEED_IDS = SEEDS.map((s) => s.id);
var HERBS = [
  ["mourning_moss", "Mourning Moss", "common", 4, 2, "Grows where the grieving sit."],
  ["nightshade", "Nightshade", "uncommon", 9, 4, "Bitter, dark and quietly useful."],
  ["corpse_lily", "Corpse-lily", "uncommon", 18, 8, "It flowers only on fresh graves."],
  ["wolfsbane", "Wolfsbane", "rare", 30, 14, "Older than the wolves that fear it."],
  ["bloodroot", "Bloodroot", "rare", 48, 22, "The soil around it is always warm."],
  ["moonpetal", "Moonpetal", "epic", 80, 36, "It opens for the dead alone."]
];
var GARDEN_ITEMS = {};
for (const [id, name, rarity, sell, seedSell, lore] of HERBS) {
  GARDEN_ITEMS[`herb_${id}`] = { name, rarity, sell, lore, stack: 250 };
  if (id !== "mourning_moss") GARDEN_ITEMS[`seed_${id}`] = { name: `${name} Seed`, rarity: rarity === "epic" ? "rare" : rarity, sell: seedSell, lore: "Plant it in a Mourning Bed.", stack: 250 };
}
GARDEN_ITEMS.sapling_oak = { name: "Coffin-Oak Sapling", rarity: "common", sell: 6, lore: "Plant it in a Coffin Patch and come back in a couple of hours.", stack: 250 };
GARDEN_ITEMS.sapling_yew = { name: "Churchyard Yew Sapling", rarity: "uncommon", sell: 20, lore: "Slow, patient and worth the wait.", stack: 250 };

// src/content/alchemy.ts
var ALCHEMY_ITEMS = {
  flask_hp_grand: {
    name: "Grand Healing Flask",
    rarity: "rare",
    sell: 45,
    lore: "Bloodroot and corpse-lily, brewed until the glass runs warm. Restores 90% health. Press Q.",
    stack: 99,
    stat: { value: 150, effect: "hp_regen", duration: 60 }
  },
  elixir_moonlight: {
    name: "Moonlight Elixir",
    rarity: "epic",
    sell: 120,
    lore: "+25% spell damage for 60 seconds. It glows faintly, and the dead lean toward it.",
    stack: 99,
    stat: { value: 0.25, effect: "damage_amp", duration: 60 }
  }
};
var ALCHEMY_HEALING = { flask_hp_grand: 0.9 };
var ALCHEMY_BUFFS = {
  elixir_moonlight: { kind: "damage", value: 0.25, seconds: 60, label: "Moonlit" }
};
var ALCHEMY_RECIPES = [
  ["brew_moss_tonic", "Brew Moss Tonic", "alchemy", 1, "flask_hp_minor", 3, [["herb_mourning_moss", 3]]],
  ["brew_nightshade_draught", "Brew Nightshade Draught", "alchemy", 12, "flask_hp_major", 2, [["herb_nightshade", 3], ["bone_meal", 1]]],
  ["brew_swift_tincture", "Brew Swift Tincture", "alchemy", 18, "flask_speed", 2, [["herb_nightshade", 2], ["herb_mourning_moss", 2]]],
  ["brew_lily_tempering", "Brew Lily Tempering", "alchemy", 32, "flask_damage", 2, [["herb_corpse_lily", 3], ["bone_meal", 2]]],
  ["brew_wolfsbane_ward", "Brew Wolfsbane Ward", "alchemy", 45, "flask_void_resist", 2, [["herb_wolfsbane", 3]]],
  ["brew_bloodroot_grand", "Brew Grand Healing Flask", "alchemy", 58, "flask_hp_grand", 2, [["herb_bloodroot", 3], ["herb_corpse_lily", 1]]],
  ["brew_moonpetal_elixir", "Brew Moonlight Elixir", "alchemy", 72, "elixir_moonlight", 1, [["herb_moonpetal", 3], ["herb_bloodroot", 1]]]
];

// src/content/armorSets.ts
var ARMOR_PARTS = ["head", "chest", "hands", "legs", "feet"];
var ARMOR_SETS = {
  gravecaller: { name: "Gravecall", wearer: "Gravecaller", color: 8485789, accent: 13090268, stats: ["stat_int", "stat_vit"], lore: "Stitched for those who command the newly buried." },
  warden: { name: "Lamplight", wearer: "Grave Warden", color: 9531463, accent: 16039271, stats: ["stat_vit", "stat_str"], lore: "Brass and soot from the grave watch." },
  monk: { name: "Bellwake", wearer: "Bell Monk", color: 9533794, accent: 14991750, stats: ["stat_str", "stat_agi"], lore: "Worn thin by a thousand measured tolls." },
  ossuary: { name: "Ivory Reliquary", wearer: "Ossuary", color: 13813672, accent: 10194658, stats: ["stat_int", "stat_vit"], lore: "Bone plates engraved with the Covenant dead." },
  mourner: { name: "Widowveil", wearer: "Mourner", color: 6711948, accent: 10795488, stats: ["stat_int", "stat_agi"], lore: "Funeral cloth that remembers every name." },
  witch: { name: "Carrionbloom", wearer: "Carrion Witch", color: 6452546, accent: 12966528, stats: ["stat_int", "stat_vit"], lore: "Living thorns bind the seams shut." },
  rotweaver: { name: "Blightweave", wearer: "Rotweaver", color: 7636039, accent: 13231213, stats: ["stat_int", "stat_vit"], lore: "A sickly mantle spun where the plague took root." },
  knight: { name: "Hollow Oath", wearer: "Hollow Knight", color: 6712188, accent: 13193039, stats: ["stat_str", "stat_vit"], lore: "Blackened plate still bearing its broken vow." },
  veil: { name: "Threshold", wearer: "Veilwalker", color: 6709646, accent: 11445744, stats: ["stat_agi", "stat_int"], lore: "A border of silver marks the edge between worlds." }
};
var ASCENDED_ARMOR_SETS = {
  gravecaller: { name: "Epitaph Sovereign", wearer: "Gravecaller", color: 4208735, accent: 14141951, stats: ["stat_int", "stat_vit"], lore: "A sovereign name is written on every bone clasp." },
  warden: { name: "Nightwatch Beacon", wearer: "Grave Warden", color: 5195318, accent: 16766070, stats: ["stat_vit", "stat_str"], lore: "Its caged flame answers the last watch bell." },
  monk: { name: "Last Toll", wearer: "Bell Monk", color: 6508865, accent: 16768412, stats: ["stat_str", "stat_agi"], lore: "Bronze thread hums with the final note." },
  ossuary: { name: "Marrow Regent", wearer: "Ossuary", color: 11970690, accent: 15985870, stats: ["stat_int", "stat_vit"], lore: "The reliquary opens only for its bearer." },
  mourner: { name: "Pale Requiem", wearer: "Mourner", color: 4540776, accent: 13163775, stats: ["stat_int", "stat_agi"], lore: "A hush follows wherever the silver hem falls." },
  witch: { name: "Thorn Covenant", wearer: "Carrion Witch", color: 3888702, accent: 12120461, stats: ["stat_int", "stat_vit"], lore: "The roots draw strength from what lies beneath." },
  rotweaver: { name: "Virulent Choir", wearer: "Rotweaver", color: 4676390, accent: 14679921, stats: ["stat_int", "stat_vit"], lore: "A bright plague song runs through its seams." },
  knight: { name: "Oathbreaker", wearer: "Hollow Knight", color: 3488070, accent: 16742255, stats: ["stat_str", "stat_vit"], lore: "The oath is broken; the shield remains." },
  veil: { name: "Umbral Crossing", wearer: "Veilwalker", color: 3748950, accent: 13154559, stats: ["stat_agi", "stat_int"], lore: "The wearer leaves no shadow on either side." }
};
var PART_NAMES = { head: "Crown", chest: "Vestment", hands: "Grips", legs: "Legguards", feet: "Treads" };
var PART_POWER = { head: 2, chest: 4, hands: 2, legs: 3, feet: 2 };
var RARITY_SCALE = { common: 1, uncommon: 1, rare: 2, epic: 3 };
var PART_AREA = { head: "graves", hands: "graves", chest: "ossuary", legs: "nave", feet: "sanctum" };
var PART_RARITY = { head: "uncommon", hands: "uncommon", chest: "rare", legs: "rare", feet: "epic" };
var ASCENDED_AREA = { head: "sanctum", hands: "sanctum", chest: "cloister", legs: "cloister", feet: "pyre" };
var ASCENDED_RARITY = { head: "rare", hands: "rare", chest: "epic", legs: "epic", feet: "epic" };
function piecesFor(sets, collection) {
  return Object.entries(sets).flatMap(([disciplineId, set]) => ARMOR_PARTS.map((part) => ({
    id: collection === 1 ? `set_${disciplineId}_${part}` : `set_${disciplineId}_ascended_${part}`,
    setId: collection === 1 ? disciplineId : `${disciplineId}_ascended`,
    disciplineId,
    collection,
    setName: set.name,
    part,
    name: `${set.name} ${PART_NAMES[part]}`,
    type: `armor_${part}`,
    rarity: collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part],
    area: collection === 1 ? PART_AREA[part] : ASCENDED_AREA[part],
    stats: { [set.stats[0]]: PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] + (collection === 2 ? 1 : 0), [set.stats[1]]: Math.max(1, Math.floor(PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] / 2)) },
    color: set.color,
    accent: set.accent,
    wearer: set.wearer,
    lore: set.lore,
    sell: PART_POWER[part] * ((collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "epic" ? 22 : (collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "rare" ? 13 : 7) + (collection === 2 ? 20 : 0)
  })));
}
var ARMOR_PIECES = [...piecesFor(ARMOR_SETS, 1), ...piecesFor(ASCENDED_ARMOR_SETS, 2)];
var ARMOR_BY_ID = Object.fromEntries(ARMOR_PIECES.map((piece) => [piece.id, piece]));

// src/content/necroWeapons.ts
var NECRO_TIERS = ["bone", "iron", "gold", "hell", "moon"];
var NECRO_WEAPON_TUNING = {
  staff: {
    /** Needle reach: +25%. */
    needleRangeMult: 1.25,
    /** Extra enemies the needle passes through behind its target, and what they take relative to the first. */
    pierce: 1,
    pierceDamageMult: 0.8,
    /** The pierced enemy must be within this distance of the needle's line, and this far behind the target. */
    pierceLane: 1.1,
    pierceReach: 4.5,
    /** Passive: +10% spell damage (folded into derived Spell power, so the stats line shows it). */
    spellDamageMult: 1.1
  },
  scythe: {
    /** LMB becomes a close reaping arc: full cone angle (degrees), reach (metres), targets hit. */
    arcDeg: 100,
    reach: 3,
    maxHits: 3,
    /** Per-target damage relative to a Needle hit, cooldown and lock (a heavier, slower swing), essence per target struck. */
    damageMult: 1.15,
    cooldownMs: 520,
    lockMs: 110,
    gestureSeconds: 0.3,
    essencePerHit: 4,
    /** Bonus souls for a kill the arc delivered, on top of the normal soul every kill gives. */
    soulsPerKill: 1,
    /** How long (ms) a struck enemy still counts as reaped when it dies. */
    reapWindowMs: 1200
  },
  wand: {
    /** Needle cooldown and cast lock are divided by this (+30% cadence). */
    cadenceMult: 1.3,
    /** Needle damage: -15%. */
    damageMult: 0.85
  },
  sickle: {
    /** Each needle adds this many Withered stacks (up to the discipline's cap). */
    witheredStacks: 1,
    /** Passive: Exhume gives back this share of its essence cost. */
    exhumeRefund: 0.2
  },
  skull_focus: {
    /** Thrall cap bonus at or above this tier. */
    thrallCap: 1,
    minTier: "gold"
  },
  grimoire: {
    /** Every rite (not the LMB primary) recovers 10% sooner. */
    riteCooldownMult: 0.9
  },
  mourning_bell: {
    /** A Mourner's wraith hit heals every ally in this range by this share of their max health. */
    allyHealFrac: 0.02,
    allyHealRange: 14
  }
};
var NECRO_TIER_INFO = {
  bone: { label: "Bone", level: 1, rarity: "common", sellMult: 1, area: ["graves", "warren"] },
  iron: { label: "Iron", level: 15, rarity: "uncommon", sellMult: 2.4, area: ["ossuary", "coliseum"] },
  gold: { label: "Gold", level: 30, rarity: "rare", sellMult: 5.5, area: ["nave", "sanctum"] },
  hell: { label: "Hell", level: 45, rarity: "epic", sellMult: 11, area: ["cloister", "pyre"] },
  moon: { label: "Moon", level: 60, rarity: "epic", sellMult: 22, area: ["pyre"] }
};
var PALETTE = {
  bone: { color: 14208957, accent: 15985881 },
  iron: { color: 8027526, accent: 12830674 },
  gold: { color: 14263361, accent: 16769946 },
  hell: { color: 9054746, accent: 16742973 },
  moon: { color: 11188456, accent: 15002623 }
};
var T = NECRO_WEAPON_TUNING;
var pct = (n) => `${Math.round(n * 100)}%`;
var KINDS = {
  staff: {
    label: "Staff",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Vertebral Staff", iron: "Crypt-Iron Crozier", gold: "Reliquary Staff", hell: "Hellcoal Crozier", moon: "Staff of the Pale Moon" },
    int: [5, 9, 15, 22, 30],
    second: { key: "stat_vit", values: [0, 1, 2, 4, 6] },
    sell: 16,
    lore: {
      bone: "Fused vertebrae, still warm from the hand that carried it. Bone Needles fly farther and pierce a second body.",
      iron: "A grave-watch crozier with a bell-metal cap. Bone Needles fly farther and pierce a second body.",
      gold: "Tithe-gold wound round a reliquary shaft. Bone Needles fly farther and pierce a second body.",
      hell: "Quenched in pyre-coal; the skull at its head never stops smoking. Bone Needles fly farther and pierce a second body.",
      moon: "Cut from a bone that never touched the ground. Bone Needles fly farther and pierce a second body."
    },
    effect: `Bone Needle: +${pct(T.staff.needleRangeMult - 1)} range, pierces ${T.staff.pierce} extra target. Passive: +${pct(T.staff.spellDamageMult - 1)} spell damage. Two-handed.`
  },
  scythe: {
    label: "Scythe",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Gleaner's Scythe", iron: "Sexton's Scythe", gold: "Tithe-Reaper", hell: "Pyre Reaper", moon: "Moonreaper" },
    int: [4, 8, 13, 19, 26],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 18,
    lore: {
      bone: "A gleaner cuts what the living left standing. Your left click becomes a reaping arc; kills in it yield a soul.",
      iron: "The sexton swings it at dusk, in rows. Your left click becomes a reaping arc; kills in it yield a soul.",
      gold: "Every swing tolls a coin against the dead. Your left click becomes a reaping arc; kills in it yield a soul.",
      hell: "Its edge glows where it has drunk ash. Your left click becomes a reaping arc; kills in it yield a soul.",
      moon: "The last harvest is always by moonlight. Your left click becomes a reaping arc; kills in it yield a soul."
    },
    effect: `Left click becomes a ${T.scythe.arcDeg}\xB0 reaping arc (${T.scythe.reach} m, hits up to ${T.scythe.maxHits}); kills in the arc give +${T.scythe.soulsPerKill} soul. Two-handed.`
  },
  wand: {
    label: "Wand",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Knucklebone Wand", iron: "Iron Mourning Wand", gold: "Gilded Censer Wand", hell: "Emberthorn Wand", moon: "Wand of Quiet Stars" },
    int: [3, 6, 10, 15, 21],
    second: { key: "stat_agi", values: [0, 1, 2, 3, 5] },
    sell: 12,
    lore: {
      bone: "Finger bones, bound in a hurry. Bone Needles come faster and strike softer.",
      iron: "A mourner flicks it like a hand-bell. Bone Needles come faster and strike softer.",
      gold: "A censer chain wound round the grip. Bone Needles come faster and strike softer.",
      hell: "Thorned, and warm to the touch. Bone Needles come faster and strike softer.",
      moon: "It weighs nothing, and is never quite still. Bone Needles come faster and strike softer."
    },
    effect: `Bone Needle: +${pct(T.wand.cadenceMult - 1)} cadence, -${pct(1 - T.wand.damageMult)} damage. One-handed: pair it with an off-hand.`
  },
  sickle: {
    label: "Ritual Sickle",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Barrow Sickle", iron: "Plague Sickle", gold: "Sexton's Gilded Sickle", hell: "Blightfire Sickle", moon: "Moonrot Sickle" },
    int: [3, 6, 10, 14, 20],
    second: { key: "stat_vit", values: [1, 2, 3, 5, 7] },
    sell: 13,
    lore: {
      bone: "A curved rib, sharpened on a headstone. Bone Needles leave the target Withered; Exhume returns essence.",
      iron: "The plague priests cut herbs and throats with it. Bone Needles leave the target Withered; Exhume returns essence.",
      gold: "Gilded for rites nobody admits to. Bone Needles leave the target Withered; Exhume returns essence.",
      hell: "The rot burns instead of festering. Bone Needles leave the target Withered; Exhume returns essence.",
      moon: "Its blade is etched with a blight the moon forgave. Bone Needles leave the target Withered; Exhume returns essence."
    },
    effect: `Bone Needle applies ${T.sickle.witheredStacks} Withered stack. Passive: Exhume refunds ${pct(T.sickle.exhumeRefund)} of its essence. One-handed.`
  },
  skull_focus: {
    label: "Skull Focus",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Skull Focus", iron: "Iron-Jawed Skull Focus", gold: "Gilded Skull Focus", hell: "Cinder Skull Focus", moon: "Moon Skull Focus" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 10,
    lore: {
      bone: "A nameless skull that still listens. (Gold and better skulls hold one more thrall.)",
      iron: "Its jaw is wired shut so it cannot argue. (Gold and better skulls hold one more thrall.)",
      gold: "It remembers a legion. Hold it and command one more thrall.",
      hell: "The eyes glow like coals in a cold hearth. Hold it and command one more thrall.",
      moon: "It was a king, once; it still expects to be obeyed. Hold it and command one more thrall."
    },
    effect: `Off-hand. Gold tier and above: +${T.skull_focus.thrallCap} thrall cap.`
  },
  grimoire: {
    label: "Grimoire",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Gravedigger's Grimoire", iron: "Iron-Clasped Grimoire", gold: "Gilt Reliquary Grimoire", hell: "Hellbound Grimoire", moon: "Moonlit Grimoire" },
    int: [2, 4, 7, 10, 14],
    sell: 11,
    lore: {
      bone: "A gravedigger's ledger of names and their uses. Rites recover sooner.",
      iron: "Chained shut, and opened only from the inside. Rites recover sooner.",
      gold: "Every page is gilt, every margin a warning. Rites recover sooner.",
      hell: "Its binding is singed along the spine. Rites recover sooner.",
      moon: "The pages turn themselves to the rite you need. Rites recover sooner."
    },
    effect: `Off-hand. Rites (your other spells, not the left click) recover ${pct(1 - T.grimoire.riteCooldownMult)} faster.`
  },
  mourning_bell: {
    label: "Mourning Bell",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Mourning Bell", iron: "Iron Mourning Bell", gold: "Gilded Mourning Bell", hell: "Cinder Mourning Bell", moon: "Moon Mourning Bell" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_agi", values: [1, 2, 3, 5, 7] },
    sell: 10,
    lore: {
      bone: "Rung once for each name you could not save. A Mourner's wraith hits mend allies.",
      iron: "Its note is flat on purpose. A Mourner's wraith hits mend allies.",
      gold: "The clapper is wrapped in widow's silk. A Mourner's wraith hits mend allies.",
      hell: "It tolls for the ones who should have stayed buried. A Mourner's wraith hits mend allies.",
      moon: "You hear it a moment before it rings. A Mourner's wraith hits mend allies."
    },
    effect: `Off-hand. Mourner: each wraith hit heals allies in ${T.mourning_bell.allyHealRange} m for ${pct(T.mourning_bell.allyHealFrac)} of their max health.`
  }
};
var NECRO_KIND_LABEL = Object.fromEntries(Object.entries(KINDS).map(([k, d]) => [k, d.label]));
function build() {
  const out = [];
  for (const [kind, def] of Object.entries(KINDS)) {
    NECRO_TIERS.forEach((tier, i) => {
      const info = NECRO_TIER_INFO[tier];
      const stats = { stat_int: def.int[i] };
      if (def.second && def.second.values[i] > 0) stats[def.second.key] = def.second.values[i];
      out.push({
        id: `${kind}_${tier}`,
        kind,
        tier,
        name: def.names[tier],
        type: def.type,
        slot: def.slot,
        twoHanded: def.twoHanded,
        rarity: info.rarity,
        level: info.level,
        stats,
        sell: Math.round(def.sell * info.sellMult),
        lore: def.lore[tier],
        effect: def.effect,
        color: PALETTE[tier].color,
        accent: PALETTE[tier].accent
      });
    });
  }
  return out;
}
var NECRO_WEAPONS = build();
var NECRO_WEAPON_BY_ID = Object.fromEntries(NECRO_WEAPONS.map((w) => [w.id, w]));
var WOOD_KINDS = ["staff", "wand", "grimoire"];
var WOOD_RECIPE = {
  bone: { level: 3, ing: [["plank_oak", 3], ["bones_old", 2]] },
  iron: { level: 8, ing: [["plank_elm", 3], ["ingot_iron", 1]] },
  gold: { level: 18, ing: [["plank_willow", 3], ["ingot_gold", 1]] },
  hell: { level: 42, ing: [["plank_yew", 3], ["ingot_hell", 1]] },
  moon: { level: 57, ing: [["plank_blackthorn", 3], ["ingot_moon", 1]] }
};
var SMITH_RECIPE = {
  bone: { level: 2, ing: [["ingot_copper", 2], ["bones_old", 3]] },
  iron: { level: 10, ing: [["ingot_iron", 3]] },
  gold: { level: 20, ing: [["ingot_gold", 3], ["ingot_iron", 1]] },
  hell: { level: 40, ing: [["ingot_hell", 3], ["ingot_gold", 1]] },
  moon: { level: 55, ing: [["ingot_moon", 3], ["ingot_hell", 1]] }
};
var NECRO_RECIPES = NECRO_WEAPONS.map((w) => {
  const wood = WOOD_KINDS.includes(w.kind);
  const r = (wood ? WOOD_RECIPE : SMITH_RECIPE)[w.tier];
  return [`craft_${w.id}`, w.name, wood ? "woodcutting" : "mining", r.level, w.id, 1, r.ing];
});

// src/content/items.ts
var m = (name, rarity, sell, lore, icon) => ({
  name,
  type: "material",
  rarity,
  sell,
  lore,
  icon
});
var g = (name, rarity, sell, lore) => ({ ...m(name, rarity, sell, lore), stack: 250 });
var ITEMS = {
  material_copper_shard: m("Copper Shard", "common", 1, "Pried from coffin fittings.", "art/items/material_copper_shard.png"),
  material_copper_bar: m("Copper Bar", "common", 4, "Smelted from grave-nails.", "art/items/material_copper_bar.png"),
  ore_copper: g("Copper Ore", "common", 1, "Green-veined stone from the grave soil."),
  ingot_copper: m("Copper Ingot", "common", 4),
  ore_tin: g("Tin Ore", "common", 1, "Dull ore, cold as a burial ring."),
  ingot_tin: m("Tin Ingot", "common", 4),
  ore_iron: g("Iron Ore", "uncommon", 3, "Rusted from ossuary damp."),
  ingot_iron: m("Iron Ingot", "uncommon", 9),
  ore_bronze: g("Bronze Ore", "uncommon", 3),
  ingot_bronze: m("Bronze Ingot", "uncommon", 9),
  ore_silver: g("Silver Ore", "uncommon", 6, "Corpse-silver; it tarnishes near the living."),
  ingot_silver: m("Silver Ingot", "uncommon", 18),
  ore_gold: g("Gold Ore", "rare", 12, "Tithe-gold from the drowned nave."),
  ingot_gold: m("Gold Ingot", "rare", 36),
  ore_steel: g("Steel Ore", "rare", 14),
  ingot_steel: m("Steel Ingot", "rare", 40),
  ore_hell: g("Hell Ore", "epic", 30),
  ingot_hell: m("Hell Ingot", "epic", 90),
  ore_moon: g("Moon Ore", "epic", 40),
  ingot_moon: m("Moon Ingot", "epic", 120),
  fish_river: g("River Fish", "common", 1),
  fish_fillet: m("River Fillet", "common", 2),
  log_oak: g("Oak Log", "common", 1, "Coffin-wood, still sound."),
  plank_oak: m("Oak Plank", "common", 3),
  // Gathering (docs/PROFESSIONS-ROADMAP.md §4; rows added by migration 002-gathering.sql).
  log_elm: g("Elm Log", "common", 3, "Cut from a hangman's elm. The rope scars run deep."),
  log_willow: g("Willow Log", "uncommon", 6, "The sap runs red and never quite dries."),
  log_yew: g("Yew Log", "uncommon", 10, "Churchyard yew: the roots drink from the graves."),
  log_blackthorn: g("Blackthorn Log", "rare", 16, "Thorned even after the axe."),
  log_ghostwood: g("Ghostwood Log", "rare", 24, "Pale, cold and lighter than it should be."),
  log_bone_elder: g("Bone Elder Log", "epic", 36, "It knocks like bone when you stack it."),
  fish_crypt_eel: g("Crypt Eel", "common", 3, "Slid out of a flooded vault."),
  fish_bell_carp: g("Bell Carp", "uncommon", 6, "Its scales ring faintly when tapped."),
  fish_drowned_pike: g("Drowned Pike", "uncommon", 10, "All teeth and black water."),
  fish_lanternfish: g("Lanternfish", "rare", 16, "Still glowing, even out of the water."),
  fish_coelacanth: g("Abyssal Coelacanth", "epic", 30, "Older than the Covenant, and it looks it."),
  bones_old: g("Old Bones", "common", 1, "A pauper's remains. Grind them for the garden."),
  bones_barrow: g("Barrow Bones", "common", 4, "Heavy bones from a burial mound."),
  bones_crypt: g("Crypt Bones", "uncommon", 8, "Crypt-dust still clings to them."),
  bones_ancient: g("Ancient Bones", "rare", 18, "A barrow-king's bones, crowned with lichen."),
  seed_mourning_moss: g("Mourning Moss Seed", "common", 2, "Plant it in a mourning bed."),
  reliquary_fragment: g("Reliquary Fragment", "rare", 25, "Gilded shards from a broken reliquary."),
  covenant_seal: g("Covenant Seal", "epic", 60, "The wax still bears the Ossuary mark."),
  gem_grave_garnet: g("Grave Garnet", "uncommon", 20, "Blood-dark and cold."),
  gem_bone_opal: g("Bone Opal", "rare", 45, "Milky fire trapped in bone."),
  gem_void_sapphire: g("Void Sapphire", "epic", 90, "Its colour has no bottom."),
  flask_hp_minor: m("Minor Healing Potion", "common", 5, "Restores 35% health. Press Q."),
  flask_hp_major: m("Major Healing Flask", "uncommon", 15, "Restores 70% health. Press Q."),
  flask_speed: m("Swiftness Flask", "uncommon", 10, "+20% movement speed for 30 seconds."),
  flask_damage: m("Forge-Tempered Flask", "rare", 20, "+15% spell damage for 45 seconds."),
  flask_void_resist: m("Void Resist Flask", "uncommon", 12, "Wards off 25% of all damage for 90 seconds."),
  ring_copper: {
    name: "Copper Ring",
    type: "ring",
    rarity: "uncommon",
    sell: 12,
    lore: "A mourning band. The name inside is scratched out.",
    icon: "art/items/ring_copper.png",
    offlineStats: { stat_int: 2, stat_vit: 1 }
  },
  helm_copper: { name: "Copper Helm", type: "armor_head", rarity: "common", sell: 10, lore: "Dented by a grave-robber's spade.", offlineStats: { stat_vit: 3 } },
  plate_copper: { name: "Copper Plate", type: "armor_chest", rarity: "uncommon", sell: 20, offlineStats: { stat_vit: 6 } },
  sword_copper: { name: "Copper Sword", type: "weapon", rarity: "uncommon", sell: 18, offlineStats: { stat_str: 4 } },
  staff_oak: { name: "Oak Staff", type: "weapon", rarity: "uncommon", sell: 16, lore: "A coffin-oak focus. Bone Needles fly truer.", offlineStats: { stat_int: 5 } },
  bow_oak: { name: "Oak Shortbow", type: "weapon", rarity: "common", sell: 14, offlineStats: { stat_agi: 4 } },
  augment_copper: { name: "Copper Augment", type: "trinket", rarity: "common", sell: 8, offlineStats: { stat_int: 2 } },
  augment_iron: { name: "Iron Augment", type: "trinket", rarity: "uncommon", sell: 22, offlineStats: { stat_int: 4 } },
  helm_iron: { name: "Iron Helm", type: "armor_head", rarity: "uncommon", sell: 24, offlineStats: { stat_vit: 5, stat_str: 1 } },
  chest_iron: { name: "Iron Chestplate", type: "armor_chest", rarity: "rare", sell: 45, lore: "Salt-bloomed plate from a crypt knight.", offlineStats: { stat_vit: 9, stat_str: 2 } },
  helm_gold: { name: "Gold-Tempered Helm", type: "armor_head", rarity: "rare", sell: 60, lore: "Prelate's regalia, bell-dented.", offlineStats: { stat_vit: 6, stat_int: 4 } },
  kit_iron_warden: { name: "Iron Warden Kit", type: "trinket", rarity: "rare", sell: 55, offlineStats: { stat_vit: 4, stat_int: 4 } }
};
for (const [id, g2] of Object.entries(GARDEN_ITEMS)) ITEMS[id] ??= { name: g2.name, type: "material", rarity: g2.rarity, sell: g2.sell, lore: g2.lore, stack: g2.stack };
for (const [id, c] of Object.entries(CHARM_ITEMS)) ITEMS[id] ??= { name: c.name, type: "material", rarity: c.rarity, sell: c.sell, lore: c.lore, stack: 1 };
for (const [id, a] of Object.entries(ALCHEMY_ITEMS)) ITEMS[id] ??= { name: a.name, type: "material", rarity: a.rarity, sell: a.sell, lore: a.lore, stack: a.stack };
for (const [id, p] of Object.entries(PROCESSING_ITEMS)) ITEMS[id] ??= { name: p.name, type: "material", rarity: p.rarity, sell: p.sell, lore: p.lore, stack: p.stack };
for (const piece of ARMOR_PIECES) ITEMS[piece.id] = {
  name: piece.name,
  type: piece.type,
  rarity: piece.rarity,
  sell: piece.sell,
  lore: piece.lore,
  icon: `art/items/${piece.id}.svg`,
  offlineStats: piece.stats
};
for (const w of NECRO_WEAPONS) ITEMS[w.id] = {
  name: w.name,
  type: w.type,
  rarity: w.rarity,
  sell: w.sell,
  lore: w.lore,
  icon: `art/items/${w.id}.svg`,
  offlineStats: w.stats
};
function itemMeta(id) {
  return ITEMS[id] ?? { name: id.replace(/_/g, " "), type: "material", rarity: "common", sell: 0 };
}
var BUFF_FLASKS = {
  flask_speed: { kind: "speed", value: 0.2, seconds: 30, label: "Swift" },
  flask_damage: { kind: "damage", value: 0.15, seconds: 45, label: "Forge-tempered" },
  flask_void_resist: { kind: "ward", value: 0.25, seconds: 90, label: "Warded" },
  ...ALCHEMY_BUFFS
};
var HEALING_FLASKS = {
  flask_hp_major: 0.7,
  flask_hp_minor: 0.35,
  ...ALCHEMY_HEALING
};

// src/gameplay/contractRules.ts
var CONTRACT_SLOTS = 3;
var dayKey = (ms) => new Date(ms).toISOString().slice(0, 10);
function nextResetMs(ms) {
  const d = new Date(ms);
  return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + 1);
}
function hashString(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function candidatesFor(levels) {
  const level = (s) => Math.max(1, levels[s] ?? 1);
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  const add = (c) => {
    if (seen.has(c.itemId)) return;
    seen.add(c.itemId);
    out.push(c);
  };
  for (const n of Object.values(NODES)) if (n.level <= level(n.skill)) add({ itemId: n.item, skill: n.skill, level: n.level, processed: false });
  for (const [, , skill, req, result] of PROCESSING_RECIPES) {
    if (result.startsWith("tool_")) continue;
    if (req <= level(skill)) add({ itemId: result, skill, level: req, processed: true });
  }
  for (const [, , skill, req, result] of ALCHEMY_RECIPES) if (req <= level(skill)) add({ itemId: result, skill, level: req, processed: true });
  for (const s of SEEDS) if (s.kind === "herb" && s.level <= level("gardening")) add({ itemId: s.harvest, skill: "gardening", level: s.level, processed: true });
  return out.sort((a, b) => a.level - b.level || a.itemId.localeCompare(b.itemId));
}
var HARD_REWARDS = [
  { minLevel: 60, item: { itemId: "gem_void_sapphire", qty: 1 } },
  { minLevel: 30, item: { itemId: "gem_bone_opal", qty: 1 } },
  { minLevel: 0, item: { itemId: "gem_grave_garnet", qty: 1 } }
];
var MEDIUM_REWARDS = [
  { itemId: "flask_hp_minor", qty: 3 },
  { itemId: "seed_mourning_moss", qty: 2 }
];
function generateBoard(characterId, day, levels) {
  const rand = mulberry32(hashString(`${characterId}:${day}`));
  const pool = candidatesFor(levels);
  const cands = pool.length >= CONTRACT_SLOTS ? pool : [...pool, ...candidatesFor({}).filter((c) => !pool.includes(c))];
  const third = Math.max(1, Math.floor(cands.length / 3));
  const bands = [cands.slice(0, third), cands.slice(third, third * 2), cands.slice(third * 2)].map((b, i) => b.length ? b : cands.slice(i));
  const used = /* @__PURE__ */ new Set();
  const board = [];
  for (let slot = 0; slot < CONTRACT_SLOTS; slot++) {
    const band = bands[slot].filter((c) => !used.has(c.itemId));
    const from = band.length ? band : cands.filter((c) => !used.has(c.itemId));
    const pick = from[Math.floor(rand() * from.length)] ?? cands[slot % cands.length];
    used.add(pick.itemId);
    let qty = Math.round(Math.min(80, Math.max(12, 70 - pick.level * 0.5)) * [1, 0.8, 0.6][slot]);
    if (pick.processed) qty = Math.max(6, Math.round(qty * 0.4));
    qty = Math.max(4, qty + Math.floor(rand() * 5) - 2);
    const sell = itemMeta(pick.itemId).sell;
    const rewardGold = Math.round(qty * sell * 1.6 + 20 * (slot + 1));
    let rewardItem = null;
    if (slot === 2) rewardItem = HARD_REWARDS.find((r) => pick.level >= r.minLevel).item;
    else if (slot === 1 && rand() < 0.35) rewardItem = MEDIUM_REWARDS[Math.floor(rand() * MEDIUM_REWARDS.length)];
    board.push({ slot, itemId: pick.itemId, qty, skill: pick.skill, rewardGold, rewardItem });
  }
  return board;
}
function bonusFor(board) {
  const gold = Math.round(board.reduce((n, c) => n + c.rewardGold, 0) * 0.5);
  return { gold, item: { itemId: "gem_grave_garnet", qty: 1 } };
}
function streakOf(doneDays, today) {
  const days = new Set(doneDays);
  const step = (d, by) => dayKey(Date.parse(`${d}T00:00:00Z`) + by * 864e5);
  let cursor = days.has(today) ? today : step(today, -1);
  let n = 0;
  while (days.has(cursor)) {
    n++;
    cursor = step(cursor, -1);
  }
  return n;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  CONTRACT_SLOTS,
  bonusFor,
  candidatesFor,
  dayKey,
  generateBoard,
  nextResetMs,
  streakOf
});
