// GENERATED by tools/build-server-rules.mjs from src/gameplay/gardeningRules.ts — do not edit by hand.
// Grave Gardening rules (plots, growth, harvest rolls) shared by the web client and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/gardeningRules.ts
var gardeningRules_exports = {};
__export(gardeningRules_exports, {
  COMPOST_ITEM: () => COMPOST_ITEM,
  PLOTS: () => PLOTS,
  SEEDS: () => SEEDS,
  growMs: () => growMs,
  plantBlocker: () => plantBlocker,
  plotDef: () => plotDef,
  remainingText: () => remainingText,
  rollHarvest: () => rollHarvest,
  seedDef: () => seedDef,
  stateOf: () => stateOf
});
module.exports = __toCommonJS(gardeningRules_exports);

// src/content/gardening.ts
var PLOTS = [
  { id: "h0", kind: "herb", label: "Mourning Bed I" },
  { id: "h1", kind: "herb", label: "Mourning Bed II" },
  { id: "h2", kind: "herb", label: "Mourning Bed III" },
  { id: "h3", kind: "herb", label: "Mourning Bed IV" },
  { id: "t0", kind: "tree", label: "Coffin Patch I" },
  { id: "t1", kind: "tree", label: "Coffin Patch II" }
];
var herb = (id, level, growMin, plantXp, harvestXp, yields = [3, 6]) => ({
  id: `seed_${id}`,
  kind: "herb",
  level,
  growMin,
  harvest: `herb_${id}`,
  yields,
  plantXp,
  harvestXp,
  seedBack: 0.4
});
var SEEDS = [
  herb("mourning_moss", 1, 20, 6, 40),
  herb("nightshade", 15, 40, 12, 105, [3, 6]),
  herb("corpse_lily", 30, 60, 20, 195),
  herb("wolfsbane", 45, 80, 30, 315, [4, 7]),
  herb("bloodroot", 60, 100, 42, 480, [4, 8]),
  herb("moonpetal", 75, 120, 60, 690, [5, 9]),
  { id: "sapling_oak", kind: "tree", level: 10, growMin: 120, harvest: "log_oak", yields: [14, 24], plantXp: 25, harvestXp: 225, seedBack: 0.15 },
  { id: "sapling_yew", kind: "tree", level: 40, growMin: 360, harvest: "log_yew", yields: [10, 18], plantXp: 60, harvestXp: 630, seedBack: 0.15 }
];
var SEED_IDS = SEEDS.map((s) => s.id);
var seedDef = (id) => SEEDS.find((s) => s.id === id);
var COMPOST_ITEM = "bone_meal";
var COMPOST_SPEED = 0.75;
var HERBS = [
  ["mourning_moss", "Mourning Moss", "common", 4, 2, "Grows where the grieving sit."],
  ["nightshade", "Nightshade", "uncommon", 9, 4, "Bitter, dark and quietly useful."],
  ["corpse_lily", "Corpse-lily", "uncommon", 18, 8, "It flowers only on fresh graves."],
  ["wolfsbane", "Wolfsbane", "rare", 30, 14, "Older than the wolves that fear it."],
  ["bloodroot", "Bloodroot", "rare", 48, 22, "The soil around it is always warm."],
  ["moonpetal", "Moonpetal", "epic", 80, 36, "It opens for the dead alone."]
];
var GARDEN_ITEMS = {};
for (const [id, name, rarity, sell, seedSell, lore] of HERBS) {
  GARDEN_ITEMS[`herb_${id}`] = { name, rarity, sell, lore, stack: 250 };
  if (id !== "mourning_moss") GARDEN_ITEMS[`seed_${id}`] = { name: `${name} Seed`, rarity: rarity === "epic" ? "rare" : rarity, sell: seedSell, lore: "Plant it in a Mourning Bed.", stack: 250 };
}
GARDEN_ITEMS.sapling_oak = { name: "Coffin-Oak Sapling", rarity: "common", sell: 6, lore: "Plant it in a Coffin Patch and come back in a couple of hours.", stack: 250 };
GARDEN_ITEMS.sapling_yew = { name: "Churchyard Yew Sapling", rarity: "uncommon", sell: 20, lore: "Slow, patient and worth the wait.", stack: 250 };

// src/gameplay/gardeningRules.ts
var plotDef = (id) => PLOTS.find((p) => p.id === id);
var stateOf = (row, now) => !row || !row.seedId ? "empty" : now >= row.readyAt ? "ready" : "growing";
var growMs = (seed, composted) => Math.round(seed.growMin * 6e4 * (composted ? COMPOST_SPEED : 1));
function plantBlocker(plot, seedId, level, existing, now) {
  const seed = seedDef(seedId);
  if (!plot) return "There is no such plot.";
  if (!seed) return "That cannot be planted.";
  if (seed.kind !== plot.kind) return seed.kind === "tree" ? "Saplings go in a Coffin Patch." : "Seeds go in a Mourning Bed.";
  if (level < seed.level) return `Requires Grave Gardening ${seed.level}.`;
  if (stateOf(existing, now) !== "empty") return "Something is already growing there.";
  return null;
}
function rollHarvest(seed, rng) {
  const [lo, hi] = seed.yields;
  const qty = lo + Math.floor(rng() * (hi - lo + 1));
  return { itemId: seed.harvest, qty, seedBack: rng() < seed.seedBack ? seed.id : null, xp: seed.harvestXp };
}
function remainingText(ms) {
  const s = Math.max(0, Math.ceil(ms / 1e3));
  const h = Math.floor(s / 3600);
  const m = Math.floor(s % 3600 / 60);
  return h ? `${h}h ${m}m` : m ? `${m}m` : `${s}s`;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  COMPOST_ITEM,
  PLOTS,
  SEEDS,
  growMs,
  plantBlocker,
  plotDef,
  remainingText,
  rollHarvest,
  seedDef,
  stateOf
});
