// GENERATED by tools/build-server-rules.mjs from src/gameplay/gatheringRules.ts — do not edit by hand.
// Gathering rules (nodes, XP curve, rolls, time budget) shared by the web client and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/gatheringRules.ts
var gatheringRules_exports = {};
__export(gatheringRules_exports, {
  ALL_SKILLS: () => ALL_SKILLS,
  BAG_SLOTS: () => BAG_SLOTS,
  GATHER_BURST: () => GATHER_BURST,
  GATHER_FLUSH_MS: () => GATHER_FLUSH_MS,
  GATHER_MAX_ACTIONS_PER_HOUR: () => GATHER_MAX_ACTIONS_PER_HOUR,
  GATHER_MAX_BATCH: () => GATHER_MAX_BATCH,
  GATHER_MAX_WINDOW_MS: () => GATHER_MAX_WINDOW_MS,
  GATHER_SKILLS: () => GATHER_SKILLS,
  LEVEL_CAP: () => LEVEL_CAP,
  MATERIAL_STACK: () => MATERIAL_STACK,
  NODES: () => NODES,
  NODE_IDS: () => NODE_IDS,
  RICH_RESPAWN: () => RICH_RESPAWN,
  RICH_YIELD: () => RICH_YIELD,
  SKILLS: () => SKILLS,
  TICK_MS: () => TICK_MS,
  XP_CURVE: () => XP_CURVE,
  actionMs: () => actionMs,
  addSkillXp: () => addSkillXp,
  blankLedger: () => blankLedger,
  checkBudget: () => checkBudget,
  grantableItems: () => grantableItems,
  nodesForSkill: () => nodesForSkill,
  placeItems: () => placeItems,
  rollBatch: () => rollBatch,
  rollGather: () => rollGather,
  successChance: () => successChance,
  totalXpFor: () => totalXpFor,
  xpPerHour: () => xpPerHour,
  xpToNext: () => xpToNext,
  xpToNextCurve: () => xpToNextCurve,
  xpToNextLive: () => xpToNextLive
});
module.exports = __toCommonJS(gatheringRules_exports);
var GATHER_SKILLS = ["woodcutting", "mining", "fishing", "gravedigging"];
var ALL_SKILLS = ["woodcutting", "mining", "fishing", "gravedigging", "gardening"];
var SKILLS = {
  woodcutting: { name: "Woodcutting", rite: "Rite of Coffin-Oak", color: "#c9a36b", gesture: "dig", sfx: "chop", verb: "Chop" },
  mining: { name: "Mining", rite: "Rite of Grave-Iron", color: "#b7bcc4", gesture: "dig", sfx: "pick", verb: "Mine" },
  fishing: { name: "Fishing", rite: "Rite of the Black Water", color: "#6fb3c8", gesture: "cast", sfx: "splash", verb: "Fish" },
  gravedigging: { name: "Gravedigging", rite: "Rite of the Sexton", color: "#d8cfa8", gesture: "dig", sfx: "shovel", verb: "Dig" },
  gardening: { name: "Grave Gardening", rite: "Rite of the Mourning Bed", color: "#9fc27a", gesture: "cast", sfx: "shovel", verb: "Tend" }
};
var TICK_MS = 600;
var LEVEL_CAP = 99;
var GATHER_BURST = 3;
var GATHER_MAX_WINDOW_MS = 3e4;
var GATHER_MAX_ACTIONS_PER_HOUR = 1800;
var GATHER_FLUSH_MS = 8e3;
var GATHER_MAX_BATCH = 40;
var RICH_YIELD = 1.5;
var RICH_RESPAWN = 0.5;
var node = (d) => ({ extras: [], ...d });
var CROWS_NEST = [
  { item: "seed_mourning_moss", chance: 1 / 300 },
  { item: "ring_copper", chance: 1 / 600 }
];
var GEMS = (scale) => [
  { item: "gem_grave_garnet", chance: 1 / 250 * 0.6 * scale },
  { item: "gem_bone_opal", chance: 1 / 250 * 0.3 * scale },
  { item: "gem_void_sapphire", chance: 1 / 250 * 0.1 * scale }
];
var NODE_LIST = [
  // Woodcutting
  node({ id: "coffin_oak", skill: "woodcutting", name: "Coffin-Oak", kind: "tree", level: 1, xp: 6, ticks: 4, item: "log_oak", yields: [1, 4], respawnS: 8, extras: CROWS_NEST, tint: 7033398 }),
  node({ id: "hangman_elm", skill: "woodcutting", name: "Hangman's Elm", kind: "tree", level: 5, xp: 14, ticks: 5, item: "log_elm", yields: [3, 6], respawnS: 12, extras: CROWS_NEST, tint: 6117948 }),
  node({ id: "bleeding_willow", skill: "woodcutting", name: "Bleeding Willow", kind: "tree", level: 15, xp: 24, ticks: 5, item: "log_willow", yields: [4, 8], respawnS: 15, extras: CROWS_NEST, tint: 8010292 }),
  node({ id: "churchyard_yew", skill: "woodcutting", name: "Churchyard Yew", kind: "tree", level: 45, xp: 38, ticks: 6, item: "log_yew", yields: [5, 10], respawnS: 30, extras: CROWS_NEST, tint: 3099187 }),
  node({ id: "blackthorn", skill: "woodcutting", name: "Blackthorn", kind: "tree", level: 60, xp: 55, ticks: 7, item: "log_blackthorn", yields: [6, 12], respawnS: 45, extras: CROWS_NEST, tint: 2762032 }),
  node({ id: "ghostwood", skill: "woodcutting", name: "Ghostwood", kind: "tree", level: 75, xp: 80, ticks: 8, item: "log_ghostwood", yields: [6, 12], respawnS: 60, extras: CROWS_NEST, tint: 10467504 }),
  node({ id: "bone_elder", skill: "woodcutting", name: "Bone Elder", kind: "tree", level: 90, xp: 115, ticks: 8, item: "log_bone_elder", yields: [8, 14], respawnS: 120, extras: CROWS_NEST, tint: 15129796 }),
  // Mining: one seam model, tinted per ore; geodes for the top tiers.
  node({ id: "seam_copper", skill: "mining", name: "Copper Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_copper", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 4170618 }),
  node({ id: "seam_tin", skill: "mining", name: "Tin Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_tin", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 10134440 }),
  node({ id: "seam_iron", skill: "mining", name: "Iron Seam", kind: "seam", level: 10, xp: 12, ticks: 5, item: "ore_iron", yields: [2, 4], respawnS: 9, extras: GEMS(1), tint: 10115644 }),
  node({ id: "seam_bronze", skill: "mining", name: "Bronze Seam", kind: "seam", level: 20, xp: 18, ticks: 5, item: "ore_bronze", yields: [2, 5], respawnS: 12, extras: GEMS(1), tint: 12618314 }),
  node({ id: "seam_silver", skill: "mining", name: "Silver Seam", kind: "seam", level: 30, xp: 24, ticks: 5, item: "ore_silver", yields: [3, 6], respawnS: 18, extras: GEMS(1.2), tint: 14212582 }),
  node({ id: "seam_gold", skill: "mining", name: "Gold Seam", kind: "seam", level: 40, xp: 32, ticks: 6, item: "ore_gold", yields: [3, 6], respawnS: 25, extras: GEMS(1.4), tint: 15251530 }),
  node({ id: "seam_steel", skill: "mining", name: "Steel Seam", kind: "seam", level: 50, xp: 42, ticks: 6, item: "ore_steel", yields: [4, 7], respawnS: 32, extras: GEMS(1.6), tint: 8228774 }),
  node({ id: "geode_hell", skill: "mining", name: "Hell Geode", kind: "geode", level: 65, xp: 60, ticks: 7, item: "ore_hell", yields: [4, 8], respawnS: 45, extras: GEMS(2), tint: 14701098 }),
  node({ id: "geode_moon", skill: "mining", name: "Moon Geode", kind: "geode", level: 80, xp: 90, ticks: 8, item: "ore_moon", yields: [5, 9], respawnS: 60, extras: GEMS(2.5), tint: 10405119 }),
  // Fishing: spots drift, so a "depleted" pool is a spot that moved on.
  node({ id: "pool_still", skill: "fishing", name: "Still Pool", kind: "pool", level: 1, xp: 6, ticks: 4, item: "fish_river", yields: [8, 16], respawnS: 6, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 2902610 }),
  node({ id: "pool_eels", skill: "fishing", name: "Crypt Eels", kind: "pool", level: 15, xp: 14, ticks: 5, item: "fish_crypt_eel", yields: [8, 16], respawnS: 8, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 3231807 }),
  node({ id: "pool_carp", skill: "fishing", name: "Bell Carp", kind: "pool", level: 30, xp: 24, ticks: 5, item: "fish_bell_carp", yields: [10, 18], respawnS: 10, extras: [{ item: "reliquary_fragment", chance: 1 / 300 }], tint: 5921336 }),
  node({ id: "pool_pike", skill: "fishing", name: "Drowned Pike", kind: "pool", level: 45, xp: 38, ticks: 6, item: "fish_drowned_pike", yields: [10, 18], respawnS: 12, extras: [{ item: "reliquary_fragment", chance: 1 / 250 }], tint: 2375754 }),
  node({ id: "pool_lantern", skill: "fishing", name: "Lanternfish", kind: "pool", level: 62, xp: 58, ticks: 7, item: "fish_lanternfish", yields: [12, 20], respawnS: 14, extras: [{ item: "reliquary_fragment", chance: 1 / 200 }], tint: 3828314 }),
  node({ id: "pool_coelacanth", skill: "fishing", name: "Abyssal Coelacanth", kind: "pool", level: 80, xp: 95, ticks: 8, item: "fish_coelacanth", yields: [12, 20], respawnS: 16, extras: [{ item: "covenant_seal", chance: 1 / 300 }], tint: 1715268 }),
  // Gravedigging: the necromancer's own skill.
  node({
    id: "grave_pauper",
    skill: "gravedigging",
    name: "Pauper's Grave",
    kind: "grave",
    level: 1,
    xp: 7,
    ticks: 4,
    item: "bones_old",
    yields: [2, 4],
    respawnS: 10,
    gold: [0, 2],
    tint: 4865068,
    extras: [{ item: "seed_mourning_moss", chance: 1 / 12 }]
  }),
  node({
    id: "grave_mound",
    skill: "gravedigging",
    name: "Burial Mound",
    kind: "grave",
    level: 20,
    xp: 18,
    ticks: 5,
    item: "bones_barrow",
    yields: [3, 5],
    respawnS: 18,
    gold: [1, 4],
    tint: 5064242,
    extras: [{ item: "ring_copper", chance: 1 / 120 }, { item: "seed_mourning_moss", chance: 1 / 20 }]
  }),
  node({
    id: "grave_crypt",
    skill: "gravedigging",
    name: "Crypt Collapse",
    kind: "grave",
    level: 40,
    xp: 34,
    ticks: 6,
    item: "bones_crypt",
    yields: [3, 6],
    respawnS: 30,
    gold: [2, 6],
    tint: 5920336,
    extras: [{ item: "ore_silver", chance: 1 / 8 }, { item: "reliquary_fragment", chance: 1 / 60 }]
  }),
  node({
    id: "grave_barrow_king",
    skill: "gravedigging",
    name: "Barrow-King's Tomb",
    kind: "grave",
    level: 70,
    xp: 70,
    ticks: 8,
    item: "bones_ancient",
    yields: [4, 8],
    respawnS: 60,
    gold: [4, 12],
    tint: 6969914,
    extras: [
      { item: "covenant_seal", chance: 1 / 40 },
      { item: "reliquary_fragment", chance: 1 / 25 },
      { item: "helm_gold", chance: 1 / 900 },
      { item: "chest_iron", chance: 1 / 700 },
      { item: "kit_iron_warden", chance: 1 / 800 }
    ]
  })
];
var NODES = Object.fromEntries(NODE_LIST.map((n) => [n.id, n]));
var NODE_IDS = NODE_LIST.map((n) => n.id);
var nodesForSkill = (skill) => NODE_LIST.filter((n) => n.skill === skill);
function grantableItems() {
  const ids = /* @__PURE__ */ new Set();
  for (const n of NODE_LIST) {
    ids.add(n.item);
    for (const e of n.extras) ids.add(e.item);
  }
  return [...ids];
}
var actionMs = (def) => def.ticks * TICK_MS;
var xpToNextLive = (level) => Math.max(1, level) * 50;
var xpToNextCurve = (level) => Math.round(50 * Math.max(1, level) * Math.pow(1.035, Math.max(0, level - 20)));
var XP_CURVE = "live";
var xpToNext = (level) => XP_CURVE === "curve" ? xpToNextCurve(level) : xpToNextLive(level);
function totalXpFor(level, fn = xpToNext) {
  let t = 0;
  for (let l = 1; l < level; l++) t += fn(l);
  return t;
}
function addSkillXp(p, gained) {
  let level = Math.max(1, Math.min(LEVEL_CAP, Math.floor(p.level) || 1));
  let xp = Math.max(0, Math.floor(p.xp) || 0) + Math.max(0, Math.floor(gained));
  let leveled = 0;
  while (level < LEVEL_CAP && xp >= xpToNext(level)) {
    xp -= xpToNext(level);
    level++;
    leveled++;
  }
  if (level >= LEVEL_CAP) xp = 0;
  return { level, xp, leveled };
}
function successChance(def, level, toolTier = 0) {
  const p = (def.level === 1 ? 0.6 : 0.45) + 0.01 * (level - def.level) + 0.05 * toolTier;
  return Math.max(0.2, Math.min(0.9, p));
}
var randInt = (rng, lo, hi) => lo + Math.floor(rng() * (hi - lo + 1));
function rollGather(def, level, rng, toolTier = 0) {
  if (level < def.level || rng() >= successChance(def, level, toolTier)) return { success: false, xp: 0, gold: 0, items: [] };
  const items = [{ itemId: def.item, qty: 1 }];
  for (const e of def.extras) {
    if (rng() < e.chance) items.push({ itemId: e.item, qty: e.qty ? randInt(rng, e.qty[0], e.qty[1]) : 1 });
  }
  return { success: true, xp: def.xp, gold: def.gold ? randInt(rng, def.gold[0], def.gold[1]) : 0, items };
}
function rollBatch(def, start, actions, rng, toolTier = 0) {
  let progress = { level: start.level, xp: start.xp };
  const bag = /* @__PURE__ */ new Map();
  let xp = 0;
  let gold = 0;
  let successes = 0;
  let leveled = 0;
  for (let i = 0; i < actions; i++) {
    const r = rollGather(def, progress.level, rng, toolTier);
    if (!r.success) continue;
    successes++;
    xp += r.xp;
    gold += r.gold;
    for (const g of r.items) bag.set(g.itemId, (bag.get(g.itemId) ?? 0) + g.qty);
    const next = addSkillXp(progress, r.xp);
    leveled += next.leveled;
    progress = { level: next.level, xp: next.xp };
  }
  return { progress, successes, xp, gold, items: [...bag].map(([itemId, qty]) => ({ itemId, qty })), leveled };
}
function xpPerHour(def, level, toolTier = 0) {
  return 36e5 / actionMs(def) * successChance(def, level, toolTier) * def.xp;
}
var blankLedger = () => ({ lastAt: 0, hourStart: 0, hourActions: 0 });
function checkBudget(def, ledger, claimed, now, afk = false) {
  const want = Math.floor(Number(claimed));
  if (!Number.isFinite(want) || want < 1) return { ok: false, error: "Nothing to gather" };
  if (afk && !ledger.lastAt) return { ok: false, error: "Start AFK gathering from Skills first." };
  const windowMs = afk ? 9e4 : GATHER_MAX_WINDOW_MS;
  const elapsed = ledger.lastAt > 0 ? Math.max(0, now - ledger.lastAt) : windowMs;
  const byTime = Math.floor(Math.min(elapsed, windowMs) / actionMs(def)) + (afk ? 0 : GATHER_BURST);
  const rolled = now - ledger.hourStart >= 36e5 || ledger.hourStart === 0;
  const hourStart = rolled ? now : ledger.hourStart;
  const hourActions = rolled ? 0 : ledger.hourActions;
  const byHour = GATHER_MAX_ACTIONS_PER_HOUR - hourActions;
  const accepted = Math.min(want, byTime, byHour, GATHER_MAX_BATCH);
  if (accepted <= 0) {
    return { ok: false, error: byHour <= 0 ? "Your hands are spent for this hour. Rest, then gather again." : "You are gathering faster than your hands allow. Slow down." };
  }
  const lastAt = afk ? Math.max(ledger.lastAt, now - windowMs) + accepted * actionMs(def) : now;
  return { ok: true, accepted, ledger: { lastAt, hourStart, hourActions: hourActions + accepted } };
}
var BAG_SLOTS = 24;
var MATERIAL_STACK = 250;
function placeItems(bag, grants, maxStack) {
  const rows = bag.map((r) => ({ ...r }));
  const touched = /* @__PURE__ */ new Map();
  const inserts = [];
  const stored = [];
  const rejected = [];
  const used = new Set(rows.map((r) => r.slot));
  for (const g of grants) {
    let left = g.qty;
    const cap = Math.max(1, maxStack(g.itemId));
    for (const r of [...rows, ...inserts]) {
      if (left <= 0) break;
      if (r.itemId !== g.itemId || r.qty >= cap) continue;
      const add = Math.min(left, cap - r.qty);
      r.qty += add;
      left -= add;
      if (rows.includes(r)) touched.set(r.slot, r.qty);
    }
    for (let s = 0; s < BAG_SLOTS && left > 0; s++) {
      if (used.has(s)) continue;
      const add = Math.min(left, cap);
      inserts.push({ slot: s, itemId: g.itemId, qty: add });
      used.add(s);
      left -= add;
    }
    if (g.qty - left > 0) stored.push({ itemId: g.itemId, qty: g.qty - left });
    if (left > 0) rejected.push({ itemId: g.itemId, qty: left });
  }
  return { updates: [...touched].map(([slot, qty]) => ({ slot, qty })), inserts, stored, rejected };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  ALL_SKILLS,
  BAG_SLOTS,
  GATHER_BURST,
  GATHER_FLUSH_MS,
  GATHER_MAX_ACTIONS_PER_HOUR,
  GATHER_MAX_BATCH,
  GATHER_MAX_WINDOW_MS,
  GATHER_SKILLS,
  LEVEL_CAP,
  MATERIAL_STACK,
  NODES,
  NODE_IDS,
  RICH_RESPAWN,
  RICH_YIELD,
  SKILLS,
  TICK_MS,
  XP_CURVE,
  actionMs,
  addSkillXp,
  blankLedger,
  checkBudget,
  grantableItems,
  nodesForSkill,
  placeItems,
  rollBatch,
  rollGather,
  successChance,
  totalXpFor,
  xpPerHour,
  xpToNext,
  xpToNextCurve,
  xpToNextLive
});
