// GENERATED by tools/build-server-rules.mjs from src/gameplay/laborRules.ts — do not edit by hand.
// Grave Laborers (thrall labour) rules shared by the web client and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/laborRules.ts
var laborRules_exports = {};
__export(laborRules_exports, {
  LABOR: () => LABOR,
  assignBlocker: () => assignBlocker,
  claimRng: () => claimRng,
  estimate: () => estimate,
  hashSeed: () => hashSeed,
  laborActions: () => laborActions,
  laborSlots: () => laborSlots,
  postsFor: () => postsFor,
  rollLabor: () => rollLabor,
  totalGatherLevel: () => totalGatherLevel
});
module.exports = __toCommonJS(laborRules_exports);

// src/content/cosmetics.ts
var PETS = [
  { id: "pet_tithe_bat", name: "Tithe Bat", charm: "charm_tithe_bat", skill: "woodcutting", model: "tithe_bat", scale: 0.7, fly: { height: 1.5, speed: 17, amp: 0.75, body: 0.22 }, rarity: "rare", lore: "It roosts in the coffin-oaks and follows the sound of the axe." },
  { id: "pet_grave_rat", name: "Grave Rat", charm: "charm_grave_rat", skill: "mining", model: "skull_rat", scale: 1.05, rarity: "rare", lore: "It found a better seam than you did, and it will not tell you where." },
  { id: "pet_drowned_pup", name: "Drowned Pup", charm: "charm_drowned_pup", skill: "fishing", model: "bone_hound", scale: 0.55, tint: 10470612, rarity: "rare", lore: "Pulled from black water, still wet, still hopeful." },
  { id: "pet_wee_thrall", name: "Wee Thrall", charm: "charm_wee_thrall", skill: "gravedigging", model: "skeleton_thrall", scale: 0.32, rarity: "epic", lore: "A very small skeleton with a very large sense of duty." },
  { id: "pet_shroud_moth", name: "Shroud Moth", charm: "charm_shroud_moth", skill: "gardening", model: "shroud_moth", scale: 0.6, fly: { height: 1.7, speed: 8, amp: 0.55, body: 0.16 }, tint: 14215360, rarity: "epic", lore: "It drinks the light from the beds and gives a little back." }
];
var petForSkill = (skill) => PETS.find((p) => p.skill === skill);
var PET_CHANCE = 1 / 3500;
var petChance = (nodeLevel) => PET_CHANCE * (1 + nodeLevel / 100);
var GARDEN_PET_CHANCE = 1 / 35;
var CHARM_ITEMS = Object.fromEntries(
  PETS.map((p) => [p.charm, { name: `${p.name} Charm`, rarity: p.rarity, sell: 250, lore: `Adopt it (Capes & Pets, N) and the ${p.name} is yours for good. ${p.lore}` }])
);

// src/gameplay/gatheringRules.ts
var GATHER_SKILLS = ["woodcutting", "mining", "fishing", "gravedigging"];
var TICK_MS = 600;
var LEVEL_CAP = 99;
var petLine = (skill, level) => {
  const pet = petForSkill(skill);
  return pet ? [{ item: pet.charm, chance: petChance(level) }] : [];
};
var node = (d) => ({ ...d, extras: [...d.extras ?? [], ...petLine(d.skill, d.level)] });
var CROWS_NEST = [
  { item: "seed_mourning_moss", chance: 1 / 300 },
  { item: "ring_copper", chance: 1 / 600 }
];
var GEMS = (scale) => [
  { item: "gem_grave_garnet", chance: 1 / 250 * 0.6 * scale },
  { item: "gem_bone_opal", chance: 1 / 250 * 0.3 * scale },
  { item: "gem_void_sapphire", chance: 1 / 250 * 0.1 * scale }
];
var NODE_LIST = [
  // Woodcutting
  node({ id: "coffin_oak", skill: "woodcutting", name: "Coffin-Oak", kind: "tree", level: 1, xp: 6, ticks: 4, item: "log_oak", yields: [1, 4], respawnS: 8, extras: [...CROWS_NEST, { item: "sapling_oak", chance: 1 / 40 }], tint: 7033398 }),
  node({ id: "hangman_elm", skill: "woodcutting", name: "Hangman's Elm", kind: "tree", level: 5, xp: 14, ticks: 5, item: "log_elm", yields: [3, 6], respawnS: 12, extras: CROWS_NEST, tint: 6117948 }),
  node({ id: "bleeding_willow", skill: "woodcutting", name: "Bleeding Willow", kind: "tree", level: 15, xp: 24, ticks: 5, item: "log_willow", yields: [4, 8], respawnS: 15, extras: CROWS_NEST, tint: 8010292 }),
  node({ id: "churchyard_yew", skill: "woodcutting", name: "Churchyard Yew", kind: "tree", level: 45, xp: 38, ticks: 6, item: "log_yew", yields: [5, 10], respawnS: 30, extras: [...CROWS_NEST, { item: "sapling_yew", chance: 1 / 50 }], tint: 3099187 }),
  node({ id: "blackthorn", skill: "woodcutting", name: "Blackthorn", kind: "tree", level: 60, xp: 55, ticks: 7, item: "log_blackthorn", yields: [6, 12], respawnS: 45, extras: CROWS_NEST, tint: 2762032 }),
  node({ id: "ghostwood", skill: "woodcutting", name: "Ghostwood", kind: "tree", level: 75, xp: 80, ticks: 8, item: "log_ghostwood", yields: [6, 12], respawnS: 60, extras: CROWS_NEST, tint: 10467504 }),
  node({ id: "bone_elder", skill: "woodcutting", name: "Bone Elder", kind: "tree", level: 90, xp: 115, ticks: 8, item: "log_bone_elder", yields: [8, 14], respawnS: 120, extras: CROWS_NEST, tint: 15129796 }),
  // Mining: one seam model, tinted per ore; geodes for the top tiers.
  node({ id: "seam_copper", skill: "mining", name: "Copper Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_copper", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 4170618 }),
  node({ id: "seam_tin", skill: "mining", name: "Tin Seam", kind: "seam", level: 1, xp: 6, ticks: 4, item: "ore_tin", yields: [1, 3], respawnS: 5, extras: GEMS(1), tint: 10134440 }),
  node({ id: "seam_iron", skill: "mining", name: "Iron Seam", kind: "seam", level: 10, xp: 12, ticks: 5, item: "ore_iron", yields: [2, 4], respawnS: 9, extras: GEMS(1), tint: 10115644 }),
  node({ id: "seam_bronze", skill: "mining", name: "Bronze Seam", kind: "seam", level: 20, xp: 18, ticks: 5, item: "ore_bronze", yields: [2, 5], respawnS: 12, extras: GEMS(1), tint: 12618314 }),
  node({ id: "seam_silver", skill: "mining", name: "Silver Seam", kind: "seam", level: 30, xp: 24, ticks: 5, item: "ore_silver", yields: [3, 6], respawnS: 18, extras: GEMS(1.2), tint: 14212582 }),
  node({ id: "seam_gold", skill: "mining", name: "Gold Seam", kind: "seam", level: 40, xp: 32, ticks: 6, item: "ore_gold", yields: [3, 6], respawnS: 25, extras: GEMS(1.4), tint: 15251530 }),
  node({ id: "seam_steel", skill: "mining", name: "Steel Seam", kind: "seam", level: 50, xp: 42, ticks: 6, item: "ore_steel", yields: [4, 7], respawnS: 32, extras: GEMS(1.6), tint: 8228774 }),
  node({ id: "geode_hell", skill: "mining", name: "Hell Geode", kind: "geode", level: 65, xp: 60, ticks: 7, item: "ore_hell", yields: [4, 8], respawnS: 45, extras: GEMS(2), tint: 14701098 }),
  node({ id: "geode_moon", skill: "mining", name: "Moon Geode", kind: "geode", level: 80, xp: 90, ticks: 8, item: "ore_moon", yields: [5, 9], respawnS: 60, extras: GEMS(2.5), tint: 10405119 }),
  // Fishing: spots drift, so a "depleted" pool is a spot that moved on.
  node({ id: "pool_still", skill: "fishing", name: "Still Pool", kind: "pool", level: 1, xp: 6, ticks: 4, item: "fish_river", yields: [8, 16], respawnS: 6, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 2902610 }),
  node({ id: "pool_eels", skill: "fishing", name: "Crypt Eels", kind: "pool", level: 15, xp: 14, ticks: 5, item: "fish_crypt_eel", yields: [8, 16], respawnS: 8, extras: [{ item: "ring_copper", chance: 1 / 400 }], tint: 3231807 }),
  node({ id: "pool_carp", skill: "fishing", name: "Bell Carp", kind: "pool", level: 30, xp: 24, ticks: 5, item: "fish_bell_carp", yields: [10, 18], respawnS: 10, extras: [{ item: "reliquary_fragment", chance: 1 / 300 }], tint: 5921336 }),
  node({ id: "pool_pike", skill: "fishing", name: "Drowned Pike", kind: "pool", level: 45, xp: 38, ticks: 6, item: "fish_drowned_pike", yields: [10, 18], respawnS: 12, extras: [{ item: "reliquary_fragment", chance: 1 / 250 }], tint: 2375754 }),
  node({ id: "pool_lantern", skill: "fishing", name: "Lanternfish", kind: "pool", level: 62, xp: 58, ticks: 7, item: "fish_lanternfish", yields: [12, 20], respawnS: 14, extras: [{ item: "reliquary_fragment", chance: 1 / 200 }], tint: 3828314 }),
  node({ id: "pool_coelacanth", skill: "fishing", name: "Abyssal Coelacanth", kind: "pool", level: 80, xp: 95, ticks: 8, item: "fish_coelacanth", yields: [12, 20], respawnS: 16, extras: [{ item: "covenant_seal", chance: 1 / 300 }], tint: 1715268 }),
  // Gravedigging: the necromancer's own skill.
  node({
    id: "grave_pauper",
    skill: "gravedigging",
    name: "Pauper's Grave",
    kind: "grave",
    level: 1,
    xp: 7,
    ticks: 4,
    item: "bones_old",
    yields: [2, 4],
    respawnS: 10,
    gold: [0, 2],
    tint: 4865068,
    extras: [{ item: "seed_mourning_moss", chance: 1 / 12 }]
  }),
  node({
    id: "grave_mound",
    skill: "gravedigging",
    name: "Burial Mound",
    kind: "grave",
    level: 20,
    xp: 18,
    ticks: 5,
    item: "bones_barrow",
    yields: [3, 5],
    respawnS: 18,
    gold: [1, 4],
    tint: 5064242,
    extras: [{ item: "ring_copper", chance: 1 / 120 }, { item: "seed_mourning_moss", chance: 1 / 20 }, { item: "seed_nightshade", chance: 1 / 25 }]
  }),
  node({
    id: "grave_crypt",
    skill: "gravedigging",
    name: "Crypt Collapse",
    kind: "grave",
    level: 40,
    xp: 34,
    ticks: 6,
    item: "bones_crypt",
    yields: [3, 6],
    respawnS: 30,
    gold: [2, 6],
    tint: 5920336,
    extras: [{ item: "ore_silver", chance: 1 / 8 }, { item: "reliquary_fragment", chance: 1 / 60 }, { item: "seed_corpse_lily", chance: 1 / 25 }, { item: "seed_wolfsbane", chance: 1 / 40 }]
  }),
  node({
    id: "grave_barrow_king",
    skill: "gravedigging",
    name: "Barrow-King's Tomb",
    kind: "grave",
    level: 70,
    xp: 70,
    ticks: 8,
    item: "bones_ancient",
    yields: [4, 8],
    respawnS: 60,
    gold: [4, 12],
    tint: 6969914,
    extras: [
      { item: "covenant_seal", chance: 1 / 40 },
      { item: "reliquary_fragment", chance: 1 / 25 },
      { item: "seed_bloodroot", chance: 1 / 20 },
      { item: "seed_moonpetal", chance: 1 / 30 },
      { item: "helm_gold", chance: 1 / 900 },
      { item: "chest_iron", chance: 1 / 700 },
      { item: "kit_iron_warden", chance: 1 / 800 }
    ]
  })
];
var NODES = Object.fromEntries(NODE_LIST.map((n) => [n.id, n]));
var NODE_IDS = NODE_LIST.map((n) => n.id);
var actionMs = (def) => def.ticks * TICK_MS;
var xpToNextLive = (level) => Math.max(1, level) * 50;
var xpToNextCurve = (level) => Math.round(50 * Math.max(1, level) * Math.pow(1.035, Math.max(0, level - 20)));
var XP_CURVE = "live";
var xpToNext = (level) => XP_CURVE === "curve" ? xpToNextCurve(level) : xpToNextLive(level);
function addSkillXp(p, gained) {
  let level = Math.max(1, Math.min(LEVEL_CAP, Math.floor(p.level) || 1));
  let xp = Math.max(0, Math.floor(p.xp) || 0) + Math.max(0, Math.floor(gained));
  let leveled = 0;
  while (level < LEVEL_CAP && xp >= xpToNext(level)) {
    xp -= xpToNext(level);
    level++;
    leveled++;
  }
  if (level >= LEVEL_CAP) xp = 0;
  return { level, xp, leveled };
}
function successChance(def, level, toolTier = 0) {
  const p = (def.level === 1 ? 0.6 : 0.45) + 0.01 * (level - def.level) + 0.05 * toolTier;
  return Math.max(0.2, Math.min(0.9, p));
}
var randInt = (rng, lo, hi) => lo + Math.floor(rng() * (hi - lo + 1));
function rollGather(def, level, rng, toolTier = 0) {
  if (level < def.level || rng() >= successChance(def, level, toolTier)) return { success: false, xp: 0, gold: 0, items: [] };
  const items = [{ itemId: def.item, qty: 1 }];
  for (const e of def.extras) {
    if (rng() < e.chance) items.push({ itemId: e.item, qty: e.qty ? randInt(rng, e.qty[0], e.qty[1]) : 1 });
  }
  return { success: true, xp: def.xp, gold: def.gold ? randInt(rng, def.gold[0], def.gold[1]) : 0, items };
}
function rollBatch(def, start, actions, rng, toolTier = 0, rollFloor = 0) {
  let progress = { level: start.level, xp: start.xp };
  const bag = /* @__PURE__ */ new Map();
  let xp = 0;
  let gold = 0;
  let successes = 0;
  let leveled = 0;
  for (let i = 0; i < actions; i++) {
    const r = rollGather(def, Math.max(progress.level, rollFloor), rng, toolTier);
    if (!r.success) continue;
    successes++;
    xp += r.xp;
    gold += r.gold;
    for (const g of r.items) bag.set(g.itemId, (bag.get(g.itemId) ?? 0) + g.qty);
    const next = addSkillXp(progress, r.xp);
    leveled += next.leveled;
    progress = { level: next.level, xp: next.xp };
  }
  return { progress, successes, xp, gold, items: [...bag].map(([itemId, qty]) => ({ itemId, qty })), leveled };
}

// src/gameplay/laborRules.ts
var LABOR = {
  /** Share of a player's own action rate. */
  factor: 0.12,
  /** Work stops accruing after this long without a collection. */
  capMs: 8 * 36e5,
  /** Share of the XP a player would earn from the same finds. */
  xpFrac: 0.25,
  maxSlots: 4,
  /** Total gathering levels (across the four gather skills) per extra laborer. */
  levelsPerSlot: 50
};
var laborSlots = (totalLevel) => Math.min(LABOR.maxSlots, 1 + Math.floor(Math.max(0, totalLevel) / LABOR.levelsPerSlot));
var totalGatherLevel = (levels) => GATHER_SKILLS.reduce((n, s) => n + Math.max(1, levels[s] ?? 1), 0);
function postsFor(levels) {
  return Object.values(NODES).filter((n) => (levels[n.skill] ?? 1) >= n.level);
}
function assignBlocker(nodeType, levels) {
  const def = NODES[nodeType];
  if (!def) return "That is not a place to work.";
  if ((levels[def.skill] ?? 1) < def.level) return `Requires level ${def.level}.`;
  return null;
}
function laborActions(def, elapsedMs) {
  const ms = Math.max(0, Math.min(elapsedMs, LABOR.capMs));
  return Math.floor(ms / actionMs(def) * LABOR.factor);
}
function estimate(def, level, elapsedMs) {
  const actions = laborActions(def, elapsedMs);
  const wins = actions * successChance(def, level);
  return { actions, items: Math.round(wins), xp: Math.round(wins * def.xp * LABOR.xpFrac) };
}
function rollLabor(def, start, elapsedMs, rng) {
  const actions = laborActions(def, elapsedMs);
  const batch = rollBatch(def, { level: start.level, xp: 0 }, actions, rng, 0);
  const xp = Math.floor(batch.xp * LABOR.xpFrac);
  const next = addSkillXp(start, xp);
  return { items: batch.items, gold: batch.gold, xp, actions, progress: { level: next.level, xp: next.xp }, leveled: next.leveled };
}
function hashSeed(...parts) {
  let h = 2166136261;
  for (const ch of parts.join(":")) {
    h ^= ch.charCodeAt(0);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function claimRng(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  LABOR,
  assignBlocker,
  claimRng,
  estimate,
  hashSeed,
  laborActions,
  laborSlots,
  postsFor,
  rollLabor,
  totalGatherLevel
});
