// GENERATED by tools/build-server-rules.mjs from src/gameplay/legionRules.ts — do not edit by hand.
// Legion kit (thrall gear) slots, eligibility and bonus rules shared by the web client, the offline mock and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/legionRules.ts
var legionRules_exports = {};
__export(legionRules_exports, {
  KIT_ARMOR_TYPES: () => KIT_ARMOR_TYPES,
  KIT_BASE: () => KIT_BASE,
  KIT_IDS: () => KIT_IDS,
  KIT_LABEL: () => KIT_LABEL,
  KIT_RATES: () => KIT_RATES,
  KIT_SLOT_COUNT: () => KIT_SLOT_COUNT,
  KIT_WEAPON_TYPES: () => KIT_WEAPON_TYPES,
  NO_LEGION: () => NO_LEGION,
  isKitSlot: () => isKitSlot,
  isNoLegion: () => isNoLegion,
  kitEquippedSlot: () => kitEquippedSlot,
  kitIdForType: () => kitIdForType,
  kitSlotId: () => kitSlotId,
  kitSlotIndex: () => kitSlotIndex,
  legionBonus: () => legionBonus,
  pieceBonus: () => pieceBonus,
  reinforceBonus: () => reinforceBonus,
  statPoints: () => statPoints,
  unusedAffixes: () => unusedAffixes
});
module.exports = __toCommonJS(legionRules_exports);

// src/content/upgrades.ts
var LEGION_UPGRADE = {
  maxTier: 12,
  perTier: 0.03,
  speedPerTier: 0.01,
  cost: (tier) => Math.round(120 * Math.pow(1.65, tier))
};

// src/gameplay/affixRules.ts
var clampInt = (x, lo, hi) => Math.max(lo, Math.min(hi, Math.round(x)));
var around = (centre, cap, floor = 1) => {
  const lo = clampInt(centre * 0.7, floor, cap);
  return [lo, clampInt(Math.max(centre * 1.3, lo), lo, cap)];
};
var tenths = (v) => `${+(v / 10).toFixed(1)}%`;
var STAT_NAME = { stat_str: "STR", stat_agi: "AGI", stat_int: "INT", stat_vit: "VIT" };
var statDef = (stat, kind, word) => ({
  id: `${kind === "prefix" ? "p" : "s"}_${stat.slice(5)}`,
  kind,
  word,
  group: stat,
  necro: false,
  weight: 9,
  unit: "stat",
  range: (L) => around(0.8 + 0.07 * Math.min(L, 25) + 0.045 * Math.max(0, L - 25), 14),
  legacy: [(L) => around(0.8 + 0.07 * L, 14)],
  effect: (v) => ({ stats: { [stat]: v } }),
  text: (v) => `+${v} ${STAT_NAME[stat]}`
});
var AFFIXES = [
  statDef("stat_str", "prefix", "Brutal"),
  statDef("stat_agi", "prefix", "Fleet"),
  statDef("stat_int", "prefix", "Occult"),
  statDef("stat_vit", "prefix", "Stout"),
  statDef("stat_str", "suffix", "of the Reaver"),
  statDef("stat_agi", "suffix", "of the Hound"),
  statDef("stat_int", "suffix", "of the Seer"),
  statDef("stat_vit", "suffix", "of the Tomb"),
  {
    id: "p_thrall_dmg",
    kind: "prefix",
    word: "Gravebound",
    group: "thrall_dmg",
    necro: true,
    weight: 13,
    unit: "pct",
    range: (L) => around(10 * (6.5 + 0.1 * L), 300),
    legacy: [(L) => around(10 * (5.5 + 0.2 * L), 300)],
    effect: (v) => ({ mult: { thrallDamageMult: 1 + v / 1e3 } }),
    text: (v) => `Thralls hit +${tenths(v)} harder`
  },
  {
    id: "s_thrall_hp",
    kind: "suffix",
    word: "of the Legion",
    group: "thrall_hp",
    necro: true,
    weight: 13,
    unit: "pct",
    range: (L) => around(10 * (9.5 + 0.34 * L), 500),
    legacy: [(L) => around(10 * (10.6 + 0.38 * L), 500)],
    effect: (v) => ({ mult: { thrallHpMult: 1 + v / 1e3 } }),
    text: (v) => `Thralls have +${tenths(v)} health`
  },
  {
    id: "p_essence_regen",
    kind: "prefix",
    word: "Whispering",
    group: "essence_regen",
    necro: true,
    weight: 11,
    unit: "pct",
    range: (L) => around(10 * (10 + 0.5 * L), 600),
    legacy: [(L) => around(10 * (10 + 0.42 * L), 600)],
    effect: (v) => ({ mult: { essenceRegenMult: 1 + v / 1e3 } }),
    text: (v) => `+${tenths(v)} essence regeneration`
  },
  {
    id: "s_miasma",
    kind: "suffix",
    word: "of the Rotting Mist",
    group: "miasma",
    necro: true,
    weight: 9,
    unit: "pct",
    range: (L) => around(10 * (5.2 + 0.12 * L), 400),
    legacy: [(L) => around(10 * (5.2 + 0.22 * L), 400)],
    effect: (v) => ({ mult: { miasmaRadiusMult: 1 + v / 1e3 } }),
    text: (v) => `Miasma is +${tenths(v)} wider`
  },
  {
    id: "p_withered",
    kind: "prefix",
    word: "Blighted",
    group: "withered",
    necro: true,
    weight: 8,
    unit: "count",
    range: (L) => [1, clampInt(2 + Math.floor(L / 9), 2, 4)],
    legacy: [(L) => [1, clampInt(2 + Math.floor(L / 7), 2, 6)]],
    effect: (v) => ({ add: { witheredMaxStacks: v } }),
    text: (v) => `+${v} max Withered stack${v === 1 ? "" : "s"}`
  },
  {
    id: "s_ward",
    kind: "suffix",
    word: "of the Ossuary Wall",
    group: "ward",
    necro: true,
    weight: 9,
    unit: "wardPct",
    range: (L) => around(12 + 0.55 * L, 55),
    legacy: [(L) => around(9 + 0.7 * L, 60)],
    effect: (v) => ({ add: { wardPerThrall: v / 1e3 } }),
    text: (v) => `${tenths(v)} less damage taken per thrall`
  }
];
var BY_ID = new Map(AFFIXES.map((a) => [a.id, a]));
var affixEffect = (a) => BY_ID.get(a.id)?.effect(a.v) ?? {};
var affixText = (a) => BY_ID.get(a.id)?.text(a.v) ?? a.id;

// src/gameplay/legionRules.ts
var KIT_BASE = 120;
var KIT_IDS = ["weapon", "armor"];
var KIT_SLOT_COUNT = KIT_IDS.length;
var KIT_LABEL = { weapon: "Weapon", armor: "Armour" };
var isKitSlot = (slot) => Number.isInteger(slot) && slot >= KIT_BASE && slot < KIT_BASE + KIT_SLOT_COUNT;
var kitSlotId = (slot) => isKitSlot(slot) ? KIT_IDS[slot - KIT_BASE] : null;
var kitSlotIndex = (id) => KIT_BASE + KIT_IDS.indexOf(id);
var kitEquippedSlot = (id) => `kit_${id}`;
var KIT_WEAPON_TYPES = ["weapon", "offhand"];
var KIT_ARMOR_TYPES = ["armor_head", "armor_chest", "armor_legs", "armor_feet", "armor_hands"];
function kitIdForType(itemType) {
  if (KIT_WEAPON_TYPES.includes(itemType ?? "")) return "weapon";
  if (KIT_ARMOR_TYPES.includes(itemType ?? "")) return "armor";
  return null;
}
var KIT_RATES = {
  weaponDamagePerPoint: 0.01,
  weaponDamageCap: 0.35,
  weaponSpeedPerPoint: 3e-3,
  weaponSpeedCap: 0.1,
  armorHpPerPoint: 0.012,
  armorHpCap: 0.45,
  affixShare: 0.6
};
var STATS = ["stat_str", "stat_agi", "stat_int", "stat_vit"];
var R = KIT_RATES;
var round4 = (x) => Math.round(x * 1e4) / 1e4;
function statPoints(piece) {
  let pts = 0;
  for (const k of STATS) pts += Math.max(0, piece.statBonus?.[k] ?? 0);
  for (const a of piece.affixes ?? []) for (const [k, v] of Object.entries(affixEffect(a).stats ?? {})) if (STATS.includes(k)) pts += Math.max(0, v);
  return pts;
}
function pieceBonus(kit, piece) {
  const none = { points: 0, hp: 0, damage: 0, speed: 0, ward: 0 };
  if (!piece || kitIdForType(piece.itemType) !== kit) return none;
  const points = statPoints(piece);
  const out = { ...none, points };
  if (kit === "weapon") {
    out.damage = Math.min(R.weaponDamageCap, points * R.weaponDamagePerPoint);
    out.speed = Math.min(R.weaponSpeedCap, points * R.weaponSpeedPerPoint);
  } else out.hp = Math.min(R.armorHpCap, points * R.armorHpPerPoint);
  for (const a of piece.affixes ?? []) {
    const e = affixEffect(a);
    out.damage += ((e.mult?.thrallDamageMult ?? 1) - 1) * R.affixShare;
    out.hp += ((e.mult?.thrallHpMult ?? 1) - 1) * R.affixShare;
    out.ward += (e.add?.wardPerThrall ?? 0) * R.affixShare;
  }
  return { points, hp: round4(out.hp), damage: round4(out.damage), speed: round4(out.speed), ward: round4(out.ward) };
}
function unusedAffixes(piece) {
  const used = (a) => {
    const e = affixEffect(a);
    return e.mult?.thrallDamageMult !== void 0 || e.mult?.thrallHpMult !== void 0 || e.add?.wardPerThrall !== void 0 || !!e.stats;
  };
  return (piece?.affixes ?? []).filter((a) => !used(a)).map((a) => affixText(a));
}
var reinforceBonus = (tier) => {
  const t = Math.max(0, Math.min(LEGION_UPGRADE.maxTier, Math.floor(Number(tier) || 0)));
  return { tier: t, hp: round4(t * LEGION_UPGRADE.perTier), damage: round4(t * LEGION_UPGRADE.perTier), speed: round4(t * LEGION_UPGRADE.speedPerTier) };
};
var NO_LEGION = {
  hpMult: 1,
  damageMult: 1,
  speedMult: 1,
  wardAdd: 0,
  kit: { hp: 0, damage: 0, speed: 0, ward: 0 },
  reinforce: { tier: 0, hp: 0, damage: 0, speed: 0 }
};
function legionBonus(kit, reinforceTier) {
  const w = pieceBonus("weapon", kit.weapon);
  const a = pieceBonus("armor", kit.armor);
  const k = { hp: round4(w.hp + a.hp), damage: round4(w.damage + a.damage), speed: round4(w.speed + a.speed), ward: round4(w.ward + a.ward) };
  const r = reinforceBonus(reinforceTier);
  return {
    hpMult: (1 + k.hp) * (1 + r.hp),
    damageMult: (1 + k.damage) * (1 + r.damage),
    speedMult: (1 + k.speed) * (1 + r.speed),
    wardAdd: k.ward,
    kit: k,
    reinforce: r
  };
}
var isNoLegion = (b) => b.hpMult === 1 && b.damageMult === 1 && b.speedMult === 1 && b.wardAdd === 0;
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  KIT_ARMOR_TYPES,
  KIT_BASE,
  KIT_IDS,
  KIT_LABEL,
  KIT_RATES,
  KIT_SLOT_COUNT,
  KIT_WEAPON_TYPES,
  NO_LEGION,
  isKitSlot,
  isNoLegion,
  kitEquippedSlot,
  kitIdForType,
  kitSlotId,
  kitSlotIndex,
  legionBonus,
  pieceBonus,
  reinforceBonus,
  statPoints,
  unusedAffixes
});
