// GENERATED by tools/build-server-rules.mjs from src/gameplay/loadoutRules.ts — do not edit by hand.
// Loadout presets (validation, capture and apply over inventory rows) shared by the web client, the offline mock and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/loadoutRules.ts
var loadoutRules_exports = {};
__export(loadoutRules_exports, {
  BAG_SLOTS: () => BAG_SLOTS,
  MAIN_HAND_SLOT: () => MAIN_HAND_SLOT,
  MAX_PRESETS: () => MAX_PRESETS,
  NAME_MAX: () => NAME_MAX,
  OFF_HAND_SLOT: () => OFF_HAND_SLOT,
  applyLoadout: () => applyLoadout,
  captureGear: () => captureGear,
  cleanName: () => cleanName,
  normalizePreset: () => normalizePreset
});
module.exports = __toCommonJS(loadoutRules_exports);

// src/content/runes.ts
var RUNE_RITES = ["bone_needle", "marrow_spear", "exhume", "miasma", "black_litany"];
var RUNE_IDS = [
  "rune_splinter",
  "rune_marrow_tap",
  "rune_volley",
  "rune_ossuary_ring",
  "rune_impale",
  "rune_mass_grave",
  "rune_bone_colossus",
  "rune_creeping_rot",
  "rune_contagion",
  "rune_hollow_choir",
  "rune_requiem"
];
var RUNE_TUNING = {
  /** Bone Needle. */
  splinter: { reach: 6, damageFrac: 0.3 },
  marrowTap: { essenceBonus: 4, damageMult: 0.7 },
  volley: { every: 4, needles: 3, damageFrac: 0.4, reach: 9 },
  /** Marrow Spear: the ring bursts on the cursor, pulled back to the spear's reach. */
  ring: { radius: 3, maxCastRange: 12, damageMult: 0.8 },
  impale: { rootS: 1.5, damageMult: 1.5 },
  /** Exhume. `slots` is how many legion places the colossus fills. */
  massGrave: { count: 3, statMult: 0.75, pickRadius: 4 },
  colossus: {
    corpses: 5,
    minCorpses: 3,
    slots: 2,
    pickRadius: 6,
    hpPerCorpse: 0.8,
    damagePerCorpse: 0.7,
    cleaveRadius: 2.4,
    cleaveFrac: 0.6,
    range: 2.4,
    interval: 1.2,
    speed: 4.8,
    /** Cooldown multiplier on Exhume's 500 ms (4 s), applied only to a cast that raised a Colossus. */
    cooldownMult: 8
  },
  /** Miasma Circle. */
  creepingRot: { speed: 1.5, radiusMult: 0.85, seekReach: 12 },
  contagion: { neighbours: 2, reach: 4.5, minStacks: 2 },
  /** Black Litany. */
  hollowChoir: { powerMult: 0.6 },
  requiem: { delayMs: 2e3, radiusMult: 1.7 }
};
var pct = (x) => `${Math.round(x * 100)}%`;
var T = RUNE_TUNING;
var RUNES = {
  rune_splinter: {
    id: "rune_splinter",
    name: "Rune of Splinters",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "The needle shatters on bone and the shards keep looking.",
    short: "Hits splinter to a second foe",
    lines: [`When a needle hits, a splinter flies to the nearest other enemy within ${T.splinter.reach} m for ${pct(T.splinter.damageFrac)} of the damage. Under a scythe, each reaping swing throws one splinter, from the nearest enemy it struck to the nearest one it missed.`],
    cost: null
  },
  rune_marrow_tap: {
    id: "rune_marrow_tap",
    name: "Rune of Marrow-Tap",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "Every wound is a spigot.",
    short: "More essence, softer needle",
    lines: [`Each needle hit returns ${T.marrowTap.essenceBonus} more Grave Essence. Under a scythe, each swing that lands returns ${T.marrowTap.essenceBonus} more once, however many enemies it strikes.`],
    cost: `Needles and scythe swings hit for ${pct(1 - T.marrowTap.damageMult)} less.`
  },
  rune_volley: {
    id: "rune_volley",
    name: "Rune of the Volley",
    rite: "bone_needle",
    rarity: "rare",
    sell: 60,
    lore: "Four breaths, then a flock.",
    short: "Every 4th needle is a volley",
    lines: [`Every ${T.volley.every}th needle you throw becomes a volley of ${T.volley.needles}, aimed at ${T.volley.needles} different enemies within ${T.volley.reach} m (or all at one target if it stands alone). The volley returns the essence of one needle between them. Needle only: a scythe's swing is not a volley.`],
    cost: `Each volley needle hits for ${pct(T.volley.damageFrac)}.`
  },
  rune_ossuary_ring: {
    id: "rune_ossuary_ring",
    name: "Ossuary Ring Rune",
    rite: "marrow_spear",
    rarity: "rare",
    sell: 60,
    lore: "The dead rise in a circle, like a congregation.",
    short: "Spikes erupt in a ring",
    lines: [`Instead of a line, bone erupts in a ${T.ring.radius} m ring at the cursor, striking everything inside and applying Fracture and Hemorrhage as usual.`],
    cost: `It no longer reaches down a long line, and strikes for ${pct(T.ring.damageMult)}.`
  },
  rune_impale: {
    id: "rune_impale",
    name: "Rune of Impaling",
    rite: "marrow_spear",
    rarity: "uncommon",
    sell: 25,
    lore: "One thorn, driven deep.",
    short: "Skewers and roots the first foe",
    lines: [`The spear stops at the first enemy it meets, hits it for ${pct(T.impale.damageMult - 1)} more and roots it for ${T.impale.rootS} s (a boss shrugs the root off but takes the hit).`],
    cost: "It no longer pierces the line behind."
  },
  rune_mass_grave: {
    id: "rune_mass_grave",
    name: "Mass Grave Rune",
    rite: "exhume",
    rarity: "rare",
    sell: 60,
    lore: "Why dig one grave when the field is full?",
    short: "Raise up to 3 corpses at once",
    lines: [`Exhume raises up to ${T.massGrave.count} corpses near the cursor at once, each with ${pct(T.massGrave.statMult)} of the usual thrall health and damage.`],
    cost: "Each thrall is weaker, and it spends more corpses."
  },
  rune_bone_colossus: {
    id: "rune_bone_colossus",
    name: "Bone Colossus Rune",
    rite: "exhume",
    rarity: "epic",
    sell: 150,
    lore: "Five dead, bound as one, and it remembers being a wall.",
    short: "Five corpses become one giant thrall",
    lines: [
      `When ${T.colossus.minCorpses} or more corpses lie within ${T.colossus.pickRadius} m of the one you name, Exhume consumes up to ${T.colossus.corpses} of them and raises one Bone Colossus instead. With fewer, or while a Colossus stands, it raises an ordinary thrall.`,
      `Its health is ${(T.colossus.hpPerCorpse * T.colossus.corpses).toFixed(1)}x and its damage ${(T.colossus.damagePerCorpse * T.colossus.corpses).toFixed(1)}x a thrall's with five corpses (less with fewer), and every blow cleaves ${T.colossus.cleaveRadius} m.`,
      `It fills ${T.colossus.slots} legion places and you can only keep one: raising another replaces it.`
    ],
    cost: `Exhume takes ${500 * T.colossus.cooldownMult / 1e3} s to ready again after raising a Colossus.`
  },
  rune_creeping_rot: {
    id: "rune_creeping_rot",
    name: "Creeping Rot Rune",
    rite: "miasma",
    rarity: "uncommon",
    sell: 25,
    lore: "Rot that has learned to walk.",
    short: "The circle crawls toward foes",
    lines: [`The circle drifts ${T.creepingRot.speed} m/s toward the nearest enemy within ${T.creepingRot.seekReach} m of it.`],
    cost: `The circle is ${pct(1 - T.creepingRot.radiusMult)} narrower.`
  },
  rune_contagion: {
    id: "rune_contagion",
    name: "Contagion Rune",
    rite: "miasma",
    rarity: "rare",
    sell: 60,
    lore: "It does not stop at the grave.",
    short: "Dying Withered foes infect others",
    lines: [`A Withered enemy that dies spreads its Withered stacks (minus one) to the ${T.contagion.neighbours} nearest enemies within ${T.contagion.reach} m, and those spread it again when they die (it needs ${T.contagion.minStacks} stacks to jump).`],
    cost: null
  },
  rune_hollow_choir: {
    id: "rune_hollow_choir",
    name: "Hollow Choir Rune",
    rite: "black_litany",
    rarity: "rare",
    sell: 60,
    lore: "The dead sing, and are not spent.",
    short: "Your thralls sing instead of dying",
    lines: ["Black Litany no longer sacrifices your thralls. They still lend their voices to its power."],
    cost: `The burst hits for ${pct(1 - T.hollowChoir.powerMult)} less.`
  },
  rune_requiem: {
    id: "rune_requiem",
    name: "Requiem Rune",
    rite: "black_litany",
    rarity: "epic",
    sell: 150,
    lore: "A hymn is only terrible once it is finished.",
    short: "The burst lands 2 s later, twice as wide",
    lines: [`Black Litany marks the ground, then bursts ${T.requiem.delayMs / 1e3} s later over ${T.requiem.radiusMult}x the radius. Corpses and thralls are consumed when it bursts.`],
    cost: "Enemies can walk out of it, and it can take more of your thralls."
  }
};
var RUNE_ORDER = [...RUNE_IDS];
var isRuneId = (id) => typeof id === "string" && Object.prototype.hasOwnProperty.call(RUNES, id);
var isRuneRite = (id) => typeof id === "string" && RUNE_RITES.includes(id);
var byRarity = (...rarities) => RUNE_ORDER.filter((id) => rarities.includes(RUNES[id].rarity));
var AREA_RUNE_POOL = {
  graves: byRarity("uncommon"),
  ossuary: byRarity("uncommon", "rare"),
  nave: byRarity("uncommon", "rare"),
  sanctum: byRarity("uncommon", "rare", "epic"),
  cloister: byRarity("uncommon", "rare", "epic"),
  pyre: byRarity("uncommon", "rare", "epic"),
  fen: byRarity("uncommon", "rare", "epic"),
  warren: byRarity("uncommon", "rare"),
  coliseum: byRarity("uncommon", "rare", "epic")
};
var ELITE_RUNE_CHANCE_BY_AREA = {
  graves: 0.05,
  warren: 0.055,
  ossuary: 0.06,
  nave: 0.07,
  coliseum: 0.08,
  sanctum: 0.09,
  cloister: 0.1,
  pyre: 0.11,
  fen: 0.12
};
var ELITE_RUNE_CHANCE = ELITE_RUNE_CHANCE_BY_AREA.graves;
var BOSS_RUNE_POOL = {
  gravedigger: ["rune_splinter", "rune_marrow_tap", "rune_mass_grave"],
  abbess: ["rune_ossuary_ring", "rune_impale", "rune_bone_colossus", "rune_volley"],
  congregation: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir"],
  prelate: ["rune_requiem", ...RUNE_ORDER],
  saint: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir", "rune_requiem", "rune_bone_colossus"],
  regent: [...RUNE_ORDER],
  mire: [...RUNE_ORDER]
};

// src/gameplay/runeRules.ts
var RUNE_BASE = 130;
var RUNE_SLOT_COUNT = RUNE_RITES.length;
var isRuneSlot = (slot) => Number.isInteger(slot) && slot >= RUNE_BASE && slot < RUNE_BASE + RUNE_SLOT_COUNT;
var runeSlotRite = (slot) => isRuneSlot(slot) ? RUNE_RITES[slot - RUNE_BASE] : null;
var runeSlotIndex = (rite) => RUNE_BASE + RUNE_RITES.indexOf(rite);
var runeFits = (runeId, rite) => isRuneId(runeId) && isRuneRite(rite) && RUNES[runeId].rite === rite;

// src/gameplay/loadoutRules.ts
var MAX_PRESETS = 6;
var NAME_MAX = 24;
var BAG_SLOTS = 48;
var MAIN_HAND_SLOT = 105;
var OFF_HAND_SLOT = 106;
var ID_RE = /^[a-z0-9_]{1,64}$/;
var isId = (x) => typeof x === "string" && ID_RE.test(x);
function cleanGear(raw) {
  if (raw === null || raw === void 0) return null;
  if (typeof raw !== "object") return void 0;
  const g = raw;
  if (!isId(g.itemId)) return void 0;
  const inst = g.instanceId === null || g.instanceId === void 0 ? null : g.instanceId;
  if (inst !== null && !(typeof inst === "number" && Number.isInteger(inst) && inst > 0)) return void 0;
  return { itemId: g.itemId, instanceId: inst };
}
function cleanName(raw) {
  if (typeof raw !== "string") return null;
  const s = raw.replace(/[\u0000-\u001f\u007f<>]/g, "").replace(/\s+/g, " ").trim().slice(0, NAME_MAX).trim();
  return s ? s : null;
}
function normalizePreset(raw) {
  if (!raw || typeof raw !== "object") return { ok: false, error: "That loadout is not readable." };
  const r = raw;
  const name = cleanName(r.name);
  if (!name) return { ok: false, error: "Give the loadout a name." };
  const rites = r.rites;
  if (!rites || !isId(rites.primary) || !Array.isArray(rites.keys) || rites.keys.length !== 5 || !rites.keys.every(isId)) return { ok: false, error: "A loadout holds a primary and five rites." };
  if (new Set(rites.keys).size !== 5) return { ok: false, error: "A rite can sit on one key only." };
  const runes = {};
  if (r.runes !== void 0 && r.runes !== null) {
    if (typeof r.runes !== "object" || Array.isArray(r.runes)) return { ok: false, error: "The runes are not readable." };
    for (const [rite, id] of Object.entries(r.runes)) {
      if (id === null || id === void 0) continue;
      if (!isRuneRite(rite) || typeof id !== "string" || !isRuneId(id) || !runeFits(id, rite)) return { ok: false, error: "A rune in that loadout does not fit its rite." };
      runes[rite] = id;
    }
  }
  const weapon = cleanGear(r.weapon);
  const offhand = cleanGear(r.offhand);
  if (weapon === void 0 || offhand === void 0) return { ok: false, error: "The weapon in that loadout is not readable." };
  return { ok: true, preset: { name, rites: { primary: rites.primary, keys: [...rites.keys] }, runes, weapon, offhand } };
}
var inBag = (r) => r.slot_index >= 0 && r.slot_index < BAG_SLOTS;
var same = (a, b) => (a ?? null) === (b ?? null);
function captureGear(rows) {
  const ref = (slot) => {
    const r = rows.find((x) => x.slot_index === slot);
    return r ? { itemId: r.item_id, instanceId: r.instance_id ?? null } : null;
  };
  const runes = {};
  for (const r of rows) {
    const rite = runeSlotRite(r.slot_index);
    if (rite && runeFits(r.item_id, rite)) runes[rite] = r.item_id;
  }
  return { weapon: ref(MAIN_HAND_SLOT), offhand: ref(OFF_HAND_SLOT), runes };
}
function applyLoadout(input, info, preset) {
  let rows = input.map((r) => ({ ...r }));
  const report = { applied: [], skipped: [], unchanged: true };
  const isEq = (r, slot) => r.slot_index === slot;
  const freeSlots = () => {
    const used = new Set(rows.filter(inBag).map((r) => r.slot_index));
    const out = [];
    for (let i = 0; i < BAG_SLOTS; i++) if (!used.has(i)) out.push(i);
    return out;
  };
  const giveBack = (itemId) => {
    const cap = info(itemId).maxStack;
    const stack = rows.find((r) => inBag(r) && r.item_id === itemId && !r.equipped && (r.instance_id ?? null) === null && r.quantity < cap);
    if (stack) {
      stack.quantity += 1;
      return true;
    }
    const free = freeSlots()[0];
    if (free === void 0) return false;
    rows.push({ slot_index: free, item_id: itemId, quantity: 1, equipped: 0, equipped_slot: null, instance_id: null });
    return true;
  };
  const step = (fn) => {
    const snapshot = rows.map((r) => ({ ...r }));
    const reason = fn();
    if (reason) rows = snapshot;
    return reason;
  };
  const hand = (part, want, equipSlot, reserved) => {
    if (!want) return;
    const worn = rows.find((r) => isEq(r, reserved));
    if (worn && worn.item_id === want.itemId && same(worn.instance_id, want.instanceId)) return;
    const from = rows.find((r) => inBag(r) && !r.equipped && r.item_id === want.itemId && same(r.instance_id, want.instanceId));
    const skip = (reason2) => report.skipped.push({ part, rite: null, itemId: want.itemId, reason: reason2 });
    if (!from) return skip("missing");
    const meta = info(want.itemId);
    if (meta.equipSlot !== equipSlot) return skip("wrong_slot");
    const reason = step(() => {
      const displaced = rows.filter((r) => r !== from && (isEq(r, reserved) || meta.twoHanded && isEq(r, OFF_HAND_SLOT) || equipSlot === "off_hand" && isEq(r, MAIN_HAND_SLOT) && info(r.item_id).twoHanded));
      const bagSlot = from.slot_index;
      const free = freeSlots();
      if (displaced.length > free.length + 1) return "no_room";
      from.slot_index = reserved;
      from.equipped = 1;
      from.equipped_slot = equipSlot;
      displaced.forEach((d, i) => {
        d.slot_index = i === 0 ? bagSlot : free[i - 1];
        d.equipped = 0;
        d.equipped_slot = null;
      });
      return null;
    });
    if (reason) return skip(reason);
    report.applied.push({ part, rite: null, itemId: want.itemId });
    report.unchanged = false;
  };
  hand("weapon", preset.weapon, "main_hand", MAIN_HAND_SLOT);
  hand("offhand", preset.offhand, "off_hand", OFF_HAND_SLOT);
  for (const rite of RUNE_RITES) {
    const want = preset.runes[rite] ?? null;
    const socket = runeSlotIndex(rite);
    const current = rows.find((r) => r.slot_index === socket);
    if ((current?.item_id ?? null) === want) continue;
    if (want !== null && !runeFits(want, rite)) {
      report.skipped.push({ part: "rune", rite, itemId: want, reason: "wrong_slot" });
      continue;
    }
    const reason = step(() => {
      if (want !== null) {
        const from = rows.find((r) => inBag(r) && !r.equipped && r.item_id === want && (r.instance_id ?? null) === null && r.quantity > 0);
        if (!from) return "missing";
        if (from.quantity > 1) from.quantity -= 1;
        else rows = rows.filter((r) => r !== from);
      }
      if (current) {
        rows = rows.filter((r) => r !== current);
        if (!giveBack(current.item_id)) return "no_room";
      }
      if (want !== null) rows.push({ slot_index: socket, item_id: want, quantity: 1, equipped: 1, equipped_slot: `rune_${rite}`, instance_id: null });
      return null;
    });
    if (reason) {
      report.skipped.push({ part: "rune", rite, itemId: want, reason });
      continue;
    }
    report.applied.push({ part: "rune", rite, itemId: want });
    report.unchanged = false;
  }
  rows.sort((a, b) => a.slot_index - b.slot_index);
  return { rows, report };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  BAG_SLOTS,
  MAIN_HAND_SLOT,
  MAX_PRESETS,
  NAME_MAX,
  OFF_HAND_SLOT,
  applyLoadout,
  captureGear,
  cleanName,
  normalizePreset
});
