// GENERATED by tools/build-server-rules.mjs from src/gameplay/runeRules.ts — do not edit by hand.
// Relic rune sockets (slots, which rune fits which rite) shared by the web client, the offline mock and the Death Muffin backend.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/runeRules.ts
var runeRules_exports = {};
__export(runeRules_exports, {
  RUNE_BASE: () => RUNE_BASE,
  RUNE_IDS: () => RUNE_IDS,
  RUNE_SLOT_COUNT: () => RUNE_SLOT_COUNT,
  isRuneId: () => isRuneId,
  isRuneRite: () => isRuneRite,
  isRuneSlot: () => isRuneSlot,
  ownedRunes: () => ownedRunes,
  runeEquippedSlot: () => runeEquippedSlot,
  runeFits: () => runeFits,
  runeSlotIndex: () => runeSlotIndex,
  runeSlotRite: () => runeSlotRite,
  socketsOf: () => socketsOf,
  socketsSignature: () => socketsSignature
});
module.exports = __toCommonJS(runeRules_exports);

// src/content/runes.ts
var RUNE_RITES = ["bone_needle", "marrow_spear", "exhume", "miasma", "black_litany"];
var RUNE_IDS = [
  "rune_splinter",
  "rune_marrow_tap",
  "rune_volley",
  "rune_ossuary_ring",
  "rune_impale",
  "rune_mass_grave",
  "rune_bone_colossus",
  "rune_creeping_rot",
  "rune_contagion",
  "rune_hollow_choir",
  "rune_requiem"
];
var RUNE_TUNING = {
  /** Bone Needle. */
  splinter: { reach: 6, damageFrac: 0.3 },
  marrowTap: { essenceBonus: 4, damageMult: 0.7 },
  volley: { every: 4, needles: 3, damageFrac: 0.4, reach: 9 },
  /** Marrow Spear: the ring bursts on the cursor, pulled back to the spear's reach. */
  ring: { radius: 3, maxCastRange: 12, damageMult: 0.8 },
  impale: { rootS: 1.5, damageMult: 1.5 },
  /** Exhume. `slots` is how many legion places the colossus fills. */
  massGrave: { count: 3, statMult: 0.75, pickRadius: 4 },
  colossus: {
    corpses: 5,
    minCorpses: 3,
    slots: 2,
    pickRadius: 6,
    hpPerCorpse: 0.8,
    damagePerCorpse: 0.7,
    cleaveRadius: 2.4,
    cleaveFrac: 0.6,
    range: 2.4,
    interval: 1.2,
    speed: 4.8,
    /** Cooldown multiplier on Exhume's 500 ms (4 s), applied only to a cast that raised a Colossus. */
    cooldownMult: 8
  },
  /** Miasma Circle. */
  creepingRot: { speed: 1.5, radiusMult: 0.85, seekReach: 12 },
  contagion: { neighbours: 2, reach: 4.5, minStacks: 2 },
  /** Black Litany. */
  hollowChoir: { powerMult: 0.6 },
  requiem: { delayMs: 2e3, radiusMult: 1.7 }
};
var pct = (x) => `${Math.round(x * 100)}%`;
var T = RUNE_TUNING;
var RUNES = {
  rune_splinter: {
    id: "rune_splinter",
    name: "Rune of Splinters",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "The needle shatters on bone and the shards keep looking.",
    short: "Hits splinter to a second foe",
    lines: [`When a needle hits, a splinter flies to the nearest other enemy within ${T.splinter.reach} m for ${pct(T.splinter.damageFrac)} of the damage. Under a scythe, each reaping swing throws one splinter, from the nearest enemy it struck to the nearest one it missed.`],
    cost: null
  },
  rune_marrow_tap: {
    id: "rune_marrow_tap",
    name: "Rune of Marrow-Tap",
    rite: "bone_needle",
    rarity: "uncommon",
    sell: 25,
    lore: "Every wound is a spigot.",
    short: "More essence, softer needle",
    lines: [`Each needle hit returns ${T.marrowTap.essenceBonus} more Grave Essence. Under a scythe, each swing that lands returns ${T.marrowTap.essenceBonus} more once, however many enemies it strikes.`],
    cost: `Needles and scythe swings hit for ${pct(1 - T.marrowTap.damageMult)} less.`
  },
  rune_volley: {
    id: "rune_volley",
    name: "Rune of the Volley",
    rite: "bone_needle",
    rarity: "rare",
    sell: 60,
    lore: "Four breaths, then a flock.",
    short: "Every 4th needle is a volley",
    lines: [`Every ${T.volley.every}th needle you throw becomes a volley of ${T.volley.needles}, aimed at ${T.volley.needles} different enemies within ${T.volley.reach} m (or all at one target if it stands alone). The volley returns the essence of one needle between them. Needle only: a scythe's swing is not a volley.`],
    cost: `Each volley needle hits for ${pct(T.volley.damageFrac)}.`
  },
  rune_ossuary_ring: {
    id: "rune_ossuary_ring",
    name: "Ossuary Ring Rune",
    rite: "marrow_spear",
    rarity: "rare",
    sell: 60,
    lore: "The dead rise in a circle, like a congregation.",
    short: "Spikes erupt in a ring",
    lines: [`Instead of a line, bone erupts in a ${T.ring.radius} m ring at the cursor, striking everything inside and applying Fracture and Hemorrhage as usual.`],
    cost: `It no longer reaches down a long line, and strikes for ${pct(T.ring.damageMult)}.`
  },
  rune_impale: {
    id: "rune_impale",
    name: "Rune of Impaling",
    rite: "marrow_spear",
    rarity: "uncommon",
    sell: 25,
    lore: "One thorn, driven deep.",
    short: "Skewers and roots the first foe",
    lines: [`The spear stops at the first enemy it meets, hits it for ${pct(T.impale.damageMult - 1)} more and roots it for ${T.impale.rootS} s (a boss shrugs the root off but takes the hit).`],
    cost: "It no longer pierces the line behind."
  },
  rune_mass_grave: {
    id: "rune_mass_grave",
    name: "Mass Grave Rune",
    rite: "exhume",
    rarity: "rare",
    sell: 60,
    lore: "Why dig one grave when the field is full?",
    short: "Raise up to 3 corpses at once",
    lines: [`Exhume raises up to ${T.massGrave.count} corpses near the cursor at once, each with ${pct(T.massGrave.statMult)} of the usual thrall health and damage.`],
    cost: "Each thrall is weaker, and it spends more corpses."
  },
  rune_bone_colossus: {
    id: "rune_bone_colossus",
    name: "Bone Colossus Rune",
    rite: "exhume",
    rarity: "epic",
    sell: 150,
    lore: "Five dead, bound as one, and it remembers being a wall.",
    short: "Five corpses become one giant thrall",
    lines: [
      `When ${T.colossus.minCorpses} or more corpses lie within ${T.colossus.pickRadius} m of the one you name, Exhume consumes up to ${T.colossus.corpses} of them and raises one Bone Colossus instead. With fewer, or while a Colossus stands, it raises an ordinary thrall.`,
      `Its health is ${(T.colossus.hpPerCorpse * T.colossus.corpses).toFixed(1)}x and its damage ${(T.colossus.damagePerCorpse * T.colossus.corpses).toFixed(1)}x a thrall's with five corpses (less with fewer), and every blow cleaves ${T.colossus.cleaveRadius} m.`,
      `It fills ${T.colossus.slots} legion places and you can only keep one: raising another replaces it.`
    ],
    cost: `Exhume takes ${500 * T.colossus.cooldownMult / 1e3} s to ready again after raising a Colossus.`
  },
  rune_creeping_rot: {
    id: "rune_creeping_rot",
    name: "Creeping Rot Rune",
    rite: "miasma",
    rarity: "uncommon",
    sell: 25,
    lore: "Rot that has learned to walk.",
    short: "The circle crawls toward foes",
    lines: [`The circle drifts ${T.creepingRot.speed} m/s toward the nearest enemy within ${T.creepingRot.seekReach} m of it.`],
    cost: `The circle is ${pct(1 - T.creepingRot.radiusMult)} narrower.`
  },
  rune_contagion: {
    id: "rune_contagion",
    name: "Contagion Rune",
    rite: "miasma",
    rarity: "rare",
    sell: 60,
    lore: "It does not stop at the grave.",
    short: "Dying Withered foes infect others",
    lines: [`A Withered enemy that dies spreads its Withered stacks (minus one) to the ${T.contagion.neighbours} nearest enemies within ${T.contagion.reach} m, and those spread it again when they die (it needs ${T.contagion.minStacks} stacks to jump).`],
    cost: null
  },
  rune_hollow_choir: {
    id: "rune_hollow_choir",
    name: "Hollow Choir Rune",
    rite: "black_litany",
    rarity: "rare",
    sell: 60,
    lore: "The dead sing, and are not spent.",
    short: "Your thralls sing instead of dying",
    lines: ["Black Litany no longer sacrifices your thralls. They still lend their voices to its power."],
    cost: `The burst hits for ${pct(1 - T.hollowChoir.powerMult)} less.`
  },
  rune_requiem: {
    id: "rune_requiem",
    name: "Requiem Rune",
    rite: "black_litany",
    rarity: "epic",
    sell: 150,
    lore: "A hymn is only terrible once it is finished.",
    short: "The burst lands 2 s later, twice as wide",
    lines: [`Black Litany marks the ground, then bursts ${T.requiem.delayMs / 1e3} s later over ${T.requiem.radiusMult}x the radius. Corpses and thralls are consumed when it bursts.`],
    cost: "Enemies can walk out of it, and it can take more of your thralls."
  }
};
var RUNE_ORDER = [...RUNE_IDS];
var isRuneId = (id) => typeof id === "string" && Object.prototype.hasOwnProperty.call(RUNES, id);
var isRuneRite = (id) => typeof id === "string" && RUNE_RITES.includes(id);
var byRarity = (...rarities) => RUNE_ORDER.filter((id) => rarities.includes(RUNES[id].rarity));
var AREA_RUNE_POOL = {
  graves: byRarity("uncommon"),
  ossuary: byRarity("uncommon", "rare"),
  nave: byRarity("uncommon", "rare"),
  sanctum: byRarity("uncommon", "rare", "epic"),
  cloister: byRarity("uncommon", "rare", "epic"),
  pyre: byRarity("uncommon", "rare", "epic"),
  fen: byRarity("uncommon", "rare", "epic"),
  warren: byRarity("uncommon", "rare"),
  coliseum: byRarity("uncommon", "rare", "epic")
};
var ELITE_RUNE_CHANCE_BY_AREA = {
  graves: 0.05,
  warren: 0.055,
  ossuary: 0.06,
  nave: 0.07,
  coliseum: 0.08,
  sanctum: 0.09,
  cloister: 0.1,
  pyre: 0.11,
  fen: 0.12
};
var ELITE_RUNE_CHANCE = ELITE_RUNE_CHANCE_BY_AREA.graves;
var BOSS_RUNE_POOL = {
  gravedigger: ["rune_splinter", "rune_marrow_tap", "rune_mass_grave"],
  abbess: ["rune_ossuary_ring", "rune_impale", "rune_bone_colossus", "rune_volley"],
  congregation: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir"],
  prelate: ["rune_requiem", ...RUNE_ORDER],
  saint: ["rune_creeping_rot", "rune_contagion", "rune_hollow_choir", "rune_requiem", "rune_bone_colossus"],
  regent: [...RUNE_ORDER],
  mire: [...RUNE_ORDER]
};

// src/gameplay/runeRules.ts
var RUNE_BASE = 130;
var RUNE_SLOT_COUNT = RUNE_RITES.length;
var isRuneSlot = (slot) => Number.isInteger(slot) && slot >= RUNE_BASE && slot < RUNE_BASE + RUNE_SLOT_COUNT;
var runeSlotRite = (slot) => isRuneSlot(slot) ? RUNE_RITES[slot - RUNE_BASE] : null;
var runeSlotIndex = (rite) => RUNE_BASE + RUNE_RITES.indexOf(rite);
var runeEquippedSlot = (rite) => `rune_${rite}`;
var runeFits = (runeId, rite) => isRuneId(runeId) && isRuneRite(rite) && RUNES[runeId].rite === rite;
function socketsOf(rows) {
  const out = {};
  for (const r of rows) {
    const rite = runeSlotRite(r.slot_index);
    if (rite && (r.quantity ?? 1) > 0 && runeFits(r.item_id, rite)) out[rite] = r.item_id;
  }
  return out;
}
function ownedRunes(rows) {
  const out = {};
  for (const r of rows) if (r.slot_index >= 0 && r.slot_index < 100 && !r.equipped && isRuneId(r.item_id)) out[r.item_id] = (out[r.item_id] ?? 0) + r.quantity;
  return out;
}
var socketsSignature = (s) => RUNE_RITES.map((r) => s[r] ?? "-").join("|");
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  RUNE_BASE,
  RUNE_IDS,
  RUNE_SLOT_COUNT,
  isRuneId,
  isRuneRite,
  isRuneSlot,
  ownedRunes,
  runeEquippedSlot,
  runeFits,
  runeSlotIndex,
  runeSlotRite,
  socketsOf,
  socketsSignature
});
