class_name DmContent
extends RefCounted
## Typed access to the exported game content (godot/data/content/*.json, generated by tools/godot/export-content.ts).
## Everything is loaded lazily once (static cache). Dictionaries/Arrays returned are SHARED: do not mutate them (duplicate(true) first).
## NOTE: JSON numbers always arrive as float; wrap with int() where the TS value is an integer (hp, levels, counts, ms, sell).
##
## Generic:   DmContent.file("items")            -> the whole file as Dictionary { ExportName: value }
##            DmContent.get_export("areas", "DOORS")
##            DmContent.computed("smartTables")  -> value from computed.json (function results baked from the TS)
## Typed:     item(id) enemy(id) area(id) ability(id) discipline(id) boss(id) rune(id) brew(id) ... (see below)

const DIR := "res://data/content/"

static var _files: Dictionary = {}
static var _manifest: Dictionary = {}
static var _recipes: Array = []


## Drop the cache (tests / hot reload).
static func reset() -> void:
	_files = {}
	_manifest = {}
	_recipes = []


static func manifest() -> Dictionary:
	if _manifest.is_empty():
		_manifest = _read(DIR + "manifest.json")
	return _manifest


## Names of every exported file (without .json), excluding manifest.
static func file_names() -> PackedStringArray:
	var out := PackedStringArray()
	for k in manifest()["files"].keys():
		out.append(k)
	return out


static func file(name: String) -> Dictionary:
	if not _files.has(name):
		var path := DIR + name + ".json"
		if not FileAccess.file_exists(path):
			push_error("DmContent: unknown content file '%s'" % name)
			return {}
		_files[name] = _read(path)
	return _files[name]


static func get_export(file_name: String, export_name: String) -> Variant:
	return file(file_name).get(export_name)


static func computed(key: String) -> Variant:
	return file("computed").get(key)


static func _read(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("DmContent: cannot open %s" % path)
		return {}
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("DmContent: %s is not a JSON object" % path)
		return {}
	return parsed


static func _dict(file_name: String, export_name: String) -> Dictionary:
	var v: Variant = get_export(file_name, export_name)
	return v if typeof(v) == TYPE_DICTIONARY else {}


# ---- items (content/items.ts: ITEMS) ----

## All item defs: id -> { name, type, rarity, sell, lore?, icon?, offlineStats?, stack? }
static func items() -> Dictionary:
	return _dict("items", "ITEMS")


static func has_item(id: String) -> bool:
	return items().has(id)


## Same fallback as TS itemMeta(): unknown ids become a 0-gold common material named after the id.
static func item(id: String) -> Dictionary:
	var d: Variant = items().get(id)
	if d != null:
		return d
	return {"name": id.replace("_", " "), "type": "material", "rarity": "common", "sell": 0}


static func rarity_color(rarity: String) -> String:
	return _dict("items", "RARITY_COLOR").get(rarity, "#ffffff")


static func rarity_mark(rarity: String) -> String:
	return _dict("items", "RARITY_MARK").get(rarity, "")


static func healing_flasks() -> Dictionary:
	return _dict("items", "HEALING_FLASKS")


static func buff_flasks() -> Dictionary:
	return _dict("items", "BUFF_FLASKS")


# ---- world content ----

static func enemies() -> Dictionary:
	return _dict("enemies", "ENEMIES")


static func enemy(id: String) -> Dictionary:
	return enemies().get(id, {})


static func areas() -> Dictionary:
	return _dict("areas", "AREAS")


static func area(id: String) -> Dictionary:
	return areas().get(id, {})


static func area_order() -> Array:
	return get_export("areas", "AREA_ORDER")


static func doors() -> Array:
	return get_export("areas", "DOORS")


static func bosses() -> Dictionary:
	return _dict("bosses", "BOSSES")


static func boss(id: String) -> Dictionary:
	return bosses().get(id, {})


static func depths() -> Dictionary:
	return _dict("depths", "DEPTHS")


static func difficulties() -> Dictionary:
	return _dict("difficulty", "DIFFICULTIES")


static func difficulty(id: String) -> Dictionary:
	return difficulties().get(id, {})


# ---- character content ----

static func abilities() -> Dictionary:
	return _dict("abilities", "ABILITIES")


static func ability(id: String) -> Dictionary:
	return abilities().get(id, {})


## SPELL_FX: family -> ability id -> colours/fx data
static func spell_fx() -> Dictionary:
	return _dict("abilities", "SPELL_FX")


static func disciplines() -> Dictionary:
	return _dict("disciplines", "DISCIPLINES")


static func discipline(id: String) -> Dictionary:
	return disciplines().get(id, {})


## Kit (hotbar/grimoire/defaults) for a class family, baked from kitFor().
static func kit(family: String) -> Dictionary:
	return _dict("computed", "kits").get(family, {})


static func runes() -> Dictionary:
	return _dict("runes", "RUNES")


static func rune(id: String) -> Dictionary:
	return runes().get(id, {})


static func brews() -> Dictionary:
	return _dict("brews", "BREWS")


static func brew(id: String) -> Dictionary:
	return brews().get(id, {})


static func armor_sets() -> Dictionary:
	return _dict("armorSets", "ARMOR_SETS")


static func ascended_armor_sets() -> Dictionary:
	return _dict("armorSets", "ASCENDED_ARMOR_SETS")


static func legendary_sets() -> Dictionary:
	return _dict("legendarySets", "LEGENDARY_SETS")


static func set_bonuses() -> Dictionary:
	return _dict("setBonuses", "SET_BONUSES")


static func necro_weapons() -> Array:
	return get_export("necroWeapons", "NECRO_WEAPONS")


static func vows() -> Dictionary:
	return _dict("ascension", "VOWS")


static func boons() -> Dictionary:
	return _dict("ascension", "BOONS")


static func affixes() -> Array:
	return get_export("gameplay_affixRules", "AFFIXES")


## [min, max] for affix `id` at item level `ilvl` (1..99), baked from AFFIXES[i].range().
static func affix_range(id: String, ilvl: int) -> Array:
	var rows: Array = _dict("computed", "affixRanges").get(id, [])
	if rows.is_empty():
		return []
	return rows[clampi(ilvl, 1, rows.size()) - 1]


static func upgrade_cost(kind: String, tier: int) -> int:
	var costs: Array = _dict("computed", "upgradeCosts").get(kind, [])
	return int(costs[tier]) if tier >= 0 and tier < costs.size() else -1


# ---- gathering / crafting ----

static func gather_skills() -> Dictionary:
	return _dict("gameplay_gatheringRules", "SKILLS")


static func gather_nodes() -> Dictionary:
	return _dict("gameplay_gatheringRules", "NODES")


static func gather_node(id: String) -> Dictionary:
	return gather_nodes().get(id, {})


static func reagents() -> Dictionary:
	return _dict("reagents", "REAGENT_ITEMS")


## Every Workbench recipe as a Dictionary: { id, name, skill, level, result, qty, inputs: [ {item, qty} ] }
static func recipes() -> Array:
	if _recipes.is_empty():
		for row in get_export("recipes", "ALL_RECIPE_ROWS"):
			var inputs: Array = []
			for ing in row[6]:
				inputs.append({"item": ing[0], "qty": int(ing[1])})
			_recipes.append({"id": row[0], "name": row[1], "skill": row[2], "level": int(row[3]), "result": row[4], "qty": int(row[5]), "inputs": inputs})
	return _recipes


static func recipe(id: String) -> Dictionary:
	for r in recipes():
		if r["id"] == id:
			return r
	return {}


# ---- text / audio ----

static func codex(section: String) -> Variant:
	return get_export("codex", section)


## Covenant counsel tip: { title, body }
static func tip(id: String) -> Dictionary:
	return _dict("onboarding", "TIPS").get(id, {})


static func tips() -> Dictionary:
	return _dict("onboarding", "TIPS")


static func audio_map() -> Dictionary:
	return _dict("audioMap", "AUDIO_MAP")


# ---- loot (baked results of smartTable / depth helpers) ----

## smartTable(area, discipline): [ {item, weight} ]
static func smart_loot_table(area_id: String, discipline_id: String) -> Array:
	return _dict("computed", "smartTables").get(area_id, {}).get(discipline_id, [])


static func depth_roster(depth: int) -> Array:
	return _dict("computed", "depthRosters").get(str(depth), [])
