// GENERATED by tools/build-server-rules.mjs from src/gameplay/necroRules.ts — do not edit by hand.
// Necromancer progression rules shared by the web client and the auth server.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/necroRules.ts
var necroRules_exports = {};
__export(necroRules_exports, {
  NECRO_LIMITS: () => NECRO_LIMITS,
  applySave: () => applySave,
  ascend: () => ascend,
  ashesOnAscend: () => ashesOnAscend,
  blankState: () => blankState,
  buyBoon: () => buyBoon,
  damageCost: () => damageCost,
  importLocal: () => importLocal,
  normalise: () => normalise,
  purchase: () => purchase,
  summonAreaBoss: () => summonAreaBoss,
  summonPrelate: () => summonPrelate,
  unlockKills: () => unlockKills,
  waveCost: () => waveCost
});
module.exports = __toCommonJS(necroRules_exports);

// src/content/armorSets.ts
var ARMOR_PARTS = ["head", "chest", "hands", "legs", "feet"];
var ARMOR_SETS = {
  gravecaller: { name: "Gravecall", wearer: "Gravecaller", color: 8485789, accent: 13090268, stats: ["stat_int", "stat_vit"], lore: "Stitched for those who command the newly buried." },
  warden: { name: "Lamplight", wearer: "Grave Warden", color: 9531463, accent: 16039271, stats: ["stat_vit", "stat_str"], lore: "Brass and soot from the grave watch." },
  monk: { name: "Bellwake", wearer: "Bell Monk", color: 9533794, accent: 14991750, stats: ["stat_str", "stat_agi"], lore: "Worn thin by a thousand measured tolls." },
  ossuary: { name: "Ivory Reliquary", wearer: "Ossuary", color: 13813672, accent: 10194658, stats: ["stat_int", "stat_vit"], lore: "Bone plates engraved with the Covenant dead." },
  mourner: { name: "Widowveil", wearer: "Mourner", color: 6711948, accent: 10795488, stats: ["stat_int", "stat_agi"], lore: "Funeral cloth that remembers every name." },
  witch: { name: "Carrionbloom", wearer: "Carrion Witch", color: 6452546, accent: 12966528, stats: ["stat_int", "stat_vit"], lore: "Living thorns bind the seams shut." },
  rotweaver: { name: "Blightweave", wearer: "Rotweaver", color: 7636039, accent: 13231213, stats: ["stat_int", "stat_vit"], lore: "A sickly mantle spun where the plague took root." },
  knight: { name: "Hollow Oath", wearer: "Hollow Knight", color: 6712188, accent: 13193039, stats: ["stat_str", "stat_vit"], lore: "Blackened plate still bearing its broken vow." },
  veil: { name: "Threshold", wearer: "Veilwalker", color: 6709646, accent: 11445744, stats: ["stat_agi", "stat_int"], lore: "A border of silver marks the edge between worlds." }
};
var ASCENDED_ARMOR_SETS = {
  gravecaller: { name: "Epitaph Sovereign", wearer: "Gravecaller", color: 4208735, accent: 14141951, stats: ["stat_int", "stat_vit"], lore: "A sovereign name is written on every bone clasp." },
  warden: { name: "Nightwatch Beacon", wearer: "Grave Warden", color: 5195318, accent: 16766070, stats: ["stat_vit", "stat_str"], lore: "Its caged flame answers the last watch bell." },
  monk: { name: "Last Toll", wearer: "Bell Monk", color: 6508865, accent: 16768412, stats: ["stat_str", "stat_agi"], lore: "Bronze thread hums with the final note." },
  ossuary: { name: "Marrow Regent", wearer: "Ossuary", color: 11970690, accent: 15985870, stats: ["stat_int", "stat_vit"], lore: "The reliquary opens only for its bearer." },
  mourner: { name: "Pale Requiem", wearer: "Mourner", color: 4540776, accent: 13163775, stats: ["stat_int", "stat_agi"], lore: "A hush follows wherever the silver hem falls." },
  witch: { name: "Thorn Covenant", wearer: "Carrion Witch", color: 3888702, accent: 12120461, stats: ["stat_int", "stat_vit"], lore: "The roots draw strength from what lies beneath." },
  rotweaver: { name: "Virulent Choir", wearer: "Rotweaver", color: 4676390, accent: 14679921, stats: ["stat_int", "stat_vit"], lore: "A bright plague song runs through its seams." },
  knight: { name: "Oathbreaker", wearer: "Hollow Knight", color: 3488070, accent: 16742255, stats: ["stat_str", "stat_vit"], lore: "The oath is broken; the shield remains." },
  veil: { name: "Umbral Crossing", wearer: "Veilwalker", color: 3748950, accent: 13154559, stats: ["stat_agi", "stat_int"], lore: "The wearer leaves no shadow on either side." }
};
var PART_NAMES = { head: "Crown", chest: "Vestment", hands: "Grips", legs: "Legguards", feet: "Treads" };
var PART_POWER = { head: 2, chest: 4, hands: 2, legs: 3, feet: 2 };
var RARITY_SCALE = { common: 1, uncommon: 1, rare: 2, epic: 3 };
var PART_AREA = { head: "graves", hands: "graves", chest: "ossuary", legs: "nave", feet: "sanctum" };
var PART_RARITY = { head: "uncommon", hands: "uncommon", chest: "rare", legs: "rare", feet: "epic" };
var ASCENDED_AREA = { head: "sanctum", hands: "sanctum", chest: "cloister", legs: "cloister", feet: "pyre" };
var ASCENDED_RARITY = { head: "rare", hands: "rare", chest: "epic", legs: "epic", feet: "epic" };
function piecesFor(sets, collection) {
  return Object.entries(sets).flatMap(([disciplineId, set]) => ARMOR_PARTS.map((part) => ({
    id: collection === 1 ? `set_${disciplineId}_${part}` : `set_${disciplineId}_ascended_${part}`,
    setId: collection === 1 ? disciplineId : `${disciplineId}_ascended`,
    disciplineId,
    collection,
    setName: set.name,
    part,
    name: `${set.name} ${PART_NAMES[part]}`,
    type: `armor_${part}`,
    rarity: collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part],
    area: collection === 1 ? PART_AREA[part] : ASCENDED_AREA[part],
    stats: { [set.stats[0]]: PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] + (collection === 2 ? 1 : 0), [set.stats[1]]: Math.max(1, Math.floor(PART_POWER[part] * RARITY_SCALE[collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]] / 2)) },
    color: set.color,
    accent: set.accent,
    wearer: set.wearer,
    lore: set.lore,
    sell: PART_POWER[part] * ((collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "epic" ? 22 : (collection === 1 ? PART_RARITY[part] : ASCENDED_RARITY[part]) === "rare" ? 13 : 7) + (collection === 2 ? 20 : 0)
  })));
}
var ARMOR_PIECES = [...piecesFor(ARMOR_SETS, 1), ...piecesFor(ASCENDED_ARMOR_SETS, 2)];
var ARMOR_BY_ID = Object.fromEntries(ARMOR_PIECES.map((piece) => [piece.id, piece]));
function armorLoot(area) {
  if (area === "fen") return ARMOR_PIECES.filter((piece) => piece.collection === 2).map((piece) => ({ item: piece.id, weight: 1 }));
  return ARMOR_PIECES.filter((piece) => piece.area === area || piece.collection === 1 && (area === "cloister" || area === "pyre") && piece.area !== "graves" || piece.collection === 2 && area === "pyre" && piece.area === "cloister").map((piece) => ({ item: piece.id, weight: 1 }));
}

// src/content/necroWeapons.ts
var NECRO_TIERS = ["bone", "iron", "gold", "hell", "moon"];
var NECRO_WEAPON_TUNING = {
  staff: {
    /** Needle reach: +25%. */
    needleRangeMult: 1.25,
    /** Extra enemies the needle passes through behind its target, and what they take relative to the first. */
    pierce: 1,
    pierceDamageMult: 0.8,
    /** The pierced enemy must be within this distance of the needle's line, and this far behind the target. */
    pierceLane: 1.1,
    pierceReach: 4.5,
    /** Passive: +10% spell damage (folded into derived Spell power, so the stats line shows it). */
    spellDamageMult: 1.1
  },
  scythe: {
    /** LMB becomes a close reaping arc: full cone angle (degrees), reach (metres), targets hit. */
    arcDeg: 100,
    reach: 3,
    maxHits: 3,
    /** Per-target damage relative to a Needle hit, cooldown and lock (a heavier, slower swing), essence per target struck. */
    damageMult: 1.15,
    cooldownMs: 520,
    lockMs: 110,
    gestureSeconds: 0.3,
    essencePerHit: 4,
    /** Bonus souls for a kill the arc delivered, on top of the normal soul every kill gives. */
    soulsPerKill: 1,
    /** How long (ms) a struck enemy still counts as reaped when it dies. */
    reapWindowMs: 1200
  },
  wand: {
    /** Needle cooldown and cast lock are divided by this (+30% cadence). */
    cadenceMult: 1.3,
    /** Needle damage: -15%. */
    damageMult: 0.85
  },
  sickle: {
    /** Each needle adds this many Withered stacks (up to the discipline's cap). */
    witheredStacks: 1,
    /** Passive: Exhume gives back this share of its essence cost. */
    exhumeRefund: 0.2
  },
  skull_focus: {
    /** Thrall cap bonus at or above this tier. */
    thrallCap: 1,
    minTier: "gold"
  },
  grimoire: {
    /** Every rite (not the LMB primary) recovers 10% sooner. */
    riteCooldownMult: 0.9
  },
  mourning_bell: {
    /** A Mourner's wraith hit heals every ally in this range by this share of their max health. */
    allyHealFrac: 0.02,
    allyHealRange: 14
  }
};
var NECRO_TIER_INFO = {
  bone: { label: "Bone", level: 1, rarity: "common", sellMult: 1, area: ["graves", "warren"] },
  iron: { label: "Iron", level: 15, rarity: "uncommon", sellMult: 2.4, area: ["ossuary", "coliseum"] },
  gold: { label: "Gold", level: 30, rarity: "rare", sellMult: 5.5, area: ["nave", "sanctum"] },
  hell: { label: "Hell", level: 45, rarity: "epic", sellMult: 11, area: ["cloister", "pyre"] },
  moon: { label: "Moon", level: 60, rarity: "epic", sellMult: 22, area: ["pyre"] }
};
var PALETTE = {
  bone: { color: 14208957, accent: 15985881 },
  iron: { color: 8027526, accent: 12830674 },
  gold: { color: 14263361, accent: 16769946 },
  hell: { color: 9054746, accent: 16742973 },
  moon: { color: 11188456, accent: 15002623 }
};
var T = NECRO_WEAPON_TUNING;
var pct = (n) => `${Math.round(n * 100)}%`;
var KINDS = {
  staff: {
    label: "Staff",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Vertebral Staff", iron: "Crypt-Iron Crozier", gold: "Reliquary Staff", hell: "Hellcoal Crozier", moon: "Staff of the Pale Moon" },
    int: [5, 9, 15, 22, 30],
    second: { key: "stat_vit", values: [0, 1, 2, 4, 6] },
    sell: 16,
    lore: {
      bone: "Fused vertebrae, still warm from the hand that carried it. Bone Needles fly farther and pierce a second body.",
      iron: "A grave-watch crozier with a bell-metal cap. Bone Needles fly farther and pierce a second body.",
      gold: "Tithe-gold wound round a reliquary shaft. Bone Needles fly farther and pierce a second body.",
      hell: "Quenched in pyre-coal; the skull at its head never stops smoking. Bone Needles fly farther and pierce a second body.",
      moon: "Cut from a bone that never touched the ground. Bone Needles fly farther and pierce a second body."
    },
    effect: `Bone Needle: +${pct(T.staff.needleRangeMult - 1)} range, pierces ${T.staff.pierce} extra target. Passive: +${pct(T.staff.spellDamageMult - 1)} spell damage. Two-handed.`
  },
  scythe: {
    label: "Scythe",
    type: "weapon",
    slot: "main_hand",
    twoHanded: true,
    names: { bone: "Gleaner's Scythe", iron: "Sexton's Scythe", gold: "Tithe-Reaper", hell: "Pyre Reaper", moon: "Moonreaper" },
    int: [4, 8, 13, 19, 26],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 18,
    lore: {
      bone: "A gleaner cuts what the living left standing. Your left click becomes a reaping arc; kills in it yield a soul.",
      iron: "The sexton swings it at dusk, in rows. Your left click becomes a reaping arc; kills in it yield a soul.",
      gold: "Every swing tolls a coin against the dead. Your left click becomes a reaping arc; kills in it yield a soul.",
      hell: "Its edge glows where it has drunk ash. Your left click becomes a reaping arc; kills in it yield a soul.",
      moon: "The last harvest is always by moonlight. Your left click becomes a reaping arc; kills in it yield a soul."
    },
    effect: `Left click becomes a ${T.scythe.arcDeg}\xB0 reaping arc (${T.scythe.reach} m, hits up to ${T.scythe.maxHits}); kills in the arc give +${T.scythe.soulsPerKill} soul. Two-handed.`
  },
  wand: {
    label: "Wand",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Knucklebone Wand", iron: "Iron Mourning Wand", gold: "Gilded Censer Wand", hell: "Emberthorn Wand", moon: "Wand of Quiet Stars" },
    int: [3, 6, 10, 15, 21],
    second: { key: "stat_agi", values: [0, 1, 2, 3, 5] },
    sell: 12,
    lore: {
      bone: "Finger bones, bound in a hurry. Bone Needles come faster and strike softer.",
      iron: "A mourner flicks it like a hand-bell. Bone Needles come faster and strike softer.",
      gold: "A censer chain wound round the grip. Bone Needles come faster and strike softer.",
      hell: "Thorned, and warm to the touch. Bone Needles come faster and strike softer.",
      moon: "It weighs nothing, and is never quite still. Bone Needles come faster and strike softer."
    },
    effect: `Bone Needle: +${pct(T.wand.cadenceMult - 1)} cadence, -${pct(1 - T.wand.damageMult)} damage. One-handed: pair it with an off-hand.`
  },
  sickle: {
    label: "Ritual Sickle",
    type: "weapon",
    slot: "main_hand",
    twoHanded: false,
    names: { bone: "Barrow Sickle", iron: "Plague Sickle", gold: "Sexton's Gilded Sickle", hell: "Blightfire Sickle", moon: "Moonrot Sickle" },
    int: [3, 6, 10, 14, 20],
    second: { key: "stat_vit", values: [1, 2, 3, 5, 7] },
    sell: 13,
    lore: {
      bone: "A curved rib, sharpened on a headstone. Bone Needles leave the target Withered; Exhume returns essence.",
      iron: "The plague priests cut herbs and throats with it. Bone Needles leave the target Withered; Exhume returns essence.",
      gold: "Gilded for rites nobody admits to. Bone Needles leave the target Withered; Exhume returns essence.",
      hell: "The rot burns instead of festering. Bone Needles leave the target Withered; Exhume returns essence.",
      moon: "Its blade is etched with a blight the moon forgave. Bone Needles leave the target Withered; Exhume returns essence."
    },
    effect: `Bone Needle applies ${T.sickle.witheredStacks} Withered stack. Passive: Exhume refunds ${pct(T.sickle.exhumeRefund)} of its essence. One-handed.`
  },
  skull_focus: {
    label: "Skull Focus",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Skull Focus", iron: "Iron-Jawed Skull Focus", gold: "Gilded Skull Focus", hell: "Cinder Skull Focus", moon: "Moon Skull Focus" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_vit", values: [2, 3, 5, 8, 11] },
    sell: 10,
    lore: {
      bone: "A nameless skull that still listens. (Gold and better skulls hold one more thrall.)",
      iron: "Its jaw is wired shut so it cannot argue. (Gold and better skulls hold one more thrall.)",
      gold: "It remembers a legion. Hold it and command one more thrall.",
      hell: "The eyes glow like coals in a cold hearth. Hold it and command one more thrall.",
      moon: "It was a king, once; it still expects to be obeyed. Hold it and command one more thrall."
    },
    effect: `Off-hand. Gold tier and above: +${T.skull_focus.thrallCap} thrall cap.`
  },
  grimoire: {
    label: "Grimoire",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Gravedigger's Grimoire", iron: "Iron-Clasped Grimoire", gold: "Gilt Reliquary Grimoire", hell: "Hellbound Grimoire", moon: "Moonlit Grimoire" },
    int: [2, 4, 7, 10, 14],
    sell: 11,
    lore: {
      bone: "A gravedigger's ledger of names and their uses. Rites recover sooner.",
      iron: "Chained shut, and opened only from the inside. Rites recover sooner.",
      gold: "Every page is gilt, every margin a warning. Rites recover sooner.",
      hell: "Its binding is singed along the spine. Rites recover sooner.",
      moon: "The pages turn themselves to the rite you need. Rites recover sooner."
    },
    effect: `Off-hand. Rites (your other spells, not the left click) recover ${pct(1 - T.grimoire.riteCooldownMult)} faster.`
  },
  mourning_bell: {
    label: "Mourning Bell",
    type: "offhand",
    slot: "off_hand",
    twoHanded: false,
    names: { bone: "Pauper's Mourning Bell", iron: "Iron Mourning Bell", gold: "Gilded Mourning Bell", hell: "Cinder Mourning Bell", moon: "Moon Mourning Bell" },
    int: [1, 3, 5, 8, 11],
    second: { key: "stat_agi", values: [1, 2, 3, 5, 7] },
    sell: 10,
    lore: {
      bone: "Rung once for each name you could not save. A Mourner's wraith hits mend allies.",
      iron: "Its note is flat on purpose. A Mourner's wraith hits mend allies.",
      gold: "The clapper is wrapped in widow's silk. A Mourner's wraith hits mend allies.",
      hell: "It tolls for the ones who should have stayed buried. A Mourner's wraith hits mend allies.",
      moon: "You hear it a moment before it rings. A Mourner's wraith hits mend allies."
    },
    effect: `Off-hand. Mourner: each wraith hit heals allies in ${T.mourning_bell.allyHealRange} m for ${pct(T.mourning_bell.allyHealFrac)} of their max health.`
  }
};
var NECRO_KIND_LABEL = Object.fromEntries(Object.entries(KINDS).map(([k, d]) => [k, d.label]));
function build() {
  const out = [];
  for (const [kind, def] of Object.entries(KINDS)) {
    NECRO_TIERS.forEach((tier, i) => {
      const info = NECRO_TIER_INFO[tier];
      const stats = { stat_int: def.int[i] };
      if (def.second && def.second.values[i] > 0) stats[def.second.key] = def.second.values[i];
      out.push({
        id: `${kind}_${tier}`,
        kind,
        tier,
        name: def.names[tier],
        type: def.type,
        slot: def.slot,
        twoHanded: def.twoHanded,
        rarity: info.rarity,
        level: info.level,
        stats,
        sell: Math.round(def.sell * info.sellMult),
        lore: def.lore[tier],
        effect: def.effect,
        color: PALETTE[tier].color,
        accent: PALETTE[tier].accent
      });
    });
  }
  return out;
}
var NECRO_WEAPONS = build();
var NECRO_WEAPON_BY_ID = Object.fromEntries(NECRO_WEAPONS.map((w) => [w.id, w]));
function necroWeaponLoot(area) {
  const out = [];
  for (const w of NECRO_WEAPONS) {
    if (!NECRO_TIER_INFO[w.tier].area.includes(area)) continue;
    out.push({ item: w.id, weight: w.tier === "moon" ? 0.5 : 1 });
  }
  return out;
}
var WOOD_KINDS = ["staff", "wand", "grimoire"];
var WOOD_RECIPE = {
  bone: { level: 3, ing: [["plank_oak", 3], ["bones_old", 2]] },
  iron: { level: 8, ing: [["plank_elm", 3], ["ingot_iron", 1]] },
  gold: { level: 18, ing: [["plank_willow", 3], ["ingot_gold", 1]] },
  hell: { level: 42, ing: [["plank_yew", 3], ["ingot_hell", 1]] },
  moon: { level: 57, ing: [["plank_blackthorn", 3], ["ingot_moon", 1]] }
};
var SMITH_RECIPE = {
  bone: { level: 2, ing: [["ingot_copper", 2], ["bones_old", 3]] },
  iron: { level: 10, ing: [["ingot_iron", 3]] },
  gold: { level: 20, ing: [["ingot_gold", 3], ["ingot_iron", 1]] },
  hell: { level: 40, ing: [["ingot_hell", 3], ["ingot_gold", 1]] },
  moon: { level: 55, ing: [["ingot_moon", 3], ["ingot_hell", 1]] }
};
var NECRO_RECIPES = NECRO_WEAPONS.map((w) => {
  const wood = WOOD_KINDS.includes(w.kind);
  const r = (wood ? WOOD_RECIPE : SMITH_RECIPE)[w.tier];
  return [`craft_${w.id}`, w.name, wood ? "woodcutting" : "mining", r.level, w.id, 1, r.ing];
});

// src/content/npcSpots.ts
var NPC_IDS = ["prior", "sexton", "apothecary"];
var NPC_SPOTS = {
  prior: { area: "chapterhouse", x: -3.4, z: 15.8, label: "The Prior" },
  sexton: { area: "acre", x: -26, z: 23, label: "The Sexton" },
  apothecary: { area: "chapterhouse", x: 8.3, z: 17.2, label: "The Apothecary" }
};
var npcInteractableId = (id) => `npc_${id}`;

// src/content/areas.ts
var npcSpots = (area) => NPC_IDS.filter((n) => NPC_SPOTS[n].area === area).map((n) => ({ id: npcInteractableId(n), kind: "npc", label: NPC_SPOTS[n].label, x: NPC_SPOTS[n].x, z: NPC_SPOTS[n].z }));
var AREAS = {
  chapterhouse: {
    id: "chapterhouse",
    name: "The Chapterhouse",
    subtitle: "Sanctuary of the Ossuary Covenant",
    theme: "chapter",
    rect: { x0: -13, z0: 8, x1: 13, z1: 32 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "reliquary", kind: "inventory", label: "Reliquary", x: -8.5, z: 14 },
      { id: "workbench", kind: "forge", label: "Ossuary Workbench", x: 8.5, z: 14 },
      { id: "niches", kind: "professions", label: "Rite Niches", x: -10.8, z: 26.5 },
      { id: "altar", kind: "upgrades", label: "Altar of Ascension", x: 0, z: 21 },
      { id: "waystone_chapterhouse", kind: "waystone", label: "Waystone", x: 9, z: 26.5 },
      // The Ossuary Vault: the sarcophagus between the Altar and the south braziers (shared stash, key V).
      { id: "ossuary_vault", kind: "vault", label: "Ossuary Vault", x: 0, z: 27 },
      ...npcSpots("chapterhouse")
    ],
    ambient: { fog: 722960, hemiSky: 3877458, hemiGround: 657168, moon: 9412305 }
  },
  // The non-combat gathering zone: every tier of every gathering node, no waves (roadmap §6).
  acre: {
    id: "acre",
    name: "The Sexton's Acre",
    subtitle: "Where the Covenant's dead are tended",
    theme: "acre",
    rect: { x0: -62, z0: 6, x1: -20, z1: 38 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "waystone_acre", kind: "waystone", label: "Waystone", x: -23, z: 25.5 },
      { id: "sawpit", kind: "sawpit", label: "Sawpit", x: -23.5, z: 12.5 },
      { id: "bone_kiln", kind: "kiln", label: "Bone Kiln", x: -23.5, z: 31.6 },
      // Salvaging: grinds spare gear into materials and reagents.
      { id: "bone_grinder", kind: "grinder", label: "Bone Grinder", x: -27, z: 33.2 },
      { id: "cooking_fire", kind: "fire", label: "Cooking Fire", x: -26.5, z: 28.5 },
      { id: "lectern", kind: "lectern", label: "Covenant Lectern", x: -24.2, z: 17.8 },
      ...npcSpots("acre")
    ],
    ambient: { fog: 790288, hemiSky: 4937828, hemiGround: 2304032, moon: 12307416 }
  },
  graves: {
    id: "graves",
    name: "The Hollow Graves",
    subtitle: "Where the Covenant buries what it cannot keep",
    theme: "graveyard",
    rect: { x0: -26, z0: -36, x1: 26, z1: 4 },
    safe: false,
    level: 1,
    enemies: [
      { id: "robber", weight: 52 },
      { id: "hound", weight: 24 },
      { id: "penitent", weight: 11 },
      { id: "sac", weight: 7 },
      { id: "moth", weight: 6 },
      { id: "bat", weight: 5 },
      { id: "ghoul", weight: 6 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6500,
    eliteChance: 0.035,
    loot: [
      ...armorLoot("graves"),
      ...necroWeaponLoot("graves"),
      { item: "material_copper_shard", weight: 30 },
      { item: "ore_copper", weight: 24 },
      { item: "ore_tin", weight: 14 },
      { item: "flask_hp_minor", weight: 12 },
      { item: "log_oak", weight: 8 },
      { item: "ring_copper", weight: 4 },
      { item: "helm_copper", weight: 4 },
      { item: "staff_oak", weight: 3 }
    ],
    itemChance: 0.08,
    breaches: [
      [-18, -29],
      [0, -31],
      [18, -29],
      [-21, -13],
      [21, -11],
      [9, -19],
      [-9, -21],
      [20, -24],
      [-14, -3],
      [14, -4]
    ],
    interactables: [
      { id: "waystone_graves", kind: "waystone", label: "Waystone", x: -5.5, z: 1 },
      // Area bosses (content/bosses.ts summonSpot: each arena's north edge).
      { id: "kings_grave", kind: "boss", label: "The King's Grave", x: -14, z: -30.5 }
    ],
    ambient: { fog: 854548, hemiSky: 3812693, hemiGround: 722960, moon: 10135252 }
  },
  ossuary: {
    id: "ossuary",
    name: "The Marrow Ossuary",
    subtitle: "Ten thousand skulls, and all of them listening",
    theme: "ossuary",
    rect: { x0: 32, z0: -38, x1: 64, z1: -2 },
    safe: false,
    level: 5,
    enemies: [
      { id: "robber", weight: 30 },
      { id: "hound", weight: 30 },
      { id: "sac", weight: 18 },
      { id: "deacon", weight: 12 },
      { id: "penitent", weight: 10 },
      { id: "rat", weight: 10 },
      { id: "golem", weight: 2 },
      { id: "moth", weight: 5 },
      { id: "bat", weight: 4 },
      { id: "ghoul", weight: 4 }
    ],
    cap: 32,
    waveSize: 10,
    waveIntervalMs: 6200,
    eliteChance: 0.045,
    unlock: { area: "graves", kills: 300 },
    loot: [
      ...armorLoot("ossuary"),
      ...necroWeaponLoot("ossuary"),
      { item: "ore_iron", weight: 24 },
      { item: "ore_copper", weight: 14 },
      { item: "material_copper_bar", weight: 14 },
      { item: "ore_bronze", weight: 10 },
      { item: "flask_hp_minor", weight: 10 },
      { item: "augment_copper", weight: 5 },
      { item: "sword_copper", weight: 4 },
      { item: "plate_copper", weight: 4 },
      { item: "helm_iron", weight: 3 }
    ],
    itemChance: 0.09,
    breaches: [[38, -33], [50, -35], [60, -27], [60, -9], [46, -6], [39, -18], [54, -19], [44, -27]],
    interactables: [
      { id: "waystone_ossuary", kind: "waystone", label: "Waystone", x: 35.5, z: -6 },
      { id: "abbess_reliquary", kind: "boss", label: "The Abbess's Reliquary", x: 48, z: -32.5 }
    ],
    ambient: { fog: 920332, hemiSky: 4207434, hemiGround: 854281, moon: 12036494 }
  },
  nave: {
    id: "nave",
    name: "The Drowned Nave",
    subtitle: "The congregation never stopped kneeling",
    theme: "nave",
    rect: { x0: -15, z0: -96, x1: 15, z1: -44 },
    safe: false,
    level: 9,
    enemies: [
      { id: "penitent", weight: 23 },
      { id: "robber", weight: 27 },
      { id: "deacon", weight: 15 },
      { id: "sac", weight: 16 },
      { id: "hound", weight: 19 },
      { id: "wraith", weight: 12 },
      { id: "censer", weight: 6 },
      { id: "gargoyle", weight: 8 },
      { id: "bat", weight: 7 },
      { id: "acolyte", weight: 8 },
      { id: "templar", weight: 3 }
    ],
    cap: 34,
    waveSize: 11,
    waveIntervalMs: 6e3,
    eliteChance: 0.055,
    unlock: { area: "ossuary", kills: 420 },
    loot: [
      ...armorLoot("nave"),
      ...necroWeaponLoot("nave"),
      { item: "ore_silver", weight: 20 },
      { item: "ore_iron", weight: 20 },
      { item: "ore_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "augment_iron", weight: 5 },
      { item: "helm_iron", weight: 6 },
      { item: "chest_iron", weight: 4 }
    ],
    itemChance: 0.1,
    breaches: [[-11, -91], [11, -91], [-11, -72], [11, -72], [-11, -53], [11, -53], [0, -82], [0, -62]],
    interactables: [
      { id: "waystone_nave", kind: "waystone", label: "Waystone", x: 6, z: -47.5 },
      { id: "drowned_font", kind: "boss", label: "The Drowned Font", x: 0, z: -70.35 }
    ],
    ambient: { fog: 723220, hemiSky: 3352666, hemiGround: 525839, moon: 9406168 }
  },
  sanctum: {
    id: "sanctum",
    name: "The Bell Sanctum",
    subtitle: "Seat of the Bell-Sworn Prelate",
    theme: "sanctum",
    rect: { x0: -18, z0: -130, x1: 18, z1: -102 },
    safe: false,
    level: 13,
    enemies: [
      { id: "penitent", weight: 30 },
      { id: "deacon", weight: 20 },
      { id: "robber", weight: 20 },
      { id: "hound", weight: 20 },
      { id: "sac", weight: 10 },
      { id: "censer", weight: 10 },
      { id: "wraith", weight: 10 },
      { id: "golem", weight: 4 },
      { id: "gargoyle", weight: 8 },
      { id: "seraph", weight: 7 },
      { id: "acolyte", weight: 8 },
      { id: "templar", weight: 6 }
    ],
    cap: 26,
    waveSize: 8,
    waveIntervalMs: 6500,
    eliteChance: 0.07,
    unlock: { area: "nave", kills: 520 },
    loot: [
      ...armorLoot("sanctum"),
      ...necroWeaponLoot("sanctum"),
      { item: "ore_gold", weight: 18 },
      { item: "ore_steel", weight: 14 },
      { item: "ingot_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "chest_iron", weight: 7 },
      { item: "helm_gold", weight: 5 },
      { item: "kit_iron_warden", weight: 5 }
    ],
    itemChance: 0.12,
    breaches: [[-14, -126], [14, -126], [-15, -109], [15, -109]],
    interactables: [
      { id: "waystone_sanctum", kind: "waystone", label: "Waystone", x: 6, z: -105 },
      { id: "sundered_bell", kind: "boss", label: "The Sundered Bell", x: 0, z: -123.4 }
    ],
    ambient: { fog: 1050644, hemiSky: 4006738, hemiGround: 787980, moon: 10848984 }
  },
  cloister: {
    id: "cloister",
    name: "The Plague Cloister",
    subtitle: "Where the blight grows with you",
    theme: "cloister",
    rect: { x0: 24, z0: -134, x1: 64, z1: -98 },
    safe: false,
    level: 20,
    scaling: { minLevel: 20 },
    enemies: [
      { id: "plague_doctor", weight: 22 },
      { id: "flagellant", weight: 24 },
      { id: "sac", weight: 14 },
      { id: "rat", weight: 10 },
      { id: "acolyte", weight: 8 },
      { id: "censer", weight: 8 },
      { id: "moth", weight: 6 },
      { id: "templar", weight: 5 },
      { id: "golem", weight: 3 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6e3,
    eliteChance: 0.08,
    unlock: { area: "sanctum", kills: 600 },
    loot: [
      ...armorLoot("cloister"),
      ...necroWeaponLoot("cloister"),
      { item: "ore_steel", weight: 14 },
      { item: "ore_hell", weight: 12 },
      { item: "ore_moon", weight: 6 },
      { item: "ingot_steel", weight: 6 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "gem_bone_opal", weight: 3 },
      { item: "flask_hp_major", weight: 10 },
      { item: "flask_damage", weight: 6 },
      { item: "flask_void_resist", weight: 5 },
      { item: "helm_gold", weight: 5 },
      { item: "chest_iron", weight: 5 }
    ],
    itemChance: 0.14,
    breaches: [[27, -101], [61, -101], [27, -131], [61, -131], [44, -100.5], [62, -116]],
    interactables: [
      { id: "waystone_cloister", kind: "waystone", label: "Waystone", x: 27.5, z: -108 },
      { id: "saints_litter", kind: "boss", label: "The Saint's Litter", x: 44, z: -129.5 }
    ],
    ambient: { fog: 659464, hemiSky: 2898468, hemiGround: 461317, moon: 10273930 }
  },
  // The Cinder Pyre (2026-09-30): the fire realm past the Plague Cloister, level-scaled like it but harder.
  pyre: {
    id: "pyre",
    name: "The Cinder Pyre",
    subtitle: "Where the Covenant burns what it cannot bury",
    theme: "pyre",
    rect: { x0: 70, z0: -134, x1: 110, z1: -98 },
    safe: false,
    level: 30,
    scaling: { minLevel: 30 },
    enemies: [
      { id: "cinder_husk", weight: 30 },
      { id: "pyre_priest", weight: 20 },
      { id: "cinderhound", weight: 22 },
      { id: "slag_brute", weight: 8 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6e3,
    eliteChance: 0.09,
    unlock: { area: "cloister", kills: 700 },
    loot: [
      ...armorLoot("pyre"),
      ...necroWeaponLoot("pyre"),
      { item: "ore_hell", weight: 22 },
      { item: "ingot_hell", weight: 6 },
      { item: "ore_steel", weight: 12 },
      { item: "ingot_steel", weight: 6 },
      { item: "ore_moon", weight: 5 },
      { item: "gem_grave_garnet", weight: 8 },
      { item: "gem_bone_opal", weight: 4 },
      { item: "flask_hp_major", weight: 10 },
      { item: "flask_damage", weight: 7 },
      { item: "flask_void_resist", weight: 5 },
      { item: "helm_gold", weight: 5 },
      { item: "chest_iron", weight: 5 }
    ],
    itemChance: 0.15,
    breaches: [[73, -101], [107, -101], [73, -131], [107, -131], [90, -100.5], [108, -116], [86.5, -131.5]],
    interactables: [
      { id: "waystone_pyre", kind: "waystone", label: "Waystone", x: 73.5, z: -108 },
      // Boss summon at the arena's north edge (content/bosses.ts summonSpot).
      { id: "ember_altar", kind: "boss", label: "The Ember Altar", x: 90, z: -126.35 }
    ],
    ambient: { fog: 1312774, hemiSky: 4858898, hemiGround: 787459, moon: 14191178 }
  },
  // The Catacomb Warren (2026-09-30): a chambered side dungeon off the Hollow Graves. Half-walls divide nine chambers;
  // they break Penitent cones and Ossuary-style line of sight, so the rooms are the fun.
  warren: {
    id: "warren",
    name: "The Catacomb Warren",
    subtitle: "Nine chambers, and something is digging in each",
    theme: "warren",
    rect: { x0: -72, z0: -52, x1: -32, z1: -8 },
    safe: false,
    level: 4,
    enemies: [
      { id: "rat", weight: 30 },
      { id: "robber", weight: 22 },
      { id: "ghoul", weight: 14 },
      { id: "bat", weight: 12 },
      { id: "sac", weight: 10 },
      { id: "hound", weight: 8 },
      { id: "penitent", weight: 4 }
    ],
    cap: 26,
    waveSize: 8,
    waveIntervalMs: 6400,
    eliteChance: 0.045,
    unlock: { area: "graves", kills: 150 },
    loot: [
      ...necroWeaponLoot("warren"),
      { item: "bones_old", weight: 20 },
      { item: "bones_barrow", weight: 12 },
      { item: "ore_tin", weight: 18 },
      { item: "ore_iron", weight: 14 },
      { item: "material_copper_bar", weight: 10 },
      { item: "seed_mourning_moss", weight: 8 },
      { item: "flask_hp_minor", weight: 12 },
      { item: "augment_copper", weight: 5 },
      { item: "plate_copper", weight: 4 },
      { item: "helm_iron", weight: 3 }
    ],
    itemChance: 0.1,
    breaches: [[-65, -45], [-52, -45], [-39, -45], [-65, -30], [-55.5, -30], [-65, -15], [-52, -15], [-39, -15]],
    interactables: [{ id: "waystone_warren", kind: "waystone", label: "Waystone", x: -35.5, z: -27 }],
    ambient: { fog: 789e3, hemiSky: 3813926, hemiGround: 657414, moon: 11049594 }
  },
  // The Bone Coliseum (2026-09-30): a wave-gauntlet pit east of the Ossuary. Four gates, fast surges, elites everywhere,
  // the best drops before the Sanctum: for players who want a fight, not a walk.
  coliseum: {
    id: "coliseum",
    name: "The Bone Coliseum",
    subtitle: "The dead cheer for whoever is still standing",
    theme: "coliseum",
    rect: { x0: 70, z0: -46, x1: 112, z1: -10 },
    safe: false,
    level: 11,
    enemies: [
      { id: "rat", weight: 18 },
      { id: "hound", weight: 16 },
      { id: "robber", weight: 14 },
      { id: "deacon", weight: 10 },
      { id: "bat", weight: 8 },
      { id: "acolyte", weight: 9 },
      { id: "wraith", weight: 8 },
      { id: "gargoyle", weight: 8 },
      { id: "templar", weight: 6 },
      { id: "censer", weight: 5 },
      { id: "seraph", weight: 5 },
      { id: "golem", weight: 3 }
    ],
    cap: 36,
    waveSize: 14,
    waveIntervalMs: 4200,
    eliteChance: 0.16,
    unlock: { area: "ossuary", kills: 350 },
    loot: [
      ...necroWeaponLoot("coliseum"),
      { item: "ore_silver", weight: 18 },
      { item: "ore_gold", weight: 12 },
      { item: "ingot_silver", weight: 6 },
      { item: "flask_hp_major", weight: 12 },
      { item: "flask_damage", weight: 6 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "gem_bone_opal", weight: 3 },
      { item: "augment_iron", weight: 6 },
      { item: "helm_iron", weight: 6 },
      { item: "chest_iron", weight: 5 },
      { item: "kit_iron_warden", weight: 4 }
    ],
    itemChance: 0.17,
    breaches: [[91, -44], [91, -12], [110, -28], [78, -43], [78, -13], [104, -42], [104, -14], [100, -28]],
    interactables: [{ id: "waystone_coliseum", kind: "waystone", label: "Waystone", x: 73.5, z: -20 }],
    ambient: { fog: 1051658, hemiSky: 4864560, hemiGround: 788486, moon: 13678736 }
  },
  // The Mourning Fen (2026-09-30): a drowned graveyard marsh west of the Drowned Nave, level-scaled like the Pyre. Bog water slows
  // whoever wades it (content/fen.ts); the dry hummocks are where you stand. Its seal is earned in the Pyre (800 kills there) but
  // the door is the Nave's west wall: the player has cleared the Nave long before, the Pyre kills are the gate, not the walk.
  fen: {
    id: "fen",
    name: "The Mourning Fen",
    subtitle: "Where the marsh keeps the names it swallows",
    theme: "fen",
    rect: { x0: -60, z0: -100, x1: -22, z1: -60 },
    safe: false,
    level: 45,
    scaling: { minLevel: 45 },
    enemies: [
      { id: "bog_hag", weight: 18 },
      { id: "mire_leech", weight: 16 },
      { id: "fen_wisp", weight: 20 },
      { id: "drowned_sexton", weight: 8 },
      { id: "wraith", weight: 12 }
    ],
    cap: 24,
    waveSize: 9,
    waveIntervalMs: 6200,
    eliteChance: 0.09,
    unlock: { area: "pyre", kills: 800 },
    loot: [
      ...armorLoot("fen"),
      { item: "gem_void_sapphire", weight: 9 },
      { item: "gem_bone_opal", weight: 8 },
      { item: "gem_grave_garnet", weight: 6 },
      { item: "herb_bog_myrtle", weight: 14 },
      { item: "herb_drowned_lotus", weight: 8 },
      { item: "seed_bog_myrtle", weight: 4 },
      { item: "seed_drowned_lotus", weight: 3 },
      { item: "ore_moon", weight: 7 },
      { item: "ingot_hell", weight: 4 },
      { item: "flask_hp_grand", weight: 8 },
      { item: "flask_void_resist", weight: 7 },
      { item: "flask_damage", weight: 6 },
      { item: "elixir_moonlight", weight: 2 },
      { item: "helm_gold", weight: 4 }
    ],
    itemChance: 0.16,
    breaches: [[-58.5, -98.5], [-25.5, -97], [-57, -63], [-28, -63], [-41, -98.5], [-58, -80], [-41, -62]],
    interactables: [
      { id: "waystone_fen", kind: "waystone", label: "Waystone", x: -24.8, z: -85.6 },
      // Boss summon on the arena's north rim (content/bosses.ts summonSpot), on its own hummock.
      { id: "mire_altar", kind: "boss", label: "The Mire Altar", x: -42, z: -90.2 }
    ],
    ambient: { fog: 661016, hemiSky: 2771538, hemiGround: 396302, moon: 8307908, fogMult: 1.7 }
  }
};
var AREA_ORDER = ["chapterhouse", "acre", "graves", "ossuary", "nave", "sanctum", "cloister", "pyre", "warren", "coliseum", "fen"];
var BOSS_SUMMON_SHARDS = 5;

// src/content/ascension.ts
var ASCENSION = {
  /** Prelate kills this run needed before the Altar will take the run. */
  prelateKillsRequired: 1,
  /** Every enemy (and the Prelate) is this many levels older per rank. */
  levelsPerRank: 3,
  /** Gold and XP bonus per rank, on top of what the older enemies already pay. */
  rewardPerRank: 0.05,
  maxRank: 20
};
var BOONS = {
  vigil: { id: "vigil", name: "Vigil of Bone", blurb: "+8% maximum health.", maxRank: 3, cost: [4, 8, 14] },
  marrow_font: { id: "marrow_font", name: "Marrow Font", blurb: "+12% Grave Essence regeneration.", maxRank: 3, cost: [4, 8, 14] },
  bone_tithe: { id: "bone_tithe", name: "Bone Tithe", blurb: "Damage upgrades cost 10% less.", maxRank: 3, cost: [3, 6, 10] },
  quickened_coin: { id: "quickened_coin", name: "Quickened Coin", blurb: "Wave Speed upgrades cost 12% less.", maxRank: 2, cost: [4, 9] },
  first_rites: { id: "first_rites", name: "First Rites", blurb: "Begin each run with 2 Damage tiers already bought.", maxRank: 2, cost: [6, 12] },
  shard_keeper: { id: "shard_keeper", name: "Shard Keeper", blurb: "Begin each run holding 2 soul shards.", maxRank: 2, cost: [5, 10] },
  soul_hunger: { id: "soul_hunger", name: "Soul Hunger", blurb: "Soul Harvest fills 8 souls sooner.", maxRank: 2, cost: [6, 12], requires: 1 },
  swift_seals: { id: "swift_seals", name: "Swift Seals", blurb: "Sealed doors open after 20% fewer kills.", maxRank: 2, cost: [6, 12], requires: 2 },
  legion_pact: { id: "legion_pact", name: "Legion Pact", blurb: "Command one more thrall.", maxRank: 1, cost: [25], requires: 3 }
};
function boonEffects(ranks) {
  const r = (id) => Math.max(0, Math.min(BOONS[id].maxRank, ranks[id] ?? 0));
  return {
    maxHpMult: 1 + 0.08 * r("vigil"),
    essenceRegenMult: 1 + 0.12 * r("marrow_font"),
    damageCostMult: 1 - 0.1 * r("bone_tithe"),
    waveCostMult: 1 - 0.12 * r("quickened_coin"),
    startDamageTier: 2 * r("first_rites"),
    startShards: 2 * r("shard_keeper"),
    soulsDiscount: 8 * r("soul_hunger"),
    unlockKillsMult: 1 - 0.2 * r("swift_seals"),
    extraThralls: r("legion_pact")
  };
}
function ashesForRun(run, rank) {
  if (run.prelateKills < ASCENSION.prelateKillsRequired) return 0;
  const base = 10 + 5 * Math.min(4, run.prelateKills - 1) + 2 * Math.max(0, Math.min(8, run.peakWaveTier)) + Math.min(15, Math.floor(run.kills / 300));
  return Math.round(base * (1 + 0.25 * rank));
}
function boonBlocked(id, ranks, ascension) {
  const def = BOONS[id];
  const owned = ranks[id] ?? 0;
  if (owned >= def.maxRank) return "Mastered";
  if (def.requires && ascension < def.requires) return `Ascension ${roman(def.requires)}`;
  return null;
}
function boonCost(id, ranks) {
  const owned = ranks[id] ?? 0;
  return owned >= BOONS[id].maxRank ? null : BOONS[id].cost[owned];
}
function roman(n) {
  if (n <= 0) return "0";
  const map = [
    [10, "X"],
    [9, "IX"],
    [5, "V"],
    [4, "IV"],
    [1, "I"]
  ];
  let out = "";
  for (const [v, s] of map) while (n >= v) out += s, n -= v;
  return out;
}

// src/content/upgrades.ts
var DAMAGE_UPGRADE = {
  maxTier: 25,
  perTier: 0.08,
  cost: (tier) => Math.round(40 * Math.pow(1.5, tier))
};
var WAVE_UPGRADE = {
  maxTier: 8,
  cost: (tier) => Math.round(120 * Math.pow(1.75, tier))
};

// src/content/fen.ts
var FEN_ARENA = { x: -42, z: -80, r: 12 };

// src/content/bosses.ts
var BOSS_IDS = ["gravedigger", "abbess", "congregation", "prelate", "saint", "regent", "mire"];
var BOSSES = {
  gravedigger: {
    id: "gravedigger",
    name: "The Gravedigger King",
    title: "Lord of the Hollow Graves",
    area: "graves",
    arena: { x: -14, z: -22, r: 10 },
    summonId: "kings_grave",
    summonLabel: "The King's Grave",
    shards: 2,
    baseHp: 15500,
    modelSlug: "boss_gravedigger_king",
    portrait: "art/portraits/boss_gravedigger_king.webp",
    color: 14722136,
    phases: ["He digs", "The graves give up their dead", "Every grave is open"],
    awaken: "The King climbs out of his own grave",
    defeated: ["The King Is Buried", "The Hollow Graves fall quiet, for now"]
  },
  abbess: {
    id: "abbess",
    name: "The Bone Abbess",
    title: "Keeper of the Marrow Ossuary",
    area: "ossuary",
    arena: { x: 48, z: -24, r: 10 },
    summonId: "abbess_reliquary",
    summonLabel: "The Abbess's Reliquary",
    shards: 3,
    baseHp: 13e3,
    modelSlug: "boss_bone_abbess",
    portrait: "art/portraits/boss_bone_abbess.webp",
    color: 13148266,
    phases: ["The niches sing", "The chorus doubles", "The Abbess rebuilds"],
    awaken: "The skull niches begin to sing",
    defeated: ["The Chorus Breaks", "The Abbess returns to her reliquary"]
  },
  congregation: {
    id: "congregation",
    name: "The Drowned Congregation",
    title: "Choir of the Drowned Nave",
    area: "nave",
    arena: { x: 0, z: -61, r: 11 },
    summonId: "drowned_font",
    summonLabel: "The Drowned Font",
    shards: 4,
    baseHp: 19e3,
    modelSlug: "boss_drowned_congregation",
    portrait: "art/portraits/boss_drowned_congregation.webp",
    color: 9417928,
    phases: ["The hymn begins", "The water rises", "The flood hymn"],
    awaken: "The nave water begins to rise",
    defeated: ["The Hymn Ends", "The Congregation sinks back into the black water"]
  },
  saint: {
    id: "saint",
    name: "The Plague Saint",
    title: "Mother of the Blight",
    area: "cloister",
    arena: { x: 44, z: -121, r: 10 },
    summonId: "saints_litter",
    summonLabel: "The Saint's Litter",
    shards: 5,
    baseHp: 24e3,
    modelSlug: "boss_plague_saint",
    portrait: "",
    color: 10273850,
    phases: ["The blight blesses her", "Her flock gathers", "The swarm"],
    awaken: "The Saint rises from her litter",
    defeated: ["The Blight Recedes", "The Plague Saint sinks back into her reliquary"]
  },
  regent: {
    id: "regent",
    name: "The Cinder Regent",
    title: "Ember-Crowned Keeper of the Pyre",
    area: "pyre",
    arena: { x: 90, z: -117, r: 11 },
    summonId: "ember_altar",
    summonLabel: "The Ember Altar",
    shards: 6,
    baseHp: 28e3,
    modelSlug: "boss_cinder_regent",
    portrait: "",
    color: 16742954,
    phases: ["The crown ignites", "The pyre feeds", "The pyre burns down"],
    awaken: "The Regent rises from the embers",
    defeated: ["The Pyre Burns Out", "The Cinder Regent crumbles to ash"]
  },
  mire: {
    id: "mire",
    name: "The Mire Mother",
    title: "Drowned Matriarch of the Mourning Fen",
    area: "fen",
    arena: FEN_ARENA,
    summonId: "mire_altar",
    summonLabel: "The Mire Altar",
    shards: 7,
    baseHp: 32e3,
    modelSlug: "boss_mire_mother",
    portrait: "",
    color: 6276276,
    phases: ["She sinks, and surfaces", "The marsh floods", "The drowned rise"],
    awaken: "The Mire Mother wakes beneath the hummocks",
    defeated: ["The Marsh Goes Still", "The Mire Mother sinks for the last time"]
  },
  prelate: {
    id: "prelate",
    name: "The Bell-Sworn Prelate",
    title: "The Sundered Bell",
    area: "sanctum",
    arena: { x: 0, z: -116, r: 13 },
    summonId: "sundered_bell",
    summonLabel: "The Sundered Bell",
    shards: 5,
    baseHp: 26e3,
    modelSlug: "prelate",
    portrait: "art/portraits/prelate.webp",
    color: 10644479,
    phases: ["The bell is silent", "The procession begins", "The bell is breaking"],
    awaken: "The Sundered Bell tolls for you",
    defeated: ["The Bell Falls Silent", "The Prelate is unmade \u2014 for now"]
  }
};
var isBossId = (v) => typeof v === "string" && BOSS_IDS.includes(v);
function arenaRim(id, angle, frac = 0.85) {
  const a = BOSSES[id].arena;
  return [a.x + Math.sin(angle) * a.r * frac, a.z + Math.cos(angle) * a.r * frac];
}
var ABBESS_NICHE_SPOTS = [0, 1, 2, 3].map((i) => arenaRim("abbess", Math.PI / 4 + i * Math.PI / 2, 0.75));
var GRAVEDIGGER_PITS = [0, 1, 2, 3].map((i) => arenaRim("gravedigger", Math.PI / 4 + i * Math.PI / 2, 0.55));

// src/gameplay/necroRules.ts
var NECRO_LIMITS = {
  killsPerSave: 900,
  shardsPerSave: 30,
  // One-time import of a browser save (browser storage is editable, so it is clamped hard).
  importMaxShards: 40,
  importMaxAreaKills: 2e4,
  importMaxBossKills: 200,
  importMaxAscension: 5,
  importMaxAshes: 400
};
var clampInt = (v, lo, hi) => {
  const n = Math.floor(Number(v));
  return Number.isFinite(n) ? Math.max(lo, Math.min(hi, n)) : lo;
};
function blankState() {
  return {
    damageTier: 0,
    waveTierOwned: 0,
    waveTierActive: 0,
    soulShards: 0,
    areaKills: {},
    unlockedAreas: ["chapterhouse", "graves"],
    bossKills: 0,
    totalKills: 0,
    ascension: 0,
    ashes: 0,
    boons: {},
    run: { prelateKills: 0, peakWaveTier: 0, kills: 0 },
    summonsPending: 0,
    migrated: false
  };
}
var copy = (s) => ({
  ...s,
  areaKills: { ...s.areaKills },
  unlockedAreas: [...s.unlockedAreas],
  boons: { ...s.boons },
  run: { ...s.run }
});
function damageCost(s) {
  if (s.damageTier >= DAMAGE_UPGRADE.maxTier) return null;
  return Math.round(DAMAGE_UPGRADE.cost(s.damageTier) * boonEffects(s.boons).damageCostMult);
}
function waveCost(s) {
  if (s.waveTierOwned >= WAVE_UPGRADE.maxTier) return null;
  return Math.round(WAVE_UPGRADE.cost(s.waveTierOwned) * boonEffects(s.boons).waveCostMult);
}
function unlockKills(s, id) {
  const u = AREAS[id].unlock;
  return u ? Math.max(1, Math.round(u.kills * boonEffects(s.boons).unlockKillsMult)) : null;
}
var isOpen = (s, id, opts) => !!opts?.staff || s.unlockedAreas.includes(id);
function openSeals(s) {
  for (const id of AREA_ORDER) {
    const u = AREAS[id].unlock;
    if (!u || s.unlockedAreas.includes(id)) continue;
    if ((s.areaKills[u.area] ?? 0) >= unlockKills(s, id) && s.unlockedAreas.includes(u.area)) s.unlockedAreas.push(id);
  }
}
function applySave(state, input, opts) {
  const s = copy(state);
  let budget = NECRO_LIMITS.killsPerSave;
  let kills = 0;
  for (const id of AREA_ORDER) {
    const n = Math.min(budget, clampInt(input.areaKills?.[id], 0, budget));
    if (!n || AREAS[id].safe || !isOpen(s, id, opts)) continue;
    s.areaKills[id] = (s.areaKills[id] ?? 0) + n;
    budget -= n;
    kills += n;
  }
  s.totalKills += kills;
  s.run.kills += kills;
  s.soulShards += clampInt(input.shards, 0, NECRO_LIMITS.shardsPerSave);
  const prelate = Math.min(clampInt(input.prelateKills, 0, 10), s.summonsPending);
  s.summonsPending -= prelate;
  s.bossKills += prelate;
  s.run.prelateKills += prelate;
  if (kills > 0) s.run.peakWaveTier = Math.max(s.run.peakWaveTier, clampInt(input.peakWaveTier, 0, s.waveTierOwned));
  if (input.waveTierActive !== void 0) s.waveTierActive = clampInt(input.waveTierActive, 0, s.waveTierOwned);
  openSeals(s);
  return { ok: true, state: s };
}
function purchase(state, gold, upgrade) {
  const s = copy(state);
  const cost = upgrade === "damage" ? damageCost(s) : upgrade === "wave" ? waveCost(s) : null;
  if (upgrade !== "damage" && upgrade !== "wave") return { ok: false, error: "Unknown upgrade" };
  if (cost === null) return { ok: false, error: "Already at max tier" };
  if (gold < cost) return { ok: false, error: `Not enough gold (need ${cost})` };
  if (upgrade === "damage") s.damageTier++;
  else {
    s.waveTierOwned++;
    s.waveTierActive = s.waveTierOwned;
  }
  return { ok: true, state: s, gold: gold - cost, cost };
}
function summonPrelate(state, opts) {
  if (state.soulShards < BOSS_SUMMON_SHARDS) {
    return { ok: false, error: `The Sundered Bell demands ${BOSS_SUMMON_SHARDS} soul shards (you have ${state.soulShards}).` };
  }
  if (!isOpen(state, "sanctum", opts)) return { ok: false, error: "The Bell Sanctum is still sealed." };
  const s = copy(state);
  s.soulShards -= BOSS_SUMMON_SHARDS;
  s.summonsPending = Math.min(5, s.summonsPending + 1);
  return { ok: true, state: s };
}
function summonAreaBoss(state, boss, opts) {
  if (!isBossId(boss) || boss === "prelate") return { ok: false, error: "Unknown boss." };
  const def = BOSSES[boss];
  if (state.soulShards < def.shards) {
    return { ok: false, error: `${def.summonLabel} demands ${def.shards} soul shards (you have ${state.soulShards}).` };
  }
  if (!isOpen(state, def.area, opts)) return { ok: false, error: `${AREAS[def.area].name} is still sealed.` };
  const s = copy(state);
  s.soulShards -= def.shards;
  return { ok: true, state: s };
}
function ashesOnAscend(state) {
  return state.ascension >= ASCENSION.maxRank ? 0 : ashesForRun(state.run, state.ascension);
}
function ascend(state) {
  const earned = ashesOnAscend(state);
  if (!earned) return { ok: false, error: "Slay the Prelate this run before you Ascend." };
  const s = copy(state);
  const fx = boonEffects(s.boons);
  s.ascension += 1;
  s.ashes += earned;
  s.damageTier = fx.startDamageTier;
  s.waveTierOwned = 0;
  s.waveTierActive = 0;
  s.soulShards = fx.startShards;
  s.areaKills = {};
  s.unlockedAreas = ["chapterhouse", "graves"];
  s.run = { prelateKills: 0, peakWaveTier: 0, kills: 0 };
  s.summonsPending = 0;
  return { ok: true, state: s, earned };
}
function buyBoon(state, id) {
  if (!(id in BOONS)) return { ok: false, error: "Unknown boon" };
  const blocked = boonBlocked(id, state.boons, state.ascension);
  if (blocked) return { ok: false, error: blocked === "Mastered" ? "That boon is already mastered." : `Requires ${blocked}.` };
  const cost = boonCost(id, state.boons);
  if (state.ashes < cost) return { ok: false, error: `Not enough Ashes (need ${cost})` };
  const s = copy(state);
  s.ashes -= cost;
  s.boons[id] = (s.boons[id] ?? 0) + 1;
  if (id === "first_rites") s.damageTier = Math.max(s.damageTier, boonEffects(s.boons).startDamageTier);
  return { ok: true, state: s, cost };
}
function importLocal(state, raw) {
  if (state.migrated) return { ok: false, error: "Progress was already imported." };
  const r = raw && typeof raw === "object" ? raw : {};
  const L = NECRO_LIMITS;
  const s = blankState();
  s.migrated = true;
  s.ascension = clampInt(r.ascension, 0, L.importMaxAscension);
  s.ashes = clampInt(r.ashes, 0, L.importMaxAshes);
  const boons = r.boons && typeof r.boons === "object" ? r.boons : {};
  for (const id of Object.keys(BOONS)) {
    const want = clampInt(boons[id], 0, BOONS[id].maxRank);
    for (let i = 0; i < want && !boonBlocked(id, s.boons, s.ascension); i++) s.boons[id] = (s.boons[id] ?? 0) + 1;
  }
  s.damageTier = clampInt(r.damageTier, 0, DAMAGE_UPGRADE.maxTier);
  s.waveTierOwned = clampInt(r.waveTierOwned, 0, WAVE_UPGRADE.maxTier);
  s.waveTierActive = clampInt(r.waveTierActive, 0, s.waveTierOwned);
  s.soulShards = clampInt(r.shards ?? r.soulShards, 0, L.importMaxShards);
  const kills = r.areaKills && typeof r.areaKills === "object" ? r.areaKills : {};
  for (const id of AREA_ORDER) {
    const n = clampInt(kills[id], 0, L.importMaxAreaKills);
    if (n && !AREAS[id].safe) s.areaKills[id] = n;
  }
  s.bossKills = clampInt(r.bossKills, 0, L.importMaxBossKills);
  s.totalKills = Math.max(
    clampInt(r.totalKills, 0, L.importMaxAreaKills * AREA_ORDER.length),
    Object.values(s.areaKills).reduce((a, b) => a + (b ?? 0), 0)
  );
  const run = r.run && typeof r.run === "object" ? r.run : {};
  s.run = {
    prelateKills: clampInt(run.prelateKills, 0, s.bossKills),
    peakWaveTier: clampInt(run.peakWaveTier, 0, s.waveTierOwned),
    kills: clampInt(run.kills, 0, s.totalKills)
  };
  openSeals(s);
  return { ok: true, state: s };
}
function normalise(raw) {
  const b = blankState();
  const r = raw && typeof raw === "object" ? raw : {};
  return {
    ...b,
    ...r,
    areaKills: { ...r.areaKills ?? {} },
    unlockedAreas: Array.isArray(r.unlockedAreas) && r.unlockedAreas.length ? [...r.unlockedAreas] : b.unlockedAreas,
    boons: { ...r.boons ?? {} },
    run: { ...b.run, ...r.run ?? {} }
  };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  NECRO_LIMITS,
  applySave,
  ascend,
  ashesOnAscend,
  blankState,
  buyBoon,
  damageCost,
  importLocal,
  normalise,
  purchase,
  summonAreaBoss,
  summonPrelate,
  unlockKills,
  waveCost
});
