// GENERATED by tools/build-server-rules.mjs from src/gameplay/necroRules.ts — do not edit by hand.
// Necromancer progression rules shared by the web client and the auth server.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/gameplay/necroRules.ts
var necroRules_exports = {};
__export(necroRules_exports, {
  NECRO_LIMITS: () => NECRO_LIMITS,
  applySave: () => applySave,
  ascend: () => ascend,
  ashesOnAscend: () => ashesOnAscend,
  blankState: () => blankState,
  buyBoon: () => buyBoon,
  damageCost: () => damageCost,
  importLocal: () => importLocal,
  normalise: () => normalise,
  purchase: () => purchase,
  summonPrelate: () => summonPrelate,
  unlockKills: () => unlockKills,
  waveCost: () => waveCost
});
module.exports = __toCommonJS(necroRules_exports);

// src/content/areas.ts
var AREAS = {
  chapterhouse: {
    id: "chapterhouse",
    name: "The Chapterhouse",
    subtitle: "Sanctuary of the Ossuary Covenant",
    theme: "chapter",
    rect: { x0: -13, z0: 8, x1: 13, z1: 32 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "reliquary", kind: "inventory", label: "Reliquary", x: -8.5, z: 14 },
      { id: "workbench", kind: "forge", label: "Ossuary Workbench", x: 8.5, z: 14 },
      { id: "niches", kind: "professions", label: "Rite Niches", x: -10.8, z: 26.5 },
      { id: "altar", kind: "upgrades", label: "Altar of Ascension", x: 0, z: 21 },
      { id: "waystone_chapterhouse", kind: "waystone", label: "Waystone", x: 9, z: 26.5 }
    ],
    ambient: { fog: 722960, hemiSky: 3877458, hemiGround: 657168, moon: 9412305 }
  },
  // The non-combat gathering zone: every tier of every gathering node, no waves (roadmap §6).
  acre: {
    id: "acre",
    name: "The Sexton's Acre",
    subtitle: "Where the Covenant's dead are tended",
    theme: "acre",
    rect: { x0: -62, z0: 6, x1: -20, z1: 38 },
    safe: true,
    level: 1,
    enemies: [],
    cap: 0,
    waveSize: 0,
    waveIntervalMs: 0,
    eliteChance: 0,
    loot: [],
    itemChance: 0,
    breaches: [],
    interactables: [
      { id: "waystone_acre", kind: "waystone", label: "Waystone", x: -23, z: 25.5 },
      { id: "sawpit", kind: "sawpit", label: "Sawpit", x: -23.5, z: 12.5 },
      { id: "bone_kiln", kind: "kiln", label: "Bone Kiln", x: -23.5, z: 31.6 },
      { id: "cooking_fire", kind: "fire", label: "Cooking Fire", x: -26.5, z: 28.5 },
      { id: "lectern", kind: "lectern", label: "Covenant Lectern", x: -24.2, z: 17.8 }
    ],
    ambient: { fog: 790288, hemiSky: 4937828, hemiGround: 2304032, moon: 12307416 }
  },
  graves: {
    id: "graves",
    name: "The Hollow Graves",
    subtitle: "Where the Covenant buries what it cannot keep",
    theme: "graveyard",
    rect: { x0: -26, z0: -36, x1: 26, z1: 4 },
    safe: false,
    level: 1,
    enemies: [
      { id: "robber", weight: 58 },
      { id: "hound", weight: 24 },
      { id: "penitent", weight: 11 },
      { id: "sac", weight: 7 }
    ],
    cap: 28,
    waveSize: 9,
    waveIntervalMs: 6500,
    eliteChance: 0.035,
    loot: [
      { item: "material_copper_shard", weight: 30 },
      { item: "ore_copper", weight: 24 },
      { item: "ore_tin", weight: 14 },
      { item: "flask_hp_minor", weight: 12 },
      { item: "log_oak", weight: 8 },
      { item: "ring_copper", weight: 4 },
      { item: "helm_copper", weight: 4 },
      { item: "staff_oak", weight: 3 }
    ],
    itemChance: 0.08,
    breaches: [
      [-18, -29],
      [0, -31],
      [18, -29],
      [-21, -13],
      [21, -11],
      [9, -19],
      [-9, -21],
      [20, -24],
      [-14, -3],
      [14, -4]
    ],
    interactables: [{ id: "waystone_graves", kind: "waystone", label: "Waystone", x: -5.5, z: 1 }],
    ambient: { fog: 854548, hemiSky: 3812693, hemiGround: 722960, moon: 10135252 }
  },
  ossuary: {
    id: "ossuary",
    name: "The Marrow Ossuary",
    subtitle: "Ten thousand skulls, and all of them listening",
    theme: "ossuary",
    rect: { x0: 32, z0: -38, x1: 64, z1: -2 },
    safe: false,
    level: 5,
    enemies: [
      { id: "robber", weight: 30 },
      { id: "hound", weight: 30 },
      { id: "sac", weight: 18 },
      { id: "deacon", weight: 12 },
      { id: "penitent", weight: 10 },
      { id: "rat", weight: 10 },
      { id: "golem", weight: 2 }
    ],
    cap: 32,
    waveSize: 10,
    waveIntervalMs: 6200,
    eliteChance: 0.045,
    unlock: { area: "graves", kills: 300 },
    loot: [
      { item: "ore_iron", weight: 24 },
      { item: "ore_copper", weight: 14 },
      { item: "material_copper_bar", weight: 14 },
      { item: "ore_bronze", weight: 10 },
      { item: "flask_hp_minor", weight: 10 },
      { item: "augment_copper", weight: 5 },
      { item: "sword_copper", weight: 4 },
      { item: "plate_copper", weight: 4 },
      { item: "helm_iron", weight: 3 }
    ],
    itemChance: 0.09,
    breaches: [[38, -33], [50, -35], [60, -27], [60, -9], [46, -6], [39, -18], [54, -19], [44, -27]],
    interactables: [{ id: "waystone_ossuary", kind: "waystone", label: "Waystone", x: 35.5, z: -6 }],
    ambient: { fog: 920332, hemiSky: 4207434, hemiGround: 854281, moon: 12036494 }
  },
  nave: {
    id: "nave",
    name: "The Drowned Nave",
    subtitle: "The congregation never stopped kneeling",
    theme: "nave",
    rect: { x0: -15, z0: -96, x1: 15, z1: -44 },
    safe: false,
    level: 9,
    enemies: [
      { id: "penitent", weight: 23 },
      { id: "robber", weight: 27 },
      { id: "deacon", weight: 15 },
      { id: "sac", weight: 16 },
      { id: "hound", weight: 19 },
      { id: "wraith", weight: 12 },
      { id: "censer", weight: 6 }
    ],
    cap: 34,
    waveSize: 11,
    waveIntervalMs: 6e3,
    eliteChance: 0.055,
    unlock: { area: "ossuary", kills: 420 },
    loot: [
      { item: "ore_silver", weight: 20 },
      { item: "ore_iron", weight: 20 },
      { item: "ore_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "augment_iron", weight: 5 },
      { item: "helm_iron", weight: 6 },
      { item: "chest_iron", weight: 4 }
    ],
    itemChance: 0.1,
    breaches: [[-11, -91], [11, -91], [-11, -72], [11, -72], [-11, -53], [11, -53], [0, -82], [0, -62]],
    interactables: [{ id: "waystone_nave", kind: "waystone", label: "Waystone", x: 6, z: -47.5 }],
    ambient: { fog: 723220, hemiSky: 3352666, hemiGround: 525839, moon: 9406168 }
  },
  sanctum: {
    id: "sanctum",
    name: "The Bell Sanctum",
    subtitle: "Seat of the Bell-Sworn Prelate",
    theme: "sanctum",
    rect: { x0: -18, z0: -130, x1: 18, z1: -102 },
    safe: false,
    level: 13,
    enemies: [
      { id: "penitent", weight: 30 },
      { id: "deacon", weight: 20 },
      { id: "robber", weight: 20 },
      { id: "hound", weight: 20 },
      { id: "sac", weight: 10 },
      { id: "censer", weight: 10 },
      { id: "wraith", weight: 10 },
      { id: "golem", weight: 4 }
    ],
    cap: 26,
    waveSize: 8,
    waveIntervalMs: 6500,
    eliteChance: 0.07,
    unlock: { area: "nave", kills: 520 },
    loot: [
      { item: "ore_gold", weight: 18 },
      { item: "ore_steel", weight: 14 },
      { item: "ingot_gold", weight: 8 },
      { item: "flask_hp_major", weight: 10 },
      { item: "chest_iron", weight: 7 },
      { item: "helm_gold", weight: 5 },
      { item: "kit_iron_warden", weight: 5 }
    ],
    itemChance: 0.12,
    breaches: [[-14, -126], [14, -126], [-15, -109], [15, -109]],
    interactables: [
      { id: "waystone_sanctum", kind: "waystone", label: "Waystone", x: 6, z: -105 },
      { id: "sundered_bell", kind: "boss", label: "The Sundered Bell", x: 0, z: -123.4 }
    ],
    ambient: { fog: 1050644, hemiSky: 4006738, hemiGround: 787980, moon: 10848984 }
  }
};
var AREA_ORDER = ["chapterhouse", "acre", "graves", "ossuary", "nave", "sanctum"];
var BOSS_SUMMON_SHARDS = 5;

// src/content/ascension.ts
var ASCENSION = {
  /** Prelate kills this run needed before the Altar will take the run. */
  prelateKillsRequired: 1,
  /** Every enemy (and the Prelate) is this many levels older per rank. */
  levelsPerRank: 3,
  /** Gold and XP bonus per rank, on top of what the older enemies already pay. */
  rewardPerRank: 0.05,
  maxRank: 20
};
var BOONS = {
  vigil: { id: "vigil", name: "Vigil of Bone", blurb: "+8% maximum health.", maxRank: 3, cost: [4, 8, 14] },
  marrow_font: { id: "marrow_font", name: "Marrow Font", blurb: "+12% Grave Essence regeneration.", maxRank: 3, cost: [4, 8, 14] },
  bone_tithe: { id: "bone_tithe", name: "Bone Tithe", blurb: "Damage upgrades cost 10% less.", maxRank: 3, cost: [3, 6, 10] },
  quickened_coin: { id: "quickened_coin", name: "Quickened Coin", blurb: "Wave Speed upgrades cost 12% less.", maxRank: 2, cost: [4, 9] },
  first_rites: { id: "first_rites", name: "First Rites", blurb: "Begin each run with 2 Damage tiers already bought.", maxRank: 2, cost: [6, 12] },
  shard_keeper: { id: "shard_keeper", name: "Shard Keeper", blurb: "Begin each run holding 2 soul shards.", maxRank: 2, cost: [5, 10] },
  soul_hunger: { id: "soul_hunger", name: "Soul Hunger", blurb: "Soul Harvest fills 8 souls sooner.", maxRank: 2, cost: [6, 12], requires: 1 },
  swift_seals: { id: "swift_seals", name: "Swift Seals", blurb: "Sealed doors open after 20% fewer kills.", maxRank: 2, cost: [6, 12], requires: 2 },
  legion_pact: { id: "legion_pact", name: "Legion Pact", blurb: "Command one more thrall.", maxRank: 1, cost: [25], requires: 3 }
};
function boonEffects(ranks) {
  const r = (id) => Math.max(0, Math.min(BOONS[id].maxRank, ranks[id] ?? 0));
  return {
    maxHpMult: 1 + 0.08 * r("vigil"),
    essenceRegenMult: 1 + 0.12 * r("marrow_font"),
    damageCostMult: 1 - 0.1 * r("bone_tithe"),
    waveCostMult: 1 - 0.12 * r("quickened_coin"),
    startDamageTier: 2 * r("first_rites"),
    startShards: 2 * r("shard_keeper"),
    soulsDiscount: 8 * r("soul_hunger"),
    unlockKillsMult: 1 - 0.2 * r("swift_seals"),
    extraThralls: r("legion_pact")
  };
}
function ashesForRun(run, rank) {
  if (run.prelateKills < ASCENSION.prelateKillsRequired) return 0;
  const base = 10 + 5 * Math.min(4, run.prelateKills - 1) + 2 * Math.max(0, Math.min(8, run.peakWaveTier)) + Math.min(15, Math.floor(run.kills / 300));
  return Math.round(base * (1 + 0.25 * rank));
}
function boonBlocked(id, ranks, ascension) {
  const def = BOONS[id];
  const owned = ranks[id] ?? 0;
  if (owned >= def.maxRank) return "Mastered";
  if (def.requires && ascension < def.requires) return `Ascension ${roman(def.requires)}`;
  return null;
}
function boonCost(id, ranks) {
  const owned = ranks[id] ?? 0;
  return owned >= BOONS[id].maxRank ? null : BOONS[id].cost[owned];
}
function roman(n) {
  if (n <= 0) return "0";
  const map = [
    [10, "X"],
    [9, "IX"],
    [5, "V"],
    [4, "IV"],
    [1, "I"]
  ];
  let out = "";
  for (const [v, s] of map) while (n >= v) out += s, n -= v;
  return out;
}

// src/content/upgrades.ts
var DAMAGE_UPGRADE = {
  maxTier: 25,
  perTier: 0.08,
  cost: (tier) => Math.round(40 * Math.pow(1.5, tier))
};
var WAVE_UPGRADE = {
  maxTier: 8,
  cost: (tier) => Math.round(120 * Math.pow(1.75, tier))
};

// src/gameplay/necroRules.ts
var NECRO_LIMITS = {
  killsPerSave: 900,
  shardsPerSave: 30,
  // One-time import of a browser save (browser storage is editable, so it is clamped hard).
  importMaxShards: 40,
  importMaxAreaKills: 2e4,
  importMaxBossKills: 200,
  importMaxAscension: 5,
  importMaxAshes: 400
};
var clampInt = (v, lo, hi) => {
  const n = Math.floor(Number(v));
  return Number.isFinite(n) ? Math.max(lo, Math.min(hi, n)) : lo;
};
function blankState() {
  return {
    damageTier: 0,
    waveTierOwned: 0,
    waveTierActive: 0,
    soulShards: 0,
    areaKills: {},
    unlockedAreas: ["chapterhouse", "graves"],
    bossKills: 0,
    totalKills: 0,
    ascension: 0,
    ashes: 0,
    boons: {},
    run: { prelateKills: 0, peakWaveTier: 0, kills: 0 },
    summonsPending: 0,
    migrated: false
  };
}
var copy = (s) => ({
  ...s,
  areaKills: { ...s.areaKills },
  unlockedAreas: [...s.unlockedAreas],
  boons: { ...s.boons },
  run: { ...s.run }
});
function damageCost(s) {
  if (s.damageTier >= DAMAGE_UPGRADE.maxTier) return null;
  return Math.round(DAMAGE_UPGRADE.cost(s.damageTier) * boonEffects(s.boons).damageCostMult);
}
function waveCost(s) {
  if (s.waveTierOwned >= WAVE_UPGRADE.maxTier) return null;
  return Math.round(WAVE_UPGRADE.cost(s.waveTierOwned) * boonEffects(s.boons).waveCostMult);
}
function unlockKills(s, id) {
  const u = AREAS[id].unlock;
  return u ? Math.max(1, Math.round(u.kills * boonEffects(s.boons).unlockKillsMult)) : null;
}
function openSeals(s) {
  for (const id of AREA_ORDER) {
    const u = AREAS[id].unlock;
    if (!u || s.unlockedAreas.includes(id)) continue;
    if ((s.areaKills[u.area] ?? 0) >= unlockKills(s, id) && s.unlockedAreas.includes(u.area)) s.unlockedAreas.push(id);
  }
}
function applySave(state, input) {
  const s = copy(state);
  let budget = NECRO_LIMITS.killsPerSave;
  let kills = 0;
  for (const id of AREA_ORDER) {
    const n = Math.min(budget, clampInt(input.areaKills?.[id], 0, budget));
    if (!n || AREAS[id].safe || !s.unlockedAreas.includes(id)) continue;
    s.areaKills[id] = (s.areaKills[id] ?? 0) + n;
    budget -= n;
    kills += n;
  }
  s.totalKills += kills;
  s.run.kills += kills;
  s.soulShards += clampInt(input.shards, 0, NECRO_LIMITS.shardsPerSave);
  const prelate = Math.min(clampInt(input.prelateKills, 0, 10), s.summonsPending);
  s.summonsPending -= prelate;
  s.bossKills += prelate;
  s.run.prelateKills += prelate;
  if (kills > 0) s.run.peakWaveTier = Math.max(s.run.peakWaveTier, clampInt(input.peakWaveTier, 0, s.waveTierOwned));
  if (input.waveTierActive !== void 0) s.waveTierActive = clampInt(input.waveTierActive, 0, s.waveTierOwned);
  openSeals(s);
  return { ok: true, state: s };
}
function purchase(state, gold, upgrade) {
  const s = copy(state);
  const cost = upgrade === "damage" ? damageCost(s) : upgrade === "wave" ? waveCost(s) : null;
  if (upgrade !== "damage" && upgrade !== "wave") return { ok: false, error: "Unknown upgrade" };
  if (cost === null) return { ok: false, error: "Already at max tier" };
  if (gold < cost) return { ok: false, error: `Not enough gold (need ${cost})` };
  if (upgrade === "damage") s.damageTier++;
  else {
    s.waveTierOwned++;
    s.waveTierActive = s.waveTierOwned;
  }
  return { ok: true, state: s, gold: gold - cost, cost };
}
function summonPrelate(state) {
  if (state.soulShards < BOSS_SUMMON_SHARDS) {
    return { ok: false, error: `The Sundered Bell demands ${BOSS_SUMMON_SHARDS} soul shards (you have ${state.soulShards}).` };
  }
  if (!state.unlockedAreas.includes("sanctum")) return { ok: false, error: "The Bell Sanctum is still sealed." };
  const s = copy(state);
  s.soulShards -= BOSS_SUMMON_SHARDS;
  s.summonsPending = Math.min(5, s.summonsPending + 1);
  return { ok: true, state: s };
}
function ashesOnAscend(state) {
  return state.ascension >= ASCENSION.maxRank ? 0 : ashesForRun(state.run, state.ascension);
}
function ascend(state) {
  const earned = ashesOnAscend(state);
  if (!earned) return { ok: false, error: "Slay the Prelate this run before you Ascend." };
  const s = copy(state);
  const fx = boonEffects(s.boons);
  s.ascension += 1;
  s.ashes += earned;
  s.damageTier = fx.startDamageTier;
  s.waveTierOwned = 0;
  s.waveTierActive = 0;
  s.soulShards = fx.startShards;
  s.areaKills = {};
  s.unlockedAreas = ["chapterhouse", "graves"];
  s.run = { prelateKills: 0, peakWaveTier: 0, kills: 0 };
  s.summonsPending = 0;
  return { ok: true, state: s, earned };
}
function buyBoon(state, id) {
  if (!(id in BOONS)) return { ok: false, error: "Unknown boon" };
  const blocked = boonBlocked(id, state.boons, state.ascension);
  if (blocked) return { ok: false, error: blocked === "Mastered" ? "That boon is already mastered." : `Requires ${blocked}.` };
  const cost = boonCost(id, state.boons);
  if (state.ashes < cost) return { ok: false, error: `Not enough Ashes (need ${cost})` };
  const s = copy(state);
  s.ashes -= cost;
  s.boons[id] = (s.boons[id] ?? 0) + 1;
  if (id === "first_rites") s.damageTier = Math.max(s.damageTier, boonEffects(s.boons).startDamageTier);
  return { ok: true, state: s, cost };
}
function importLocal(state, raw) {
  if (state.migrated) return { ok: false, error: "Progress was already imported." };
  const r = raw && typeof raw === "object" ? raw : {};
  const L = NECRO_LIMITS;
  const s = blankState();
  s.migrated = true;
  s.ascension = clampInt(r.ascension, 0, L.importMaxAscension);
  s.ashes = clampInt(r.ashes, 0, L.importMaxAshes);
  const boons = r.boons && typeof r.boons === "object" ? r.boons : {};
  for (const id of Object.keys(BOONS)) {
    const want = clampInt(boons[id], 0, BOONS[id].maxRank);
    for (let i = 0; i < want && !boonBlocked(id, s.boons, s.ascension); i++) s.boons[id] = (s.boons[id] ?? 0) + 1;
  }
  s.damageTier = clampInt(r.damageTier, 0, DAMAGE_UPGRADE.maxTier);
  s.waveTierOwned = clampInt(r.waveTierOwned, 0, WAVE_UPGRADE.maxTier);
  s.waveTierActive = clampInt(r.waveTierActive, 0, s.waveTierOwned);
  s.soulShards = clampInt(r.shards ?? r.soulShards, 0, L.importMaxShards);
  const kills = r.areaKills && typeof r.areaKills === "object" ? r.areaKills : {};
  for (const id of AREA_ORDER) {
    const n = clampInt(kills[id], 0, L.importMaxAreaKills);
    if (n && !AREAS[id].safe) s.areaKills[id] = n;
  }
  s.bossKills = clampInt(r.bossKills, 0, L.importMaxBossKills);
  s.totalKills = Math.max(
    clampInt(r.totalKills, 0, L.importMaxAreaKills * AREA_ORDER.length),
    Object.values(s.areaKills).reduce((a, b) => a + (b ?? 0), 0)
  );
  const run = r.run && typeof r.run === "object" ? r.run : {};
  s.run = {
    prelateKills: clampInt(run.prelateKills, 0, s.bossKills),
    peakWaveTier: clampInt(run.peakWaveTier, 0, s.waveTierOwned),
    kills: clampInt(run.kills, 0, s.totalKills)
  };
  openSeals(s);
  return { ok: true, state: s };
}
function normalise(raw) {
  const b = blankState();
  const r = raw && typeof raw === "object" ? raw : {};
  return {
    ...b,
    ...r,
    areaKills: { ...r.areaKills ?? {} },
    unlockedAreas: Array.isArray(r.unlockedAreas) && r.unlockedAreas.length ? [...r.unlockedAreas] : b.unlockedAreas,
    boons: { ...r.boons ?? {} },
    run: { ...b.run, ...r.run ?? {} }
  };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  NECRO_LIMITS,
  applySave,
  ascend,
  ashesOnAscend,
  blankState,
  buyBoon,
  damageCost,
  importLocal,
  normalise,
  purchase,
  summonPrelate,
  unlockKills,
  waveCost
});
