import type { Rarity } from '../net/types';
import type { RecipeRow } from './processing';

/**
 * Alchemy (docs/PROFESSIONS-ROADMAP.md §3): herbs from Grave Gardening (and bone meal from the Kiln) become flasks and elixirs at
 * the Workbench. One source for the client catalogue (content/items.ts registers ALCHEMY_ITEMS and the effect tables), the offline
 * mock and the server migration (009-alchemy.sql is generated by `node tools/build-alchemy-sql.mjs`), so the three can't drift.
 * The flasks that already exist (minor/major healing, swiftness, forge-tempered, void resist) keep their ids and effects; alchemy is
 * the herb road to them, plus two new top-tier potions.
 */

export interface AlchemyItem {
  name: string;
  rarity: Rarity;
  sell: number;
  lore: string;
  stack: number;
  /** The server `stat_bonus` row (the Unity game's shape; the web client reads the effect tables below). */
  stat: Record<string, unknown>;
}

export const ALCHEMY_ITEMS: Record<string, AlchemyItem> = {
  flask_hp_grand: {
    name: 'Grand Healing Flask',
    rarity: 'rare',
    sell: 45,
    lore: 'Bloodroot and corpse-lily, brewed until the glass runs warm. Restores 90% health. Press Q.',
    stack: 99,
    stat: { value: 150, effect: 'hp_regen', duration: 60 },
  },
  elixir_moonlight: {
    name: 'Moonlight Elixir',
    rarity: 'epic',
    sell: 120,
    lore: '+25% spell damage for 60 seconds. It glows faintly, and the dead lean toward it.',
    stack: 99,
    stat: { value: 0.25, effect: 'damage_amp', duration: 60 },
  },
};

/** Heal fractions for the new healing flask (merged into HEALING_FLASKS). */
export const ALCHEMY_HEALING: Record<string, number> = { flask_hp_grand: 0.9 };
/** The new buff (merged into BUFF_FLASKS). */
export const ALCHEMY_BUFFS: Record<string, { kind: 'speed' | 'damage' | 'ward'; value: number; seconds: number; label: string }> = {
  elixir_moonlight: { kind: 'damage', value: 0.25, seconds: 60, label: 'Moonlit' },
};

/** [id, name, profession, level, result, quantity, ingredients]: the same shape as the processing recipes. */
export const ALCHEMY_RECIPES: RecipeRow[] = [
  ['brew_moss_tonic', 'Brew Moss Tonic', 'alchemy', 1, 'flask_hp_minor', 3, [['herb_mourning_moss', 3]]],
  ['brew_nightshade_draught', 'Brew Nightshade Draught', 'alchemy', 12, 'flask_hp_major', 2, [['herb_nightshade', 3], ['bone_meal', 1]]],
  ['brew_swift_tincture', 'Brew Swift Tincture', 'alchemy', 18, 'flask_speed', 2, [['herb_nightshade', 2], ['herb_mourning_moss', 2]]],
  ['brew_lily_tempering', 'Brew Lily Tempering', 'alchemy', 32, 'flask_damage', 2, [['herb_corpse_lily', 3], ['bone_meal', 2]]],
  ['brew_wolfsbane_ward', 'Brew Wolfsbane Ward', 'alchemy', 45, 'flask_void_resist', 2, [['herb_wolfsbane', 3]]],
  ['brew_bloodroot_grand', 'Brew Grand Healing Flask', 'alchemy', 58, 'flask_hp_grand', 2, [['herb_bloodroot', 3], ['herb_corpse_lily', 1]]],
  ['brew_moonpetal_elixir', 'Brew Moonlight Elixir', 'alchemy', 72, 'elixir_moonlight', 1, [['herb_moonpetal', 3], ['herb_bloodroot', 1]]],
];
