import type { Rarity } from '../../../src/net/types';
import type { SkillId } from '../gameplay/gatheringRules';

/**
 * Capes and pets (docs/PROFESSIONS-ROADMAP.md §13, G7): cosmetic rewards for skilling. One source for the client catalogue, the shared
 * rules (gameplay/cosmeticRules.ts) and the server migration (010-cosmetics.sql is generated by `node tools/build-cosmetics-sql.mjs`).
 *
 *  - Capes are unlocked by levels: a mastery cape at 99 in each skill, and mantles for total level. You choose what to wear.
 *  - Pets are rare finds while working (a "charm" item). Adopt a charm and the companion is yours for good.
 */

export interface CapeDef {
  id: string;
  name: string;
  lore: string;
  /** Cloth and trim colours (0xRRGGBB). */
  color: number;
  trim: number;
  /** Unlock: level 99 in this skill, or a total level across every skill. */
  skill?: SkillId;
  total?: number;
}

export const CAPES: CapeDef[] = [
  { id: 'cape_apprentice', name: 'Apprentice’s Mantle', lore: 'A plain grey mantle, sewn by someone who believed in you.', color: 0x6d6a63, trim: 0xb9b2a4, total: 100 },
  { id: 'cape_journeyman', name: 'Journeyman’s Mantle', lore: 'Stitched with the small marks of every trade you have tried.', color: 0x3f5a6b, trim: 0xd8cfa8, total: 300 },
  { id: 'cape_woodcutting', name: 'Cape of Coffin-Oak', lore: 'Mastery of the axe. It smells faintly of sawdust and old promises.', color: 0x5b3f26, trim: 0xd9b26f, skill: 'woodcutting' },
  { id: 'cape_mining', name: 'Cape of Grave-Iron', lore: 'Mastery of the pick. Heavy, and cold to the touch.', color: 0x4a4f58, trim: 0xd7dce6, skill: 'mining' },
  { id: 'cape_fishing', name: 'Cape of the Black Water', lore: 'Mastery of the line. It is always a little damp.', color: 0x1f4a57, trim: 0x7fd0e6, skill: 'fishing' },
  { id: 'cape_gravedigging', name: 'Cape of the Sexton', lore: 'Mastery of the spade. The dead are quiet around it.', color: 0x4a4030, trim: 0xe0d6a8, skill: 'gravedigging' },
  { id: 'cape_gardening', name: 'Cape of the Mourning Bed', lore: 'Mastery of the garden. Something is always growing on it.', color: 0x34552f, trim: 0xb5e08a, skill: 'gardening' },
  { id: 'cape_alchemy', name: 'Cape of the Alembic', lore: 'Mastery of the brew. It shifts colour when you are not looking.', color: 0x4a2f6b, trim: 0xd9b6ff, skill: 'alchemy' },
  { id: 'cape_salvaging', name: 'Cape of the Bone Grinder', lore: 'Mastery of the grinder. Nothing is wasted, and nothing stays whole.', color: 0x4d4130, trim: 0xe3c89a, skill: 'salvaging' },
  { id: 'cape_sexton', name: 'The Sexton’s Mantle', lore: 'Ninety-nine in every rite. The Covenant has no higher thanks to give.', color: 0x1a1420, trim: 0xe2c98f, total: 693 },
];

export const capeDef = (id: string) => CAPES.find((c) => c.id === id);

export interface PetDef {
  id: string;
  name: string;
  /** The charm item found while working; adopting it unlocks the pet. */
  charm: string;
  /** Skill whose work can turn it up. */
  skill: SkillId;
  /** Creature model to borrow and how to draw it small. */
  model: 'tithe_bat' | 'skull_rat' | 'bone_hound' | 'skeleton_thrall' | 'shroud_moth';
  scale: number;
  tint?: number;
  /** Flying pets hover and flap (wings settings for the shared wing shader). */
  fly?: { height: number; speed: number; amp: number; body: number };
  rarity: Rarity;
  lore: string;
}

export const PETS: PetDef[] = [
  { id: 'pet_tithe_bat', name: 'Tithe Bat', charm: 'charm_tithe_bat', skill: 'woodcutting', model: 'tithe_bat', scale: 0.7, fly: { height: 1.5, speed: 17, amp: 0.75, body: 0.22 }, rarity: 'rare', lore: 'It roosts in the coffin-oaks and follows the sound of the axe.' },
  { id: 'pet_grave_rat', name: 'Grave Rat', charm: 'charm_grave_rat', skill: 'mining', model: 'skull_rat', scale: 1.05, rarity: 'rare', lore: 'It found a better seam than you did, and it will not tell you where.' },
  { id: 'pet_drowned_pup', name: 'Drowned Pup', charm: 'charm_drowned_pup', skill: 'fishing', model: 'bone_hound', scale: 0.55, tint: 0x9fc4d4, rarity: 'rare', lore: 'Pulled from black water, still wet, still hopeful.' },
  { id: 'pet_wee_thrall', name: 'Wee Thrall', charm: 'charm_wee_thrall', skill: 'gravedigging', model: 'skeleton_thrall', scale: 0.32, rarity: 'epic', lore: 'A very small skeleton with a very large sense of duty.' },
  { id: 'pet_shroud_moth', name: 'Shroud Moth', charm: 'charm_shroud_moth', skill: 'gardening', model: 'shroud_moth', scale: 0.6, fly: { height: 1.7, speed: 8, amp: 0.55, body: 0.16 }, tint: 0xd8e8c0, rarity: 'epic', lore: 'It drinks the light from the beds and gives a little back.' },
];

export const petDef = (id: string) => PETS.find((p) => p.id === id);
export const petForCharm = (itemId: string) => PETS.find((p) => p.charm === itemId);
export const petForSkill = (skill: SkillId) => PETS.find((p) => p.skill === skill);

/** Base chance per successful gather (or per harvest, for gardening) of finding the skill's charm. */
export const PET_CHANCE = 1 / 3500;
/** Higher-tier nodes turn charms up a little more often (× 1 + level / 100). */
export const petChance = (nodeLevel: number) => PET_CHANCE * (1 + nodeLevel / 100);
/** Gardening: one charm in this many harvests. */
export const GARDEN_PET_CHANCE = 1 / 35;

export interface CharmItem {
  name: string;
  rarity: Rarity;
  sell: number;
  lore: string;
}

/** The items pets add: one charm each. */
export const CHARM_ITEMS: Record<string, CharmItem> = Object.fromEntries(
  PETS.map((p) => [p.charm, { name: `${p.name} Charm`, rarity: p.rarity, sell: 250, lore: `Adopt it (Capes & Pets, N) and the ${p.name} is yours for good. ${p.lore}` }]),
);
