import type { Rarity } from '../net/types';
import type { RecipeRow } from './processing';

/**
 * The Mourning Fen's herbs (2026-09-30): two marsh plants, found as gathering nodes in the Fen and as seeds to plant in the Acre
 * (SeedDefs live in content/gardening.ts). One source for the client catalogue (content/items.ts registers FEN_ITEMS), the offline
 * mock and the server migration (015-fen.sql is generated by `node tools/build-fen-sql.mjs`), so the three can't drift.
 * Kept out of gardening.ts / alchemy.ts on purpose: their generated migrations (007, 009) are already applied on the server.
 *
 * Neither herb is a dead end: both brew (FEN_RECIPES, existing flasks), and both sell.
 */
export interface FenItem {
  name: string;
  rarity: Rarity;
  sell: number;
  lore: string;
  stack: number;
}

export const FEN_ITEMS: Record<string, FenItem> = {
  herb_bog_myrtle: { name: 'Bog Myrtle', rarity: 'rare', sell: 34, lore: 'Waxy grey leaves dug from the peat. Its smoke keeps the marsh-fever off the living.', stack: 250 },
  herb_drowned_lotus: { name: 'Drowned Lotus', rarity: 'epic', sell: 72, lore: 'It blooms under black water and glows faintly, as if lit from below.', stack: 250 },
  seed_bog_myrtle: { name: 'Bog Myrtle Seed', rarity: 'rare', sell: 16, lore: 'Plant it in a Mourning Bed. It grows best in damp, dark ground.', stack: 250 },
  seed_drowned_lotus: { name: 'Drowned Lotus Seed', rarity: 'rare', sell: 28, lore: 'Plant it in a Mourning Bed and keep it patient.', stack: 250 },
  ichor_mire: { name: 'Mire Ichor', rarity: 'epic', sell: 60, lore: 'The Mire Mother leaves this dark, silver-flecked ichor. Brew it with drowned lotus for Moonlight Elixir.', stack: 250 },
};

/** [id, name, profession, level, result, quantity, ingredients]: brewed at the Workbench like every alchemy recipe. */
export const FEN_RECIPES: RecipeRow[] = [
  ['brew_myrtle_ward', 'Brew Myrtle Ward', 'alchemy', 52, 'flask_void_resist', 2, [['herb_bog_myrtle', 3]]],
  ['brew_lotus_moonlight', 'Brew Lotus Moonlight', 'alchemy', 68, 'elixir_moonlight', 1, [['herb_drowned_lotus', 3], ['ichor_mire', 1]]],
];
