import type { Rarity } from '../../../src/net/types';

/**
 * Grave Gardening content (docs/PROFESSIONS-ROADMAP.md §5): the seeds, the herbs and trees they grow into, and the plots. One source
 * for the client catalogue (content/items.ts registers GARDEN_ITEMS), the shared rules (gameplay/gardeningRules.ts) and the server
 * migration (007-gardening.sql is generated by `node tools/build-gardening-sql.mjs`), so the three can't drift.
 */

export type PlotKind = 'herb' | 'tree';

export interface PlotDef {
  id: string;
  kind: PlotKind;
  label: string;
}

/** Personal plots in the Sexton's Acre: four herb beds and two tree patches per character. */
export const PLOTS: PlotDef[] = [
  { id: 'h0', kind: 'herb', label: 'Mourning Bed I' },
  { id: 'h1', kind: 'herb', label: 'Mourning Bed II' },
  { id: 'h2', kind: 'herb', label: 'Mourning Bed III' },
  { id: 'h3', kind: 'herb', label: 'Mourning Bed IV' },
  { id: 't0', kind: 'tree', label: 'Coffin Patch I' },
  { id: 't1', kind: 'tree', label: 'Coffin Patch II' },
];

export interface SeedDef {
  /** The seed / sapling item you plant. */
  id: string;
  kind: PlotKind;
  /** Gardening level needed to plant it. */
  level: number;
  /** Real-time minutes to grow (server timestamps: it grows while you are away). */
  growMin: number;
  /** What harvesting gives. */
  harvest: string;
  yields: [number, number];
  /** XP for planting, and for harvesting. */
  plantXp: number;
  harvestXp: number;
  /** Chance a harvest also returns a seed to replant. */
  seedBack: number;
}

const herb = (id: string, level: number, growMin: number, plantXp: number, harvestXp: number, yields: [number, number] = [3, 6]): SeedDef => ({
  id: `seed_${id}`,
  kind: 'herb',
  level,
  growMin,
  harvest: `herb_${id}`,
  yields,
  plantXp,
  harvestXp,
  seedBack: 0.4,
});

export const SEEDS: SeedDef[] = [
  herb('mourning_moss', 1, 20, 6, 40),
  herb('nightshade', 15, 40, 12, 105, [3, 6]),
  herb('corpse_lily', 30, 60, 20, 195),
  herb('wolfsbane', 45, 80, 30, 315, [4, 7]),
  herb('bloodroot', 60, 100, 42, 480, [4, 8]),
  herb('moonpetal', 75, 120, 60, 690, [5, 9]),
  // Zone herbs (content/reagents.ts): foraged in the Cloister and the Pyre, grown in the Acre. Their items live in reagents.ts so migration 007 stays as applied.
  herb('rot_cap', 35, 75, 26, 360, [3, 6]),
  herb('ash_bloom', 50, 90, 34, 450, [3, 6]),
  // The Mourning Fen's herbs (items in content/fenItems.ts; found as gathering nodes in the Fen).
  herb('bog_myrtle', 55, 90, 36, 420, [4, 7]),
  herb('drowned_lotus', 70, 110, 52, 600, [4, 8]),
  { id: 'sapling_oak', kind: 'tree', level: 10, growMin: 120, harvest: 'log_oak', yields: [14, 24], plantXp: 25, harvestXp: 225, seedBack: 0.15 },
  { id: 'sapling_yew', kind: 'tree', level: 40, growMin: 360, harvest: 'log_yew', yields: [10, 18], plantXp: 60, harvestXp: 630, seedBack: 0.15 },
];

export const SEED_IDS = SEEDS.map((s) => s.id);
export const seedDef = (id: string): SeedDef | undefined => SEEDS.find((s) => s.id === id);

/** Bone meal (the Bone Kiln's product) makes a plot grow faster. */
export const COMPOST_ITEM = 'bone_meal';
export const COMPOST_SPEED = 0.75;

export interface GardenItem {
  name: string;
  rarity: Rarity;
  sell: number;
  lore: string;
  stack: number;
}

const HERBS: [id: string, name: string, rarity: Rarity, sell: number, seedSell: number, lore: string][] = [
  ['mourning_moss', 'Mourning Moss', 'common', 4, 2, 'Grows where the grieving sit.'],
  ['nightshade', 'Nightshade', 'uncommon', 9, 4, 'Bitter, dark and quietly useful.'],
  ['corpse_lily', 'Corpse-lily', 'uncommon', 18, 8, 'It flowers only on fresh graves.'],
  ['wolfsbane', 'Wolfsbane', 'rare', 30, 14, 'Older than the wolves that fear it.'],
  ['bloodroot', 'Bloodroot', 'rare', 48, 22, 'The soil around it is always warm.'],
  ['moonpetal', 'Moonpetal', 'epic', 80, 36, 'It opens for the dead alone.'],
];

/** Every item gardening adds (seed_mourning_moss already exists in the base catalogue, so it is skipped here). */
export const GARDEN_ITEMS: Record<string, GardenItem> = {};
for (const [id, name, rarity, sell, seedSell, lore] of HERBS) {
  GARDEN_ITEMS[`herb_${id}`] = { name, rarity, sell, lore, stack: 250 };
  if (id !== 'mourning_moss') GARDEN_ITEMS[`seed_${id}`] = { name: `${name} Seed`, rarity: rarity === 'epic' ? 'rare' : rarity, sell: seedSell, lore: 'Plant it in a Mourning Bed.', stack: 250 };
}
GARDEN_ITEMS.sapling_oak = { name: 'Coffin-Oak Sapling', rarity: 'common', sell: 6, lore: 'Plant it in a Coffin Patch and come back in a couple of hours.', stack: 250 };
GARDEN_ITEMS.sapling_yew = { name: 'Churchyard Yew Sapling', rarity: 'uncommon', sell: 20, lore: 'Slow, patient and worth the wait.', stack: 250 };
