/**
 * GENERATED by tools/gen-grip-sockets.mjs: do not edit. Per-rig grip sockets for the four necromancer heroes.
 * Each entry is [x, y, z, qx, qy, qz, qw]: the prop's offset (metres, in the hand bone's axes) and orientation relative to
 * the hand bone. Creature.attach places a held prop from it on the first frame (no runtime calibration).
 */
export type GripSocket = readonly [number, number, number, number, number, number, number];

export const GRIP_SOCKETS: Readonly<Record<string, Readonly<Record<string, GripSocket>>>> = {
  hero_ossuary: {
    staff: [0, 0, 0, 0.71479, 0, -0.69165, 0.10342],
    scythe: [0, 0, 0, 0.71479, 0, -0.69165, 0.10342],
    wand: [0, 0, 0, 0.29917, 0, -0.92247, 0.24404],
    sickle: [0, 0, 0, 0.29917, 0, -0.92247, 0.24404],
    skull_focus: [0, 0, 0, -0.00162, 0, 0.97815, 0.20788],
    grimoire: [-0.06512, -0.00909, 0.03573, -0.07234, 0, 0.95315, 0.29373],
    mourning_bell: [-0.07081, 0.01194, 0.03071, 0.8893, 0, -0.40499, 0.21242],
  },
  hero_gravecaller: {
    staff: [0, 0, 0, 0.01956, 0, -0.9718, 0.23501],
    scythe: [0, 0, 0, 0.01956, 0, -0.9718, 0.23501],
    wand: [0, 0, 0, 0.04788, 0, -0.92026, 0.38836],
    sickle: [0, 0, 0, 0.04788, 0, -0.92026, 0.38836],
    skull_focus: [0, 0, 0, -0.48121, 0, 0.84097, 0.24739],
    grimoire: [-0.06451, -0.01807, 0.03334, -0.38205, 0, 0.86334, 0.32967],
    mourning_bell: [-0.07008, 0.00357, 0.0343, 0.55781, 0, -0.82354, 0.10309],
  },
  hero_mourner: {
    staff: [0, 0, 0, 0.42367, 0, -0.89171, 0.15927],
    scythe: [0, 0, 0, 0.42367, 0, -0.89171, 0.15927],
    wand: [0, 0, 0, 0.21853, 0, -0.92528, 0.31001],
    sickle: [0, 0, 0, 0.21853, 0, -0.92528, 0.31001],
    skull_focus: [0, 0, 0, -0.32017, 0, 0.93377, 0.15987],
    grimoire: [-0.06314, -0.02049, 0.03454, -0.27062, 0, 0.93021, 0.24796],
    mourning_bell: [-0.07129, 0.00016, 0.03191, 0.68365, 0, -0.70181, 0.20019],
  },
  hero_rotweaver: {
    staff: [0, 0, 0, -0.34753, 0, -0.92821, 0.13285],
    scythe: [0, 0, 0, -0.34753, 0, -0.92821, 0.13285],
    wand: [0, 0, 0, -0.09255, 0, -0.95454, 0.28335],
    sickle: [0, 0, 0, -0.09255, 0, -0.95454, 0.28335],
    skull_focus: [0, 0, 0, 0.01572, 0, 0.9926, 0.12044],
    grimoire: [-0.06259, -0.02025, 0.03567, -0.09327, 0, 0.97367, 0.20799],
    mourning_bell: [-0.07189, -0.00058, 0.03052, 0.7325, 0, -0.62849, 0.26161],
  },
};
