import type { AbilityId } from './abilities';

/** Short commitment, quick recovery: gestures can blend while walking resumes. */
export const CAST_FLOW: Record<AbilityId, { lockMs: number; gestureSeconds: number }> = {
  bone_needle: { lockMs: 60, gestureSeconds: 0.22 },
  marrow_spear: { lockMs: 100, gestureSeconds: 0.30 },
  exhume: { lockMs: 110, gestureSeconds: 0.34 },
  miasma: { lockMs: 90, gestureSeconds: 0.30 },
  black_litany: { lockMs: 160, gestureSeconds: 0.48 },
  corpse_explosion: { lockMs: 70, gestureSeconds: 0.24 },
  wailing_skull: { lockMs: 80, gestureSeconds: 0.26 },
  grave_step: { lockMs: 60, gestureSeconds: 0.22 },
  grave_frost: { lockMs: 100, gestureSeconds: 0.30 },
  bone_mantle: { lockMs: 140, gestureSeconds: 0.40 },
  bone_fan: { lockMs: 60, gestureSeconds: 0.22 },
  rot_lance: { lockMs: 80, gestureSeconds: 0.26 },
  grave_offering: { lockMs: 90, gestureSeconds: 0.30 },
  ivory_cleave: { lockMs: 110, gestureSeconds: 0.30 },
  veil_step: { lockMs: 60, gestureSeconds: 0.20 },
  rally_dead: { lockMs: 120, gestureSeconds: 0.36 },
  carrion_seed: { lockMs: 90, gestureSeconds: 0.30 },
  hollow_cut: { lockMs: 150, gestureSeconds: 0.55 },
  shield_bash: { lockMs: 140, gestureSeconds: 0.40 },
  grave_slam: { lockMs: 200, gestureSeconds: 0.50 },
  bulwark: { lockMs: 120, gestureSeconds: 0.35 },
  corpse_vigil: { lockMs: 160, gestureSeconds: 0.45 },
  grave_brand: { lockMs: 110, gestureSeconds: 0.32 },
  oath_unbroken: { lockMs: 180, gestureSeconds: 0.55 },
  ossuary_wall: { lockMs: 130, gestureSeconds: 0.36 },
  command_rend: { lockMs: 130, gestureSeconds: 0.36 },
  dirge: { lockMs: 130, gestureSeconds: 0.36 },
  plague_bloom: { lockMs: 130, gestureSeconds: 0.36 },
};
