import type { Rarity } from '../net/types';
import type { AreaId } from './areas';
import type { BossDef, BossId } from './bosses';
import type { BrewDef, BrewKind } from './brews';
import type { EnemyId } from './enemies';
import type { RecipeRow } from './processing';

/**
 * Reagents and the brews made from them (docs/ALCHEMY-AND-WORLDS-PLAN.md Part 1 §D): the way into Alchemy that does NOT start
 * with farming. Mobs drop reagents (Grave Dust from the Graves and Warren, Wraith Ectoplasm from wraiths and seraphs, Plague
 * Bile in the Cloister, Cinder Ash in the Pyre), every area boss leaves an epic ichor, and two zone herbs (Rot-cap, Ash-bloom)
 * are foraged in the Cloister and the Pyre and planted in the Acre.
 *
 * One source for the client catalogue (content/items.ts), the Brew engine rows (content/brews.ts merges REAGENT_BREWS), the
 * drop rolls (gameplay/loot.ts), the offline mock, contracts and the server migration
 * (014-alchemy-reagents.sql is generated by `node tools/build-alchemy-reagents-sql.mjs`), so they can't drift. Migration 009
 * (alchemy.ts) is already applied live and is not touched: every new row lives here.
 *
 * Type-only imports keep this module a leaf, so brews.ts can import it without a cycle.
 */

export interface ReagentItem {
  name: string;
  rarity: Rarity;
  sell: number;
  lore: string;
  stack: number;
  /** Icon drawn by tools/build-reagent-icons.mjs into public/art/items/<id>.svg (drawing recipe, see that file). */
  art: string;
}

const item = (name: string, rarity: Rarity, sell: number, lore: string, art: string): ReagentItem => ({ name, rarity, sell, lore, stack: 250, art });

/** Mob reagents, zone herbs and their seeds, and the boss ichors. All gathered-material shaped (stack 250). */
export const REAGENT_ITEMS: Record<string, ReagentItem> = {
  reagent_grave_dust: item('Grave Dust', 'common', 2, 'Sifted from what the dead leave behind. Take it to the Great Cauldron in the Alchemist\'s Wing: four dust brew a Grave-Dust Tonic, no garden needed.', 'dust'),
  reagent_wraith_ectoplasm: item('Wraith Ectoplasm', 'uncommon', 8, 'Cold, weightless and faintly singing. Choir Wraiths and Weeping Seraphs shed it when they unravel. Brews into haste and insight.', 'ecto'),
  reagent_plague_bile: item('Plague Bile', 'rare', 16, 'Bottled from the Cloister dead, still green and still spoiling. The base of the lifesteal and rot-proof brews.', 'bile'),
  reagent_cinder_ash: item('Cinder Ash', 'rare', 16, 'Grey ash with a red heart that never cools. Falls from the Pyre; brews into fire-proofing.', 'ash'),
  herb_rot_cap: item('Rot-cap', 'rare', 24, 'A pale mushroom that grows out of the Cloister flagstones. Forage it there, or plant its seed in the Acre (Gardening 35).', 'rotcap'),
  seed_rot_cap: item('Rot-cap Seed', 'rare', 10, 'Plant it in a Mourning Bed (Grave Gardening 35). Foraged in the Plague Cloister.', 'seed_rotcap'),
  herb_ash_bloom: item('Ash-bloom', 'rare', 40, 'A black flower that only opens in cinders. Forage it in the Pyre, or plant its seed in the Acre (Gardening 50).', 'ashbloom'),
  seed_ash_bloom: item('Ash-bloom Seed', 'rare', 14, 'Plant it in a Mourning Bed (Grave Gardening 50). Foraged in the Cinder Pyre.', 'seed_ashbloom'),
  ichor_gravedigger: item('Gravedigger Ichor', 'epic', 60, "The Gravedigger King's blood, black as churned earth. Guaranteed from his spoils; top-tier elixirs need it.", 'ichor_earth'),
  ichor_abbess: item('Abbess Ichor', 'epic', 60, 'Marrow-pale and never quite still. Guaranteed from the Bone Abbess; top-tier elixirs need it.', 'ichor_bone'),
  ichor_congregation: item('Congregation Ichor', 'epic', 60, 'Drowned-blue, and it hums a hymn. Guaranteed from the Drowned Congregation; top-tier elixirs need it.', 'ichor_water'),
  ichor_prelate: item('Prelate Ichor', 'epic', 60, 'Bell-bronze and heavy. Guaranteed from the Bell-Sworn Prelate; top-tier elixirs need it.', 'ichor_bell'),
  ichor_plague_saint: item('Plague Saint Ichor', 'epic', 60, "The Saint's own blight, sweet and green. Guaranteed from the Plague Saint; top-tier elixirs need it.", 'ichor_rot'),
  ichor_regent: item('Regent Ichor', 'epic', 60, 'Liquid ember that does not burn the glass. Guaranteed from the Cinder Regent; top-tier elixirs need it.', 'ichor_fire'),
};

/** Boss id → the ichor its spoils always include (exactly one). */
export const BOSS_ICHOR: Record<BossId, string> = {
  gravedigger: 'ichor_gravedigger',
  abbess: 'ichor_abbess',
  congregation: 'ichor_congregation',
  prelate: 'ichor_prelate',
  saint: 'ichor_plague_saint',
  regent: 'ichor_regent',
  mire: 'ichor_mire',
};
export const bossIchor = (boss: BossDef['id']): string => BOSS_ICHOR[boss];

// ── Mob drops ───────────────────────────────────────────────────────────────────────────────────────────────────────────
// Independent rolls per kill (the area loot tables stay untouched and keep their own roll). Elites roll ELITE_REAGENT_MULT
// times as often; a fortune tonic also helps. Target pace: ~4-8 Grave Dust per 10 minutes in the Graves at 30-50 kills/min.

export interface ReagentDrop {
  item: string;
  /** Chance per kill (0-1). */
  chance: number;
  qty: [number, number];
}

export const ELITE_REAGENT_MULT = 4;

export const AREA_REAGENT_DROPS: Partial<Record<AreaId, ReagentDrop[]>> = {
  graves: [{ item: 'reagent_grave_dust', chance: 0.01, qty: [1, 2] }],
  warren: [{ item: 'reagent_grave_dust', chance: 0.012, qty: [1, 2] }],
  cloister: [{ item: 'reagent_plague_bile', chance: 0.01, qty: [1, 1] }],
  pyre: [{ item: 'reagent_cinder_ash', chance: 0.012, qty: [1, 1] }],
};

/** Spirits shed ectoplasm wherever they walk (Nave, Sanctum, Coliseum, ...). */
export const ENEMY_REAGENT_DROPS: Partial<Record<EnemyId, ReagentDrop[]>> = {
  wraith: [{ item: 'reagent_wraith_ectoplasm', chance: 0.1, qty: [1, 1] }],
  seraph: [{ item: 'reagent_wraith_ectoplasm', chance: 0.08, qty: [1, 1] }],
};

/** Every reagent id a kill can drop (unit tests check each is a known item). */
export const reagentDropIds = (): string[] => [
  ...new Set([...Object.values(AREA_REAGENT_DROPS), ...Object.values(ENEMY_REAGENT_DROPS)].flatMap((l) => (l ?? []).map((d) => d.item))),
];

// ── Brews ───────────────────────────────────────────────────────────────────────────────────────────────────────────────

export interface ReagentBrew {
  name: string;
  rarity: Rarity;
  sell: number;
  /** Lore states the numbers (the tooltip adds the same from the BREWS row). */
  lore: string;
  def: BrewDef;
  /** The Workbench recipe that makes it: [alchemy level, result quantity, ingredients]. */
  recipe: { id: string; name: string; level: number; qty: number; ings: [string, number][] };
  art: string;
}

const brew = (
  name: string,
  rarity: Rarity,
  sell: number,
  lore: string,
  def: BrewDef,
  recipe: ReagentBrew['recipe'],
  art: string,
): ReagentBrew => ({ name, rarity, sell, lore, def, recipe, art });

/** Ordered by alchemy level (a unit test checks it). Magnitudes: fortune <= +30%, wisdom <= +25%, lifesteal <= 0.08. */
export const REAGENT_BREW_LIST: [id: string, b: ReagentBrew][] = [
  ['tonic_grave_dust', brew(
    'Grave-Dust Tonic', 'common', 6,
    'Tonic. +20% essence regeneration for 60 seconds. Four pinches of grave dust in black water: the first brew anyone can make from what the dead drop.',
    { slot: 'tonic', effects: [{ kind: 'essence', value: 0.2 }], seconds: 60, label: 'Dust-breathed', color: 0xd8cfbd, glyph: '∴' },
    { id: 'brew_grave_dust_tonic', name: 'Brew Grave-Dust Tonic', level: 1, qty: 2, ings: [['reagent_grave_dust', 4]] }, 'flask_tonic_dust',
  )],
  ['elixir_wraithquick', brew(
    'Wraithquick Elixir', 'uncommon', 28,
    'Elixir. +15% cooldown recovery for 45 seconds. Ectoplasm sings in the glass, and your rites come back quicker for it.',
    { slot: 'elixir', effects: [{ kind: 'haste', value: 0.15 }], seconds: 45, label: 'Wraithquick', color: 0x8fb4ff, glyph: '⇶' },
    { id: 'brew_wraithquick', name: 'Brew Wraithquick Elixir', level: 10, qty: 1, ings: [['reagent_wraith_ectoplasm', 2], ['reagent_grave_dust', 2]] }, 'flask_haste',
  )],
  ['tonic_graveluck', brew(
    'Grave-Luck Tonic', 'uncommon', 36,
    'Tonic. +15% item drop chance for 60 seconds. Nightshade and a fistful of grave dust: the dead hold on to their things a little less tightly.',
    { slot: 'tonic', effects: [{ kind: 'fortune', value: 0.15 }], seconds: 60, label: 'Grave-lucky', color: 0xe8c35a, glyph: '◆' },
    { id: 'brew_graveluck', name: 'Brew Grave-Luck Tonic', level: 22, qty: 1, ings: [['reagent_grave_dust', 6], ['herb_nightshade', 2]] }, 'flask_fortune',
  )],
  ['tonic_insight', brew(
    "Sexton's Insight", 'uncommon', 40,
    'Tonic. +15% experience from kills for 60 seconds. Ectoplasm and mourning moss steeped together; every death teaches a little more.',
    { slot: 'tonic', effects: [{ kind: 'wisdom', value: 0.15 }], seconds: 60, label: 'Insightful', color: 0xe6d6ff, glyph: '✧' },
    { id: 'brew_insight', name: "Brew Sexton's Insight", level: 28, qty: 1, ings: [['reagent_wraith_ectoplasm', 3], ['herb_mourning_moss', 3]] }, 'flask_wisdom',
  )],
  ['elixir_leechblood', brew(
    'Leechblood Elixir', 'rare', 52,
    'Elixir. Heal 4% of the damage you deal for 45 seconds (up to three targets per hit, at most 1.5% of your health per hit). Plague bile that remembers being alive.',
    { slot: 'elixir', effects: [{ kind: 'lifesteal', value: 0.04 }], seconds: 45, label: 'Leechblood', color: 0xc23a48, glyph: '❖' },
    { id: 'brew_leechblood', name: 'Brew Leechblood Elixir', level: 38, qty: 1, ings: [['reagent_plague_bile', 2], ['reagent_grave_dust', 3]] }, 'flask_lifesteal',
  )],
  ['elixir_rotproof', brew(
    'Rot-Proof Elixir', 'rare', 48,
    'Elixir. 40% less rot and plague damage for 75 seconds (adds to other wards; the total caps at 60%). Bile and rot-cap, taken before the Plague Saint.',
    { slot: 'elixir', effects: [{ kind: 'resist_rot', value: 0.4 }], seconds: 75, label: 'Rot-proof', color: 0xc7e04a, glyph: '✥' },
    { id: 'brew_rotproof', name: 'Brew Rot-Proof Elixir', level: 42, qty: 1, ings: [['reagent_plague_bile', 1], ['herb_rot_cap', 3]] }, 'flask_rotproof',
  )],
  ['elixir_cinderskin', brew(
    'Cinderskin Elixir', 'rare', 60,
    'Elixir. 40% less fire damage for 75 seconds (adds to other wards; the total caps at 60%). Cinder ash and ash-bloom: walk the Pyre as if it were a hearth.',
    { slot: 'elixir', effects: [{ kind: 'resist_fire', value: 0.4 }], seconds: 75, label: 'Cinderskin', color: 0xff7a2a, glyph: '▲' },
    { id: 'brew_cinderskin', name: 'Brew Cinderskin Elixir', level: 52, qty: 1, ings: [['reagent_cinder_ash', 1], ['herb_ash_bloom', 3]] }, 'flask_cinderskin',
  )],
  ['tonic_ghostwalk', brew(
    'Ghostwalk Tonic', 'rare', 90,
    'Tonic. +30% essence regeneration and +10% move speed for 75 seconds. Ectoplasm and wolfsbane: you drift more than you walk.',
    { slot: 'tonic', effects: [{ kind: 'essence', value: 0.3 }, { kind: 'speed', value: 0.1 }], seconds: 75, label: 'Ghostwalking', color: 0x6fe3c8, glyph: '≈' },
    { id: 'brew_ghostwalk', name: 'Brew Ghostwalk Tonic', level: 62, qty: 1, ings: [['reagent_wraith_ectoplasm', 4], ['herb_wolfsbane', 2]] }, 'flask_ghostwalk',
  )],
  ['elixir_bloodmoon', brew(
    'Bloodmoon Elixir', 'epic', 200,
    'Elixir. +20% spell damage and heal 6% of the damage you deal for 60 seconds. Two kings\' ichor and plague bile, drunk under a red moon.',
    { slot: 'elixir', effects: [{ kind: 'damage', value: 0.2 }, { kind: 'lifesteal', value: 0.06 }], seconds: 60, label: 'Bloodmoon', color: 0xd05068, glyph: '◐' },
    { id: 'brew_bloodmoon', name: 'Brew Bloodmoon Elixir', level: 70, qty: 1, ings: [['ichor_gravedigger', 1], ['ichor_abbess', 1], ['reagent_plague_bile', 2]] }, 'flask_bloodmoon',
  )],
  ['elixir_hymnal', brew(
    'Hymnal Elixir', 'epic', 170,
    'Elixir. 15% less damage taken, 20% less rot and plague damage, and heal 3% of the damage you deal, for 75 seconds. The drowned hymn and the Saint\'s blight, made to cancel each other out.',
    { slot: 'elixir', effects: [{ kind: 'ward', value: 0.15 }, { kind: 'resist_rot', value: 0.2 }, { kind: 'lifesteal', value: 0.03 }], seconds: 75, label: 'Hymnal', color: 0xb9c8ff, glyph: '♱' },
    { id: 'brew_hymnal', name: 'Brew Hymnal Elixir', level: 78, qty: 1, ings: [['ichor_congregation', 1], ['ichor_plague_saint', 1], ['reagent_wraith_ectoplasm', 4]] }, 'flask_hymnal',
  )],
  ['elixir_regent', brew(
    "Regent's Vigil Elixir", 'epic', 300,
    'Elixir. +12% spell damage, 15% less damage taken and +10% cooldown recovery for 60 seconds. The Regent\'s ichor and the Prelate\'s, bound with cinder ash: the last word in elixirs.',
    { slot: 'elixir', effects: [{ kind: 'damage', value: 0.12 }, { kind: 'ward', value: 0.15 }, { kind: 'haste', value: 0.1 }], seconds: 60, label: "Regent's Vigil", color: 0xffc45a, glyph: '♛' },
    { id: 'brew_regent_vigil', name: "Brew Regent's Vigil Elixir", level: 85, qty: 1, ings: [['ichor_regent', 1], ['ichor_prelate', 1], ['reagent_cinder_ash', 3]] }, 'flask_regent',
  )],
];

/** Brew engine rows (brews.ts merges these into BREWS). */
export const REAGENT_BREWS: Record<string, BrewDef> = Object.fromEntries(REAGENT_BREW_LIST.map(([id, b]) => [id, b.def]));

/** The server `effect` names (the Unity game's stat_bonus vocabulary) for each brew kind. */
const SERVER_EFFECT: Record<BrewKind, string> = {
  damage: 'damage_amp',
  ward: 'resist_void',
  lifesteal: 'lifesteal',
  haste: 'cooldown_rate',
  resist_fire: 'resist_fire',
  resist_rot: 'resist_rot',
  speed: 'move_speed',
  essence: 'essence_regen',
  wisdom: 'xp_amp',
  fortune: 'drop_amp',
};

/** Server stat_bonus shape like ALCHEMY_ITEMS ({ value, effect, duration }); multi-effect brews list the rest under `effects`. */
export function brewStat(def: BrewDef): Record<string, unknown> {
  const [first, ...rest] = def.effects;
  const stat: Record<string, unknown> = { value: first.value, effect: SERVER_EFFECT[first.kind], duration: def.seconds };
  if (rest.length) stat.effects = def.effects.map((e) => ({ effect: SERVER_EFFECT[e.kind], value: e.value }));
  return stat;
}

/** New brew items as the server stores them (consumable) and as the client catalogue shows them. */
export const REAGENT_BREW_ITEMS: Record<string, { name: string; rarity: Rarity; sell: number; lore: string; stack: number; stat: Record<string, unknown>; art: string }> = Object.fromEntries(
  REAGENT_BREW_LIST.map(([id, b]) => [id, { name: b.name, rarity: b.rarity, sell: b.sell, lore: b.lore, stack: 99, stat: brewStat(b.def), art: b.art }]),
);

/** Workbench recipes, same row shape as the processing and alchemy recipes. */
export const REAGENT_RECIPES: RecipeRow[] = REAGENT_BREW_LIST.map(([id, b]) => [b.recipe.id, b.recipe.name, 'alchemy', b.recipe.level, id, b.recipe.qty, b.recipe.ings]);

/** Every new item id (reagents, herbs, seeds, ichors, brews) and its icon drawing. */
export const ALL_REAGENT_IDS: string[] = [...Object.keys(REAGENT_ITEMS), ...Object.keys(REAGENT_BREW_ITEMS)];
export const reagentIcon = (id: string): string => `art/items/${id}.svg`;
export const isReagentItem = (id: string): boolean => id in REAGENT_ITEMS || id in REAGENT_BREW_ITEMS;
/** The mob reagents, for the first-pickup counsel tip and the Codex. */
export const MOB_REAGENTS = ['reagent_grave_dust', 'reagent_wraith_ectoplasm', 'reagent_plague_bile', 'reagent_cinder_ash'];
export const ICHORS = Object.values(BOSS_ICHOR);
