/**
 * Writes server/death-muffin/backend/migrations/015-fen.sql from server/rules/content/fenItems.ts (the Mourning Fen's herbs, seeds and the
 * two alchemy recipes that use them), so the server's items and recipes can't drift from the client and the offline mock.
 *   node tools/build-fen-sql.mjs          (write)
 *   node tools/build-fen-sql.mjs --check  (exit 1 if the committed file is stale; the tests run this)
 * Idempotent SQL: INSERT IGNORE everywhere, safe to re-run. Apply after 013/014 (it only needs the base items/recipes tables).
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUT = join(root, 'server/death-muffin/backend/migrations/015-fen.sql');

async function load() {
  const res = await build({ entryPoints: [join(root, 'server/rules/content/fenItems.ts')], bundle: true, platform: 'node', format: 'esm', write: false });
  return import('data:text/javascript;base64,' + Buffer.from(res.outputFiles[0].text).toString('base64'));
}

const q = (v) => (v === null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`);

export async function render() {
  const { FEN_ITEMS, FEN_RECIPES } = await load();
  const lines = [
    "-- 015-fen.sql — The Mourning Fen: bog myrtle and drowned lotus (herbs + seeds) and the two alchemy recipes that use them.",
    '-- GENERATED by tools/build-fen-sql.mjs from server/rules/content/fenItems.ts. Do not edit by hand.',
    '-- Additive and idempotent (INSERT IGNORE): re-running it changes nothing. Apply after 013 and 014.',
    '',
  ];
  for (const [id, it] of Object.entries(FEN_ITEMS)) {
    lines.push(`INSERT IGNORE INTO items (id, name, rarity, item_type, equipment_slot, two_handed, stat_bonus, icon_id, sell_value, crafted, modifiers, stackable, max_stack_size) VALUES (${[
      id, it.name, it.rarity, 'material', null, 0, '{}', null, it.sell, 0, null, 1, it.stack,
    ].map(q).join(', ')});`);
  }
  lines.push('');
  for (const [id, name, prof, level, result, qty, ings] of FEN_RECIPES) {
    lines.push(`INSERT IGNORE INTO recipes (id, name, profession_id, skill_level_required, result_item_id, recipe_type, craft_time_seconds, result_quantity) VALUES (${[
      id, name, prof, level, result, 'craft', 4, qty,
    ].map(q).join(', ')});`);
    for (const [item, n] of ings) lines.push(`INSERT IGNORE INTO recipe_ingredients (recipe_id, item_id, quantity) VALUES (${[id, item, n].map(q).join(', ')});`);
  }
  return lines.join('\n') + '\n';
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sql = await render();
  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (cur !== sql) {
      console.error(`${OUT} is stale — run node tools/build-fen-sql.mjs`);
      process.exit(1);
    }
    console.log('015-fen.sql is up to date');
  } else {
    writeFileSync(OUT, sql);
    console.log(`wrote ${OUT} (${sql.split('\n').length} lines)`);
  }
}
