/**
 * Golden fixtures for godot/sim/bosses (run: npx vite-node tools/godot/fixtures-bosses.ts).
 * Drives the REAL BossBrain classes (src/gameplay/sim/BossBrain.ts) against a minimal stub of the WorldSim surface they use
 * (StubWorld below = the boss-world view documented in godot/sim/bosses/README.md), through seeded scripted scenarios, and records
 * for every tick: the ops applied, the boss state, and an ordered log of everything the brain asked the world to do
 * (emitted events, spawns, removals, pools, thrall/corpse changes). The GDScript port must reproduce it.
 * Output: godot/tests/bosses/fixtures/<scenario>.json (gitignored, regenerated by tools/godot/gen-fixtures.sh).
 */
import { mkdirSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import { mulberry32 } from '../../src/gameplay/rng';
import { AREAS } from '../../src/content/areas';
import { BOSSES, BOSS_IDS, GRAVEDIGGER_PITS, type BossId } from '../../src/content/bosses';
import { FEN_HUMMOCKS } from '../../src/content/fen';
import { makeBossBrains, type BossBrain, type CoverBox } from '../../src/gameplay/sim/BossBrain';
import type { PlayerBody } from '../../src/gameplay/sim/types';

const OUT = 'godot/tests/bosses/fixtures';
mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) if (f.endsWith('.json')) rmSync(`${OUT}/${f}`);

type Log = Record<string, unknown>;

/** The subset of WorldSim a BossBrain touches. Every entity is a plain object, like the real sim's. */
class StubWorld {
  time = 0;
  difficulty: string;
  vowFx = { echoes: 0 };
  players = new Map<string, PlayerBody>();
  enemies = new Map<number, any>();
  thralls = new Map<number, any>();
  corpses = new Map<number, any>();
  zones = new Map<number, any>();
  cover: CoverBox[] = [];
  log: Log[] = [];
  private nextId = 1000;
  private nextZone = 1;
  constructor(readonly rand: () => number, difficulty: string, private level: number) {
    this.difficulty = difficulty;
  }
  areaLevel(_area: string) {
    return this.level;
  }
  emit(ev: unknown) {
    this.log.push({ k: 'emit', ev: JSON.parse(JSON.stringify(ev)) });
  }
  spawnEnemy(def: string, area: string, x: number, z: number, elite: boolean, rising = true) {
    const e = { id: this.nextId++, def, area, x, z, elite, hp: 100, maxHp: 100, state: 'idle' };
    this.enemies.set(e.id, e);
    this.log.push({ k: 'spawn', id: e.id, def, area, x, z, elite, rising });
    return e;
  }
  addHostilePool(x: number, z: number, r: number, dps: number, seconds: number) {
    this.log.push({ k: 'hostilePool', x, z, r, dps, seconds });
    const zone = { id: this.nextZone++, kind: 'toxic', x, z, r, until: this.time + seconds, hostile: true };
    this.zones.set(zone.id, zone);
    return zone;
  }
  emberPool(x: number, z: number, r: number, seconds: number, dps: number) {
    this.log.push({ k: 'emberPool', x, z, r, seconds, dps });
    const zone = { id: this.nextZone++, kind: 'ember', x, z, r, until: this.time + seconds, hostile: true };
    this.zones.set(zone.id, zone);
    return zone;
  }
  killThrall(t: any, reason: string) {
    if (!this.thralls.delete(t.id)) return;
    this.log.push({ k: 'killThrall', id: t.id, reason });
  }
  removeCorpse(c: any, reason: string) {
    if (!this.corpses.delete(c.id)) return;
    this.log.push({ k: 'rmCorpse', id: c.id, reason });
  }
  /** Zones expire like the real sim's (checked by the harness each tick). */
  expireZones() {
    for (const z of [...this.zones.values()]) if (this.time >= z.until) this.zones.delete(z.id);
  }
}


interface Cfg {
  name: string;
  boss: BossId;
  seed: number;
  difficulty: 'easy' | 'medium' | 'hard';
  level: number;
  nPlayers: number;
  empowered?: boolean;
  echoes?: number;
  ticks: number;
  dt: number | 'irregular';
  /** Fraction of boss health remaining at the end of the damage ramp (negative = defeat). */
  endRatio: number;
  /** Ticks at which an extra scripted event runs (scenario-specific, see `special`). */
  special?: (c: Ctx) => void;
  cover?: CoverBox[];
  fracture?: boolean;
  /** Tick range during which no player is in the area. */
  away?: [number, number];
}

interface Ctx {
  cfg: Cfg;
  w: StubWorld;
  brain: BossBrain;
  tick: number;
  ops: Log[];
  rng: () => number;
  walkers: { id: string; alive: boolean }[];
  /** Apply + record an op. */
  op(o: Log): void;
}

function applyOp(c: Ctx, o: Log) {
  const { w, brain } = c;
  switch (o.op) {
    case 'awaken': brain.awaken(o.by as string, !!o.empowered); break;
    case 'damage': brain.damage(o.amount as number, o.by as string, o.fracture as number); break;
    case 'stagger': brain.stagger(o.seconds as number); break;
    case 'resume': brain.resume(); break;
    case 'set_players': {
      w.players.clear();
      for (const p of o.players as PlayerBody[]) w.players.set(p.id, { ...p });
      break;
    }
    case 'kill_enemy': { const e = w.enemies.get(o.id as number); if (e) { e.hp = 0; e.state = 'dead'; } break; }
    case 'del_enemy': w.enemies.delete(o.id as number); break;
    case 'add_enemy': w.enemies.set(o.id as number, { id: o.id, def: o.def, area: o.area, x: o.x, z: o.z, elite: false, hp: o.hp, maxHp: o.hp, state: 'idle' }); break;
    case 'del_corpse': w.corpses.delete(o.id as number); break;
    case 'add_corpse': w.corpses.set(o.id as number, { id: o.id, area: o.area, x: o.x, z: o.z }); break;
    case 'add_thrall': w.thralls.set(o.id as number, { id: o.id, x: o.x, z: o.z, hp: o.hp, maxHp: o.hp, flash: 0, state: 'idle' }); break;
    case 'set_boss': Object.assign(brain.state, o.fields as object); break;
    case 'set_cover': w.cover = (o.boxes as CoverBox[]).map((b) => ({ ...b })); break;
    default: throw new Error('unknown op ' + o.op);
  }
}

function snapshotWorld(w: StubWorld) {
  const f = (m: Map<number, any>) => [...m.values()].map((e) => ({ id: e.id, hp: e.hp, maxHp: e.maxHp, state: e.state, x: e.x, z: e.z })).sort((a, b) => a.id - b.id);
  return { enemies: f(w.enemies), thralls: f(w.thralls), corpses: [...w.corpses.keys()].sort((a, b) => a - b), zones: [...w.zones.keys()].sort((a, b) => a - b) };
}

function bossSnap(b: BossBrain) {
  const s = b.state;
  return { active: s.active, x: s.x, z: s.z, facing: s.facing, hp: s.hp, maxHp: s.maxHp, phase: s.phase, state: s.state, stateT: s.stateT, flash: s.flash, fracture: s.fracture, fractureT: s.fractureT, withered: s.withered, witheredT: s.witheredT, witheredDps: s.witheredDps, level: s.level, empowered: !!s.empowered };
}

function run(cfg: Cfg) {
  const rng = mulberry32(cfg.seed);
  const prng = mulberry32(cfg.seed ^ 0x9e3779b9); // the scenario script's own randomness (not the sim's)
  const w = new StubWorld(mulberry32(cfg.seed + 1), cfg.difficulty, cfg.level);
  w.vowFx.echoes = cfg.echoes ?? 0;
  if (cfg.cover) w.cover = cfg.cover.map((b) => ({ ...b }));
  const brain = makeBossBrains(w as never)[cfg.boss];
  const def = BOSSES[cfg.boss];
  const arena = def.arena;
  const ticks: Log[] = [];
  const ctx: Ctx = { cfg, w, brain, tick: 0, ops: [], rng: prng, walkers: [] as never, op: (o) => { ctx.ops.push(o); applyOp(ctx, o); } };

  // players
  type Walker = { id: string; x: number; z: number; tx: number; tz: number; alive: boolean; speed: number };
  const walkers: Walker[] = [];
  for (let i = 0; i < cfg.nPlayers; i++) {
    const a = prng() * Math.PI * 2;
    const r = prng() * arena.r * 0.7;
    walkers.push({ id: 'p' + i, x: arena.x + Math.sin(a) * r, z: arena.z + Math.cos(a) * r, tx: arena.x, tz: arena.z, alive: true, speed: 4.5 + prng() * 2 });
  }
  ctx.walkers = walkers;
  const pickTarget = (wk: Walker) => {
    const roll = prng();
    if (roll < 0.35) { wk.tx = brain.state.x + (prng() - 0.5) * 6; wk.tz = brain.state.z + (prng() - 0.5) * 6; }
    else if (roll < 0.5 && cfg.boss === 'gravedigger') { const p = GRAVEDIGGER_PITS[Math.floor(prng() * 4)]; wk.tx = p[0]; wk.tz = p[1]; }
    else if (roll < 0.75 && cfg.boss === 'mire') { const h = FEN_HUMMOCKS[1 + Math.floor(prng() * 6)]; wk.tx = h.x + (prng() - 0.5) * 2; wk.tz = h.z + (prng() - 0.5) * 2; }
    else { const a = prng() * Math.PI * 2; const r = Math.sqrt(prng()) * arena.r * 0.95; wk.tx = arena.x + Math.sin(a) * r; wk.tz = arena.z + Math.cos(a) * r; }
  };
  const syncPlayers = (extraAreaFor?: string) => {
    const away = cfg.away && ctx.tick >= cfg.away[0] && ctx.tick < cfg.away[1];
    ctx.op({ op: 'set_players', players: away ? [] : walkers.map((wk) => ({ id: wk.id, x: wk.x, z: wk.z, alive: wk.alive, area: wk.id === extraAreaFor ? 'graves_other' : def.area })) });
  };
  const dtSeq = (): number => (cfg.dt === 'irregular' ? 0.01 + prng() * 0.12 : cfg.dt);

  for (let t = 0; t < cfg.ticks; t++) {
    ctx.tick = t;
    ctx.ops = [];
    w.log = [];
    const dt = dtSeq();
    // players walk
    for (const wk of walkers) {
      if (!wk.alive) continue;
      const dx = wk.tx - wk.x, dz = wk.tz - wk.z, d = Math.hypot(dx, dz);
      if (d < 0.5) pickTarget(wk);
      else { wk.x += (dx / d) * wk.speed * dt; wk.z += (dz / d) * wk.speed * dt; }
    }
    if (t === 0) {
      syncPlayers();
      ctx.op({ op: 'awaken', by: 'p0', empowered: !!cfg.empowered });
    } else if (t % 3 === 0 || t < 3) syncPlayers();
    // damage ramp toward the scenario's end ratio
    if (brain.state.active && t % 10 === 5) {
      const prog = t / cfg.ticks;
      const want = 1 + (cfg.endRatio - 1) * prog;
      const ratio = brain.state.hp / brain.state.maxHp;
      if (ratio > want) ctx.op({ op: 'damage', amount: (ratio - want) * brain.state.maxHp * (0.5 + prng()), by: walkers[Math.floor(prng() * walkers.length)].id, fracture: cfg.fracture && prng() < 0.5 ? 1 : 0 });
    }
    cfg.special?.(ctx);
    w.time += dt;
    w.expireZones();
    brain.update(dt);
    ticks.push({ t, dt, ops: ctx.ops, boss: bossSnap(brain), time: w.time, log: w.log.slice(), world: snapshotWorld(w) });
  }
  // world snapshots only on change, to keep the files small
  let prev = '';
  for (const tk of ticks) {
    const s = JSON.stringify(tk.world);
    if (s === prev) delete tk.world;
    else prev = s;
  }
  writeFileSync(`${OUT}/${cfg.name}.json`, JSON.stringify({ name: cfg.name, boss: cfg.boss, seed: cfg.seed, difficulty: cfg.difficulty, level: cfg.level, echoes: cfg.echoes ?? 0, cover: cfg.cover ?? [], area_level: cfg.level, ticks }) + '\n');
  return ticks;
}

// --- scenarios -------------------------------------------------------------------------------------------------------

const scenarios: Cfg[] = [];
let seed = 100;
for (const boss of BOSS_IDS) {
  scenarios.push({ name: `${boss}_solo_full`, boss, seed: seed++, difficulty: 'medium', level: AREAS[BOSSES[boss].area].level, nPlayers: 1, ticks: 1400, dt: 0.05, endRatio: -0.1 });
  scenarios.push({ name: `${boss}_party_hard_empowered`, boss, seed: seed++, difficulty: 'hard', level: 14, nPlayers: 4, empowered: true, ticks: 1600, dt: 0.05, endRatio: -0.05, fracture: true });
  scenarios.push({ name: `${boss}_irregular_dt_easy`, boss, seed: seed++, difficulty: 'easy', level: 5, nPlayers: 2, ticks: 1500, dt: 'irregular', endRatio: 0.2, fracture: true });
  scenarios.push({
    name: `${boss}_wipe_reawaken`, boss, seed: seed++, difficulty: 'medium', level: 9, nPlayers: 2, ticks: 1000, dt: 0.05, endRatio: 0.35, away: [300, 400],
    special: (c) => {
      // everyone leaves the area at 300 (boss resets), they come back (one dead) and re-summon at 400, then it dies at 800.
      if (c.tick === 400) { c.walkers[1].alive = false; c.op({ op: 'set_players', players: c.walkers.map((wk: any) => ({ id: wk.id, x: wk.x, z: wk.z, alive: wk.alive, area: BOSSES[c.cfg.boss].area })) }); c.op({ op: 'awaken', by: 'p0', empowered: false }); }
      if (c.tick === 800) c.op({ op: 'damage', amount: 1e12, by: 'p0', fracture: 0 });
    },
  });
  scenarios.push({
    name: `${boss}_stagger_withered`, boss, seed: seed++, difficulty: 'medium', level: 12, nPlayers: 3, ticks: 1200, dt: 0.05, endRatio: 0.1, fracture: true,
    special: (c) => {
      if (c.tick % 97 === 40) c.op({ op: 'stagger', seconds: 0.4 + c.rng() * 2 });
      if (c.tick === 200 || c.tick === 700) c.op({ op: 'set_boss', fields: { withered: 3, witheredT: 6, witheredDps: c.brain.state.maxHp * 0.002 } });
      if (c.tick === 500) c.op({ op: 'resume' });
    },
  });
}
// --- boss-specific extras
const arenaOf = (b: BossId) => BOSSES[b].arena;
for (const echoes of [1, 2, 3]) scenarios.push({ name: `prelate_echoes${echoes}`, boss: 'prelate', seed: seed++, difficulty: 'medium', level: 10, nPlayers: 3, echoes, ticks: 1500, dt: 0.05, endRatio: -0.05 });
scenarios.push({
  name: 'abbess_niches_communion', boss: 'abbess', seed: seed++, difficulty: 'medium', level: 11, nPlayers: 3, ticks: 1600, dt: 0.05, endRatio: 0.05,
  special: (c) => {
    const b = c.brain as any;
    const ids: number[] = b.nicheIds;
    if (c.tick === 150) c.op({ op: 'kill_enemy', id: ids[0] });
    if (c.tick === 260) c.op({ op: 'kill_enemy', id: ids[2] });
    if (c.tick === 320) c.op({ op: 'kill_enemy', id: ids[1] });
    if (c.tick === 600) c.op({ op: 'kill_enemy', id: ids[3] });
    const a = arenaOf('abbess');
    if (c.tick >= 100 && c.tick % 60 === 0) c.op({ op: 'add_corpse', id: 50000 + c.tick, area: 'ossuary', x: a.x + (c.rng() - 0.5) * 16, z: a.z + (c.rng() - 0.5) * 16 });
    if (c.tick === 900) c.op({ op: 'add_corpse', id: 99999, area: 'ossuary', x: a.x + 50, z: a.z }); // outside the arena
    if (c.tick === 1000) c.op({ op: 'resume' });
    if (c.tick === 1100) c.op({ op: 'add_corpse', id: 88888, area: 'other', x: a.x, z: a.z });
  },
});
scenarios.push({
  name: 'saint_doctors_rot', boss: 'saint', seed: seed++, difficulty: 'medium', level: 16, nPlayers: 2, ticks: 1500, dt: 0.05, endRatio: 0.4,
  special: (c) => {
    const a = arenaOf('saint');
    if (c.tick === 20) { c.op({ op: 'add_enemy', id: 70001, def: 'plague_doctor', area: 'cloister', x: a.x + 3, z: a.z, hp: 50 }); c.op({ op: 'add_enemy', id: 70002, def: 'plague_doctor', area: 'cloister', x: a.x + a.r + 1, z: a.z, hp: 50 }); c.op({ op: 'add_enemy', id: 70003, def: 'plague_doctor', area: 'cloister', x: a.x + a.r + 5, z: a.z, hp: 50 }); }
    if (c.tick === 400) c.op({ op: 'kill_enemy', id: 70001 });
    if (c.tick === 600) c.op({ op: 'add_thrall', id: 80001, x: a.x + 2, z: a.z + 2, hp: 3 });
  },
});
scenarios.push({
  name: 'regent_thralls', boss: 'regent', seed: seed++, difficulty: 'medium', level: 18, nPlayers: 5, ticks: 1500, dt: 0.05, endRatio: -0.05,
  special: (c) => {
    const a = arenaOf('regent');
    if (c.tick === 5) for (let i = 0; i < 4; i++) c.op({ op: 'add_thrall', id: 81000 + i, x: a.x + (i - 1.5) * 2, z: a.z + 1, hp: 40 });
  },
});
scenarios.push({
  name: 'gravedigger_pits_thralls', boss: 'gravedigger', seed: seed++, difficulty: 'medium', level: 6, nPlayers: 3, ticks: 1500, dt: 0.05, endRatio: 0.1,
  special: (c) => {
    const a = arenaOf('gravedigger');
    if (c.tick === 5) for (let i = 0; i < 3; i++) c.op({ op: 'add_thrall', id: 81000 + i, x: a.x + i * 1.5, z: a.z + 2, hp: 30 });
    if (c.tick === 1000) c.op({ op: 'resume' });
  },
});
scenarios.push({
  name: 'congregation_pews', boss: 'congregation', seed: seed++, difficulty: 'medium', level: 8, nPlayers: 4, ticks: 1500, dt: 0.05, endRatio: 0.05,
  cover: [{ x0: -6, z0: -66, x1: -3, z1: -64.5 }, { x0: 3, z0: -66, x1: 6, z1: -64.5 }, { x0: -2, z0: -70, x1: 2, z1: -69 }, { x0: -9, z0: -58, x1: -7.5, z1: -54 }],
  special: (c) => {
    if (c.tick === 5) c.op({ op: 'add_thrall', id: 81000, x: 0, z: -65, hp: 40 });
  },
});
scenarios.push({
  name: 'mire_corpses_rite', boss: 'mire', seed: seed++, difficulty: 'medium', level: 20, nPlayers: 3, ticks: 1800, dt: 0.05, endRatio: 0.05, fracture: true,
  special: (c) => {
    const a = arenaOf('mire');
    // Corpses lie in the Fen until about 900, then are all spent (the rite should fail and stagger her).
    if (c.tick >= 60 && c.tick < 900 && c.tick % 40 === 0) c.op({ op: 'add_corpse', id: 60000 + c.tick, area: 'fen', x: a.x + (c.rng() - 0.5) * 20, z: a.z + (c.rng() - 0.5) * 20 });
    if (c.tick === 900) for (const id of [...c.w.corpses.keys()]) c.op({ op: 'del_corpse', id }); // spent by the players
    if (c.tick % 41 === 7) c.op({ op: 'damage', amount: 5, by: 'p0', fracture: 0 }); // some hits land while she is sunk (refused)
    if (c.tick === 1300) c.op({ op: 'resume' });
  },
});

let total = 0;
for (const s of scenarios) {
  const t = run(s);
  total += t.length;
  const phases = new Set(t.map((x: any) => x.boss.phase));
  const events = t.reduce((n: number, x: any) => n + x.log.length, 0);
  console.log(`${s.name}: ${t.length} ticks, ${events} log entries, phases ${[...phases].join(',')}, final hp ${(t[t.length - 1] as any).boss.hp > 0 ? 'alive' : 'dead'}`);
}
console.log(`${scenarios.length} scenarios, ${total} ticks -> ${OUT}`);
