import { CAPE_ID, HEROES, HELM_ID, MAINS, OFFS, TWO_HANDED, clipNames, type Matrix, type Support } from './gearClipHarness';
import { WEAPON_CLIPS } from '../../content/castClips';

const mm = (v: number) => `${(v * 100).toFixed(1)} cm`;
/** What counts as a problem, metres: a value of 1.0x its budget ranks as 1.0. `pen` is the budget of prop-clipping.test.ts. */
const BUDGET: Record<string, number> = { pen: 0.07, drift: 1.0, gap: 0.03, float: 0.03, sink: 0.02, hem: 0.05 };
const METRIC_NOTE: Record<string, string> = {
  pen: 'prop (or cape cloth) vertex inside the body capsules',
  drift: 'held prop tip off where the wrist alone would put it: the grip stabiliser (follow < 1) overriding the hand, which reads as a floaty or detached weapon. Bigger is worse; 0 means follow = 1',
  gap: 'nearest prop vertex to the hand bone, beyond its distance at the settled idle pose (the prop origin rides the wrist, so this stays small unless the grip offset moves)',
  float: 'helm apex above the crown past a 5 cm seat',
  sink: 'skull through the helm',
  hem: 'cape hem inside thigh / calf capsules',
};

/** Clips the game plays for a weapon kind (castClips.ts), as a set. */
function mappedClips(kind: string): Set<string> {
  const row = WEAPON_CLIPS[kind as 'staff'];
  return new Set(Object.values(row ?? {}).filter((c): c is NonNullable<typeof c> => !!c));
}

export function renderReport(matrix: Matrix, support: Record<string, Support>): string {
  const rows = Object.entries(matrix).map(([k, c]) => {
    const [hero, item, clip, metric] = k.split('|');
    return { hero, item, clip, metric, ...c };
  });
  const ranked = [...rows].sort((a, b) => b.worst / BUDGET[b.metric] - a.worst / BUDGET[a.metric]);
  const L: string[] = [];
  L.push('# Gear x clip clearance report', '');
  L.push('Generated by `npm run qa:gear-clip` (src/graphics/__tests__/gear-clip.test.ts). Measurement only: nothing here changes rendering.', '');
  L.push(`Matrix: ${HEROES.length} heroes x ${MAINS.length} main-hand kinds (${MAINS.join(', ')}) x ${OFFS.length} off-hand kinds (${OFFS.join(', ')}), helm \`${HELM_ID}\`, cape \`${CAPE_ID}\` (buildCape), every clip in each hero's clips.json, sampled every 1/15 s through the real Avatars / Creature attach path (calibration + follow).`, '');
  L.push('## Metrics', '');
  for (const [k, v] of Object.entries(METRIC_NOTE)) L.push(`- **${k}** (budget ${mm(BUDGET[k])}): ${v}.`);
  L.push('- Per clip, *worst* is the largest value on any sampled frame and *p95* the 95th percentile over frames. A frame\'s value is its worst prop vertex.');
  L.push('- Rank = worst / budget, so metrics of different scale compare. The game\'s idle self-heal (re-calibrating a prop that drifted >25 deg, a visible snap every 2 s) is disabled in the harness so numbers do not depend on clip order.');
  L.push('- Capsules (torso, chest, head, upper arms, thighs; calves for the cape hem) take their endpoints from bones every frame and their radius from the skinned mesh: the 20th percentile of the bind-pose distance of the vertices each bone owns, so a hit is buried in the solid body, not resting on cloth.', '');
  const table = (list: typeof rows) => {
    L.push('| # | hero | item | clip | frame (s) | metric | worst | p95 | x budget |', '|---|---|---|---|---|---|---|---|---|');
    list.forEach((r, i) => L.push(`| ${i + 1} | ${r.hero.replace('hero_', '')} | ${r.item} | ${r.clip} | ${r.t.toFixed(2)} | ${r.metric} | ${mm(r.worst)} | ${mm(r.p95)} | ${(r.worst / BUDGET[r.metric]).toFixed(1)} |`));
    L.push('');
  };
  L.push('## Worst 40 pairs (all metrics, ranked by x budget)', '');
  table(ranked.slice(0, 40));
  for (const metric of Object.keys(BUDGET)) {
    L.push(`## Worst 10 by ${metric}`, '');
    table(rows.filter((r) => r.metric === metric).sort((a, b) => b.worst - a.worst).slice(0, 10));
  }

  L.push('## Worst per item (over every clip and hero)', '', '| item | metric | worst | hero | clip | frame (s) |', '|---|---|---|---|---|---|');
  const best = new Map<string, (typeof rows)[number]>();
  for (const r of rows) {
    const k = `${r.item}|${r.metric}`;
    if (!best.has(k) || r.worst > best.get(k)!.worst) best.set(k, r);
  }
  for (const r of [...best.values()].sort((a, b) => b.worst - a.worst)) L.push(`| ${r.item} | ${r.metric} | ${mm(r.worst)} | ${r.hero.replace('hero_', '')} | ${r.clip} | ${r.t.toFixed(2)} |`);
  L.push('');

  L.push('## Per hero: worst of each metric', '', '| hero | metric | item | worst | clip |', '|---|---|---|---|---|');
  for (const hero of HEROES) {
    const per = new Map<string, (typeof rows)[number]>();
    for (const r of rows.filter((x) => x.hero === hero)) {
      if (!per.has(r.metric) || r.worst > per.get(r.metric)!.worst) per.set(r.metric, r);
    }
    for (const r of per.values()) L.push(`| ${hero.replace('hero_', '')} | ${r.metric} | ${r.item} | ${mm(r.worst)} | ${r.clip} |`);
  }
  L.push('');

  L.push('## Clips with no weapon-appropriate pose (input for Phase 2)', '');
  L.push('Two-handers (staff, scythe) should have the left hand on the shaft. For each hero and clip the table gives the left hand\'s distance to the shaft axis: **min** is the closest it comes on any frame, **median** the typical value. `one-handed` = median above 15 cm; `never` = it never comes within 15 cm. `*` marks a clip the game actually plays for that weapon (content/castClips.ts); idle, run, walk, attack, cast and dig are always in use.', '');
  const ALWAYS = new Set(['idle', 'run', 'walk', 'attack', 'cast', 'dig']);
  const never: Record<string, string[]> = {};
  for (const kind of MAINS.filter((m) => TWO_HANDED.has(m))) {
    L.push(`### ${kind}`, '', '| hero | clip | min | median | verdict |', '|---|---|---|---|---|');
    for (const hero of HEROES) {
      for (const clip of clipNames(hero)) {
        const s = support[`${hero}|${kind}|${clip}`];
        if (!s) continue;
        const verdict = s.min > 0.15 ? 'never two-handed' : s.med > 0.15 ? 'one-handed' : 'ok';
        const used = ALWAYS.has(clip) || mappedClips(kind).has(clip);
        if (verdict !== 'ok') (never[`${kind}|${hero}`] ??= []).push(`${clip}${used ? '*' : ''} (${verdict === 'never two-handed' ? 'never' : 'mostly 1H'})`);
        L.push(`| ${hero.replace('hero_', '')} | ${clip}${used ? ' *' : ''} | ${mm(s.min)} | ${mm(s.med)} | ${verdict} |`);
      }
    }
    L.push('');
  }
  L.push('### Summary: two-hander clips that need a two-handed pose', '');
  for (const [k, v] of Object.entries(never)) {
    const [kind, hero] = k.split('|');
    L.push(`- **${kind}**, ${hero.replace('hero_', '')}: ${v.join(', ')}`);
  }
  L.push('', 'One-handed weapons (wand, sickle) have no support-hand requirement; their problem is arm and body clearance, in the tables above.', '');
  L.push('## Reproduce', '', '`npm run qa:gear-clip` rewrites this file and `docs/gear-clip/baseline.json`. `npm test` runs a subset (4 heroes x 4 weapon/off-hand pairings x 10 clips) and fails if any pair is worse than the baseline by more than max(4 mm, 10 %). When a phase improves a number, rerun the script and commit the new baseline so the improvement is locked in.', '');
  return L.join('\n');
}
